### ISSUE TITLE
@strawberry.input ignore Optional annotation

### ISSUE THREAD

**Issue by Dotrox** [strawberry-graphql/strawberry#1011]
My code:

```python
@strawberry.type
class User:
    id: str
    name: str
    email: str


@strawberry.input
class UserInput:
    id: Optional[str]
    name: Optional[str]
    email: Optional[str]


@strawberry.type
class Query:
    @strawberry.field
    def user(self, data: UserInput) -> User:
        return User(id='607cd31af240b0b527d0a97e', name='Test', email='test@test.com')
```

My request:
```gql
query MyQuery {
  user(data: {id: "607cd31af240b0b527d0a97e"}) {
    id
    name
    email
  }
}
```

And I've got the following error:
```json
{
  "data": null,
  "errors": [
    {
      "message": "__init__() missing 2 required positional arguments: 'name' and 'email'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "user"
      ]
    }
  ]
}
```

And the same with a mutation.

Also, when I tried make a whole `data` argument optional:
```python
data: Optional[UserInput]
```
and query without it:
```gql
query MyQuery {
  user {
    id
    name
    email
  }
}
```
I've got this:
```json
{
  "data": null,
  "errors": [
    {
      "message": "user() missing 1 required positional argument: 'data'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "user"
      ]
    }
  ]
}
```

So it seems that Strawberry completely ignore `Optional` annotation.

**Comment by BryceBeagle** [comment]
In Strawberry, just as with standard Python typing, the `Optional` indicates that the value is `None`-able/nullable; not that it can be omitted. You need to give the field a default value. 

```python
@strawberry.input
class UserInput:
    id: Optional[str]
    name: Optional[str] = None
    email: Optional[str] = None
```

**Comment by Dotrox** [comment]
It seems graphene_pydantic plugin misled me (I am migrating from Graphene). When I use Pydantic model with `Optional` and without any default value it works as I expected (no errors when value not provided).
And now I see that `strawberry.experimental.pydantic.input` works the same way, but I don't use it because I need custom scalars, so I made my own wrapper and use standard `strawberry.input`.
I've added default values to my wrapper and now it works fine. Thank you!

**Comment by lovetoburnswhen** [comment]
Still getting this error with `default=UNSET`. `default=None` seems to work but is not preferred since we can't differentiate between an actual `null` argument vs one that wasn't passed

**Comment by coady** [comment]
Yeah, it's unintuitive that `name: Optional[str] = strawberry.field(default=UNSET)` is not omissible given that `name: Optional[str] = UNSET` is omissible. The root problem is that `UNSET` is now overloaded as both a user's default and a core lib default. I'm not sure there's a clean - or at least backwards-compatible - fix.

The workaround I've been using is: `name: Optional[str] = strawberry.field(default_factory=lambda: UNSET)`.
