### ISSUE TITLE
Forward types not working

### ISSUE THREAD

**Issue by N-Maas** [strawberry-graphql/strawberry#1020]
According to the changelog, I would expect strawberry to support forward types. However, I always get a `NameError` when trying to use them. Thus I looked for a minimal example:

Executing
```
import strawberry

@strawberry.type
class ForwardType:
    me: ForwardType
```

I get

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    @strawberry.type
  File "test.py", line 5, in ForwardType
    me: ForwardType
NameError: name 'ForwardType' is not defined
```

Strawberry version: 0.64.5

**Comment by patrick91** [comment]
@N-Maas have you tried using:


```
from __future__ import annotations
```

or quoting ForwardType? :)

**Comment by N-Maas** [comment]
`from __future__ import annotations` fixes it, thanks! :D
