### ISSUE TITLE
subquery doesn't  work 

### ISSUE THREAD

**Issue by peach-lasagna** [strawberry-graphql/strawberry#1023]
```python
import strawberry

@strawberry.type
class Book:
    title: str
    author: str

@strawberry.type 
class Books:
    # book: Book
    @strawberry.field
    def get(self) -> list[Book]:
        return [Book("MyTitle", "Henry"),]

@strawberry.type
class Query:
    books: Books
    @strawberry.field
    def get(self) -> list[Book]:
        return [Book("MyTitle", "Henry"),]

schema = strawberry.Schema(query=Query)
```
![изображение](https://user-images.githubusercontent.com/59787538/122221327-62761e80-cedb-11eb-97d8-6384e19918dc.png)
![изображение](https://user-images.githubusercontent.com/59787538/122221526-8b96af00-cedb-11eb-8ec2-edaef5419493.png)

**Comment by peach-lasagna** [comment]
how about create book ?

**Comment by jkimbo** [comment]
You'll probably want to define a mutation to create a book. You can read more about how to define a mutation here: https://strawberry.rocks/docs/general/mutations

**Comment by peach-lasagna** [comment]
Sorry, I forgot about it
