### ISSUE TITLE
GraphiQL sometimes fails to render due to CDN issue

### ISSUE THREAD

**Issue by taybenlor** [strawberry-graphql/strawberry#1029]
I have intermittently had issues where GraphiQL doesn't render because of an issue with a dependency from the CDN.

Right now I'm seeing a `404` on `https://cdn.jsdelivr.net/npm/graphiql-subscriptions-fetcher@0.0.2/browser/client.js`. The response is:

```
Failed to fetch version info for npm.
```

My understanding from reading [this thread](https://github.com/jsdelivr/jsdelivr/issues/18216) is that this happens when a cache of the source doesn't exist and they run into throttling issues. However I may not be understanding this correctly.

I'm honestly not sure what to suggest as a fix for this. Potentially a less flakey CDN, or inlining the GraphiQL source in the HTML file.

**Comment by aalexei** [comment]
Just hit the same problem when trying out the basic example in "Getting Started". Server starts, but visiting url just produces a blank page. 
`https://cdn.jsdelivr.net/npm/graphiql-subscriptions-fetcher@0.0.2/browser/client.js` returns `Failed to fetch version info for npm.`

**Comment by timsavage** [comment]
Has been resolved in #1096 was merged and the fix released in 0.70.1

**Comment by taybenlor** [comment]
Thanks @timsavage
