### ISSUE TITLE
How to use snake_case in graphql schema for propeties too?

### ISSUE THREAD

**Issue by zerocewl** [strawberry-graphql/strawberry#1045]
Is there a solution to use the `snake_case` as a **property name** inside a strawberry data class **and** the graphql schema?

My problem is, that my `snake_case` property name is always replaced by a `camelCase` one.

I searched inside the docs, but could only find the `name` setting for the class and field names.

Minimal example of what i'm trying:

```py
...
@strawberry.type
class SomeClass:
   creation_date: Optional[str]
```
graphql schema
```graphql
...
type SomeClass {
   creation_date: String
}

```

**Comment by patrick91** [comment]
this will be fixed when I merge https://github.com/strawberry-graphql/strawberry/pull/798 

hopefully this week :)

**Comment by zerocewl** [comment]
Thx for the fast reply.

Is there any setting like a mapping for the class properties?

In another case our current schema uses python keywords like e.g. `global` which leads to an error if used as property in the strawberry class.

**Comment by patrick91** [comment]
@zerocewl yes, the workaround is what you need 😊 it is recommended way to use python keywords as field names :)

**Comment by zerocewl** [comment]
Maybe it would be nice to add one example of this to the docs?

e.g. this one? https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/field.py#L222-L224

**Comment by patrick91** [comment]
@zerocewl we have documented it here: https://strawberry.rocks/docs/types/object-types#api

but it is probably hard to discover, 🤔 do you have any suggestion for how to make it more visibile?

**Comment by zerocewl** [comment]
ah ok.
i discovered this page but could not build the concrete examples in my mind =)

maybe add them from the docs?
```
    @strawberry.type:
    class X:
        field_abc: str = strawberry.field(description="ABC")
        @strawberry.field(description="ABC")
           def field_with_resolver(self) -> str:
               return "abc"    
```

**Comment by patrick91** [comment]
ok, I'll think about adding those examples somewhere 😊
