### ISSUE TITLE
Overriding parsers/serializers of existing scalars

### ISSUE THREAD

**Issue by Apakottur** [strawberry-graphql/strawberry#1061]
Is there a way to override parsers/serializers of existing scalars like `Date`, `DateTime` or `ID`?

For example, if I want to use the following function
```python
def my_cool_parser(value: Any) -> datetime.datetime:
    if ...:
       return dateutil.parser.isoparse(value)
    else:
       ...
```

Instead of `dateutil.parser.isoparse` for parsing datetimes, it would be awesome to have something along:

```python
from strawberry.??? import scalar_mapping
scalar_mapping[datetime.datetime].parse_value = my_cool_parser
```

------

I didn't find a clean way of doing this so I ended up overriding `strawberry.schema.types.scalar.DEFAULT_SCALAR_REGISTRY` before the schema is being generated, which seems to work.

**Comment by jkimbo** [comment]
I think this is related to #1028 - ideally scalars would be scoped to a schema and they could be overridden.

**Comment by jkimbo** [comment]
@Apakottur you should now be able to override the built in scalar implementations in [v0.75.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.75.0)

Let me know if you have any issues with it.
