### ISSUE TITLE
Throw an error when using a Union or Interface as an argument type

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#1065]
```python
@strawberry.type
class Noun:
    text: str

@strawberry.type
class Verb:
    text: str

Word = strawberry.union("Word", types=(Noun, Verb))

@strawberry.field
def add_word(word: Word) -> bool:
    _word = word
    return True
```

Creating the `field` currently does not throw an error. The error is only thrown in `graphql-core` once a schema is created.

**Comment by jkimbo** [comment]
We should also throw an error if a union is used in an input field.

**Comment by MAM-SYS** [comment]
Hello friends @BryceBeagle @jkimbo 
I wrote some lines of code for this issue
Is it ok to send them to you to take a look at them?

**Comment by jkimbo** [comment]
@MAM-SYS that would be great!

**Comment by patrick91** [comment]
This is done :)
