### ISSUE TITLE
Custom directives

### ISSUE THREAD

**Issue by japrogramer** [strawberry-graphql/strawberry#109]
I need a way to declare custom directives.

@key (fields: ...)
@external
@requires(fields: ...)

for reference this is how some of graphql-python's directives are declared
https://github.com/graphql-python/graphql-core/blob/master/graphql/type/directives.py

**Comment by Kerl1310** [comment]
I'd be willing to look into this

**Comment by patrick91** [comment]
@Kerl1310 nice! this seems to be a non easy task, so happy to see someone wanting to contribute :)

I was trying to create directives for apollo federation here: https://github.com/strawberry-graphql/strawberry/issues/115

but I noticed that graphql-core doesn't support server directives, so I think we'd need to extend graphql-core for that

**Comment by patrick91** [comment]
Support for schema directives has been available for quite a while now: https://github.com/strawberry-graphql/strawberry/blob/master/CHANGELOG.md#0140---2019-08-14

We also have experimental support for federation, so I think we can close this issue.
