### ISSUE TITLE
allow docstrings to be field descriptions

### ISSUE THREAD

**Issue by codebyaryan** [strawberry-graphql/strawberry#1098]
when writing and documenting my schema, I noticed this pattern evolve.
My sample mutation type looks like this.
```py
@strawberry.type(
    description="this is the root `mutation` field for the GraphQL schema. This class must subclass all other Mutation classes."
)
class Mutation:
    pass
```
as you can see, the syntax and code doesn't really look nice when you have very detailed descriptions.
For a better developer experience, I propose the following solution:

allow docstrings to be the description for the fields.
In practice, the same code would look like this.
```py
@strawberry.type
class Mutation:
    """
    this is the root `mutation` field for the
    GraphQL schema. This class must subclass
    all other Mutation classes.
    """
    pass
```
now, that looks really neat. The best part is line breaks can also be captured elegantly with docstrings.
When we write function resolvers, the docstring of the function can also be the description for the resolver.
What is your opinion on this?

this could be an optional feature, in the schema config object (like auto camel case).
If you like this idea, I am willing to work on this feature.

**Comment by patrick91** [comment]
@codebyaryan thanks for the suggestion! we already have a ticket for this here: https://github.com/strawberry-graphql/strawberry/issues/653

I'll close this since it is duplicated 😊
