### ISSUE TITLE
Type checking support for PyRight

### ISSUE THREAD

**Issue by rmzr7** [strawberry-graphql/strawberry#1135]
Hi, 

Given the following type

```
@strawberry.type
class Person():
   id: int
   name: str
```

PyRight throws an error on `Person(3, "Rob")`: `Expected no arguments to Person Constructor`. The way to get around this is to create an `__init__` function. However, when classes are decorated with @strawberry.type the fields within the Strawberry type cannot be selected. If an ```__init__``` is provided, the following gql requests will fail

```
person {
   id
   name
}
```

With `AttributeError: 'Person' object has no attribute 'id'`. What is the preferred way to create initializers for Strawberry Types?

**Comment by patrick91** [comment]
I want to add support for PyRight here: https://github.com/strawberry-graphql/strawberry/pull/922

but I wanted to get in touch with PyRight's maintainer to get some feedback first

Anyway, the error from PyRight is a false positive. You should be able to use the constructor provided by default by Strawberry :)

**Comment by DoctorJohn** [comment]
PyRight support has been added in #922 🎉, I'll close this issue for now. Feel free to reopen if needed :)
