### ISSUE TITLE
Custom scalars

### ISSUE THREAD

**Issue by marcoacierno** [strawberry-graphql/strawberry#114]
Sometimes it's useful to define custom scalar types in your schema, the examples I can think of right now are DateTime and Date.

That's how I implemented them in a project

```python
DateTime = NewType("DateTime", str)


def serialize_datetime(value):
    return value.isoformat()


def parse_value_datetime(value):
    return parse_datetime(value)


def parse_literal_datetime(ast, _variables=None):
    if not isinstance(ast, StringValueNode):
        return INVALID

    try:
        return parse_datetime(ast.value)
    except ValueError:
        return INVALID


REGISTRY[DateTime] = GraphQLScalarType(
    name="DateTime",
    description="Date with time (isoformat)",
    serialize=serialize_datetime,
    parse_value=parse_value_datetime,
    parse_literal=parse_literal_datetime,
)
```

It would be cool to have a decorator like `strawberry.scalar` that allows you to automatically define and register a new type + scalar:

```python

@strawberry.scalar
class DateTime:
    ???
```

I'm not sure how the interface might look to define `serialize`, `parse_value` and `parse_literal`.

This is how it's implemented in Graphene: https://github.com/graphql-python/graphene/blob/master/graphene/types/datetime.py

I feel like `parse_literal` can be implemented on a strawberry level by simply doing something like:

```
if typing == str:
   # Check that the AST is a StringValue and then call parse_value
elif typing == int:
   # Check that the AST is a int type and then call parse_value
```

While `serialize` and `parse_value` have to be implemented custom in the scalar

```python

@strawberry.scalar
class DateTime:
    @staticmethod
    def serialize(value):
        return value.isoformat()

    @staticmethod
    def parse_value(value):
       return parse_datetime(value)
```

To make it easier to understand we might want to call them `to_python` and `from_python`. But.. it doesn't really look good :)

We also need to change the type resolution system to support a class as scalar

```python
@strawberry.scalar
class Always5(int):
    @staticmethod
    def from_python(value):
        return 5

    @staticmethod
    def to_python(value):
        if value != 5:
            return None

        return 5


@strawberry.type
class Query:
    hey: Always5 = 10
```

**Comment by agritheory** [comment]
Additional examples might include Decimal (or a similar custom currency type) and uuid?

**Comment by patrick91** [comment]
@agritheory good point! I think I saw somewhere also a Currency scalar :)

We definitely want to support this, we are currently using a hack for this for PyCon Italy's website: https://github.com/pythonitalia/pycon/blob/master/backend/api/scalars.py

but we'll add first class support for this soon!

**Comment by jgosmann** [comment]
Is anyone already working on this? I'd be interested in taking a stab at this.

**Comment by patrick91** [comment]
@jgosmann  don't think anyone is working on this, feel free to take it :)
