### ISSUE TITLE
Inability to access parent resolver params in child resolver

### ISSUE THREAD

**Issue by navyamehta** [strawberry-graphql/strawberry#1141]
I've read the documentation extensively to find any mention of this, but my use-case is the following:
```
parentResolver(someParam: ...) {
    field1
    field2
    field3Resolver() {
      //need access to someParam here
    }
```
The docs state that parameters in the execution context are available in the info parameter. However, info.variable_values seems to be an empty dictionary. Is this feature not implemented or am I reading the docs incorrectly?

**Comment by patrick91** [comment]
how are you querying the data?

`info.variable_values` should represent the variables passed to the operation, if I remember correctly

**Comment by navyamehta** [comment]
For more detail, in my main query schema:
```
#Make the query object for the song session
@strawberry.type
class MyQuery:

	@strawberry.field
	def first_resolver(self, input_params: custom_input) -> MyObject: //here custom_input is my own strawberry.input definition
		...
                return MyObject(....)

graphql_schema = strawberry.Schema(query=MyQuery)
```
Then, the definition of MyObject goes as:
```
@strawberry.type
class MyObject:
    param1: int
    param2Resolver(self, info:Info):
        //info.variable_values here does not give me access to custom_input
```

**Comment by patrick91** [comment]
Here's an example how how variable_values work:

```python
import strawberry

from typing import List



@strawberry.type
class User:    
    name: str

    @strawberry.field
    def example(self, info) -> str:
      return info.variable_values['name']

def get_users(name: str):
  return [User("Patrick")]


@strawberry.type
class Query:
   users: List[User] = strawberry.field(get_users)


schema = strawberry.Schema(Query)

print(
  schema.execute_sync(
    'query ($name: String!) { users(name: $name) { name, example } }', 
    variable_values={"name": "Marco"}
  )
)
```

They will only return variables passed to the operation. So if you pass a literal directly, like so:

```
query { users(name: "Patrick") { name, example } }
```

your variable values will be empty :)

hope this make sense. Maybe you can put the variables on the context object? /cc @jkimbo is this something you ever needed to do?

**Comment by jkimbo** [comment]
@navyamehta what might help you is `strawberry.Private` which lets you attach extra information to your `MyObject` type without it being exposed in the schema (we really need to document this).

So your example becomes:

```python
@strawberry.type
class MyQuery:

	@strawberry.field
	def first_resolver(self, input_params: custom_input) -> MyObject:
		...
        return MyObject(param1=3, input_params=input_params) # pass the input params to your object (or the subset that it cares about)

@strawberry.type
class MyObject:
	input_params: strawberry.Private[custom_input]
    param1: int
    
	@strawberry.field
	def param2Resolver(self, info:Info):
		# access the input params on self.input_params
```

The benefit of this is that your `MyObject` doesn't need to be explicitly aware of context "above" it in the graph and it could be reused somewhere else in the graph.

---

Side note: `info.variable_values` is poorly named. It should probably be called `operation_variables` or something like that.

**Comment by jkimbo** [comment]
@navyamehta can we close this issue now?
