### ISSUE TITLE
GraphQL Federation guidance

### ISSUE THREAD

**Issue by Vichoko** [strawberry-graphql/strawberry#1145]
Hi! I'm very happy with Strawberry so far.

I've been trying to implement a federated schema where I want to delegate some part of the query to another GraphQL server.

I noted that there is the intention to provide support for this kind of requirements (there're [some code](https://github.com/strawberry-graphql/strawberry/issues?q=federation) regarding federation, and a [place holder on the docs](https://strawberry.rocks/docs/guides/federation)). But actually, I don't know the state of this feature.

So, my questions are:
1. Is this feature functional?
2. Is there any documentation about its usage?

## Details

Actually, I'm a kind of a starter on the GraphQL world so my first approach was (naively) to use meta-programming to define the schemas on runtime, but yeah, the more I thought about it, the more complex it looked. Until I found there's this "Federation" concept that might be useful for what I want to accomplish (Is it?).

Just to give more details, the idea is that I want to receive a query like this:

```
Query {
  library {
    building(*kwargs){
      address
     }
     books(*kwargs){
       title
     }
   }
}
```

The thing I need is to resolve the: 
```
books(*kwargs){
  title
}
```
Part with a GraphQL endpoint on another machine. 

But the actual query that I want to forward might have lots of nesting, arguments in each level, and complex Object Types.
How may I accomplish this? It's federation the solution to this?

Any comment or resource regarding the issue I'm facing would be really appreciated.

Thanks again for this wonderful framework, and keep up the good work!

**Comment by patrick91** [comment]
Hi there, the feature is fully functional, we use it in production at [pollen](https://pollen.co/team)

I was writing some docs, but never managed to finish them: https://github.com/strawberry-graphql/strawberry/pull/440

I should pick up them again at some point 😊

@marcoacierno did a test repo here, you can use it as a reference -> https://github.com/strawberry-graphql/e2e-federation

Here's how you define a type that can be extended with federation:
https://github.com/strawberry-graphql/e2e-federation/blob/main/products/api/types.py#L5-L8

and here's how you extend it:

https://github.com/strawberry-graphql/e2e-federation/blob/main/orders/api/types.py#L13

**Comment by Vichoko** [comment]
Thank you for the guidance! Finally, my use case was a little more complex than what a federation scheme would help.
But your explanation helped me a lot to know better how to approach it.

**Comment by marcoacierno** [comment]
@Vichoko feel free to also use PyCon repo as reference: https://github.com/pythonitalia/pycon this is a bit more complex (but not too much) to follow but it is a real world usage of federation

From your question, I feel like what you want is something like:

Library type implemented in service A, with `@strawberry.federation.type(keys=["id"])`

In the other service, you can define the Library type there adding a `books` field

like

```python

# Service Library

@strawberry.federation.type(keys=["id"])
class Library:
	id: ID


# Inside this Books service

# This Type doesn't need to be marked as federation type
@strawberry.type
class Book:
	id: ID

@strawberry.federation.type(keys=["id"], extend=True)
class Library:
    id: ID = strawberry.federation.field(external=True)

	@strawberry.field
	def books(self) -> List[Book]:    
		# Inside self.id you have the ID of the library
		return Books.get_books_of_library_id(self.id)

	@classmethod
    async def resolve_reference(cls, id: ID):
        return cls(id=id) 
```


with this setup, you can do

```graphql
{
	library(id: 1) {
		books {
			id
		}
	}
}
```

and you will get the books of library id 1
