### ISSUE TITLE
Apollo Federation Support

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#115]
I was thinking of adding support for Apollo Federation, in order to make this happen the following TODOs need to be tackled:

- [ ] Allow support for custom directives #109 
	not really true, but having a pythonic way of defining directives will help
- [ ] Output types in schema even if they are not used by a query
	Right now we only output fields that are used (directly and indirectly) in a query. Federated schemas might not define a query at all, so we need to output types anyway.
- [x] Add support for custom scalars #3 

# Federation specification

```gql
scalar _Any
scalar _FieldSet

# a union of all types that use the @key directive
union _Entity

type _Service {
  sdl: String
}

extend type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
}

directive @external on FIELD_DEFINITION
directive @requires(fields: _FieldSet!) on FIELD_DEFINITION
directive @provides(fields: _FieldSet!) on FIELD_DEFINITION
directive @key(fields: _FieldSet!) on OBJECT | INTERFACE

directive @extends on OBJECT | INTERFACE
```

Federation spec: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

# Python API

Initial Ideas

```gql
type Review {
  body: String
  author: User @provides(fields: "username")
  product: Product
}

extend type User @key(fields: "id") {
  id: ID! @external
  reviews: [Review]
}

extend type Product @key(fields: "upc") {
  upc: String! @external
  reviews: [Review]
}
```

```python
@strawberry.type
class Review:
  body: str
  author: User = strawberry.field(directives=[provides(fields="username")])
  product: Product


@strawberry.type(extend=True, directives=[key(fields="id")])
class User:
  id: ID = strawberry.field(directives=[external()])
  reviews: typing.list[Review]


@strawberry.type(extend=True, directives=[key(fields="upc")])
class Product:
  upc: str = strawberry.field(directives=[external()])
  reviews: typing.list[Review]
```

**Comment by patrick91** [comment]
Another example, a bit more abstracted:

```python
import strawberry
import typing


@strawberry.federation.extend(keys=["upc"])
class Product:
    upc: str = strawberry.federation.external_field()
    reviews: typing.list["Review"]


@strawberry.federation.extend(keys=["id"])
class User:
    id: strawberry.ID = strawberry.federation.external_field()
    reviews: typing.list["Review"]


@strawberry.type
class Review:
    body: str
    author: User = strawberry.federation.provider_field("username")
    product: Product


schema = strawberry.federation.FederatedSchema()
```

**Comment by ethe** [comment]
I think `author: User = strawberry.field(directives=[provides(fields="username")])` does not make sense to Python semantics. `strawberry.field(directives=[provides(fields="username")])` is not a field default value to `Review.author`.

**Comment by Ambro17** [comment]
I would like to help in any task available to give support to Apollo federation to strawberry. I personally prefer the first alternative as it is more easily translatable to the SDL

**Comment by patrick91** [comment]
Hey @Ambro17! I did an initial PR here: https://github.com/strawberry-graphql/strawberry/pull/259

Would you like to give me a review? Code isn't great, but it worked with a simple test-scenario 😊

**Comment by Ambro17** [comment]
Hello Patrick, the other day I looked over the PR and made some comments

**Comment by patrick91** [comment]
@Ambro17 don't see any comments 🤔 I saw your issue, but no comments on the PR

**Comment by Ambro17** [comment]
My bad, I thought that merely writing the comments was enough, but apparently github requires to end your review with a comment/request changes/approve. Now you should be able to see my comments

**Comment by patrick91** [comment]
> My bad, I thought that merely writing the comments was enough, but apparently github requires to end your review with a comment/request changes/approve. Now you should be able to see my comments

No worries! It happened to me as well a few times ^^ Thanks for the comments. By the way, I put federation on hold at the moment as I was trying to understand how to make a pagination API. By the way I was thinking of using discord and maybe livestream/pair with other people since we are all at home nowadays :D Here’s the link: https://discord.gg/ZkRTEJQ if you want to join ^^

**Comment by japrogramer** [comment]
Relay does pagination fairly well. I made a pagination that extends relay

connection_type(
            edges=edges,
            page_info=page
        )

where connection_type returns an object type with fields edges and page_info,
the connection takes a page and per_page argument by default.

edges is an array of types and page_info is a type that describes the results

```
class PaginatorInfo(graphene.ObjectType):
    count = Int(
        name='Count',
        description='The total number of objects, across all pages.'
    )

    current_page = Int(
        name='CurrentPage',
        description='The current page number.'
    )

    num_pages = Int(
        name='NumPages',
        description='The total number of pages.'
    )

    page_range = List(
        Int,
        name='PageRange',
        description='A 1-based range iterator of page numbers, e.g. yielding [1, 2, 3, 4].'
    )

    has_next = Boolean(
        description='Returns True if there\'s a next page.')

    has_previous = Boolean(
        description='Returns True if there\'s a previous page.')

    has_other_pages = Boolean(
        description='Returns True if there\'s a next or previous page.')

    next_page_number = Int(
        description='Returns the next page number. Raises InvalidPage if next page'
                    'doesn\'t exist.')

    previous_page_number = Int(
        description='Returns the previous page number. Raises InvalidPage if'
                    'previous page doesn\'t exist.')

    start_index = Int(
        description='Returns the 1-based index of the first object on the page,'
                    'relative to all of the objects in the paginator\'s list. For example,'
                    ' when paginating a list of 5 objects with 2 objects per page, the'
                    'second page\'s start_index() would return 3.')

    end_index = Int(
        description='Returns the 1-based index of the last object on the page,'
                    'relative to all of the objects in the paginator\'s list. For'
                    'example, when paginating a list of 5 objects with 2 objects'
                    'per page, the second page\'s end_index() would return 4.')
```

**Comment by patrick91** [comment]
@japrogramer did mean to write a comment here: https://github.com/strawberry-graphql/strawberry/issues/175?

**Comment by japrogramer** [comment]
@patrick91 I was responding to your comment in this issue, was not aware of #175

**Comment by patrick91** [comment]
@japrogramer my bad, I forgot what I wrote :D

**Comment by patrick91** [comment]
This is done, we'll add documentation and examples soon, I'll close this now 😊

**Comment by Speedy1991** [comment]
Hey @patrick91!

Any chance to get some docs on federation in the next time?
I would write some docs myself and give you a PR but I'm not sure, that I fully understand federation yet.
A minimal working example would be great with some introducing words to the decorators.

**Comment by patrick91** [comment]
Hi @Speedy1991 I have some docs here: https://github.com/strawberry-graphql/strawberry/pull/440

I wanted to make a full example[1], but didn't manage to make time, would you like to make one? We can put it in our strawberry-graphql/examples repo 😊

Feel free to join our discord and ask questions there too 😊 https://strawberry.rocks/discord

[1] https://github.com/patrick91/strawberry-federation-demo

**Comment by Sheikhharis50** [comment]
Hi @patrick91, 

can you help me out with the N+1 problem in the federation? I have used the same approach given in the documentation of strawberry and it was extremely helpful, but I have observed that it's causing an N+1 problem, is there any example in which I can use Dataloader to resolve this issue.

Thanks
