### ISSUE TITLE
Working offline with GraphiQL

### ISSUE THREAD

**Issue by lecuivre-alban** [strawberry-graphql/strawberry#1160]
Hi,

My question is maybe not really related to strawberry but here it is:

**Is it possible to use GraphiQL offline ?**

I wanted to try strawberry but once I tried loading up GraphiQL I realized that it calls a bunch of online ressources (stylesheets and scripts). Unfortunately I need to be able to use GraphiQL offline so I wanted to know if it's possible to somewhere configure it to work with local ressources.

**Comment by jkimbo** [comment]
@lecuivre-alban I would recommend using one of these standalone graphiql desktop clients like: 

* [postman](https://www.postman.com/)
* [insomnia](https://insomnia.rest/)
* [graphql-playground](https://github.com/graphql/graphql-playground)
* [altair](https://altair.sirmuel.design/)

**Comment by lecuivre-alban** [comment]
I was hoping for a better solution using the integrated GraphiQL but thanks anyway.

**Comment by jkimbo** [comment]
@lecuivre-alban out of curiosity what is wrong with using a standalone graphiql desktop client?

To get the Strawberry hosted graphiql working offline we would have to include the JS files in the library which I'd like to avoid because it just increases the size of the library. We can't make it PWA either because that needs to be served over https. I can't think of another way to make it work offline.

**Comment by lecuivre-alban** [comment]
@jkimbo 
Using the integrated GraphiQL is a way to read the schema/docs easly without needing additionnal software.
It's good for the backend developpers to test the api but having worked previously on the frontend part on projects with a GQL API, I found tools like GraphiQL/ GQL Playground really helpfull  for frontend devs because of the access to the docs.

If only backend developpers would need to install a desktop client it could be a suitable solution. Like you have your database tools, you can have you tool to test the API you're creating.

But because frontend devs would also need this client just to read the docs, it means a large part of the team would need to install and use an additionnal software. If it can be avoided it's better.

We are currently using FastAPI so when running the server locally, we have have access to the docs (whether being offline or online) of the API with OpenApi. (But this means that frontend devs need to run the server locally which I know is not ideal but that's how we work for now until we set up a better workflow)

So that's why I wanted to know if there is a way to use GraphiQL while being offline, to follow the current workflow we have with FastAPI and OpenApi.

**Comment by jkimbo** [comment]
Ok thanks for expanding, that's very interesting. 

Is this what you do to get fastapi working offline https://fastapi.tiangolo.com/advanced/extending-openapi/ ? We could probably support something like that with the default being the CDN.

**Comment by ulgens** [comment]
> But because frontend devs would also need this client just to read the docs, it means a large part of the team would need to install and use additional software. If it can be avoided it's better.

I'm a bit lost there. There are multiple frontend developers that need access to GQL API docs, but they don't have an internet connection. They don't want to install additional tools, so I assume they didn't install the backend application on their machines. Then how do they access the API in the first place? Are we talking about some isolated office network or sth?

**Comment by lecuivre-alban** [comment]
> Are we talking about some isolated office network

@ulgens  Yes. 

They access the API by running the server on their local machine. So yes they need some backend tools to setup everything but once installed they don't really need to use those. But this workflow is bound to change as it is not ideal.
 
I found that the main issue is not really about installing additional tools but rather using additional tools. I think that keeping things simple, to the bare minimum better.

**Comment by aiimi-cclifton** [comment]
@jkimbo it looks like there's been no more ask for this since the original issue

We work in an air gapped environment and would love to use strawberry with the playground available for people to explore our data, without having to install a client. 

Would you still be open to having an option to bundle the UI? I'm happy to contribute however with a bit of guidance to get it in

**Comment by patrick91** [comment]
@aiimi-cclifton wouldn't be easier/better for you to implement this on your application side? 😊

**Comment by Honest-Objections** [comment]
If you know how, then would be more than happy to approach it that way! 

My understanding is that you can choose between `graphiql`, `apollo-sandbox` or `pathfinder` when setting `graphql_ide`. All of those three options then load successfully, but rely on CDNs to actually display the UI, so you end up with a blank page when running offline. 

Couldn't really think of a nice way to mitigate that from the application side, but happily will if you have any thoughts! 

My original thinking was seeing if an additional fixed option could be added in strawberry, pointing either to a new static file that links/has bundled assets, or have it look for custom package of the name supplied. 

Appreciate your response!

**Comment by patrick91** [comment]
@Honest-Objections what integration are you using?

**Comment by Honest-Objections** [comment]
None of them work offline, so none at the moment! 

Based on that PR I might have a crack at a draft PR of a similar implementation if you're open to it and can't think of an easier way?

**Comment by patrick91** [comment]
@Honest-Objections, sorry I meant the web integration (django, fastapi, etc) 😊

**Comment by Honest-Objections** [comment]
Ah, sorry! We're using fast-api
