### ISSUE TITLE
LazyType on resolver type-hint collides with return type 

### ISSUE THREAD

**Issue by Vichoko** [strawberry-graphql/strawberry#1177]
## Description

While using LazyTypes on function-based resolvers, the IDE code inspector goes crazy with the return type and type-hint mismatch.

## Context 

I've been trying to define an extensible and modular project file structure. After some iterations, I came up with the following:
* schema.py
* types.py
* resolvers.py

This structure became pretty comfortable as query and type contain very compact method-less classes that define my schemas. And most business-related logic is contained in resolvers and other util modules.

But as I've progressed on my project, I noted that this project structure has some circular dependencies that difficult the develop. Expanding this idea, the resolvers functions need a reference to the types, as they will return an Object Type to populate the resolved field. And types will need a reference to the resolvers, as a way to indicate the schema how to resolve each field that has inputs and some complex resolving logic.

## Example code
The following is the project structure that avoids any circular import issues.

> schema.py
```python
@strawberry.type
class Query: 
    library: Library = strawberry.field(
        Resolvers.library
    )

schema = strawberry.Schema(query=Query)
```

> types.py
```python
@strawberry.type
class Book:
    title: str
    language: str

@strawberry.type
class Library:
    """For this example we assume a Library can only has Books of the library's language.""""
    name: str
    language: str
    books: Book = strawberry.field(
        Resolvers.books
    )
```

> resolvers.py
```python
if TYPE_CHECKING:
    from types import Book, Library

class Resolvers:
    @staticmethod
    def library(self, name: str, language: str) -> LazyType["Library", "types"]:
        from types import Library
        # the next line shows: Expected type 'LazyType[Library, Any]', got 'Library' instead 
        return Library(name=name, language=language)

    @staticmethod
    def books(self, title: str) -> List[LazyType["Book", "types"]]:
        from types import Book
         # the next line shows: Expected type 'List[LazyType[Book, Any]]', got 'List[Book]' instead 
        return [Book(title=title, language=self.language)]
```

## Questions

Generally speaking, I think the issues I'm having might be a code-smell pointing that my project's structure isn't healthy. 
So my first question is if there's any suggestion on an extensible and clean project structure with some separation of concerns?

My second question is if there are any updates on how are the good practices on using LazyTypes that help me avoid the warnings that are popping up in my IDE with this approach?

As I'm using PyCharm I think #796 might be slightly related to this issue.

**Comment by BryceBeagle** [comment]
> My second question is if there are any updates on how are the good practices on using LazyTypes that help me avoid the warnings that are popping up in my IDE with this approach?

It might be the case that the [PyCharm plugin](https://github.com/strawberry-graphql/strawberry-pycharm-plugin) needs to be updated to support `LazyType` return annotations

**Comment by patrick91** [comment]
We now have `Annotated["Type", strawberry.lazy("path")]` so we can close this issue 😊

Let me know if using the new annotated version doesn't work 😊
