### ISSUE TITLE
Update Pydantic integration to match Django's integration

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1192]
@la4de proposed a great way of integrating strawberry with Django:

```
@strawberry.django.type(models.Fruit)
class Fruit:
    id: auto
    name: auto
    color: 'Color'
```

This is better than what we have with Pydantic as you might get a better autocomplete, better type definition (if we add mypy support for it) and it makes it easier to override fields (even when you only want to override the name or description, as you can use `auto as the type`).

We should do the same thing[1] for Pydantic and promote it be a non-experimental feature.

Also worth mentioning that adding Pydantic support might mean that we also get support for https://github.com/tiangolo/sqlmodel which is probably going to be super helpful!

[1] We should keep the old way of passing fields as deprecated for now, and remove in version 1 or 2 :)

**Comment by Matt343** [comment]
I'm wondering if it would be possible to provide a shortcut for types where we just want to copy all of the fields without modification. Right now using the existing method I can sort of do this by passing `list(MyPydanticType.schema()["properties"].keys())` to the fields argument in the decorator, and that's removed quite a bit of boilerplate from my project where I have lots of models I just want to expose without modification.

Perhaps we could use an optional argument to the decorator to tell it to copy the existing fields as is, that way the user could pick between the more explicit version with better autocomplete or the implicit version with less boilerplate?

**Comment by patrick91** [comment]
> Perhaps we could use an optional argument to the decorator to tell it to copy the existing fields as is, that way the user could pick between the more explicit version with better autocomplete or the implicit version with less boilerplate?

yes, I think we can allow that 😊

```python
@strawberry.django.type(models.Fruit, all_fields=True)
class Fruit:
    ...
```

something like this, or maybe more explicit `expose_all_fields=True` :)

**Comment by jkimbo** [comment]
Another option:

```python
@strawberry.django.type(models.Fruit, fields="__all__")
class Fruit:
    ...
```

**Comment by patrick91** [comment]
would that allow this:

```python
@strawberry.django.type(models.Fruit, fields=["id", "type"])
class Fruit:
    ...
```

?

**Comment by jkimbo** [comment]
Yeah, `fields` take either a list or a string.

**Comment by patrick91** [comment]
> Yeah, `fields` take either a list or a string.

This is what wee do already though 😊 not sure I like the idea how having two ways of declaring fields (auto vs fields list)

**Comment by jkimbo** [comment]
Oh I see what you mean, I was just thinking about the current API. For the new API `all_fields` is probably better.
