### ISSUE TITLE
TypeVar locking in types inherited from generics

### ISSUE THREAD

**Issue by ThirVondukr** [strawberry-graphql/strawberry#1195]
Currently it's impossible to inherit from generic types and lock/fix their type variables
According to python docs it should be possible to do so:
```py
T = TypeVar('T')

class MyDict(Mapping[str, T]):
    ...
```

I created a repository with a reproducable example:
https://github.com/ThirVondukr/strawberry-generics-issue
```py
from typing import Generic, TypeVar

import strawberry

Node = TypeVar("Node")
Cursor = TypeVar("Cursor")


@strawberry.interface
class Edge(Generic[Node, Cursor]):
    node: Node
    cursor: Cursor


@strawberry.type
class SpecificEdge(Edge[str, str]):
    pass


@strawberry.type
class Root:
    edge: Edge[int, int]
    specific_edge: SpecificEdge


schema = strawberry.Schema(query=Root)
```
Expected behavior: `specificEdge` on schema having `{node: String!, cursor: String!}` type,
currently error occurs.

**Comment by BryceBeagle** [comment]
Similar test: https://github.com/strawberry-graphql/strawberry/blob/86eba966b112c43e6e05e1cc3c030741648b75bc/tests/schema/test_generics.py#L708-L745

However, no field on `Node` uses the generic. Note that the `_resolve` is not marked with `@strawberry.field`. Perhaps this test has a bug

**Comment by BryceBeagle** [comment]
Here's a more minimal reproduction of the issue:
```python
T = TypeVar("T")

@strawberry.type
class MyType(Generic[T]):
    field: T

strawberry.Schema(MyType[int])
```

Trying to find a fix now...

**Comment by BryceBeagle** [comment]
After investigation, we're going to defer solving this issue until we've implemented `StrawberryObject`. At that point we can make `StrawberryObject.__class_getitem__` directly return a new concrete `StrawberryObject` generic copy.
