### ISSUE TITLE
Refactor CLI folder structure

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#12]

**Comment by harry-7** [comment]
Can you elaborate a bit on what you meant by refactor?

**Comment by patrick91** [comment]
@harry-7 hi there!

Currently our CLI consist of only one file: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/cli/__init__.py

Would be nice to move to multiple files as we are going to have multiple commands in future. I'd love to fix the reloader too, which seems to be a bit broken at the moment.

**Comment by harry-7** [comment]
Hello. So I don't see what else I need to move that directory.

**Comment by bryanculver** [comment]
✋ I raised a PR regarding this.
