### ISSUE TITLE
Gracefully handling invalid JSON input from a client

### ISSUE THREAD

**Issue by Apakottur** [strawberry-graphql/strawberry#1214]
## How to reproduce
Given the file `app.py` with the following code (from the main README):

```python
import strawberry


@strawberry.type
class User:
    name: str
    age: int


@strawberry.type
class Query:
    @strawberry.field
    def user(self) -> User:
        return User(name="Patrick", age=100)


schema = strawberry.Schema(query=Query)
```

Run the server with
```sh
strawberry server app
```

And then run the following command:
```sh
curl 'http://localhost:8000/graphql' -H 'Content-Type: application/json' --data-raw ''
```

This will result in the JSON decode error: `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`  (which neither Starlette nor Strawberry gracefully handle).

When running a full setup (with Uvicorn, for example), the client will get a 5xx instead of a 2xx/4xx from the server, since Strawberry crashes internally.

Should we convert the JSON decode error into something more friendly, and avoid a 5xx in this case?

**Comment by patrick91** [comment]
We should probably return an error 400 😊

**Comment by jkimbo** [comment]
Btw there is now a draft GraphQL over HTTP spec: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

We should follow that (and it says that the server should return 400 for a malformed input)

**Comment by DoctorJohn** [comment]
Apparently this has been fixen in #1260, so I'll close this issue now :)
