### ISSUE TITLE
Add instructions on how to setup the mypy plugin

### ISSUE THREAD

**Issue by jkimbo** [strawberry-graphql/strawberry#1224]
Should be part of the install process and maybe part of each of the integration guides as well.

**Comment by Shashwat-05** [comment]
Can I be assigned with this? I'm interested.

**Comment by patrick91** [comment]
@Shashwat-05 done :)

**Comment by Shashwat-05** [comment]
> @Shashwat-05 done :)

thanks. I'll start working now.

**Comment by Shashwat-05** [comment]
@patrick91 This is my very first document contribution so can you please tell me shall I create a separate mypy-setup guide inside /docs/guides/ or directly append it into the README.md as it has a section for type-checking (the setup guide is around 20 lines).

**Comment by patrick91** [comment]
> @patrick91 This is my very first document contribution so can you please tell me shall I create a separate mypy-setup guide inside /docs/guides/ or directly append it into the README.md as it already has a section for type-checking (the setup guide is around 20 lines).

I'd say maybe we can make a new section under "Editor integration", like we did for vs code and pylance -> https://github.com/strawberry-graphql/strawberry/blob/main/docs/editors/vscode.md

**Comment by Shashwat-05** [comment]
> > @patrick91 This is my very first document contribution so can you please tell me shall I create a separate mypy-setup guide inside /docs/guides/ or directly append it into the README.md as it already has a section for type-checking (the setup guide is around 20 lines).
> 
> I'd say maybe we can make a new section under "Editor integration", like we did for vs code and pylance -> https://github.com/strawberry-graphql/strawberry/blob/main/docs/editors/vscode.md

ok Cap.

**Comment by Shashwat-05** [comment]
@patrick91 what should I do now, It's waiting for a Review on PR!! It's my first experience...

**Comment by patrick91** [comment]
> @patrick91 what should I do now, It's waiting for a Review on my PR!! It's my first experience...

Nice 👏 I'll do a review later today 😊

thank you!

**Comment by nrbnlulu** [comment]
fixed by #2207
