### ISSUE TITLE
Running the FastAPI integration example yields lots of WebSocket connection failures in the log

### ISSUE THREAD

**Issue by nemmiz** [strawberry-graphql/strawberry#1227]
By running the small example for integrating with FastAPI and visiting the GraphiQL page, I see lots of 403 Forbidden issues from WebSocket in the log. The example still works as expected, but getting the lots of failures in the log is confusing. Changing `app.add_route` to `app.mount` seems to fix the issue.

Example of how the log looks:
```
INFO:     ('127.0.0.1', 43230) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
INFO:     ('127.0.0.1', 43232) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
INFO:     ('127.0.0.1', 43234) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
INFO:     ('127.0.0.1', 43236) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
INFO:     ('127.0.0.1', 43238) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
INFO:     ('127.0.0.1', 43240) - "WebSocket /graphql" 403
INFO:     connection failed (403 Forbidden)
INFO:     connection closed
```

The example code:
```python
from fastapi import FastAPI
from strawberry.asgi import GraphQL
import strawberry
import typing

@strawberry.type
class Book:
    title: str
    author: str

def get_books():
    return [
        Book(
            title='The Great Gatsby',
            author='F. Scott Fitzgerald',
        ),
    ]

@strawberry.type
class Query:
    books: typing.List[Book] = strawberry.field(resolver=get_books)

graphql_app = GraphQL(strawberry.Schema(query=Query))

app = FastAPI()
app.add_route("/graphql", graphql_app)
app.add_websocket_route("/subscriptions", graphql_app)
```

Steps to reproduce:
* Start with a clean python env (tested with python 3.8 and 3.9).
* Run `python -m pip install fastapi uvicorn[standard] strawberry-graphql[asgi]`
* Run the example: `uvicorn main:app --reload`
* Go to `localhost:8000/graphql` and check the terminal log.

Full pip freeze output:
```
asgiref==3.4.1
cached-property==1.5.2
click==8.0.1
fastapi==0.68.1
graphql-core==3.1.6
h11==0.12.0
httptools==0.2.0
pydantic==1.8.2
Pygments==2.10.0
python-dateutil==2.8.2
python-dotenv==0.19.0
python-multipart==0.0.5
PyYAML==5.4.1
six==1.16.0
starlette==0.14.2
strawberry-graphql==0.76.0
typing-extensions==3.10.0.2
uvicorn==0.15.0
uvloop==0.16.0
watchgod==0.7
websockets==10.0
```

**Comment by DoctorJohn** [comment]
Thanks for the detailed report @nemmiz and your patience waiting for a response :)

The issue can be resolved by changing `app.add_websocket_route("/subscriptions", graphql_app)` to `app.add_websocket_route("/graphql", graphql_app)`.

The underlying problem here is that graphiql expects one endpoint that handles all requests (both http and websockets). I'm not sure why we decided to have a separate route for subscriptions in our fastapi example.

**Comment by memark** [comment]
@DoctorJohn I'm not using subscriptions at all. Does this mean I still have to add a subscriptions route for this error to disappear?

**Comment by DoctorJohn** [comment]
@memark I would consider it a bug if you get the warning without using subscriptions at all. That would mean that we do not configure the graphiql template correctly.

**Comment by memark** [comment]
@DoctorJohn My bad. I was using the old ASGI integration, not the new FastAPI one.
