### ISSUE TITLE
Mutable input field required even with default_factory defined

### ISSUE THREAD

**Issue by rabbittsoup** [strawberry-graphql/strawberry#1234]
```
@strawberry.input
class Parameters():
    something: str
    hello: str = 'hello'
    things: List[str] = strawberry.field(default_factory=list)

@strawberry.type
class Query():
    @strawberry.field
    get_things(data: Parameters) -> List[str]:
        return [data.something, data.hello] + data.things
```
```
query {
    getThings(data: {something: "abc"})
}
```
The expectation would be that Parameters.things has a default, an empty list, and providing the argument would be optional.  But an error occurs because Parameters.things is not recognized as having a default and would be optional.

Changing the annotation of Parameters.things to Optional[List[str]] is not correct, either, as this allows you to pass null in as the value, which is not desired.  Removing the default_factory and fixing the default to None, then changing the resolver to test for None is a workaround, but not preferable.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1234">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1234/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1234/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@rabbittsoup thanks for the report! I'll try to have a look at it in the next couple of days :)

**Comment by coady** [comment]
I think `default_factory` for mutables is working. The schema output is
```
things: [String!]! = []
```
If the error you're seeing is
```
"message": "can only concatenate list (not \"Parameters\") to list"
```
that's happening in the resolver. Try
```
        return [things.something, things.hello] + things.things
```

**Comment by rabbittsoup** [comment]
@coady You are right, I had a typo in my example.  However, this was not the point of the issue.  I corrected the example.

**Comment by rabbittsoup** [comment]
Obviously I haven't looked at this in quite some time, ha!  It appears #1371 may have fixed the crux of the issue, me thinks.
