### ISSUE TITLE
Undefined variable issue in 0.77.6

### ISSUE THREAD

**Issue by g-as** [strawberry-graphql/strawberry#1248]
With the latest release of #1213, this [line](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/nodes.py#L40) raises a KeyError when a variable is used in a query, but not defined in the payload under the key `variables`.

This used to work, and, I guess, is ok when the variable/argument is optional.

I do not know what the specs are, meaning if variable definition should be enforced all the way. If it's the way to go, maybe there should be a validation step/graceful way to handle such a case.

If not, `return info.variable_values.get(name)` should do the trick.

**Comment by patrick91** [comment]
@jkimbo do you know what the spec says?

I think I've seen other frameworks fail in this case, but I might be wrong

**Comment by jkimbo** [comment]
Hmm I'm not sure. I would have assumed validation would have failed if you were not passing a variable that was defined in the query but I could be wrong. Will check.

**Comment by jkimbo** [comment]
Can't find anything explicit about it in the spec but @g-as makes a good point that if variable/arguments are optional then you shouldn't have to pass them in the variable payload. So I'll make the change to `.get(name)`

**Comment by jkimbo** [comment]
@g-as should be fixed in the latest version. Thanks for reporting the bug!

**Comment by g-as** [comment]
Cheers.
