### ISSUE TITLE
Should we have a base class exception? `StrawberryException`

### ISSUE THREAD

**Issue by scratchmex** [strawberry-graphql/strawberry#1253]
As the title says, should we have a base class exception to inherit from? Instead of inheriting from `Exception`. This facilitates catching strawberry-only exceptions.

```python
class StrawberryException(Exception):
   pass
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1253">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1253/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1253/pledge.svg">
</picture>
</a>

**Comment by jkimbo** [comment]
I think this is a great idea! Can you create a PR @scratchmex ?

**Comment by BryceBeagle** [comment]
I petitioned for this with @patrick91 a while back, but he was opposed to it. @patrick91, do you remember why?

**Comment by estyxx** [comment]
It wouldn't hurt anybody... will make catching strawberry exceptions more flexible. The clients can choose to catch any StrawberryException or only the specific ones.

**Comment by patrick91** [comment]
I'm not 100% sure I was opposed, but I don't really see how it can be useful, the exceptions we raise aren't really meant to be caught, no?

**Comment by estyxx** [comment]
on second thought those are exceptions that are thrown when you are developing and building the schema, so they are good exceptions! There are only a few exceptions that can happen runtime and think the error will end up in the query's errors... 
Hey, @scratchmex do you have a specific use case/reason for wrapping the exceptions?

**Comment by scratchmex** [comment]
Honestly I don't remember the use case I thought before as it was a while ago but what I remember is that I was working on some parsing error exceptions and that you wrapped the graphQL exceptions with strawberry ones.
