### ISSUE TITLE
Why isn't there the GraphQL playground instead of GraphiQL?

### ISSUE THREAD

**Issue by basvandriel** [strawberry-graphql/strawberry#1270]

**Comment by marcoacierno** [comment]
Hello @basvandriel!

GraphQL Playground is being deprecated (https://github.com/graphql/graphql-playground/issues/1143) and GraphiQL will soon have all the features of GraphQL Playground and even more.

If you want to still use GraphQL Playground you can override the GraphQL view and use a custom template.

**Comment by marcoacierno** [comment]
Closing this issue, please let me know if my answer above isn't clear enough and feel free to join our Discord if you need more!

Thanks!
