### ISSUE TITLE
OpenTelemetry Extension Should Create Spans for Parsing and Validation

### ISSUE THREAD

**Issue by ossareh** [strawberry-graphql/strawberry#1272]
While looking into performance related characteristics of my stack @jkimbo has pointed out that the current OpenTelemetry extension should create spans for other time intensive steps such as:

* parsing
* validation

Context is on discord: https://discord.com/channels/689806334337482765/890275147955703831/890304451338989670

I'm happy to do this work since I've a setup which allows me to verify it is all working.

**Comment by jkimbo** [comment]
Closing this now since #1274 has been merged.
