### ISSUE TITLE
[DOCS] Can we add Starlette on on Integrations section?

### ISSUE THREAD

**Issue by Kludex** [strawberry-graphql/strawberry#1284]
Hi! :wave: 

I'm part of [encode](https://github.com/encode), and we're going to remove the native GraphQL from Starlette, check [here](https://github.com/encode/starlette/pull/1198).

Currently, it's already deprecated, and [we recommend](https://www.starlette.io/graphql/) a set of packages that can be used to work with GraphQL, which strawberry is one of them. And... I'm planning on refactoring the GraphQL docs page on Starlette to point to some different tutorial integrations. 

That being said, I was wondering if we could add an analogous page of the current [FastAPI integration](https://strawberry.rocks/docs/integrations/fastapi) to Starlette. I know it's trivial, but it will be cool anyway. :)

Furthermore, I can create the PR, I just wanted to ask first.

**Comment by patrick91** [comment]
@Kludex why not! we have the [ASGI section](https://strawberry.rocks/docs/integrations/asgi) that is basically that (our ASGI integration is based on Starlette :D)

Do you think we should rename that or just create a new page and link to the asgi section for further information?

btw happy to review and merge the PR :)

**Comment by Kludex** [comment]
Hmmm... I'm not sure. What I had in mind is to see the integration explicitly.

Maybe importing `Starlette` here and changing some wording?

![image](https://user-images.githubusercontent.com/7353520/135527402-bf987efc-50cd-4f5c-b9c1-3fd5772c6661.png)

Like "Once that's done, you can use Strawberry with ASGI, see the example with [`Starlette`](https://www.starlette.io/):"

Or just a page... :sweat_smile:

**Comment by patrick91** [comment]
let’s go with a page, we can figure later what to do with the ASGI page 😊
