### ISSUE TITLE
Add quotes around Pip extra installs in `README`/docs to support ZSH shells

### ISSUE THREAD

**Issue by ajhynes7** [strawberry-graphql/strawberry#1326]
Hello, I wanted to try out this package but I can't install the extra dependency `debug-server`.

`pip install strawberry-graphql` is successful, but `pip install strawberry-graphql[debug-server]` is not.

```sh
❯ pip install strawberry-graphql[debug-server]
zsh: no matches found: strawberry-graphql[debug-server]
```

**Environment**
- Python version: 3.10.0 (installed with pyenv)
- OS: Fedora 34
- Shell: zsh

**Comment by jkimbo** [comment]
@ajhynes7 it's a zsh thing: https://zsh.sourceforge.io/Doc/Release/Expansion.html#Glob-Operators

**Comment by jkimbo** [comment]
Fixed in #1356

**Comment by BryceBeagle** [comment]
I'm not sure this is entirely resolved in #1356 because that just updated the README. We still have the docs to update

**Comment by jkimbo** [comment]
I think we've successfully resolved this now.

**Comment by ajhynes7** [comment]
Ok thank you!
