### ISSUE TITLE
VS Code/Pylance: 'Expected no type arguments for class "Private"'

### ISSUE THREAD

**Issue by holtergram** [strawberry-graphql/strawberry#1362]
Adding type argumetents to strawberry.Private fields throws the following error.

![grafik](https://user-images.githubusercontent.com/42282368/137599353-6b3dfc9a-254a-4e79-9929-b8b853e0cbe0.png)

Assigning a value to given fiield throws this:

![grafik](https://user-images.githubusercontent.com/42282368/137599471-6c2e94b6-cdb6-4ba6-a16c-0438b4c7986c.png)

**Comment by patrick91** [comment]
@holtergram I think this might have been fixed, I can't reproduce it anymore, let me know if it is still an issue for you!
