### ISSUE TITLE
`dacite` library doesn't compatible after 0.69.0 strawberry-graphql. (unhasable type 'StrawberryOptional' problem)

### ISSUE THREAD

**Issue by leo6104** [strawberry-graphql/strawberry#1364]
I have a regression issue with StrawberryOptional (breaking changes in 0.69.0) 
When I use dacite library to convert dict to strawberry.type class instance, it works in 0.67.x version. 

```
from dacite import from_dict

@strawberry.type
class Tag:
    tag_id: int = None
    category: str = None
    images: List[str] = None

    @strawberry.field()
    def image(self, info: Info) -> Optional[str]:
        ...

from_dict(data_class=Tag, data=dict(tag_id=34, category="song", images=["a", "b"]))
// same with Tag(tag_id=34, category="song", images=["a", "b"]) 
```

`dacite.from_dict` method convert `dict(**attributes)` to `Tag(tag_id=~, ...)` automatically. 
It makes ORM model instance <-> Strawberry type instance conversion easily. 

After upgrade, it occur an error unhashable type: 'StrawberryOptional'  because of Optional[str] type. 

Can we make `StrawberryOptional`, `StrawberryList` to be hashable type to use dacite.from_dict ? 
Or is there any alternative way to convert dict to strawberry.type instance?

**Comment by zifeo** [comment]
@leo6104 Can you retry with `@strawberry.field` instead of `@strawberry.field()`?

**Comment by michal-cech** [comment]
Example:
```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json
import strawberry
from typing import Optional



def get_b(self) -> Optional['B']:
    return B(name="something")

@dataclass_json
@strawberry.type
class A:
    name: str

    @strawberry.field
    def b(self) -> 'B':
        return get_b(self)

@dataclass_json
@strawberry.type
class B:
    name: str

@dataclass_json
@strawberry.type
class C:
    name: str

    @strawberry.field
    def b(self) -> Optional['B']:
        return get_b(self)




# a works
a = A.from_dict({'name': 'name_a'})

#b works 
b = B.from_dict({'name': 'name_b'})

#c does not work due to Optional
c = C.from_dict({'name': 'name_c'})

```

**Comment by patrick91** [comment]
This should have been fixed in https://pypi.org/project/strawberry-graphql/0.102.3/ :)
