### ISSUE TITLE
re-organize integration code

### ISSUE THREAD

**Issue by aryaniyaps** [strawberry-graphql/strawberry#1368]
Right now, we have a lot of integrations in our codebase, so I think it would be nice to re-organize and clean it up a bit!
I was thinking whether we should move all the integrations into a `strawberry/contrib` folder, so that users can import integrations from `strawberry/contrib/integration_name`.

Therefore, the current project structure would turn into:
```text
strawberry/
    __init__.py
    contrib/
        aiohttp
        asgi
        django
        fastapi
        flask
        sanic
        starlette
        chalice
```

If you're okay with this, I could make a PR! :)

The only thing I'm concerned about is that this could be a breaking change - people who already use our integrations could have their imports broken.

**Comment by aryaniyaps** [comment]
With new integrations like aws chalice dropping in is it a good time to revisit this issue? 🤔

**Comment by patrick91** [comment]
I think we should work with @BryceBeagle proposal (#849) but keep the imports nice 😊

I prefer `import strawberry.django` to `import strawberry.contrib.django` :D

**Comment by aryaniyaps** [comment]
That sounds good!
