### ISSUE TITLE
Improve client directives and schema directives

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1374]
We should probably make multiple issues, but let's just have this one for now.

For client directives we should:

1. Add documentation
2. Add support for lists
3. Improve typing 

For schema directives (after https://github.com/strawberry-graphql/strawberry/pull/815):

1. Improve printer
2. Print schema directive definition
3. Print schema directive arguments and inputs
4. Improve typings

We should also probably decided what happens when using schema directives (I have some ideas, but let's discuss those later) :)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1374">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1374/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1374/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @patrick91 ,

Don't know if this is the right issue or https://github.com/strawberry-graphql/strawberry/issues/1180 would be...

I created a custom schema directive implementation in my lib (https://github.com/blb-ventures/strawberry-django-plus/blob/master/strawberry_django_plus/directives.py), which can act as a middleware if a resolver is defined in it. I wrote it to be able to use it for permissioning (https://github.com/blb-ventures/strawberry-django-plus/blob/master/strawberry_django_plus/permissions.py), but it can be used for anything.

It is still a simple implementation and can for sure be improved.

I also fixed the schema directive printer to print types/fields schema directives correctly: https://github.com/blb-ventures/strawberry-django-plus/blob/master/strawberry_django_plus/utils/printer.py

What do you think?

**Comment by patrick91** [comment]
Pretty sure this was done 😊
