### ISSUE TITLE
Feature request: Django debug toolbar integration

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry#1375]
Hey Strawberrians,

it'd be great to have some kind of toolbar to inspect and benchmark queries and mutations like with the 
[Django debug toolbar](https://github.com/jazzband/django-debug-toolbar). Unfortunately I cannot get it to work with GraphiQL.

Apparently there is a port for [Graphene](https://github.com/flavors/django-graphiql-debug-toolbar) available. Maybe this can be a starting point?

Since I'm not using any dataloaders as of now I'm pretty suree I'm already hammering my DB (N+1 problem) so any tool that'd help me to nail down weaknesses would be very appreciated.

Thanks!
🍓

**Comment by bellini666** [comment]
Hey, just a quick heads up. I created the integration in this lib: https://github.com/strawberry-graphql/strawberry-graphql-django
