### ISSUE TITLE
Feature Request: 'Rejecting' Requests in Extensions

### ISSUE THREAD

**Issue by navyamehta** [strawberry-graphql/strawberry#1397]
Is it possible to extend the extensions class in strawberry such that we can 'reject' a request in on_request_start? Maybe we wish to perform rate-limiting etc. and not service the request at all. This is connected to https://github.com/strawberry-graphql/strawberry/issues/1396 since we can rate-limit not by requests but by the cost of the query. Potentially, we should be able to throw exceptions in extensions that can be caught by fastAPI exception handlers?

**Comment by jkimbo** [comment]
@navyamehta it's possible to do this already actually if you just want to raise an exception if the request hits the rate limit:

```python
    class RateLimiting(Extension):
        def on_request_start(self):
            execution_context = self.execution_context
			rate_limited = # check if the request is rate limited
			if rate_limited:
                raise Exception("Too many requests!")
```

Then you can catch that exception in FastAPI.

I've also created a PR to allow you to reject a request with a GraphQL error instead: #1400
