### ISSUE TITLE
No way to resolve type of non-strawberry types returned for an interface

### ISSUE THREAD

**Issue by AlecRosenbaum** [strawberry-graphql/strawberry#1405]
This comment is correct: https://github.com/strawberry-graphql/strawberry/blob/feb6edee0df8cac3aeb663f67a169035a0271f40/strawberry/schema/schema_converter.py#L235-L244

It's correctly [reflected in the docs](https://strawberry.rocks/docs/types/interfaces#resolving-an-interface), but still does pose a pretty bad limitation for implementations that resolve to non-strawberry types.

The following test fails (using a similar example to https://github.com/strawberry-graphql/strawberry/pull/1150):

```python
def test_interface_type_resolution():
    @strawberry.interface
    class Node:
        id: int

    @strawberry.type
    class Anime(Node):
        name: str

    @dataclass
    class AnimeORM:
        id: int
        name: str

    @strawberry.type
    class Query:
        @strawberry.field
        def node(self) -> Node:
            return AnimeORM(id=1, name="One Piece")  # type: ignore

    schema = strawberry.Schema(query=Query)

    query = "{ node { __typename, id } }"
    result = schema.execute_sync(query)

    assert not result.errors
    assert result.data == {"node": {"__typename": "Anime", "id": 1}}
    # errors with: "type object 'AnimeORM' has no attribute '_type_definition'"
```

In `graphene`, the converter allows you to define `is_type_of` classmethods on concrete types or a `resolve_type` classmethod on the interface. I think the equivalent within strawberry would be to optionally include `is_type_of` [here](https://github.com/strawberry-graphql/strawberry/blob/feb6edee0df8cac3aeb663f67a169035a0271f40/strawberry/schema/schema_converter.py#L300-L305), and to gracefully fail type resolution for non-strawberry objects (by returning `None`) within [`resolve_type`](https://github.com/strawberry-graphql/strawberry/blob/feb6edee0df8cac3aeb663f67a169035a0271f40/strawberry/schema/schema_converter.py#L235-L248).

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1405">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1405/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1405/pledge.svg">
</picture>
</a>

**Comment by AlecRosenbaum** [comment]
I was wrong about the graceful failure on `resolve_type`. `graphene` doesn't provide a `resolve_type` function by default. It seem that `resolve_type` takes precedence over `is_type_of` if it's present, regardless of what it returns.

If I understand correctly, it seems that `graphene` forces the presence of a user-defined `is_type_of` function on implementing types, a `resolve_type` function on the interface, or will generate an `is_type_of` function for you based on a list of types provided within the metadata (still explicit / opt-in).

Should strawberry require explicit type resolution for duck-typed objects?

**Comment by AlecRosenbaum** [comment]
Not sure why this closed...

**Comment by pheki** [comment]
I think this was fixed by https://github.com/strawberry-graphql/strawberry/pull/1406
