### ISSUE TITLE
[Feature Request] translate GraphQL Queries & Mutations into Cypher Queries

### ISSUE THREAD

**Issue by yeus** [strawberry-graphql/strawberry#1411]
it would be great to have automatic access to graph-dbs through strawberry..  similar to this js library:  

- https://neo4j.com/developer/graphql/#_the_neo4j_graphql_library
- https://www.npmjs.com/package/@neo4j/graphql

it would translate GraphQL Queries into Cypher Queries.

It might also make sense to derive OGM classes from strawberry.types (for example using the "neomodel" library). or the other way around...  similar to how strawberry can generate types from pydantic classes..

- Would anybody like this feature ;)?
- Does is already exist in some form?
- i might consider implementing something like that. What would be a good way to do this with strawberry? An extension?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1411">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1411/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1411/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
At the moment, there are no plans to implement something similar. This can however be a great idea for a strawberry integration, complementing `strawberry-django` and `strawberry-sqlalchemy`. In any case, that would be a separate library and not part of this core repo 😊
