### ISSUE TITLE
experimental pydantic support for nested pydantic models?

### ISSUE THREAD

**Issue by yeus** [strawberry-graphql/strawberry#1413]
hi, I am trying out the experimental support of pydantic models. When I do this:

```
@strawberry.experimental.pydantic.type(model=Project, all_fields=True)
class ProjectType:
    pass
```

I get the following error:

`TypeError: ProjectType fields cannot be resolved. Field type must be an output type.`

Is this intended behavior for security reasons?  it works if I leave out the `all_fields=True`

and declare the class with strawberry.auto fields...

```
@strawberry.experimental.pydantic.type(model=Project)
class ProjectType:
    uuid: strawberry.auto
    name: strawberry.auto
```

would be great do be able to use the al_fields=True flag ;).

EDIT: I am realizing that this happens, because I am actually using nested pydantic classes:

```
class User(pydantic.BaseModel):
    uuid: uuid.UUID
    type: str


class Project(pydantic.BaseModel):
    uuid: uuid.UUID
    name: str
    project_type: str
    owner: User
```

@strawberry.experimental.pydantic.type(model=Project) decorator doesn't seem to convert nested hirarchies into strawberry models..  Is this already possible? I am I missing something here? Any way around this?

**Comment by peniqliotuv** [comment]
Encountering this as well. It also seems to happen to Enums

**Comment by yeus** [comment]
Duplicate of #1325
