### ISSUE TITLE
Add Graphene compatibility

### ISSUE THREAD

**Issue by jaydenwindle** [strawberry-graphql/strawberry#143]
It would be awesome to be able to incrementally adopt strawberry types into an existing Graphene project. That way users don't have to re-write their existing GraphQL APIs if they want to try strawberry. 

Perhaps we could create a way for users to merge Graphene and strawberry schemas, and serve the combined schema from a single endpoint.

This may be easier to implement now that both libraries use `graphql-core-next` under the hood (as of graphene v3).

**Comment by lucasvazq** [comment]
What does strawberry contribute that graphene doesn't?

**Comment by patrick91** [comment]
@lucasvazq at the moment we don't really offer much more than Graphene, we are mainly playing with a nicer API and trying to add new functionalities (like field permissions) :)

**Comment by agritheory** [comment]
I'm new to both these packages, but doesn't graphene support `class MyClass(object)`-flavored classes, as opposed to _just_ dataclasses? I can image additional class methods beyond just a data store would be helpful (event hooks, data validation that requires a database connection, duplication...)

**Comment by patrick91** [comment]
You can still do that with data classes, like:

```python
@dataclass
class User:
     name: str

     def add_friend(self, user: "User") -> Bool:
          return True
```

is that what you meant? :)

**Comment by agritheory** [comment]
This is going to sound dumb, but I didn't think that dataclasses allowed methods. The "mutable namedtuples with default" description would make you think that _wasn't_ a feature. Happy to be wrong about this.

**Comment by patrick91** [comment]
@agritheory you can have methods on dataclasses (and I think also on named tuples when using them as `class X(NamedTuple)`) :)

<img width="373" alt="image" src="https://user-images.githubusercontent.com/667029/65521863-2d958d00-deea-11e9-8c76-55d2225099bf.png">

**Comment by un33k** [comment]
Graphene is meant to remain in the past.   This seems to be a lean and clean fresh start.  Bloating it with logic to look into the past will cost energy that can be put in forward looking features.  Such as pagination etc.

**Comment by patrick91** [comment]
I'm going to close this for now, not sure support Graphene type is valuable at the moment, we can always reopen this in future :)
