### ISSUE TITLE
Add Enum generation for Django choice fields

### ISSUE THREAD

**Issue by jaydenwindle** [strawberry-graphql/strawberry#144]
It would be great to support generating enum return types for Django `CharField`s where `choices` are defined. Currently strawberry resolves all `CharField` values to a `String` type.

We'll need to make sure that we don't define duplicate enum types or use names that would clash with other types in the schema.

See https://github.com/graphql-python/graphene-django/issues/185#issuecomment-388639988 for a discussion about auto-generated choice enum types in Graphene.

**Comment by agritheory** [comment]
Does this have to be Django specific? A choice-to-enum pattern/utility would be helpful regardless of framework or database.

**Comment by patrick91** [comment]
@agritheory we do support python enums already! See here: https://github.com/strawberry-graphql/strawberry/blob/master/tests/test_enum.py

I've asked a friend to work on the design for the new website+docs so hopefully we'll start working on documentation soon :)

**Comment by patrick91** [comment]
Closing as we have this https://github.com/strawberry-graphql/strawberry-graphql-django :D
