### ISSUE TITLE
TypeError: Query fields cannot be resolved. Unexpected type '<class 'dict'>'

### ISSUE THREAD

**Issue by sowri1** [strawberry-graphql/strawberry#1444]
Greetings all,
I have just started to use strawberry and i find it quiet fascinating and easy to use. But i have been facing a small issue.
I have decorators which I need to use to almost all the queries and mutations.
I am defining the queries and mutations as 
```
def checkDecorator(func):
	def wrapper(*args: list, **kwargs: dict):
		### Some Func
		return func(*args, **kwargs)
		# return None
	return wrapper

@checkDecorator
def login_user(email: str, password: str):
	print(email, password)
	return True


@strawberry.type
class Query:
	login_user: bool = strawberry.field(resolver = login_user)
```
But when I try to run the server, I get 
```TypeError: Query fields cannot be resolved. Unexpected type '<class 'list'>'.```
I cannot provide all the arguments list in the decorator because the same decorator can be used for another function. 
Please help me fix this issue.

**Comment by 12306hujunjie** [comment]
you can define a "strawberry-compatible" decorator with this [#601 ](https://github.com/strawberry-graphql/strawberry/issues/601#issuecomment-734469660)

**Comment by jkimbo** [comment]
This can now be achieved using [Field extensions](https://strawberry.rocks/docs/guides/field-extensions) so closing this issue.
