### ISSUE TITLE
Bulk Mutations

### ISSUE THREAD

**Issue by Casyfill** [strawberry-graphql/strawberry#1452]
Hey! A newbie to graphql here. I have a case where I need to get and set multiple objects at once, and I'd really prefer to do that via one endpoint, each. There is no problem getting bulk objects, but I am a bit lost with bulk upserts. 

Here are two attempts I made:
```python

@strawberry.type
class Premium:
    # property_id: int
    updated_at: datetime
    type: str
    amount: int
    note: Optional[str] = None

@strawberry.type
class PremiumSet:
    property_id: int
    user_id: int
    premiums: List[Premium]

@strawberry.type
class Mutation:
    @strawberry.mutation
    async def set_premiums_v1(self, premiums:List[Premium])->List[Premium]:
        # something
        return premiums

    @strawberry.mutation
    async def set_premiums_v2(self, premiums:PremiumSet)->PremiumSet:
        # something
        return premiums
```

I tried running API with both approaches (commenting out one or the other), but in each case got ` TypeError: Mutation fields cannot be resolved. Argument type must be a GraphQL input type.`.

Can it be done with strawberry? What is the right approach to do that? I'd really appreciate any guidance

**Comment by jkimbo** [comment]
@Casyfill The inputs to your mutations need to be input types. They can't be ordinary object types. You can read more about why here: https://strawberry.rocks/docs/types/input-types

**Comment by patrick91** [comment]
@Casyfill Jon is correct, [here's an example based on your code](https://la4de.github.io/strawberry-playground/#UEsDBAoAAAAAAJFVelMb6i/pvwMAAL8DAAAJAAAAc2NoZW1hLnB5ZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSB0eXBpbmcgaW1wb3J0IE9wdGlvbmFsLCBMaXN0CgpAc3RyYXdiZXJyeS50eXBlCmNsYXNzIFByZW1pdW06CiAgICAjIHByb3BlcnR5X2lkOiBpbnQKICAgIHVwZGF0ZWRfYXQ6IGRhdGV0aW1lCiAgICB0eXBlOiBzdHIKICAgIGFtb3VudDogaW50CiAgICBub3RlOiBPcHRpb25hbFtzdHJdID0gTm9uZQoKQHN0cmF3YmVycnkuaW5wdXQKY2xhc3MgUHJlbWl1bUlucHV0OgogICAgIyBwcm9wZXJ0eV9pZDogaW50CiAgICB1cGRhdGVkX2F0OiBkYXRldGltZQogICAgdHlwZTogc3RyCiAgICBhbW91bnQ6IGludAogICAgbm90ZTogT3B0aW9uYWxbc3RyXSA9IE5vbmUKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgUHJlbWl1bVNldDoKICAgIHByb3BlcnR5X2lkOiBpbnQKICAgIHVzZXJfaWQ6IGludAogICAgcHJlbWl1bXM6IExpc3RbUHJlbWl1bV0KCgpAc3RyYXdiZXJyeS5pbnB1dApjbGFzcyBQcmVtaXVtU2V0SW5wdXQ6CiAgICBwcm9wZXJ0eV9pZDogaW50CiAgICB1c2VyX2lkOiBpbnQKICAgIHByZW1pdW1zOiBMaXN0W1ByZW1pdW1JbnB1dF0KCgpAc3RyYXdiZXJyeS50eXBlCmNsYXNzIE11dGF0aW9uOgogICAgIyBAc3RyYXdiZXJyeS5tdXRhdGlvbgogICAgIyBhc3luYyBkZWYgc2V0X3ByZW1pdW1zX3YxKHNlbGYsIHByZW1pdW1zOiBMaXN0W1ByZW1pdW1JbnB1dF0pIC0+IExpc3RbUHJlbWl1bV06CiAgICAjICAgICAjIHNvbWV0aGluZwogICAgIyAgICAgcmV0dXJuIHByZW1pdW1zCgogICAgQHN0cmF3YmVycnkubXV0YXRpb24KICAgIGFzeW5jIGRlZiBzZXRfcHJlbWl1bXNfdjIoc2VsZiwgcHJlbWl1bXM6IFByZW1pdW1TZXRJbnB1dCkgLT4gUHJlbWl1bVNldDoKICAgICAgICAjIHNvbWV0aGluZwogICAgICAgIHJldHVybiBwcmVtaXVtcwoKCnNjaGVtYSA9IHN0cmF3YmVycnkuU2NoZW1hKFF1ZXJ5LCBNdXRhdGlvbilQSwMECgAAAAAAkVV6Uxxk//JhAAAAYQAAAAkAAABxdWVyeS5ncWxtdXRhdGlvbiB7CiAgc2V0UHJlbWl1bXNWMihwcmVtaXVtczoge3Byb3BlcnR5SWQ6IDEsIHVzZXJJZDogMSwgcHJlbWl1bXM6IFtdfSkgewogICAgdXNlcklkCiAgfQp9UEsDBAoAAAAAAJFVelOou75zAwAAAAMAAAAOAAAAdmFyaWFibGVzLmpzb257Cn1QSwECFAAKAAAAAACRVXpTG+ov6b8DAAC/AwAACQAAAAAAAAAAAAAAAAAAAAAAc2NoZW1hLnB5UEsBAhQACgAAAAAAkVV6Uxxk//JhAAAAYQAAAAkAAAAAAAAAAAAAAAAA5gMAAHF1ZXJ5LmdxbFBLAQIUAAoAAAAAAJFVelOou75zAwAAAAMAAAAOAAAAAAAAAAAAAAAAAG4EAAB2YXJpYWJsZXMuanNvblBLBQYAAAAAAwADAKoAAACdBAAAAAA=) 😊

**Comment by Casyfill** [comment]
Thank you both! Somehow missed the input part. 
it all "works" now, but I noticed that the mutation does not allow list of premiums, and itself generates an example that does not work:
```graphql
mutation MyMutation {
  __typename
  setPremiums(premiumsInput: {propertyId: 10, userId: 10, premiums: {updatedAt: "", type: "", amount: 10}})
}

```
which results in :
`"message": "type object argument after ** must be a mapping, not PremiumInput",`

The attempts below do not work either:
#### try 1
```graphql
mutation MyMutation {
  setPremiums(premiumsInput: {propertyId: 10, userId: 10, premiums: [{updatedAt: "2021-12-13", type: "", amount: 10}]}){
    propertyId
  }
}

```

#### try 2
```graphql
mutation MyMutation {
  setPremiums(premiumsInput: {propertyId: 10, userId: 10, premiums: {attempt:{updatedAt: "2021-12-13", type: "", amount: 10}}}){
    propertyId
  }
}
```

Does it mean that `List[Premiums]` is not supported in general, and I should have an explicit Mapping (dict) instead?

**Comment by patrick91** [comment]
@Casyfill [this works](https://la4de.github.io/strawberry-playground/#UEsDBAoAAAAAAPR8elMb6i/pvwMAAL8DAAAJAAAAc2NoZW1hLnB5ZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSB0eXBpbmcgaW1wb3J0IE9wdGlvbmFsLCBMaXN0CgpAc3RyYXdiZXJyeS50eXBlCmNsYXNzIFByZW1pdW06CiAgICAjIHByb3BlcnR5X2lkOiBpbnQKICAgIHVwZGF0ZWRfYXQ6IGRhdGV0aW1lCiAgICB0eXBlOiBzdHIKICAgIGFtb3VudDogaW50CiAgICBub3RlOiBPcHRpb25hbFtzdHJdID0gTm9uZQoKQHN0cmF3YmVycnkuaW5wdXQKY2xhc3MgUHJlbWl1bUlucHV0OgogICAgIyBwcm9wZXJ0eV9pZDogaW50CiAgICB1cGRhdGVkX2F0OiBkYXRldGltZQogICAgdHlwZTogc3RyCiAgICBhbW91bnQ6IGludAogICAgbm90ZTogT3B0aW9uYWxbc3RyXSA9IE5vbmUKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgUHJlbWl1bVNldDoKICAgIHByb3BlcnR5X2lkOiBpbnQKICAgIHVzZXJfaWQ6IGludAogICAgcHJlbWl1bXM6IExpc3RbUHJlbWl1bV0KCgpAc3RyYXdiZXJyeS5pbnB1dApjbGFzcyBQcmVtaXVtU2V0SW5wdXQ6CiAgICBwcm9wZXJ0eV9pZDogaW50CiAgICB1c2VyX2lkOiBpbnQKICAgIHByZW1pdW1zOiBMaXN0W1ByZW1pdW1JbnB1dF0KCgpAc3RyYXdiZXJyeS50eXBlCmNsYXNzIE11dGF0aW9uOgogICAgIyBAc3RyYXdiZXJyeS5tdXRhdGlvbgogICAgIyBhc3luYyBkZWYgc2V0X3ByZW1pdW1zX3YxKHNlbGYsIHByZW1pdW1zOiBMaXN0W1ByZW1pdW1JbnB1dF0pIC0+IExpc3RbUHJlbWl1bV06CiAgICAjICAgICAjIHNvbWV0aGluZwogICAgIyAgICAgcmV0dXJuIHByZW1pdW1zCgogICAgQHN0cmF3YmVycnkubXV0YXRpb24KICAgIGFzeW5jIGRlZiBzZXRfcHJlbWl1bXNfdjIoc2VsZiwgcHJlbWl1bXM6IFByZW1pdW1TZXRJbnB1dCkgLT4gUHJlbWl1bVNldDoKICAgICAgICAjIHNvbWV0aGluZwogICAgICAgIHJldHVybiBwcmVtaXVtcwoKCnNjaGVtYSA9IHN0cmF3YmVycnkuU2NoZW1hKFF1ZXJ5LCBNdXRhdGlvbilQSwMECgAAAAAA9Hx6Uyd0bk/FAAAAxQAAAAkAAABxdWVyeS5ncWxtdXRhdGlvbiBNeU11dGF0aW9uIHsKICBzZXRQcmVtaXVtc1YyKHByZW1pdW1zOiB7cHJvcGVydHlJZDogMTAsIHVzZXJJZDogMTAsIHByZW1pdW1zOiBbe3VwZGF0ZWRBdDogIjIwMjEtMTItMTMiLCB0eXBlOiAiIiwgYW1vdW50OiAxMH1dfSl7CiAgICBwcm9wZXJ0eUlkCiAgICBwcmVtaXVtcyB7CiAgICAgIHVwZGF0ZWRBdAogICAgfQogIH0KfVBLAwQKAAAAAAD0fHpTqLu+cwMAAAADAAAADgAAAHZhcmlhYmxlcy5qc29uewp9UEsBAhQACgAAAAAA9Hx6UxvqL+m/AwAAvwMAAAkAAAAAAAAAAAAAAAAAAAAAAHNjaGVtYS5weVBLAQIUAAoAAAAAAPR8elMndG5PxQAAAMUAAAAJAAAAAAAAAAAAAAAAAOYDAABxdWVyeS5ncWxQSwECFAAKAAAAAAD0fHpTqLu+cwMAAAADAAAADgAAAAAAAAAAAAAAAADSBAAAdmFyaWFibGVzLmpzb25QSwUGAAAAAAMAAwCqAAAAAQUAAAAA) for me :)

do you have a full example so I can check what's wrong? :)

**Comment by Casyfill** [comment]
strawberry-graphql==0.89.2

```python
from .models import PremiumSet
from ..data_queries import set_premiums_to_db
from ..postgres import postgres

@strawberry.input
class PremiumInput:
    # property_id: int
    updated_at: datetime
    type: str
    amount: int
    note: Optional[str] = None


@strawberry.input
class PremiumSetInput:
    property_id: int
    user_id: int
    premiums: List[PremiumInput]


@strawberry.type
class Mutation:
    @strawberry.mutation
    async def set_premiums(self, premiums_input: PremiumSetInput) -> PremiumSet:
        ps = [dict(**p, property_id=premiums_input.property_id, user_id=premiums_input.user_id) for p in premiums_input.premiums ]  # type: ignore
        await set_premiums_to_db(postgres, premiums=ps)

        return PremiumSet(
            property_id=int(premiums_input.property_id),
            user_id=int(premiums_input.user_id),
            premiums=[Premium(**dict(el)) for el in premiums_input.premiums],  # type: ignore
        )  # type: ignore
```

**Comment by Casyfill** [comment]
P.S. awesome strawberry playground, but it raises
```
aceback (most recent call last):
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 415, in eval_code
    CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 296, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 4, in <module>
NameError: name 'strawberry' is not defined
``` 
for me.  is it something with my chrome, or playground is still in the works?

**Comment by patrick91** [comment]
> NameError: name 'strawberry' is not defined

you need to import strawberry in the playground too :)

**Comment by Casyfill** [comment]
thanks! Yeah, issue persist for me. I refactored the code to have better graphql mutation structure, but issue persists
```python
from .models import PremiumSet, Premium

@strawberry.input
class PremiumInput:
    updated_at: datetime
    type: str
    amount: int
    note: Optional[str] = None

@strawberry.type
class Mutation:

    @strawberry.mutation
    async def set_premiums(self, property_id:int, user_id:int, premiums:List[PremiumInput]) -> PremiumSet:
        # ps = [dict(**p, property_id=premiums_input.property_id, user_id=premiums_input.user_id) for p in premiums_input.premiums ]  # type: ignore
        # await set_premiums_to_db(postgres, premiums=ps)
        
        return PremiumSet(
            property_id=int(property_id),
            user_id=int(user_id),
            premiums=[Premium(**dict(el)) for el in premiums],  # type: ignore
        )  # type: ignore

```

**Comment by patrick91** [comment]
would you be able to send me a dm on Discord? might be easy to help you  😊 http://strawberry.rocks/discord

**Comment by Casyfill** [comment]
Thanks @patrick91 , all works now that I use
```
dataclasses.asdict(obj)` instead of dict(obj)
```
as FastAPI user, I keep failing to remember strawbery objects are not Pydantic objects 😢
