### ISSUE TITLE
Reorganize testing code

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#1456]
Currently the tests are really disorganized. Many concepts are untested, while many other tests are redundant.

I propose we start with the following structure for tests. We shoiuld end up with something fairly similar to the actual codebase structure in #849 

- [ ] types
	- [ ] resolving 
	- [ ] enums
	- [ ] scalars
- [ ] fields (#1457)
- [ ] resolvers
- [ ] objects
- [ ] schema
  - [ ] federation
- [ ] utils
  - [ ] printer
- [ ] integrati\ons
  - [ ] aiohttp
  - [ ] chalice
  - [ ] django
  - [ ] fastapi
  - [ ] etc...
- [ ] cli
- [ ] typing
  - [ ] mypy
  - [ ] pyright

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1456">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1456/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1456/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
We did some of this, I'll close since it might be hard to do the rest :D
