### ISSUE TITLE
Add integration for flask and quart

### ISSUE THREAD

**Issue by davidroeca** [strawberry-graphql/strawberry#149]
Any plans for implementations targeting [flask](https://github.com/pallets/flask) or [quart](https://gitlab.com/pgjones/quart/)?

Alternatively, is there a standard way a third party could write a plugin for strawberry that targets an alternative framework? Asking because I like the design of `strawberry` models, but switching the entire framework leads to a pretty big migration rather than just swapping out `graphene`.

**Comment by davidroeca** [comment]
:man_facepalming: forgot that [flask-graphql](https://github.com/graphql-python/flask-graphql) just targets a schema. Closing

**Comment by patrick91** [comment]
@davidroeca I think it might still be worth adding a view like the one we did for Django, so you don't need to install another package for this :)

**Comment by johnchuks** [comment]
@patrick91 I would love to take a crack at this issue.

**Comment by patrick91** [comment]
@johnchuks assigned to you! :)

**Comment by johnchuks** [comment]
Awesome!

**Comment by LeptoSpira** [comment]
Is there still help wanted for this?

**Comment by patrick91** [comment]
Let's wait a couple of days for @johnchuks to answer :) otherwise I think you can work on this :)

**Comment by agritheory** [comment]
I asked about Strawberry + Quart over on the Quart gitter channel and Phil (Quart's author) had this interesting pattern:

    class SplitMount:
        def __init__(self, base, extra, path):
            self.base = base
            self.extra = extra
            self.path = path

        async def __call__(self, scope, receive, send):
            if scope["path"].startswith(self.path):
                return await self.extra(scope, receive, send)
            else:
                return await self.base(scope, receive, send)

I was able to integrate Ariadne directly into a Quart blueprint, but that doesn't really let you write a class-based View (with GraphQL) the way one typically would in Quart or Flask app, nor with Strawberry's dataclass syntax or advantages. I like Ariadne's approach, but for my current project/ experiment, I'm only working with a handful of tables and views and it feels like using a screwdriver to pound in a nail. If I had lots (maybe even a few dozen) of views/tables/schemas to worry about, I think Ariadne's approach might be a better fit. 

I'm not sure how you'd directly integrate Strawberry's ASGI pattern with Flask's WSGI architecture, so Phil's approach might be better for Flask than Quart. Haven't tried it.

**Comment by davidroeca** [comment]
More motivation for this - https://github.com/graphql-python/graphene-sqlalchemy/issues/248#issuecomment-584981555

Support for graphql-core async in flask-graphql is blocked by graphene 3.0

**Comment by patrick91** [comment]
I'll close this issue for now as we have a Flask view now. We can always add a Quart view later, if needed (not sure if it is different from Flask) :)
