### ISSUE TITLE
Debug option for Django view

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#153]
Would be nice to have the ability to see queries and responses directly from the django shell, I was trying to debug an error on CI and it would have been helpful :)

**Comment by susw12** [comment]
I might be able to help out with this. Could you please provide a little bit more information about what you are looking for?

**Comment by patrick91** [comment]
Hi @susw12, not really to be honest we also have a pretty printer we use for the ASGI server: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/utils/debug.py#L11

But not sure how that would look in django, maybe we can use django's logging mechanism?

**Comment by patrick91** [comment]
Let's rethink the debug option in future :)
