### ISSUE TITLE
Prevent from GraphQL endpoints displayed in FastAPI Swagger UI

### ISSUE THREAD

**Issue by fkromer** [strawberry-graphql/strawberry#1532]
When adding support for GraphQL to FastAPI using the [FastAPI integration](https://strawberry.rocks/docs/integrations/fastapi) one get's missleading output in the Swagger UI (`/docs`):

![image](https://user-images.githubusercontent.com/10199742/147835056-a308e47d-13f2-4762-b7e6-4b4ef666d152.png)

`/docs` should show this instead:

![image](https://user-images.githubusercontent.com/10199742/147835118-0bb99d2e-2b51-46e5-a50f-703d26e04764.png)

**Comment by aryaniyaps** [comment]
@fkromer when including routers in FastAPI you can set the include_in_schema parameter to false to exclude it from the openAPI schema.

**Comment by ArjArav98** [comment]
@aryaniyaps Do you know if it's possible to display only the POST endpoint in the auto-generated docs rather than both GET and POST? I tried setting the `allow_queries_via_get` attribute in the `GraphQLRouter`, provided by Strawberry, but that didn't work.

**Comment by fkromer** [comment]
@aryaniyaps Thanks!
