### ISSUE TITLE
Can child types be queried using the FastAPI + pydantic integration?

### ISSUE THREAD

**Issue by fkromer** [strawberry-graphql/strawberry#1535]
I'm re-implementing the [SWAPI GraphQL API](https://github.com/strawberry-graphql/strawberry-swapi) in a minimal fashion using strawberry, fastapi and the experimental pydantic integration [here](https://github.com/fkromer/fastapi-microservice-patterns/tree/graphql-api/graphql-api). My approach is similar to the one in the [docs about the pydantic integration](https://strawberry.rocks/docs/integrations/pydantic). The difference is that I'm using pydantic.uuid types for the IDs and [custom input types](https://github.com/fkromer/fastapi-microservice-patterns/blob/graphql-api/graphql-api/app/api/types.py#L15-L19).

I'm using these pydantic models:

```
class Person(BaseModel):
    id: UUID1 = Field(default_factory=uuid1)
    name: str
    height: int
    mass: float


class Film(BaseModel):
    id: UUID1 = Field(default_factory=uuid1)
    episode_id: int
    title: str
    characters: List[Person]
```

I can successfully query all films without the characters field with

```
query {
  films {
    id
    title
    episodeId
  }
}
```

However querying all films with characters with

```
query {
  films {
    id
    title
    episodeId
    characters {
      id
      name
      height
      mass
    }
  }
}
```

fails:

```
{
  "data": null,
  "errors": [
    {
      "message": "Expected value of type 'PersonType' but got: <PersonCreateInput instance>.",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "films",
        0,
        "characters",
        0
      ]
    }
  ]
}
```

Am I miss-using something or is this an open issue?

**Comment by patrick91** [comment]
@fkromer do you have the full stack trace? there should be one in the terminal output :)

**Comment by fkromer** [comment]
@patrick91 Here we go...

```
app_1  | INFO:     172.24.0.1:44834 - "POST /graphql HTTP/1.1" 200 OK
app_1  | Expected value of type 'PersonType' but got: <PersonCreateInput instance>.
app_1  | 
app_1  | GraphQL request:6:5
app_1  | 5 |     episodeId
app_1  | 6 |     characters {
app_1  |   |     ^
app_1  | 7 |       id
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/execution/execute.py", line 809, in complete_list_value
app_1  |     completed_item = self.complete_value(
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/execution/execute.py", line 709, in complete_value
app_1  |     completed = self.complete_value(
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/execution/execute.py", line 747, in complete_value
app_1  |     return self.complete_object_value(
app_1  |   File "/usr/local/lib/python3.9/site-packages/graphql/execution/execute.py", line 1005, in complete_object_value
app_1  |     raise invalid_return_type_error(return_type, result, field_nodes)
app_1  | graphql.error.graphql_error.GraphQLError: Expected value of type 'PersonType' but got: <PersonCreateInput instance>.
app_1  | 
app_1  | GraphQL request:6:5
app_1  | 5 |     episodeId
app_1  | 6 |     characters {
app_1  |   |     ^
app_1  | 7 |       id
app_1  | Stack (most recent call last):
app_1  |   File "/usr/local/lib/python3.9/site-packages/strawberry/fastapi/router.py", line 217, in execute
app_1  |     return await self.schema.execute(
app_1  |   File "/usr/local/lib/python3.9/site-packages/strawberry/schema/schema.py", line 152, in execute
app_1  |     self.process_errors(result.errors, execution_context=execution_context)
app_1  | INFO:     172.24.0.1:44836 - "POST /graphql HTTP/1.1" 200 OK
```

**Comment by patrick91** [comment]
@fkromer if you're using interfaces you might need implement `is_type_of`, see: https://github.com/strawberry-graphql/strawberry/pull/1406/files#diff-d7173ce27c6eabcab0b92f00c4769d9fd8ae63d119e70707aeb6174db72b9edeR155

**Comment by fkromer** [comment]
If I add `is_type_of` to all types in [`types.py`](https://github.com/fkromer/fastapi-microservice-patterns/blob/graphql-api/graphql-api/app/api/types.py#L5-L19) like following

```
@strawberry.experimental.pydantic.type(model=Person, all_fields=True)
class PersonType:
    pass

    @classmethod
    def is_type_of(cls, obj, _info) -> bool:
        return isinstance(obj, Person)


@strawberry.experimental.pydantic.type(model=Film, all_fields=True)
class FilmType:
    pass

    @classmethod
    def is_type_of(cls, obj, _info) -> bool:
        return isinstance(obj, Film)


@strawberry.experimental.pydantic.input(model=Person)
class PersonCreateInput:
    name: strawberry.auto
    height: strawberry.auto
    mass: strawberry.auto

    @classmethod
    def is_type_of(cls, obj, _info) -> bool:
        return isinstance(obj, Person)
```

nothing changes.

**Comment by patrick91** [comment]
@fkromer would you be able to paste the whole code for the schema? Or a minimal reproduction case :)

**Comment by fkromer** [comment]
Isn't it easier to reproduce with the overall code? It's available [here](https://github.com/fkromer/fastapi-microservice-patterns/tree/graphql-api/graphql-api).

**Comment by bbsbb** [comment]
Hey @fkromer  you are running into the same issue as reported here https://github.com/strawberry-graphql/strawberry/issues/1504 (for which I have also provided an example).

Since 0.92 order of definition(import) is significant. As a workaround, downgrading strawberry to 0.91 restores the ability to use pydantic with strawberry in a somehow reliable way.

**Comment by fkromer** [comment]
@bbsbb Thanks a lot for that hint!

**Comment by lovetoburnswhen** [comment]
I'm running into the same issue without the use of interfaces and with different models for input/types

**Comment by patrick91** [comment]
@lovetoburnswhen do you have a minimal example we can use to check the issue? :)

**Comment by Matt343** [comment]
@fkromer BTW that issue should be resolved in the latest version 😃

**Comment by fkromer** [comment]
@Matt343 Thx for letting me know.
