### ISSUE TITLE
Loading schema from SDL file

### ISSUE THREAD

**Issue by gokceneraslan** [strawberry-graphql/strawberry#154]
Hi, thanks for this great package. 

I was wondering if there is convenient way to automatically populate Schema objects using a json/SDL file e.g. something similar to the build_schema function in graphql-core-next https://graphql-core-next.readthedocs.io/en/latest/usage/sdl.html ?

**Comment by patrick91** [comment]
Hi @gokceneraslan, this is something we are not planning on implementing, do you have any particular reason why you'd want this in Strawberry? 

Have you already seen [Ariadne](https://github.com/mirumee/ariadne)? Might be what you're looking for!

We were thinking of adding support for converting a SDL to strawberry types (without resolvers), so you could import an SDL as a one time operation, would that be something useful for you?

**Comment by gokceneraslan** [comment]
> Have you already seen [Ariadne](https://github.com/mirumee/ariadne)? Might be what you're looking for!

Oh I didn't know about it, thanks!

> 
> We were thinking of adding support for converting a SDL to strawberry types (without resolvers), so you could import an SDL as a one time operation, would that be something useful for you?

That'd be awesome thanks!
