### ISSUE TITLE
FastAPI router Dependency Context regression - Mapping required.

### ISSUE THREAD

**Issue by bbsbb** [strawberry-graphql/strawberry#1541]
Hey there,

We use a typed object as dependency context with FastAPI( https://fastapi.tiangolo.com/tutorial/dependencies/classes-as-dependencies/ )

After the merge of:  #1494, we are affected by a regression - there is an implicit assumption that the context is limited to Mapping ( https://github.com/strawberry-graphql/strawberry/blob/0.93.16/strawberry/fastapi/router.py#L46 ).
This is not actually a FastAPI requirement. Is it possible to be defensive and allow objects as context as well?

@tsmith023

**Comment by tsmith023** [comment]
Hi Boyan,

If I understand you correctly, you have a custom-defined context dependency in the form of a class rather than a simple dictionary. Then the line that you linked causes your code to break with an error like: ``TypeError: argument must be a mapping, not 'CustomContext'``, as a result. Is this analysis correct?

Since the default context object from previous versions was also a dictionary containing `request` and `background_tasks`, I think the structure of the the merged context object should also be as a dictionary. The `**` operator was introduced so that these default keys were integrated into the context object without introducing breaking changes to those using dictionary custom contexts.

I think the way to appease both class-based and dictionary-based custom contexts is to add functionality in router.py to
- add new attributes `request` and `background_tasks` to the custom context if it's a class,
- maintain the current logic if the custom context is a dictionary.

@patrick91, @Kludex, @BryceBeagle do you guys agree?

If this were implemented, would it be an issue for you if `request` and `background_tasks` were injected into your context object @bbsbb?

**Comment by bbsbb** [comment]
Hey Tommy,

This is spot on and your understanding is correct. The default was indeed always dictionary, but it worked seamlessly with objects.

The suggested implementation seems interesting. It would resolve the underlying issue as far as we are concerned!

**Comment by patrick91** [comment]
@tsmith023 that sounds good! would you be able to send a PR for that? 😊

**Comment by tsmith023** [comment]
@bbsbb, I notice in your initial comment that opened this issue that you describe you custom context dependency as a 'typed object'. Do you mean an instance of a class that has been decorated with @strawberry.type or just a normal class, perhaps even a Pydantic one given your recent PR :)?

**Comment by bbsbb** [comment]
Hey @tsmith023 ,

Good catch. We use a concrete **_instance_** of a class that is a mix of properties passed at instantiation and derived python properties. We use the approach to be able to provide a consistent context between different application entry points (e.g. request, cli etc)

There is no strawberry or pydantic involved. I said typed, simply because we remove some of the brittleness by not using a mapping.

As an example:

```
Class:
 class AppContext:                                                                                                                                                                                                                                                                                                                                                              
     def __init__(                                                                                                                                                                            
         self,                                                                                                                                                                                
         *,                                                                                                                                                                                   
         dep1: Optional[Dep1] = None,                                                                                                                                                                                                                                                                                    
     ):                                                                                                                                                                                                                                                                                                                                                           
         self.dep1 = dep1                                                                                                                     
                                                                                                                                                                                              
     def __call__(self) -> "AppContext":                                                                                                                                                                                                                                                                                 
         return self   
         
# Then within the file and function where app initialization happens and a context would be required:
     # Depends is fastapi's Dependss
     def build_context(app_ctx: AppContext = Depends(ctx)) -> AppContext:                                                                                                                                                                                                                                                                                                   
         return app_ctx          
         
     # ....later with strawberry's GraphQLRouter
     .....GraphQLRouter(graphql_schema(), context_getter=build_context)      
```

The flow is:

Explicitly wire dependencies within the app starting function, create a closure for injector that uses fastapi's Depends with the object.

**Comment by tsmith023** [comment]
@bbsbb, the pull request to address this issue has been merged so I this issue should be closed now.

In short, a new BaseContext class has been introduced that your CustomContext classes must inherit from. Take a look at the docs for a more detailed run-through: https://strawberry.rocks/docs/integrations/fastapi.

Thanks for raising this issue! In my book, the class-based context object is lot clearer than the dictionary-based one so it's great that this has been implemented :smiley:
