### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by agritheory** [strawberry-graphql/strawberry#156]
Because GitHub does not support PR's against wikis, please review the changes at:
https://github.com/agritheory/strawberrywiki

I added what was to me the next obvious step, which was documenting interactions with the strawberry dev server.

I plan to continue to add add tutorial-ish pages, next with a nested data example and a fragment.

**Comment by patrick91** [comment]
@agritheory oh that looks like a good start! would like to add a PR using Mkdocs? 

I was speaking with @jaydenwindle about using Gatsby for the new website, but that's going to take a bit of time (as I'm waiting for a design), but I'm sure we can re-use the mkdocs things :D

**Comment by agritheory** [comment]
Really any markdown-friendly static site generator will work, right? Having it read the md from here does two things: it synchronizes the wiki and the documents but still allows you to host project documentation in the style you want to on an independent site (presumably with other features if needed, like a independent dev blog or something). GitHub pages would work for this, I would think.

**Comment by patrick91** [comment]
@agritheory yes, so my idea was, add docs here, so one could read on GitHub (or even locally if you downloaded the repo).

Make a new repo for the website and automatically pull docs from this repo (should be easy with Gatsby). So all the docs will live here, but the code for the site will be in another repo :)

I can setup an example in the next few days to show how this would work :)

**Comment by patrick91** [comment]
I’ll close this as we will be using Gatsby for our website and docs.
