### ISSUE TITLE
Lightning Talk on Strawberry

### ISSUE THREAD

**Issue by PythonLinks** [strawberry-graphql/strawberry#157]
i watched the excellent talk on GraphQL and strawberry at EuroPython 1019.  This library makes a lot of sense to me.  But sadly people want 5 minute lightning talks.  Has anyone created one.  I want to add it to PythonLinks.info.

**Comment by patrick91** [comment]
@PythonLinks I did one here: https://youtu.be/TAhBIzOjo2c?t=1047 hope that's good enough :)

**Comment by patrick91** [comment]
I'll close this for now, let me know if there's any other question!
