### ISSUE TITLE
GraphQLTestClient doesn't handle variables correctly if files are present

### ISSUE THREAD

**Issue by N-Maas** [strawberry-graphql/strawberry#1572]
If at least one file is used, the `query` method of the test client interprets all variables as if they were a file upload, although the query may contain other variables that are not files.

I think the cause is the implementation of `BaseGraphQLTestClient._build_multipart_file_map` in `strawberry.test.client` which behaves as if each variable is a file.

**Comment by estyxx** [comment]
Oh I will have a look at this!
