### ISSUE TITLE
Variable '$user' of type 'AddUserInput' used in position expecting type 'AddUserInput!

### ISSUE THREAD

**Issue by zy7y** [strawberry-graphql/strawberry#1575]
code
```python
from datetime import datetime
from typing import List

import strawberry
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

engine = create_async_engine(
    "mysql+aiomysql://root:123456@localhost:3306/sqlmap?charset=utf8mb4",
    echo=True,
)

async_session = sessionmaker(
    engine, expire_on_commit=True, class_=AsyncSession
)

session = async_session()


# 查询模型
@strawberry.type
class User:
    id: int = strawberry.field(description='用户id')
    username: str = strawberry.field(description='用户名')
    created: datetime = strawberry.field(description='创建时间')


@strawberry.type
class Message:
    errmsg: str = 'ok'


# 输入参数模型
@strawberry.input
class AddUserInput:
    username: str = strawberry.field(description='用户名')
    password: str = strawberry.field(description='密码')


# resolver
async def resolver_get_user():
    """获取用户列表"""
    results = await session.execute('select id, created, username from user;')
    return [User(**dict(zip(result.keys(), result))) for result in results]


@strawberry.type
class Query:
    users: List[User] = strawberry.field(resolver=resolver_get_user)


@strawberry.type
class Mutation:

    @strawberry.field
    async def add_user_input(self, user: AddUserInput) -> User:
        sql = 'insert into user (username, password) values ( "%s", "%s")' % (user.username, user.password)
        await session.execute(sql)
        await session.commit()
        sql = 'select id,username,created from user order by id desc limit 1'
        results = await session.execute(sql)
        return [User(**dict(zip(result.keys(), result))) for result in results][0]


schema = strawberry.Schema(query=Query, mutation=Mutation)

```
error:  Variable '$user' of type 'AddUserInput' used in position expecting type 'AddUserInput!
![image](https://user-images.githubusercontent.com/67154681/149260888-25a6fe17-0a21-40ff-889d-8228269a6494.png)

suceess
![image](https://user-images.githubusercontent.com/67154681/149261243-2bb4a1f4-d1df-4ea9-8959-a57f3c9d227a.png)

I don't know what's wrong

**Comment by BryceBeagle** [comment]
In your Python code, you annotated the function as being non-nullable (or rather, you _didn't_ use `Optional`), but in your query you made it nullable (by not using `!`).

That's what the error message is complaining about.

**Comment by zy7y** [comment]
> In your Python code, you annotated the function as being non-nullable (or rather, you _didn't_ use `Optional`), but in your query you made it nullable (by not using `!`).
> 
> That's what the error message is complaining about. Because the actual resolver is stricter than the function in your query, GraphQL doesn't allow it.
> 
> This can be a bit tricky, as the patterns that GraphQL schemas/queries use are a bit backwards from the way you define them in Strawberry.

Thank you. It has been modified and the result I expected is normal
```query
mutation addUserInput($user: AddUserInput!){
  addUserInput(user:$user){
    id
  }
}
```
