### ISSUE TITLE
Replace `cached_property` with `backports.cached_property`

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1578]
A minor one, but I'm getting typing errors due to `cached_property` not being type annotated.

I've tested https://github.com/penguinolog/backports.cached_property and the types are working fine so I'd say we can move to that library instead.

Unless there's any reason not to move 😊

**Comment by RishiKumarRay** [comment]
I would like to do it, can you tell where i can find the code

**Comment by patrick91** [comment]
We have it in a couple of places: https://github.com/strawberry-graphql/strawberry/search?q=cached_property

You need to remove the old dependency with `poetry remove cached_property`, add the new one and then replace the imports :)

**Comment by RishiKumarRay** [comment]
Assign it to me , i will do this

**Comment by patrick91** [comment]
> Assign it to me , i will do this
> 
> 

Done :)

**Comment by RishiKumarRay** [comment]
Please do review , I have updated as you suggested

**Comment by RishiKumarRay** [comment]
@BryceBeagle  Hi, Actually while discussing the issue i thought i have to just update the references wherever cached_property is present , first I removed cached-property with poetry remove cached-property then added backports.cached_property with poetry added  backports.cached_property and the renamed everywhere where cached_property was present.

but now i understood how to import , i would like to ask one more thing do i have to change @cached_property annotations too?

**Comment by RishiKumarRay** [comment]
@patrick91 @BryceBeagle I have done the changes can you review the PR now and let me know
