### ISSUE TITLE
Setup docs with mkdocs

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#158]
https://www.mkdocs.org

A friend of mine is working on a design for the new website which will also include the docs, but for now I think we can start with mkdocs. The new website will pull the documentation from this repo so no work will be wasted in case we start this before the new website :)

**Comment by LeptoSpira** [comment]
Just as a note, we can also use other tools such as [Docusaurus](https://docusaurus.io/) and [DocFX](https://dotnet.github.io/docfx/)

**Comment by LeptoSpira** [comment]
If I were to have a go at this, would I be able to use any of these other tools?

**Comment by patrick91** [comment]
@LeptoSpira hi there! My only requirement is that the docs source are in markdown files :) 

The end goal would be to have documentation files here and maybe in the meantime use a tool like mkdocs (the only one I tried) or similar to have a documentation site and the migrate to the new website which is going to use Gatbsy JS (a friend of mine is working on the design for it). 

The idea is to have all the docs here in markdown files and have a new repo for the website which will then pull docs content from this repo, but for now we can't start in the website as I'm waiting for designs :) So in the meanwhile we can use mkdocs or similar, if that makes sense :)

**Comment by Ultra-Instinct-05** [comment]
Hello @patrick91. Can I take up this issue ? I had documented one of my previous projects with mkdocs.

**Comment by patrick91** [comment]
@Ultra-Instinct-05 yes!

**Comment by Ultra-Instinct-05** [comment]
@patrick91 . How should I proceed with this ? Anything specific to remember before implementing this ?

**Comment by patrick91** [comment]
@Ultra-Instinct-05 other that what has been mentioned here not really, feel free to send a draft PR when you have one and I'll review the approach ;)

I'll take care of deploy the docs too :)

**Comment by tomasmor42** [comment]
Looks like this one doesn't have any movement for a while, so I'm starting working on it.

**Comment by patrick91** [comment]
I’ll close this as we will be using Gatsby for the docs :)
