### ISSUE TITLE
Support GET for fetching queries when GraphiQL is turned off (FastAPI)

### ISSUE THREAD

**Issue by nina-j** [strawberry-graphql/strawberry#1584]
The official documentation lists best practices for serving over HTTP [here](https://graphql.org/learn/serving-over-http).
In particular, it mentions support of [GET requests to fetch queries](https://graphql.org/learn/serving-over-http/#get-request).

Strawberry does not currently support this (at least not in the FastAPI integration, unsure about others), and will simply return 404 when GraphiQL is turned off. 

I think it should! For the FastAPI integration, we probably need something along the lines of how POST requests are handled, cf. https://github.com/strawberry-graphql/strawberry/blob/b021481d253f5e6cc56f4bd09c548f97acd9fd84/strawberry/fastapi/router.py#L111-L123

**Comment by MattExact** [comment]
Just FYI I have started looking at adding this for FastAPI and the other integrations 👍

**Comment by DoctorJohn** [comment]
(Related to #834)

**Comment by MattExact** [comment]
Hey just to update, apologies I got busy with work / personal stuff
I have done most of the leg work already, and got query params working on all integrations at the time of my last comment - it's just been sitting on a branch on my fork 😬
Just needs a bit of polish which I am gonna try get done this weekend.
I need to check test coverage, ensure consistent request logic, and maybe add documentation on supported requests to the respective integrations.
