### ISSUE TITLE
Ability to hide elements from federated schema but preserve in internal schema

### ISSUE THREAD

**Issue by djmcgreal-cc** [strawberry-graphql/strawberry#1585]
Hi, 
I haven't found a way to hide fields from federation, i.e. exclude them from `service { sdl }`. Coupled with Strawberry validating that types must have "one or more fields", this means that my outward facing Query has to have at least one field from every backing service I want to use Strawberry to serve. Currently I'm making `void: str @deprecated` fields, which are rather unsightly.

Thanks, Dan.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1585">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1585/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1585/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@djmcgreal-cc is this something that's supported by federation itself?

**Comment by djmcgreal-cc** [comment]
Hi Patrick,
Yes, a backing service decides what to include by adding it to the `service { sdl } }`.

**Comment by patrick91** [comment]
> Hi Patrick, Yes, a backing service decides what to include by adding it to the `service { sdl } }`.

Can you show me an example of this in a code first framework? I don't think I have ever seen it :)

**Comment by djmcgreal-cc** [comment]
I can't help you there I'm afraid, I don't have enough experience of other frameworks. I don't think it's related to choice of paradigm though. Apollo's `buildFederatedSchema` method doesn't require a Query definition, so it's possible to contribute to a subgraph that doesn't extend from the Query root.

Other than an ability to hide fields from federation, can you think of another way to add a subgraph via Strawberry that doesn't also introduce redundant fields into the Query type?

Thanks, Dan.

**Comment by patrick91** [comment]
This should be supported by using @inaccessible https://www.apollographql.com/docs/federation/federated-types/federated-directives/#inaccessible
