### ISSUE TITLE
Add a complete example in schema basic documentation

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1595]
This came up from discord, in the Schema Basic docs: https://strawberry.rocks/docs/general/schema-basics we have two types that reference each other but we don't show how to create resolvers for that. This is not beginners friendly

The easiest solution could be to clean up and copy this gist (https://gist.github.com/patrick91/362b4de2a341c879a53f8c2ae8588b7e) at the end of the page

**Comment by tsmith023** [comment]
@patrick91, I'll make these changes today :smile:
