### ISSUE TITLE
Feature Request: provide a mechanism to change the conversion from Pydantic to Strawberry

### ISSUE THREAD

**Issue by Matt343** [strawberry-graphql/strawberry#1617]
Currently, we use a registration mechanism and some basic rules to figure out how a type should be converted from Pydantic to Strawberry and vice versa. The rules map scalars to their equivalent scalar using some hard-coded mappings, then recursively build up more complex types from there.

This is all great for automatic conversion, but there are use cases where I'd like to be able to provide a registered Strawberry type that doesn't follow these rules, and instead uses some custom logic to convert to and from the Pydantic type. 

An example of when this would be useful is if I'm defining a custom scalar that I want to be used in some of the fields of the model:

```python
class MyModel(pydantic.BaseModel):
    my_field: int

CustomInt = strawberry.scalar(NewType("CustomInt", int), ...)

@strawberry.experimental.pydantic.type(model=MyModel)
class MyStrawberryModel:
    my_field: strawberry.auto  # I want this to be wrapped in CustomInt during the conversion so it uses my custom serializer logic
```

Another time this would be helpful is when the Pydantic model represents some type or value that I don't want to translate directly to GraphQL types, either because it is cumbersome/undesirable, or because it is actually not representable in GraphQL. An example of the latter case would be anything involving unions of scalar fields, which GraphQL doesn't know how to represent. If I could provide custom conversion logic, I could keep the union type in Pydantic but provide some alternative concrete type in Strawberry land.

```python
class MyModel(pydantic.BaseModel):
    my_field: Union[int, str]

@strawberry.experimental.pydantic.type(model=MyModel)
class MyStrawberryModel:
    my_field: strawberry.auto  # I want this to be mapped to a specific type in Strawberry
```

The overall goal here is to be able to support existing (possibly highly used and constrained already) Pydantic models in Strawberry with more flexibility. There are definitely cases where it's helpful to be able to change the data representation during conversion beyond these, this is just what I've run into during my implementation. The problem today is that if you want to do custom conversions/types for one piece of a deeply nested hierarchy, the entire conversion process from Pydantic fails because the types aren't registered as being related to the Pydantic models.

**Comment by patrick91** [comment]
This is reasonable. Did you have any idea on how it would look?

The first idea I can think of is of doing a global configuration, but this is something we don't really support right now[1].

The other option is to add a configuration on the schema and do the conversion of the types later 🤔 

[1]: we support per schema configuration at the moment

**Comment by Matt343** [comment]
My thought was something like this:

```
class MyModel(pydantic.BaseModel):
    my_field: int

CustomInt = strawberry.scalar(NewType("CustomInt", int), ...)

@strawberry.experimental.pydantic.type(model=MyModel)
class MyStrawberryModel:
    my_field: CustomInt

    def to_pydantic(self):
        return MyModel(my_field=int(self.my_field))

    @classmethod
    def from_pydantic(cls, pydantic_model):
        return MyStrawberryModel(my_field=CustomInt(pydantic_model.my_field))
```

Note that this code works today if you use `strawberry.type` and then set up the `_strawberry_type` and `_pydantic_type` references yourself, but that's a horrible hack 😆

**Comment by thejaminator** [comment]
just to clarify :) 
for the first example whats the rationale behind not doing it in the parse_value / serialize argument of scalar type?
```
class MyModel(pydantic.BaseModel):
    my_field: int

CustomInt = strawberry.scalar(NewType("CustomInt", int), parse_value = my_custom_parsing, serialize = my_custom_serialize)

@strawberry.experimental.pydantic.type(model=MyModel)
class MyStrawberryModel:
    my_field: CustomInt
```
is the reason to provide that logic for that particular MyStrawberryModel instead of that particular type?

**Comment by Matt343** [comment]
So if you try that example it actually doesn't work for me, because it's not clear what's supposed to happen when you have a field redefined in the Strawberry model but you don't use `auto`. What happens right now is confusing, if it's the only field in the model like this example it fails because technically you haven't pulled any fields from the pydantic model. If you add a second field, you will get the desired behavior, but only because there is an undocumented feature that the Pydantic converter implicitly calls the constructor of the type you specify on the Strawberry type (I'm still not sure why this actually happens btw). So in that case it will wrap the int in `CustomInt` when converting to Strawberry, and then things will work.

I'm not sure what we're actually supposed to do in this kind of case, because the current behavior gives you some limited control over the conversion behavior by specifying alternate types, but only allows you to use types that are convertible to each other through their constructors. This behavior just seems weird and counterintuitive to me, and I think a more explicit approach is better in the long run, whether that's refining and documenting this behavior or something like I've proposed here.

Additionally, if you want to make more structural changes to the type (like combining two fields into one or flattening a list or something), then the type conversion method is definitely not powerful enough to use.

**Comment by thejaminator** [comment]
> Additionally, if you want to make more structural changes to the type (like combining two fields into one or flattening a list or something), then the type conversion method is definitely not powerful enough to use.

yep definitely agreed on this. overriding to_pydantic and from_pydantic is nice and explicit / discoverable too. :)

**Comment by Matt343** [comment]
> I'm not sure what we're actually supposed to do in this kind of case, because the current behavior gives you some limited control over the conversion behavior by specifying alternate types, but only allows you to use types that are convertible to each other through their constructors. This behavior just seems weird and counterintuitive to me, and I think a more explicit approach is better in the long run, whether that's refining and documenting this behavior or something like I've proposed here.

Anyone have thoughts on this part? I'm thinking the current behavior is nice but can be confusing, but maybe with some documentation and cleanup it could be useful?
