### ISSUE TITLE
[Feature Request] Name attribute for schema

### ISSUE THREAD

**Issue by Speedy1991** [strawberry-graphql/strawberry#1651]
I have two schemas (frontend/backend) with a shared type
Inside the Type I want to resolve all items for the backend admins but a filtered set for the frontend
My current solution is a path chek like this:

```python
@strawberry.type
class SharedType:

  @strawberry.field
  def items(self, info) -> List[ItemType]:
    if info.context.request.path == '/api/backend/':
        return self.item_set.all()
    return self.item_set.exlude(hidden=True)
```
But this is bounded to the path. A better solution would be a named schema - so I can resolve depending on the mounted schema, e.g.:

```python
def items(self, info) -> List[ItemType]:
    if info.schema.name == 'backendSchema':
        ...
```
instanciating the schema with an optional name like this:

```python
frontend_schema = strawberry.Schema(..., name="backendSchema", types=[SharedType])
backend_schema = strawberry.Schema(..., name="frontendSchema", types=[SharedType])
```

**Comment by patrick91** [comment]
@Speedy1991 have you tried extending the schema class and adding a name there? 😊

**Comment by patrick91** [comment]
@Speedy1991 did that work? :)

**Comment by Speedy1991** [comment]
Yea works like a charm. Thanks for the idea :)
