### ISSUE TITLE
auto cannot be used with Annotated

### ISSUE THREAD

**Issue by bellini666** [strawberry-graphql/strawberry#1659]
Because `strawberry.auto` is a sentinel, and thus an object, it cannot be used with `Annotated` or anything else expecting a type instead an object.

It should probably change to:

```python
class auto:
    pass
```

Any downsides to that approach? Any extra protection we need to add to it?

**Comment by patrick91** [comment]
what's your use case for annotated? 😊

**Comment by bellini666** [comment]
Hey @patrick91 !

In a project at my company we have an automatic CRUD builder at the frontend (something like django admin does). The backend introspects itself to provide information regarding fields and retrieve information like label, help text and other relevant information from the django field.

Sometimes the field might be a virtual field (so we don't have info like `verbose_name`, `help_text` in it), or even I may want to send something different from the model's definition to the frontend. To workaround that, I'm annotating the field to provide extra information for that introspection code. For example:

```python
@strawberry.django.field(Foobar):
class FoobarType
    field_a: Annotated[str, FieldOverride(label="Overriden Label A")]
    field_b: Annotated[auto, FieldOverride(label="Overriden Label B")]
```

That works for `field_a`, because `str` is a type`, but `strawberry.auto` raises an error because it is not. For example:

```python
In [4]: Annotated[object, object()]
Out[4]: typing.Annotated[object, <object object at 0x7f54920ee880>]

In [5]: Annotated[object(), object()]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <module>
----> 1 Annotated[object(), object()]

File /usr/lib/python3.9/typing.py:277, in _tp_cache.<locals>.decorator.<locals>.inner(*args, **kwds)
    275 except TypeError:
    276     pass  # All real errors (not unhashable args) are raised below.
--> 277 return func(*args, **kwds)

File /usr/lib/python3.9/typing.py:1339, in Annotated.__class_getitem__(cls, params)
   1335     raise TypeError("Annotated[...] should be used "
   1336                     "with at least two arguments (a type and an "
   1337                     "annotation).")
   1338 msg = "Annotated[t, ...]: t must be a type."
-> 1339 origin = _type_check(params[0], msg)
   1340 metadata = tuple(params[1:])
   1341 return _AnnotatedAlias(origin, metadata)

File /usr/lib/python3.9/typing.py:166, in _type_check(arg, msg, is_argument, module, is_class)
    164     return arg
    165 if not callable(arg):
--> 166     raise TypeError(f"{msg} Got {arg!r:.100}.")
    167 return arg

TypeError: Annotated[t, ...]: t must be a type. Got <object object at 0x7f54920ee8e0>.
```

Maybe there are some other use cases like mine out there =P

obs. Note that the current django integration defines its own `auto`, which is basically a `class auto: pass`. I monkey patched it previously in my strawberry-django-plus extension to use this repo's auto, to keep a default auto between the two (so I could use `strawberry.auto` directly), but had to revert that change because it prevented me from using it in with `Annotated`
