### ISSUE TITLE
How to pass a custom name to an argument?

### ISSUE THREAD

**Issue by gpsa** [strawberry-graphql/strawberry#1693]
Hi, 

when trying to implement a mutation (but it also happens on queries' arguments as well), I got the W0622 pylint complain.

```
Field's Argument's alternative declaration to avoid W0622: Redefining built-in 'id' (redefined-builtin)
Field's Argument's alternative declaration to avoid W0622: Redefining built-in 'type' (redefined-builtin)
```

The mutation example:

```python
@strawberry.mutation
async def update_tag(
        self,
        id: int,
        name: str,
        type: typing.Optional[str],
        desc: typing.Optional[str] = None,
        active: typing.Optional[bool] = None,
    ) -> TagNode:
```

Would that make sense to have something like:
- `argument_aliases={"pk": "id", "tag_type": "type"}`
```python
@strawberry.mutation(argument_aliases={"pk": "id"})
async def update_tag(
        self,
        pk: int, 
        name: str,
        tag_type: typing.Optional[str],
        desc: typing.Optional[str] = None,
        active: typing.Optional[bool] = None,}
    ) -> TagNode:
```

**Comment by patrick91** [comment]
@gpsa we support the following syntax:

```python
@strawberry.mutation
async def update_tag(
        self,
        id_: int = Annotated[strawberry.ID, strawberry.argument(name="id")],
        name: str,
        type_: Annotated[Optional[str] strawberry.argument(name="type")],
        desc: typing.Optional[str] = None,
        active: typing.Optional[bool] = None,
    ) -> TagNode:
```

see an example [here](https://la4de.github.io/strawberry-playground/#UEsDBAoAAAAAACCcYlQgaUU4EgAAABIAAAAQAAAAcmVxdWlyZW1lbnRzLnR4dHN0cmF3YmVycnktZ3JhcGhxbFBLAwQKAAAAAAAgnGJUpbii500BAABNAQAACQAAAHNjaGVtYS5weWltcG9ydCBzdHJhd2JlcnJ5CmZyb20gdHlwaW5nIGltcG9ydCBBbm5vdGF0ZWQKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgVXNlcjoKICAgIG5hbWU6IHN0cgogICAgYWdlOiBpbnQKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgUXVlcnk6CiAgICBAc3RyYXdiZXJyeS5maWVsZAogICAgZGVmIHVzZXIoc2VsZiwgaWRfOiBBbm5vdGF0ZWRbc3RyYXdiZXJyeS5JRCwgc3RyYXdiZXJyeS5hcmd1bWVudChuYW1lPSJpZCIpXSkgLT4gVXNlcjoKICAgICAgICByZXR1cm4gVXNlcihuYW1lPSJQYXRyaWNrIiwgYWdlPTEwMCkKCnNjaGVtYSA9IHN0cmF3YmVycnkuU2NoZW1hKHF1ZXJ5PVF1ZXJ5KVBLAwQKAAAAAAAgnGJUhjc84igAAAAoAAAACQAAAHF1ZXJ5LmdxbHsKICB1c2VyKGlkOiAxKSB7CiAgICBuYW1lCiAgICBhZ2UKICB9Cn1QSwMECgAAAAAAIJxiVKi7vnMDAAAAAwAAAA4AAAB2YXJpYWJsZXMuanNvbnsKfVBLAQIUAAoAAAAAACCcYlQgaUU4EgAAABIAAAAQAAAAAAAAAAAAAAAAAAAAAAByZXF1aXJlbWVudHMudHh0UEsBAhQACgAAAAAAIJxiVKW4oudNAQAATQEAAAkAAAAAAAAAAAAAAAAAQAAAAHNjaGVtYS5weVBLAQIUAAoAAAAAACCcYlSGNzziKAAAACgAAAAJAAAAAAAAAAAAAAAAALQBAABxdWVyeS5ncWxQSwECFAAKAAAAAAAgnGJUqLu+cwMAAAADAAAADgAAAAAAAAAAAAAAAAADAgAAdmFyaWFibGVzLmpzb25QSwUGAAAAAAQABADoAAAAMgIAAAAA)

I'll close this, but let me know if you have more questions :)

**Comment by gpsa** [comment]
Hey @patrick91 ,  thank you so much your quick reply. Yeah that's good to know that we have this option 👏 
Can I at least suggest an update to the documentation? I didn't see any example of the `Annotated` (except by the fact that it's only exemplified on [exceptions](https://strawberry.rocks/docs/types/exceptions#multiplestrawberryargumentserror))

Maybe something [here](https://strawberry.rocks/docs/types/resolvers#resolvers) or a full topic explaining about `strawberry.fields`?
