### ISSUE TITLE
Documentation sidebar is inaccessible on mobile/narrow screens

### ISSUE THREAD

**Issue by huonw** [strawberry-graphql/strawberry#1724]
Thanks for Strawberry, and its documentation.

I noticed that on a narrow screen (e.g. mobile or a desktop window that's been made thin), the sidebar disappears, and most of the pages within it become inaccessible. The only link to documentation is the one in the header (https://strawberry.rocks/docs), and then there's a few links within that, but other than those, the rest of the pages cannot be found either by the side bar or search, because those elements seem to be fully hidden.

Wide screen:

![image](https://user-images.githubusercontent.com/1203825/158104369-c75eb15a-4000-48f5-bcf5-27dafe12e3b4.png)

Narrow screen:

![image](https://user-images.githubusercontent.com/1203825/158104394-2cb6c463-bb93-45ff-bbe7-a070ce00790f.png)

Maybe the sidebar could be hidden under an expandable menu rather than totally removed? (Admittedly it's slightly unusual to be reading technical docs on a mobile/narrow screen like this.)

**Comment by patrick91** [comment]
@huonw don't you get a compass at the bottom? 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/667029/158105285-5cc0f6ac-183a-472b-b589-7f8846acb669.png">

**Comment by huonw** [comment]
Ah, I do. I didn't realise it was for navigation, sorry. (I guess I just skipped over it as if it was one of those buttons for support or sales, rather than something relevant to me 😄 )
