### ISSUE TITLE
Single-result-operations don't reserve the Subscription ID

### ISSUE THREAD

**Issue by kristjanvalur** [strawberry-graphql/strawberry#1734]
Single request operations should behave like regular streaming operations, in that they must have a
unique **Id** (for any active oprations).
The Id provided for a single result operation is not placed in `self.subscriptions` and therefore there is no validation on it.  Hence it would appear that it is possible to schedule two single result operations simultaneously with the same ID, or to use an ID that is currently in use for a regular streaming operation.

All Ids should probably be put into the same table (`self.subscriptions`) when encountered and removed from it once completed.

**Comment by kristjanvalur** [comment]
Please see recently updated https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

**Comment by DoctorJohn** [comment]
This issue has been resolved in #1792. Thanks for the report and the PR :)
