### ISSUE TITLE
Single-result-operation cannot be overlapped or cancelled

### ISSUE THREAD

**Issue by kristjanvalur** [strawberry-graphql/strawberry#1738]
Single result operations are performed synchronously in response to a websocket message, meaning that other messages are not handled on the websocket until they complete.
This prevents single-result requests from taking a long time or being cancelled.

**Comment by kristjanvalur** [comment]
The protocol spec at https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md has recently been updated to clarify how single-response-requests are simply special cases of subscriptions.

**Comment by DoctorJohn** [comment]
This issue has been resolved in #1792. Thanks for the report and the PR :)
