### ISSUE TITLE
GET-request's data gets searched in request.json

### ISSUE THREAD

**Issue by basvandriel** [strawberry-graphql/strawberry#1758]
[On this line](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/flask/views.py#L52) (Flask's view) the data is retrieved from `request.json`. [Stated in the docs](https://graphql.org/learn/serving-over-http/#get-request), a query can be send like;

`http://myapi/graphql?query={me{name}}`

This data lands in `request.args`. This [feature ](https://www.apollographql.com/docs/react/networking/advanced-http-networking/#constructor-options)can be used in Apollo using the `useGETForQueries` option. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1758">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1758/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1758/pledge.svg">
</picture>
</a>

**Comment by basvandriel** [comment]
Related to #1708

**Comment by patrick91** [comment]
This should be done here: https://github.com/strawberry-graphql/strawberry/pull/1686
