### ISSUE TITLE
How to add description to enum members

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#1780]
How can I add a description for enum members?

**Comment by patrick91** [comment]
Hi @devkral this is not supported yet! I think we can easily add it after merging this PR: https://github.com/strawberry-graphql/strawberry/pull/1720

**Comment by N-Maas** [comment]
+1 to the feature request. Now that #1720 is merged, I hope it should be rather easy.

**Comment by devkral** [comment]
solved
