### ISSUE TITLE
Access authenticated user from permissions

### ISSUE THREAD

**Issue by ZeroIntensity** [strawberry-graphql/strawberry#1786]
is it possible to access the authenticated user from a resolver when using permission classes?

for example:
```py
class Authenticated(BasePermission):
    message = "Not authenticated."

    def has_permission(self, source: typing.Any, info: Info, **kwargs) -> bool:
        ...

@strawberry.field(permission_classes=[Authenticated])
def requires_login(something: str) -> str:
    # is it possible to get the authenticated user from here?
    ...

@strawberry.type
class Query:
    requires_login = requires_login
```

if there's an easy solution to this, please put it in the documentation.

**Comment by patrick91** [comment]
@ZeroIntensity you should be able to access the context from `info.context`, if your view sets the user there you should be able to access it :)

Here's the documentation for get context (in django, but the concept is the same for other integrations): https://strawberry.rocks/docs/integrations/django#get_context

You'd need to do something like

```python
class MyGraphQLView(GraphQLView):
    def get_context(self, request: HttpRequest, response: HttpResponse) -> Any:
        return {"user": request.user}
```

and then you can do `info.context["user"]` :)

**Comment by ZeroIntensity** [comment]
i'm not using django in my case, is it possible to do it with fastapi/starlette?

**Comment by ZeroIntensity** [comment]
oh wait, didn't read the full thing, my bad. thank you!
