### ISSUE TITLE
Security vulnerabilities when passing credentials in resolver?

### ISSUE THREAD

**Issue by ZeroIntensity** [strawberry-graphql/strawberry#1788]
yesterday i created an issue addressing how to work with authentication classes inside resolvers. it seemed like a bit of a hassle to work with opposed to just passing the credentials inside the resolver itself. does this have any known issues or security vulnerabilities?

for example:

```gql
doSomethingThatRequiresLogin(
  login: { # is it ok to pass in the credentials here?
    username: "some username",
    password: "c29tZSBwYXNzd29yZA==" # base64 encoded
  },
  data: {
    a: "b" # actual data here
  }
)
```

i understand sending login info in the graphql request may get a bit repetitive, but is there any reason not to in terms of security?

**Comment by patrick91** [comment]
Hi @ZeroIntensity, that's a great question!

So i wouldn't send username and password on every GraphQL operation, I'd instead use a mutation to login (and one to logout) your users, then you can use either cookies or JWT for handling the authentication. Cookies are usually easier to work with, so I'd recommend that :)

The other thing I'd advise is to **not** pass the credentials inside the operation, but instead use variables:

```graphql
mutation login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ok
  }
)
```			

client libraries usually allow to pass variables pretty easily :)

The reason why I recommend this is that operations might be logged and in that case you would be leaking user data.

**Comment by ZeroIntensity** [comment]
sounds good, but wouldn't cookies cause other vulnerabilities?

another website could execute the following code:

```js
!async function main() {
    await fetch(".../graphql", {
        headers: {
            "Content-Type": "application/json",
        },
        method: "POST",
        body: JSON.stringify({
            query: 'mutation { changePassword(newpass: "abc123") }' // the site doesn't have to know the password
        })
    })
}()
```

**Comment by patrick91** [comment]
@ZeroIntensity take a look at this https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security

> Cookies that are used for sensitive information (such as indicating authentication) should have a short lifetime, with the [SameSite attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#samesite_attribute) set to Strict or Lax. (See SameSite attribute, above.) In [browsers that support SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#browser_compatibility), this ensures that the authentication cookie isn't sent with cross-site requests. This would make the request effectively unauthenticated to the application server.

**Comment by ZeroIntensity** [comment]
alright, thank you!
