### ISSUE TITLE
Add better documentation for `UNSET`

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#1805]
Currently, the only documentation of `UNSET` is on our [pagination docs ](https://strawberry.rocks/docs/guides/pagination)(and in our unit tests). We should add first-class documentation for it

**Comment by patrick91** [comment]
we might want to move it as well, right now it lives inside strawberry.arguments, but it also useful for input fields 🤔

**Comment by DominiqueGarmier** [comment]
I have never used `UNSET`, if I understand it correctly it is used to differentiate between `null` (`None` in python) and no argument passed i.e. `UNSET`?

Also I would recommend to simply move `UNSET` into https://github.com/strawberry-graphql/strawberry/blob/7d79bf9a7d7f2816bd1243f24216903c020758e3/strawberry/unset.py since this file already exists it would make sense to move the instantiation there too. Any opinions?

**Comment by patrick91** [comment]
@DominiqueGarmier yes, exactly, here's an example of it [playground](https://play.strawberry.rocks/#UEsDBAoAAAAAAHF8kFQgaUU4EgAAABIAAAAQAAAAcmVxdWlyZW1lbnRzLnR4dHN0cmF3YmVycnktZ3JhcGhxbFBLAwQKAAAAAABxfJBUV3pSGm0BAABtAQAACQAAAHNjaGVtYS5weWZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbAoKaW1wb3J0IHN0cmF3YmVycnkKZnJvbSBzdHJhd2JlcnJ5LmFyZ3VtZW50cyBpbXBvcnQgVU5TRVQKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgVXNlcjoKICAgIG5hbWU6IHN0cgogICAgYWdlOiBpbnQKCkBzdHJhd2JlcnJ5LnR5cGUKY2xhc3MgUXVlcnk6CiAgICBAc3RyYXdiZXJyeS5maWVsZAogICAgZGVmIHVzZXIoc2VsZiwgbmFtZTogT3B0aW9uYWxbc3RyXSA9IFVOU0VULCBhZ2U6IE9wdGlvbmFsW2ludF0gPSBOb25lKSAtPiBVc2VyOgogICAgICAgIHJldHVybiBVc2VyKG5hbWU9IlBhdHJpY2siLCBhZ2U9MTAwKQoKc2NoZW1hID0gc3RyYXdiZXJyeS5TY2hlbWEocXVlcnk9UXVlcnkpUEsDBAoAAAAAAHF8kFRuzJgNIQAAACEAAAAJAAAAcXVlcnkuZ3FsewogIHVzZXIgewogICAgbmFtZQogICAgYWdlCiAgfQp9UEsDBAoAAAAAAHF8kFSou75zAwAAAAMAAAAOAAAAdmFyaWFibGVzLmpzb257Cn1QSwECFAAKAAAAAABxfJBUIGlFOBIAAAASAAAAEAAAAAAAAAAAAAAAAAAAAAAAcmVxdWlyZW1lbnRzLnR4dFBLAQIUAAoAAAAAAHF8kFRXelIabQEAAG0BAAAJAAAAAAAAAAAAAAAAAEAAAABzY2hlbWEucHlQSwECFAAKAAAAAABxfJBUbsyYDSEAAAAhAAAACQAAAAAAAAAAAAAAAADUAQAAcXVlcnkuZ3FsUEsBAhQACgAAAAAAcXyQVKi7vnMDAAAAAwAAAA4AAAAAAAAAAAAAAAAAHAIAAHZhcmlhYmxlcy5qc29uUEsFBgAAAAAEAAQA6AAAAEsCAAAAAA==)

**Comment by DominiqueGarmier** [comment]
https://github.com/strawberry-graphql/strawberry/pull/1813 i wrote a pull request

**Comment by Sarahoyos** [comment]
Hey @BryceBeagle can you please provide an updated documentation `of UNSET` when I click on the link you provided it gives me an error ![Image](https://github.com/user-attachments/assets/1c62fb76-f54b-4bde-bdc2-3c0658e4d5f5)

**Comment by BryceBeagle** [comment]
The new documentation can be found at https://strawberry.rocks/api-reference/strawberry.UNSET
