### ISSUE TITLE
Apollo Federation 2

### ISSUE THREAD

**Issue by maspling** [strawberry-graphql/strawberry#1827]
Since Apollo Federation 2 is now released and introduced a few new directives and some optional fields, is there any current efforts in the project to support those?

What is new in Federation 2: https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2

Compatibility Chart: https://github.com/apollographql/apollo-federation-subgraph-compatibility

**Comment by patrick91** [comment]
@maspling thanks for the report, so it looks like we need to add the following directives, right?

- `@link`
- `@shareable`
- `@tag`
- `@override`
- `@inaccessbile`

**Comment by maspling** [comment]
Yes, that is mostly it. There are some changes to how the directives work (for example, `@key` should now be able to have an optional param called resolvable that hints the federation if there is a resolver for the field in the subgraph - https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2/#changes-to-key).

**Comment by DominiqueGarmier** [comment]
> Yes, that is mostly it. There are some changes to how the directives work (for example, `@key` should now be able to have an optional param called resolvable that hints the federation if there is a resolver for the field in the subgraph - https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2/#changes-to-key).

how should we best implement this? add a new argument to `straberry.federation.type` called `resolvable` or somehow pass something other than just a list of keys to `keys`?
