### ISSUE TITLE
mypy errors when using Pydantic integration

### ISSUE THREAD

**Issue by olivier-thatch** [strawberry-graphql/strawberry#1830]
Hello,

I'm trying to use the Pydantic integration and getting a few mypy errors.

Simplified version of the code:

```python
import strawberry
from pydantic import BaseModel, EmailStr


class UserBase(BaseModel):
    email: Optional[EmailStr] = None


class UserCreate(PatientBase):
    email: EmailStr


@strawberry.experimental.pydantic.input(model=UserCreate, all_fields=True)
class UserCreateInput:
    pass


@strawberry.mutation
def create_user(self, info: Info, input_data: UserCreateInput) -> PatientType:
    instance = input_data.to_pydantic()
    # ...
```

This causes 2 errors:

1. `@strawberry.experimental.pydantic.input(model=UserCreate, all_fields=True)` causes this error:
    ```
    error: model argument in decorator failed to be parsed
    ```

2. `instance = input_data.to_pydantic()` causes this error:
    ```
    error: "UserCreateInput" has no attribute "to_pydantic"
    ```

Package versions:
* Python 3.10.3
* strawberry-graphql 0.106.3
* pydantic 1.9.0

**Comment by motherofcoconuts** [comment]
Secpnd this issue. Also get issues with `from_pydantic`. Ex: `error: "Type[User]" has no attribute "from_pydantic"`

**Comment by thejaminator** [comment]
hey @motherofcoconuts  and @olivier-thatch are you using our mypy plugin? i fixed that
```
[mypy]
plugins = strawberry.ext.mypy_plugin
```

**Comment by motherofcoconuts** [comment]
hey @thejaminator i am indeed:

**Comment by thejaminator** [comment]
@motherofcoconuts uhoh. can you get your mypy version and strawberry version for me please

**Comment by motherofcoconuts** [comment]
Pulled from my poetry.lock file:

```
[[package]]
name = "strawberry-graphql"
version = "0.97.0"
description = "A library for creating GraphQL APIs"
category = "main"
optional = false
python-versions = ">=3.7,<4.0"
```

```
[[package]]
name = "mypy"
version = "0.942"
description = "Optional static typing for Python"
category = "dev"
optional = false
python-versions = ">=3.6"
```

**Comment by thejaminator** [comment]
@motherofcoconuts as a temporary workaround use the `is_input=True` parameter instead for `strawberry.experimental.pydantic.type` 

```
from typing import Optional
import strawberry
from pydantic import BaseModel, EmailStr


class UserBase(BaseModel):
    email: Optional[EmailStr] = None


class UserCreate(BaseModel):
    email: EmailStr


@strawberry.experimental.pydantic.type(model=UserCreate, all_fields=True, is_input=True)
class UserCreateInput:
    pass


@strawberry.mutation
def create_user(self, info, input_data: UserCreateInput) -> None:
    instance = input_data.to_pydantic()
    # ...
```

**Comment by motherofcoconuts** [comment]
@thejaminator @olivier-thatch  is using the `pydantic.input` type. I actually use the following partials:

```
type = partial(strawberry.experimental.pydantic.type, all_fields=True)
input = partial(strawberry.experimental.pydantic.type, is_input=True, all_fields=True)
```

and experience it for both types with the `@type` decorator as well as the `@tinput` decoratior.

**Comment by thejaminator** [comment]
> @thejaminator @olivier-thatch is using the `pydantic.input` type. I actually use the following partials:
> 
> ```
> type = partial(strawberry.experimental.pydantic.type, all_fields=True)
> input = partial(strawberry.experimental.pydantic.type, is_input=True, all_fields=True)
> ```
> 
> and experience it for both types with the `@type` decorator as well as the `@input` decoratior.

ah ok, yeah seems like the mypy plugin isn't working well with those partials :(

**Comment by thejaminator** [comment]
@motherofcoconuts for your case, where you manually define your own decorator. unfortunately there are issues with mypy that i write here https://github.com/strawberry-graphql/strawberry/issues/1833
