### ISSUE TITLE
Add poetry plugin to wrap development tasks once poetry plugins is stable

### ISSUE THREAD

**Issue by Ambro17** [strawberry-graphql/strawberry#1878]
Once https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md#120a1---2021-05-21 is stable, we should research for poetry plugins to run tests with `poetry run tests` to get them as native commands

**Comment by patrick91** [comment]
hatch has support for matrix as well https://hatch.pypa.io/latest/config/environment/#matrix

**Comment by patrick91** [comment]
I'm going to close this as I think we'll migrate to PDM once autopub supports it 😊
