### ISSUE TITLE
Add documentation for query directives

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1888]
We only have documentation for schema directives, we should document query directives, here's an example of how they work: https://github.com/strawberry-graphql/strawberry/blob/main/tests/schema/test_directives.py

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1888">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1888/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1888/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
We should call them operation directives, to stay consistent with other docs/articles:

- https://www.apollographql.com/docs/apollo-server/schema/directives/#schema-directives-vs-operation-directives
- https://stepzen.com/blog/graphql-directives
- https://css-tricks.com/working-with-built-in-graphql-directives/

**Comment by bradleyoesch** [comment]
Should this be closed with the merge of https://github.com/strawberry-graphql/strawberry/pull/2728?

**Comment by brunodantas** [comment]
Looks like it should be closed: https://strawberry.rocks/docs/types/operation-directives
