### ISSUE TITLE
Add Async Graphql View for Flask

### ISSUE THREAD

**Issue by scottweitzner** [strawberry-graphql/strawberry#1903]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

My team uses flask and we've adapted [the existing graphql view](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/flask/views.py) to work with async calls. We have this working currently in production but were hoping a async-enabled flask view would be on the roadmap. If one is not on the roadmap I'd be more than happy to submit a PR of what we have working internally and iterate on that.

cc @kevinmsun

**Comment by scottweitzner** [comment]
I created a compare MR [here](https://github.com/scottweitzner/strawberry/pull/1/files)

**Comment by DoctorJohn** [comment]
Looks like this has been resolved via #1907 :)
