### ISSUE TITLE
Add documentation for LazyType

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [strawberry-graphql/strawberry#1905]
Hi all, I think adding documentation for LazyType would be a great idea. Just mentioning that it exists somewhere in the official docs would be very helpful. Circular dependencies are kinda common in graphql, and LazyType is a really important tool to deal with those issues. So it would be important to talk about it somewhere in the official docs.

Thanks :)

**Comment by invokermain** [comment]
Yes please, a wider discussion on Circular imports and the strategies to solve them would be great as well. I.e. does LazyType only help the top level type annotation? Can it be used in a resolver?

**Comment by patrick91** [comment]
We should do this after this is merged: https://github.com/strawberry-graphql/strawberry/pull/1904

**Comment by everdrone** [comment]
Does anybody have a working example on how to use lazy types before the documentation is up?
Can't manage to get around a circular import and it's blocking.

**Comment by vamshiaruru-virgodesigns** [comment]
@everdrone this is how you do it

```python
from strawberry import LazyType

class Query:
    @strawberry.field
    async def resolver(self, info) -> LazyType["TypeName", "import.path.to.type"]:
        from import.path.to.type import TypeName
        return TypeName()
 ```

**Comment by everdrone** [comment]
Thanks for the reply @vamshiaruru-virgodesigns 
Is there any advantage from importing `TypeName` into the resolver rather than at the root level using `TYPE_CHECKING`?

Like:
```py
if TYPE_CHECKING:
    from import.path.to.type import TypeName
else:
    TypeName = gql.LazyType["TypeName", "import.path.to.type"]

# ...

class Query:
    @gql.field
    def resolver(self, info, root) -> TypeName:
        return TypeName()

**Comment by vamshiaruru-virgodesigns** [comment]
If I understand correctly, the `LazyType["TypeName", "import.path.to.type"]` is just a type, it can't be instantiated. So to get the actual class and instantiate it, you have to import it from the resolver. All the LazyType does is let strawberry figure out what Type we are returning.

**Comment by patrick91** [comment]
LazyTypes have been document here: https://strawberry.rocks/docs/types/lazy#lazy-types 😊

**Comment by bRameshShivakumar** [comment]
> you have to import it from the resolve

Hello @vamshiaruru-virgodesigns 
do you have any sample of how do you import it from the resolver, since in resolver also we need to import actual class reference. if you have any complete sample of how lazy type will solve  cyclic reference .
Thank you
