### ISSUE TITLE
Issues on windows (?)

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1914]
We got this bug report on our docs page:

> Cannot get this to run on Windows. When I issue the 'strawberry server schema' command in git bash, it just hangs and there is no message about a running server. Sure enough, the http://0.0.0.0:8000/graphql site cannot be reached.

We have tests for windows, so in theory this should work, would anyone be willing to check? maybe we can improve docs.

I wonder why it hangs

**Comment by DoctorJohn** [comment]
Just took a look at this in a VM. First I noticed that run the `python` command itself hangs. Running Python via `winpty python` [as suggested on stackoverflow](https://stackoverflow.com/questions/32597209/python-not-working-in-the-command-line-of-git-bash) resolved that issue. The same solution works for strawberry as well, just run `winpty strawberry server app` and the debug-server runs as expected.

Note that this workaround is not needed when PowerShell is used

**Comment by jkimbo** [comment]
Is this still an issue?

**Comment by patrick91** [comment]
@jkimbo I don't think so, let's close for now 😊

**Comment by DoctorJohn** [comment]
It's on my list of things I want to add to our docs. Could help some windows users.
