### ISSUE TITLE
Execute arbitrary GraphQL requests (including mutations) via HTTP GET

### ISSUE THREAD

**Issue by vpatov** [strawberry-graphql/strawberry#1933]
It would be very useful to be able to execute GraphQL mutations via an HTTP GET request (i.e. clicking on a link), e.g. `https://mywebsite.com/graphqlapi?query=%7B%22form%22:%7B%22field1%22:%22value1%22,%22field2%22:%22value2%22%7D%7D`, or something of the like.

## Feature Request Type
- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

## Description
As far as I understand this is only possible with queries (and not mutations) as of now, and it is not possible to include variables in the query params (please correct me if I am wrong, and this is all possible already).

**Comment by DoctorJohn** [comment]
Hey. We're trying to closely follow official [GraphQL recommendations](https://graphql.org/learn/queries/#mutations) and work in progress [GraphQL-over-HTTP spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#get) which states `GET requests MUST NOT be used for executing mutation operations`. The GraphQL website explains it like this:

> In REST, any request might end up causing some side-effects on the server, but by convention it's suggested that one doesn't use GET requests to modify data. GraphQL is similar

If I remember correctly, it should be possible to include query parameters in GET requests. At least the mentioned spec says `For HTTP GET requests [...] The variables parameter, if used, MUST be represented as a URL-encoded JSON string.`
