### ISSUE TITLE
Schema hot reload

### ISSUE THREAD

**Issue by gcemaj** [strawberry-graphql/strawberry#1941]
Would it be possible to reload the schema at runtime?

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Support for dynamic schema alteration, a way to refresh the schema during run time.

**Comment by patrick91** [comment]
@gcemaj I'll close the issue since this is something you can do via unicorn or your web framework of choice 😊

If you meant something different, let us know!
