### ISSUE TITLE
Ability to ignore a property as a field in a @type

### ISSUE THREAD

**Issue by vdurmont** [strawberry-graphql/strawberry#1951]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

## Description

Apologies if I missed it, but I don't seem to be able to ignore a property of the object as a field.
My use case is that I often pass a database model in the constructor and store it as a property on my object, but I don't want to expose it in the GraphQL API. Example:
```
@type
class User:
    _db_model: UserModel

    def __init__(self, db_model: UserModel) -> None:
        self._db_model = db_model

    @field
    def get_id(self) -> str:
        return self._db_model.id
```
I'd imagine we could have something like:
```
@field(ignore=True)
# Or:
@not_a_field  # :)
```

**Comment by patrick91** [comment]
Hi @vdurmont, you can use `strawberry.Private` for this

```python
@strawberry.type
class User:
    name: str
    age: int
    demo: strawberry.Private[int]
```

here's a full example: https://play.strawberry.rocks/?gist=c908187f6f94a482e7fc76a8612cba1a

hope this helps, I'll close the issue but feel free to reopen it in case I didn't understand the issue 😊

**Comment by vdurmont** [comment]
Oh that is perfect, thanks @patrick91 and sorry for not seeing that.
