### ISSUE TITLE
StrawberryResolver.annotation removed in release 0.115.0

### ISSUE THREAD

**Issue by nrbnlulu** [strawberry-graphql/strawberry#1989]
I, and possibly others, am relying on the annotations of the resolver in order to "inherit" resolvers.
It would be great if we could have that information returned in a future release.

**Comment by skilkis** [comment]
@nrbnlulu I'm sorry that you were inconvenienced by the removal of `annotations`. I've re-implemented the property in #1990. The output should be identical to how it was prior to Release v0.115. However, it makes use of the new implementation to determine reserved parameters. Please let me know if you experience any bugs once #1990 is released 😊
