### ISSUE TITLE
Add support for description in fields

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#20]
```python
@strawberry.type
class Query:
    @strawberry.field
    async def todos(self, info) -> typing.List[str]:
        """A list of TODOs"""
        return ["a", "b"]
```

```python
@strawberry.type
class Query:
    @strawberry.field(description="A list of TODOs")
    async def todos(self, info) -> typing.List[str]:
        return ["a", "b"]
```

We also need a way to define descriptions on simple fields

```python
@strawberry.type
class TODO:
    id: strawberry.ID
    """This would be unique"""
```

```python
@strawberry.type
class TODO:
    id: str = strawberry.field(description="This would be unique")
```

See:
- https://www.python.org/dev/peps/pep-0257/
- https://stackoverflow.com/a/20529741/169274
- http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)
