### ISSUE TITLE
Allow using tuple (and/or iterable) as an alias to the GraphQL type

### ISSUE THREAD

**Issue by dogweather** [strawberry-graphql/strawberry#2035]
## Feature Request Type

Alteration (enhancement/optimization) of existing feature(s)

## Description

Returning a `tuple` when the attribute is hinted as `list` [works](https://play.strawberry.rocks/?gist=0815d1a1f0c58a613bd356cbeb45c8a1).

But hinting the return type _correctly as a tuple_ causes an error:

```python
@strawberry.type
class Dictionary:
    entries: tuple[Entry]
    sources: tuple[Source]
```

```
TypeError: Unexpected type tuple[Entry]
```

Our code uses tuples and iterables whenever appropriate for robustness, efficiency, and documentation. We also use strict type hinting. It'd be great for these read-only sequences to be explicitly supported.

**Comment by lonelyteapot** [comment]
I think that a more general `Sequence` annotation makes sense.

**Comment by jkimbo** [comment]
Support added in [v0.130.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.130.0)

**Comment by dperetti** [comment]
However, if the tuple is `Tuple[Date, float]` for instance, and it will yield a wrong type!

**Comment by patrick91** [comment]
@dperetti good catch! I think in this case we should probably throw an error, what do you think?

**Comment by dperetti** [comment]
@patrick91 yeah, along with a reminder that GraphQL doesn't support tuples anyway!
