### ISSUE TITLE
Add description to enum values

### ISSUE THREAD

**Issue by gonzalezzfelipe** [strawberry-graphql/strawberry#2043]
I was writing documentation when I realised that enum values don't implement the description, and looking at the code I saw that it wouldn't be difficult to implement. I made the changes and tested it, seems to work okay. Would you like it for me to add a PR with this functionality?

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by BryceBeagle** [comment]
There's never any harm with opening a PR. We'd love to see what you've got working! There's also another PR out that touches on enum descriptions if you want to look: #1645. We're still reviewing that one too, and scope of the change might change before it lands

**Comment by gonzalezzfelipe** [comment]
Oh cool, that PR actually includes the changes I was talking about, adding the handling of the description on the enum value and the schema converter. If that PR is on the way of being merged then my PR doesn't really add anything to the mix.

**Comment by gonzalezzfelipe** [comment]
@BryceBeagle I just saw [this comment](https://github.com/strawberry-graphql/strawberry/pull/1645#issuecomment-1173104533) on the PR, saying that it would be maybe a better idea to split the PR, and it seems to be kind of stuck, I'll add the PR that adds the functionality for adding the description parameter and then you can choose to do whatever you like with it #:wink:
