### ISSUE TITLE
Django AsyncGraphQLView param: subscriptions_enabled misleading

### ISSUE THREAD

**Issue by nrbnlulu** [strawberry-graphql/strawberry#2051]
### The docs about `subscriptions_enabled` are misleading.
the docs says:
> subscriptions_enabled: optional boolean parameter enabling subscriptions in the GraphiQL interface, defaults to False.  

I as a new user couldn't understand that It is just some hack to satisfy GraphiQL and not at all supporting websockets... 
especially because Django can handle only HTTP requests and not websockets.

I realized that only after digging threw the source code and #726 , #1215 , #344.

I would remove that and I think what @patrick91 suggested in #726 :
> Or we should tell people to use the ASGI view even for non websockets GraphQL :)    

Is a better solution.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/2051">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2051/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2051/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
yes, we should change that 😊 feel free to make a PR!
