### ISSUE TITLE
Enum missing @strawberry.enum has errors talk about user types, not enum itself

### ISSUE THREAD

**Issue by huonw** [strawberry-graphql/strawberry#2107]
## Describe the Bug

If an enum is used in a `@strawberry.type`, but is missing the `@strawberry.enum` decorator, there's an error, but that error refers to the `@strawberry.type`, rather than the enum.

```python
import enum

import strawberry

class MyEnum(enum.Enum):
    X = "x"


@strawberry.type
class Query:
    field: MyEnum


strawberry.Schema(Query)
```

Executing that file gives an exception: `TypeError: Query fields cannot be resolved. _enum_definition`. Note that the name referenced is `Query`. It'd be better if the error message referred to the enum itself: `TypeError: MyEnum fields cannot be resolved. _enum_definition`.

Work-around: manually check each enum fields of the `@strawberry.type`. (If required, binary search on the fields: comment out half of them, and then see if the error persists, if it disappears, the bad fields are the ones commented out, otherwise they're in the ones left alone, and continue.)

## System Information

 - Operating system: macOS
 - Strawberry version (if applicable): 0.126.0

## Additional Context

Thanks for strawberry! 🍓

**Comment by patrick91** [comment]
@huonw thanks for the report! I've been doing some improvements on how errors work here: https://github.com/strawberry-graphql/strawberry/pull/2027

I'll see if I can make this error case better too 😊

**Comment by patrick91** [comment]
Reproduction here: https://play.strawberry.rocks/?gist=6ac38ba61d3c1836e723c20857cee8b0
