### ISSUE TITLE
`backports.cached-property` should only be required for python<3.8

### ISSUE THREAD

**Issue by ljnsn** [strawberry-graphql/strawberry#2108]
Hi,

the change introduced in #1582 causes my pipeline to fail, I think due to the dependency name it cannot be found on our private repo server. As far as I know, this library is in any case only required for Python<3.8, so would it be possible to mark the dependency as such?

Suggested change to pyproject.toml would be this:

```
backports-cached-property = { version = "^1.0.1", python = ">=3.6,<3.8" }
```

If for some reason, you don't want to restrict to a specific Python version, could we rename the dependency to `backports-cached-property`?

Happy to make a PR for either case.

**Comment by patrick91** [comment]
great suggestion! let's only use it when we are on python before 3.8 ☺️
