### ISSUE TITLE
mutation

### ISSUE THREAD

**Issue by musavirchukkan** [strawberry-graphql/strawberry#213]
It would be great to have a way to specify permissions for a mutation, something similar to what we did for the fields

**Comment by musavirchukkan** [comment]
It would be great to have a way to specify permissions for a mutation, something similar to what we did for the fields

**Comment by jaydenwindle** [comment]
Hey @musavirchukkan! This looks like a duplicate of #112, so I'm going to close it for now. Please have a look at the solution proposed there and let me know if that works for you.
