### ISSUE TITLE
Subclassing `Info`

### ISSUE THREAD

**Issue by ThirVondukr** [strawberry-graphql/strawberry#2134]
Subclassing `strawberry.types.Info` raises a warning when using it in resolvers.
`"Argument name-based matching of 'info' is deprecated and will be removed in v1.0."`
But it gets injected into resolvers without any problems, in my use case i only change `Info.context` to provide my custom `Context` class and original `Info` gets injected: `strawberry.types.info.Info`

## System Information

 - Strawberry version: 0.126.2

## Additional Context

Repository with bug reproduction: https://gitlab.com/ThirVondukr/strawberry-info-warning
Strawberry code where warning originates from: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/fields/resolver.py#L126

**Comment by skilkis** [comment]
Thanks for the bug report @ThirVondukr , this is byproduct of what I introduced in #1713. I'm having a look now to be able to support sub-classed reserved types 😊
