### ISSUE TITLE
Allow Sequence to be used as return value from resolver

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [strawberry-graphql/strawberry#2161]
Hi all,
I would like to define resolvers in strawberry which return a `Sequence` instead of `List`. This is purely to help with python type checking. List is invariant, and Sequence is not, so it helps with type hints.

## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

**Comment by jkimbo** [comment]
Support added in [v0.130.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.130.0)
