### ISSUE TITLE
Document breaking changes 

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#2208]
In #1187 @jkimbo and I were discussing how to document breaking changes. We could see if we can implement something like this: https://react-native-community.github.io/upgrade-helper/ and maybe a page that lists all the breaking changes (and maybe the deprecations too).

Not sure how to implement something like the upgrade helper for react native, but I think it might be a nice thing to have. 

In #2027 I'm adding an optional dependency of libcst, maybe after merging that we can think of adding codemods?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/2208">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2208/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2208/pledge.svg">
</picture>
</a>

**Comment by jkimbo** [comment]
@patrick91 maybe the first step would just be to have a page on the website with 2 inputs: what version are you on and what version do you want to upgrade to and then a list of all changes between those versions, ideally highlighting any breaking changes. Maybe this is already possible with GitHub releases?

**Comment by patrick91** [comment]
changes as in the release notes?

**Comment by jkimbo** [comment]
Yes, the release notes.

**Comment by estyxx** [comment]
Frist easy step can be adding just the CHANGELOG in the docs site

**Comment by DoctorJohn** [comment]
I feel like we fully addressed this issue by adding the "breaking changes" and "upgrading strawberry" sections to the docs and by adding the strawberry upgrade command.

(I'm late night checking older issues. Feel free to reopen if I missed something).
