### ISSUE TITLE
Homepage: Client or Server

### ISSUE THREAD

**Issue by guettli** [strawberry-graphql/strawberry#222]
If you look at this page, then you don't know if this project provides a graphQL client or server.

I would add this to this page:

https://strawberry.rocks/

**Comment by patrick91** [comment]
@guettli that's a very good feedback! we are working on the new site at the moment: https://github.com/strawberry-graphql/strawberry.rocks/pull/3

you can see a preview here: https://strawberryrocks-git-feature-v2.strawberry-graphql.now.sh/

Do you think the new landing page is clear? :)

**Comment by guettli** [comment]
Feedback: For you"inspired by dataclasses." says everything. For me it says nothing. I don't know dataclasses. I would not use that in the first sentance everybody reads.

**Comment by guettli** [comment]
Feedback2: I don't care much about code. I love data. How does data get stored in strawberry?

**Comment by marcoacierno** [comment]
> Feedback: For you"inspired by dataclasses." says everything. For me it says nothing. I don't know dataclasses. I would not use that in the first sentance everybody reads.

Thanks for this, we will keep it in mind once we start designing the website.

> Feedback2: I don't care much about code. I love data. How does data get stored in strawberry?

Strawberry (and GraphQL in general) is about APIs (think for example REST) and how to expose to the UI (e.g Frontends, or other BEs) information or allow users to do actions (e.g. create an account). 
It is independent on how you store said data (you can use Postgres, Mongo, a json file, anything) and doesn't force you to use any specific storage.

If you have any further questions feel free to join our [Discord](https://strawberry.rocks/discord) where we can discuss together!
