### ISSUE TITLE
strawberry UnsetType regression starting with 0.133.1

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2221]
Starting with strawberry 0.133.1 I get following error

```
...
  File "-/secretgraph/secretgraph/server/schema/schema.py", line 43, in <module>
    class SecretgraphObject:
  File "-/secretgraph/secretgraph/server/schema/schema.py", line 60, in SecretgraphObject
    config: SecretgraphConfig = strawberry.field(default=SecretgraphConfig())
  File "<string>", line 3, in __init__
TypeError: 'UnsetType' object is not callable

```

Definition of SecretgraphConfig:

``` python


@gql.type()
class SecretgraphConfig(relay.Node):
    ...
```

Note: I use strawberry-django-plus but it seems to be an error with core strawberry, as the gql.type is a pass-through to strawberry.type.
Removing relay.Node or initializing a variable like: `_config = SecretgraphConfig()` doesn't fix the issue

**Comment by patrick91** [comment]
@devkral thanks for the bug report! Do you have a minimal reproduction?  

It seems to work for me: https://play.strawberry.rocks/?gist=ac6ef9d60916c9d2e039c39c02b3b11b

**Comment by devkral** [comment]
Sadly no, I am not even sure if it is strawberry issue or a strawberry-django-plus issue.
I have currenlty not much time. But I will try to provide you more information.

**Comment by devkral** [comment]
nailed it down to a  strawberry-django-plus issue.
