### ISSUE TITLE
Ability to dynamically set `status_code` on Response from `MaskErrors` extension

### ISSUE THREAD

**Issue by jerber** [strawberry-graphql/strawberry#2276]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

`MaskErrors` is great but I also want to be able to set the Response `status_code` dynamically based on the error.

For example, internal errors that I am now masking should return `500` status codes whereas visible errors should return `400` status codes. I would also like the ability to further customize the `status_code` on a per error basis, and it seems like adding a function hook to `MaskErrors` would be the easiest way to achieve this.

Ideally, `MaskErrors` could take in an optional function hook that reads in the error and can set the `status_code` according to custom logic.

**Comment by jkimbo** [comment]
Going to close this issue for the reasons outlined in the corresponding PR
