### ISSUE TITLE
Generic types are not supported as inputs.

### ISSUE THREAD

**Issue by coady** [strawberry-graphql/strawberry#2285]
## Describe the Bug
```python
from typing import Generic, TypeVar
import strawberry

T = TypeVar('T')

@strawberry.type
class Node(Generic[T]):
    @strawberry.field
    def data(self, arg: T) -> T:  # `arg` is also generic
        return arg

@strawberry.type
class Query:
    node: Node[int]

schema = strawberry.Schema(Query)  # raises TypeError
print(strawberry.printer.print_schema(schema))
```

## System Information

N/A

## Additional Context
If `arg: T` is replaced with a regular type, the generic output type works.

**Comment by patrick91** [comment]
ah, interesting, I never thought of this use case! I wonder how long it could take to implement it though 🤔

**Comment by skilkis** [comment]
@patrick91 I believe it's an easy fix, I had to recently implement this functionality for a use-case in my thesis. We would have to modify `TypeDefinition.copy_with`. I've currently implemented this in my use-case as a pre-processing step for root-types such as Query, Mutation, Subscription types before schema conversion. However, it makes more sense to implement this re-usably for any type in the schema by modifying `TypeDefinition.copy_with`. 

I'm happy to work on this in December. If anyone needs this urgently, the modification to `TypeDefinition.copy_with` would need one to iterate over the generic arguments in each field and resolve them individually.

```python
fields = []
for field in self.fields:
    ...
    # Resolve generic arguments
    for argument in field.arguments:
        if isinstance(argument.type, StrawberryType):
            if argument.type.is_generic:
                annotation = argument.type_annotation
                argument.type_annotation = StrawberryAnnotation(
                    annotation=argument.type.copy_with(type_var_map),
                    namespace=annotation.namespace,
                )
```

**Comment by patrick91** [comment]
ah neat! thanks for the pointer 😊 feel free to work on it when you have time (and after resting from your thesis)

**Comment by coady** [comment]
#2293 isn't working right, because it modifies the argument. The test should include 2 subscripts.

**Comment by skilkis** [comment]
@coady you're indeed right, the snippet I posted above wasn't meant to be production ready yet. `StrawberryArgument` can implement a `copy_with` method to return a new argument to prevent side-effecting 😊
