### ISSUE TITLE
Duck typing / being allow to override the field types 🦆

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#2308]
I'm opening this issue to document how we can make it easier to override return types.

## Problem description

When using a framework like Django, you tend to directly return models in resolvers, for example:

```python
@strawberry.type
class Query:
    @strawberry.field
    def all_users(self) -> list[UserType]:
         return models.User.objects.all()
```

Assuming that `UserType` has a subset of models.User fields, this will work at runtime as we don't do a type check of the returned type[1].

Unfortunately this break type checking (mypy, pyright, etc) as the return type of `models.User.objects.all()` is `Queryset[models.User]` and the return type of `all_users` is `list[UserType]`.

## Ideas 

One way to work around this is the following:

```python
@strawberry.type
class Query:
    @strawberry.field
    def all_users(self) -> list[UserType]:
         return cast(list[UserType], models.User.objects.all())
```

---

@jkimbo suggested to allow doing something like this:

```python
@strawberry.type
class Query:
    @strawberry.field(field_type=list[UserType])
    def all_users(self) -> Queryset[models.User]:
        return models.User.objects.all()
```

and 

```python
@strawberry.type
class MyType:
  my_field: float = strawberry.field(field_type=str)

MyType(my_field=1.33) # this wouldn’t be a problem
```

[1] graphql-core has some type checks, but it is for scalars and nullability.

**Comment by jkimbo** [comment]
(it was actually @aryaniyaps that suggested it first here: https://discord.com/channels/689806334337482765/741575032257511485/1027417798839914546 )
