### ISSUE TITLE
Generic types are duplicated when using lazy types

### ISSUE THREAD

**Issue by lonelyteapot** [strawberry-graphql/strawberry#2379]
## Code sample

```python
# main.py (module name used later in lazy annotation)
from typing import Annotated, Generic, TypeVar
import strawberry


NodeType = TypeVar("NodeType")


@strawberry.type
class Edge(Generic[NodeType]):
    node: NodeType


@strawberry.type
class Foo:
    pass


@strawberry.type
class Query:
    regular: Edge[Foo]
    lazy: Edge[Annotated["Foo", strawberry.lazy(".main")]]


schema = strawberry.Schema(query=Query)
```

## Exception

`
Query fields cannot be resolved. Types need to have unique names in the entire schema. Duplicated type name: FooEdge
`

## Expected behavior

Regular Strawberry types and their lazy annotations should be treated as equal and result in a single SDL type.

## Additional context

Here's the line that I suspect causes the issue (`{~NodeType: Foo}` != `{~NodeType: LazyType(Foo)}`):

https://github.com/strawberry-graphql/strawberry/blob/d5e62ac9ad38f061bcbd45c6d5ac420697f0e1c8/strawberry/schema/schema_converter.py#L703

**Comment by lonelyteapot** [comment]
If someone can confirm that the solution is as easy as expanding the mentioned line to check for lazy types, I can submit a PR

**Comment by patrick91** [comment]
@lonelyteapot yes, that’s where the fix should go! 

thanks for the report ☺️
