### ISSUE TITLE
Enhancement: Starlite Integration

### ISSUE THREAD

**Issue by Goldziher** [strawberry-graphql/strawberry#2382]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

Hi there, as discussed in the discord server - I would like to suggest a new integration with [Starlite](https://github.com/starlite-api/starlite). If you guys need assistance we can certainly help, and you're always welcome to pop by our discord server to chat (link in our github). I will also be available here of course, so feel free to ping me.

**Comment by patrick91** [comment]
Thanks @Goldziher, once #1809 is merge, I'll take a look at this!

**Comment by gazorby** [comment]
Hi @patrick91 @Goldziher, I got a working integration in #2391, it needs review but tests are passing.
