### ISSUE TITLE
Error in handling enum values while using IntEnum in input type

### ISSUE THREAD

**Issue by srotsinha** [strawberry-graphql/strawberry#2385]
## Describe the Bug

I have enum defined as below and when I initialize input, I get Type Error. The same works when I use Enum instead of IntEnum

```python
@strawberry.enum(description="Reproducing IntEnum issue")
class Color(IntEnum):
    OTHER = strawberry.enum_value(
        -1,
    RED = strawberry.enum_value(0, description="Red: The color red.")
    BLUE = strawberry.enum_value(1, description="Blue: The color blue.")
    GREEN = strawberry.enum_value(2, description="Green: The color green.")

@strawberry.input(description="Test Input for reproducing issue")
class ShirtInput:
    color: Optional[ScoreId] = None

arg = ShirtInput(color=random.choice(list(Color)))
```
Exception:
```python
enum_member = __new__(enum_class, *args)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'EnumValueDefinition'
```

I am using latest release which has the fix for enum value as metioned in [this PR](https://github.com/strawberry-graphql/strawberry/pull/2306)

## System Information

 - Operating system: MacOS
 - Strawberry version (if applicable): 0.146.0

**Comment by kyle-query** [comment]
Encountered this issue today. Any chance of it being fixed? @patrick91 if you can give a back-of-napkin sketch of how it should be solve I can submit a PR.

**Comment by patrick91** [comment]
@kyle-query thanks for offering! I was about to write down a potential (quite involved though) solution, but I did find an easy fix, here: https://github.com/strawberry-graphql/strawberry/pull/2761
