### ISSUE TITLE
Duplicate Auto-Generated Types

### ISSUE THREAD

**Issue by gravy-jones-locker** [strawberry-graphql/strawberry#2397]
## Describe the Bug

Having updated to 0.150.1 I started experiencing issues with Strawberry's auto-generated types.

I am using a `PaginatedConnection` type (similar to the Strawberry guide) to return paginated results for a particular object. Previously the relevant output annotation `PaginatedConnect[OutputType]` could be returned from multiple fields.

Since the update this raises `strawberry.exceptions.duplicated_type_name.DuplicatedTypeName`. The duplicate is the subsidiary OutputType which is exposed as an edge field with a dynamically generated name `OutputTypeEdge`.

This seems like a bug not a feature as it is important for multiple fields to be able to return the same type - even when those types are auto-generated by Strawberry.

## Additional Context

It seems this release is probably relevant 

![image](https://user-images.githubusercontent.com/67203163/207377980-b9d65e76-578d-46d6-8067-849a9286c0a3.png)

**Comment by patrick91** [comment]
@gravy-jones-locker this is definitely a bug, do you have a small reproduction? 

We had this bug and we fixed it, so maybe there was a regression somewhere

**Comment by gauthamkamath** [comment]
I am also facing same issue. First time strawberry user.

strawberry-graphql version == 0.152.0

Exception: **strawberry.exceptions.duplicated_type_name.DuplicatedTypeName: Type PlayerOptionalConnection is defined multiple times in the schema**

Reproduction:

```python
# straw/schemas/pagination.py
# Same as in documentation
from typing import List, Generic, TypeVar, Optional
import strawberry
from strawberry import UNSET

GenericType = TypeVar("GenericType")

@strawberry.type
class Connection(Generic[GenericType]):
    page_info: "PageInfo"
    edges: List["Edge[GenericType]"]

@strawberry.type
class PageInfo:
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str]
    end_cursor: Optional[str]

@strawberry.type
class Edge(Generic[GenericType]):
    node: GenericType
    cursor: str

```

```python
# straw/schemas/team.py
import strawberry
from typing import TYPE_CHECKING, Annotated
from straw.schemas.pagination import Connection

if TYPE_CHECKING:
    from straw.schemas.player import Player

@strawberry.type
class Team:
    id: strawberry.ID
    name: str

    @strawberry.field
    def players(self, first: int = 2, after: str | None = None) -> Connection[Annotated["Player", strawberry.lazy("straw.schemas.player")] | None]:
        pass

@strawberry.type
class TeamQuery:
    @strawberry.field
    def teams(self) -> Connection[Team | None]:
        return list()

```

```python
# straw/schemas/player.py
import strawberry
from straw.schemas.pagination import Connection

@strawberry.type
class Player:
    id: strawberry.ID
    name: str

@strawberry.type
class PlayerQuery:
    @strawberry.field
    def players(self) -> Connection[Player | None]:
        return list()

```

```python
# straw/schema.py
import strawberry
from straw.schemas import team
from straw.schemas import player


@strawberry.type
class Query(
    team.TeamQuery,
    player.PlayerQuery,
):
    pass

schema = strawberry.Schema(query=Query)

```

**Comment by skilkis** [comment]
@gauthamkamath thank you for the repro, I will look at this tonight!

**Comment by snr200** [comment]
Hey team, any updates on this?
I am also facing the same issue.

**Comment by gauthamkamath** [comment]
@skilkis Unable to test this because of #2469

**Comment by skilkis** [comment]
@gauthamkamath thanks for the bug report, I'll have a look!

**Comment by gauthamkamath** [comment]
After upgrading to v 0.155.4, I am not getting this issue anymore. Thank you @skilkis !
