### ISSUE TITLE
Slow schema import time

### ISSUE THREAD

**Issue by fabien-michel** [strawberry-graphql/strawberry#2403]
I'm currently building a small app with strawberry django.

I'm using:
* strawberry==0.151
* strawberry-graphql-django==0.8.2
* strawberry-django-plus==0.132

I've noticed a slower django boot time than usual. (around 10s on my recent dev computer)

`cProfile` show me that most of the boot time is passed into my schema import (`schema.py`) which is responsible of importing all strawberry types

There are 11 `django.type` classes, and 11 `django.filter` classes. Many of them a linked to each other.

Here the cProfile output for the command : `python -m cProfile -o django_boot.cprofile  manage.py check`
[django_boot.cprofile.zip](https://github.com/strawberry-graphql/strawberry/files/10245357/django_boot.cprofile.zip)

**Comment by patrick91** [comment]
Hi @fabien-michel! Thanks for the report. Wow 10 seconds seems like a lot, I'll try to replicate it in the next few days.

Also, @bellini666 have you had any issues with slow starting time?

**Comment by bellini666** [comment]
Indeed 10 seconds seems a lot!

@patrick91 no, no slow starting times, and I have a lot of types/django-types/filters/etc

@fabien-michel are you seeing the slow starting time in `run_server` or when running an ASGI worker? Also, what ASGI implementation are you using?

**Comment by pazaan** [comment]
We have a similar problem in our project - the strawberry imports are taking 17.7 seconds.
We are adding this as a router to FastAPI which is running in uvicorn.
I'll see if I can put together a standalone repro.

**Comment by pazaan** [comment]
> I'll see if I can put together a standalone repro.

Just a quick update on the repro. A simple standalone repro fails to reproduce the problem (of course 😄). So it's entirely possible that it has nothing to do with `strawberry`, but that's just where the `PYTHONPROFILEIMPORTTIME` gun is pointing. I'll keep digging...

**Comment by fabien-michel** [comment]
Recently upgraded strawberry and the import slowness is gone. Thanks for the amazing works !
