### ISSUE TITLE
App breaking when using Enum as field for Generic

### ISSUE THREAD

**Issue by iamkhav** [strawberry-graphql/strawberry#2410]
When using an Enum as a field on a Generic, the app breaks, throwing a `NotImplementedError`.

## Describe the Bug
The below code is an example of the error.
```python
from enum import Enum
from typing import Generic, Optional, TypeVar

import strawberry

T = TypeVar("T")


@strawberry.enum
class EstimatedValueEnum(Enum):
    test = "test"
    testtest = "testtest"


@strawberry.type
class EstimatedValue(Generic[T]):
    value: T
    type: EstimatedValueEnum


@strawberry.type
class Query:
    id_translations: Optional[EstimatedValue[int]]


schema = strawberry.Schema(query=Query)
```
Are we doing something wrong and this is intended or is this a bug?

## System Information

 - Operating system: Docker
 - Strawberry version (if applicable): Since [0.149.2](https://github.com/strawberry-graphql/strawberry/blob/main/CHANGELOG.md#01492---2022-12-09)

**Comment by patrick91** [comment]
Hi @iamkhav this is a bug! I'll try to make a fix for it soon :)

**Comment by iamkhav** [comment]
Thanks a lot @patrick91 🙏
