### ISSUE TITLE
Implement oneOf for input types

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#2421]
Might be worth implementing this upcoming feature, unions are not allowed in input types and this is a good alternative to that, also should be easy to implement in code 😊

https://stepzen.com/blog/coming-soon-to-graphql-the-oneof-input-object

It's also been implemented in other libraries, for example async GraphQL (a rust library)

From: https://github.com/strawberry-graphql/strawberry/discussions/2420#discussioncomment-4499708

The specs: https://github.com/graphql/graphql-spec/pull/825/files

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/2421">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2421/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2421/pledge.svg">
</picture>
</a>

**Comment by nrbnlulu** [comment]
Would that be

```py
@strawberry.mutations.oneOf()
def foo(arg1: Optional[str], arg2: Optional[int]):
    ...
```
or use enums like async-graphql?

**Comment by Aponace** [comment]
Any progress on that? It seems the PR is open and ready but no one approves it :(

**Comment by patrick91** [comment]
@Aponace while the PR adds the directive, it doesn't add runtime support for it, we'd need to implement that to make it work 😊
