### ISSUE TITLE
Default value for `strawberry.argument`

### ISSUE THREAD

**Issue by mmiermans** [strawberry-graphql/strawberry#2436]
Allow a default value to be passed to `strawberry.argument`.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
Currently, either a default value can be provided through a plain Python default argument:

```python
@strawberry.field
def hello(self, name: str = 'Jane') -> str:
```

Or a description using `strawberry.argument`:

```python
@strawberry.field
def hello(self, name: str = strawberry.argument(description='Your name')) -> str:
```

By adding a `default` attribute to `strawberry.argument` both could be provided:

```python
@strawberry.field
def hello(self, name: str = strawberry.argument(default='Jane', description='Your name')) -> str:
```

**Comment by patrick91** [comment]
Hi @mmiermans sorry I totally missed this, we currently allow this:

```python
@strawberry.field
def hello(self, name: Annotated[str, strawberry.argument(description='Your name')] = 'Jane') -> str:
```

would that work for you?
