### ISSUE TITLE
Fail to launch server for fastapi == 0.89.0

### ISSUE THREAD

**Issue by yuyupopo** [strawberry-graphql/strawberry#2439]
Using `GraphQLRouter` for fastapi version 0.89.0 fails.
This is due to https://github.com/tiangolo/fastapi/issues/5857 .

## Describe the Bug

In fastapi 0.89.0, it automatically parses `response_class` from the router function return type (https://github.com/tiangolo/fastapi/pull/1436).
However, fastapi has a bug (https://github.com/tiangolo/fastapi/issues/5857) which it cannot accept `starlette.responses.*` classes when it should.

Strawberry-graphql's https://github.com/strawberry-graphql/strawberry/blob/db81482513ecb464f19c9621cae293f7397935e4/strawberry/fastapi/router.py#L164 line defines `starlette.responses.Response` as return type. Therefore an error is raised.

Maybe remove the return type for now?

**Comment by tiangolo** [comment]
BTW, there was a fix and a release in FastAPI to have special handling when the type annotation is a `Response`, to avoid all the Pydantic validation, etc. So this should now work normally without problems. You probably already noticed, but as I just saw this issue linked from the original PR I wanted to come and comment that here. :nerd_face:
