### ISSUE TITLE
Improve permissions support

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#244]
Right now permissions are working well, but I think we can improve them a bit. 

- [ ] (1) Return an exception or warning if field with permission classes is not optional
- [ ] (2) Right now we return errors for each field that you don't have permissions to (see screenshot)

For (1) we currently don't do anything if the field that has permission classes is not optional, this breaks when we don't return anything since GraphQL core checks if non-nullable fields have null values. We should either update the return type to make it optional or throw a warning/exception as soon as possible so that this can be fixed.

For (2) I'm a bit conflicted, as the current implementation makes sense in a way, but I'm wondering if we should provide a way to not throw the errors. Any idea @marcoacierno @jaydenwindle?

![image](https://user-images.githubusercontent.com/667029/71695430-06344300-2daa-11ea-9363-71f6432b9a8d.png)

**Comment by marcoacierno** [comment]
I think (1) ((1) Return an exception or warning if a field with permission classes is not optional) feels more natural and intuitive without "magic" (i.e why my type becomes optional without me saying it in the dataclass definition?).

So basically: throw an exception/warning so the user can update the field and be aware of what is going on, instead of just changing it without saying anything...

**Comment by nrbnlulu** [comment]
The following is an alternative for throwing errors.
GraphQL is all about types and it is only expected that such a valuable piece of data like permission would be expressed in your schema.

```py
import strawberry
from graphql import GraphQLResolveInfo
from strawberry.types import Info
from strawberry.field import StrawberryField
from typing import Union, Any, List, Dict, Awaitable, Generic, TypeVar, get_args, Optional

T = TypeVar('T')

@strawberry.type
class AuthError:
    code: int
    message: str
    field: str = None


@strawberry.type
class AuthWrapper(Generic[T]):
    data: Optional[T] = None
    errors: Optional[List[AuthError]] = strawberry.field(default_factory=list)


class AuthRootField(StrawberryField):
    def get_result(
            self, source: Any, info: Info, args: List[Any], kwargs: Dict[str, Any]
    ) -> Union[Awaitable[Any], Any]:
        token = info.context.request.headers['Authorization']
        try:
            user = get_user_from_token(token)
            info.context.user = user
            info.context.auth_output = AuthWrapper()
            return super().get_result(source, info, args, kwargs)
        except TokenExpired:
            return AuthWrapper(errors=[AuthError(code=-1, message='expired token.')]


class AuthField(StrawberryDjangoField):
    def __init__(self, *args, permissions=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.permissions = permissions or []

    def get_result(self, source, info, args, kwargs):
        if not info.context.user.has_permissions(self.permissions):
            info.context.auth_ouput.errors.append(
                AuthError(
                    code=-2,
                    message="no sufficient permission",
                    field=str(self.python_name)
                )
            )
            return None
        return super().get_result(source, info, args, kwargs)


@strawberry.type
class Query:
    @strawberry.field
    def hello(self) -> Optional[str]:
        return "world"


@strawberry.type
class RootQuery:
    @AuthRootField()
    def auth_entry(self) -> AuthWrapper[Query]:
        return AuthWrapper(data=Query())


class AuthExtension(Extension):
    def resolve(
            self, _next, root, info: GraphQLResolveInfo, *args, **kwargs
    ) -> AwaitableOrValue[object]:
        if isinstance(root, AuthWrapper):
            return info.context.auth_output
        return _next(root, info, *args, **kwargs)


schema = strawberry.schema(extensions=[AuthExtension, ])
```
