### ISSUE TITLE
Add blacken-docs pre-commit hook

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#2453]
https://github.com/adamchainz/blacken-docs

This should make our code blocks look a bit nicer without much effort 😊

**Comment by sairevanth0007** [comment]
Hello @patrick91 ,
I am new to this project. Since it is mentioned as a good first issue I would like to know what needs to be done and a basic idea of how to do it.

**Comment by patrick91** [comment]
hi @sairevanth0007! sure, this is not going to involve any strawberry code, rather it will need a change to our [.pre-commit-config.yaml file](https://github.com/strawberry-graphql/strawberry/blob/main/.pre-commit-config.yaml)

It will need the follow hook:

```
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
```

let me know if tha helps :)

**Comment by sairevanth0007** [comment]
@patrick91 So I need to add the above hook to [.pre-commit-config.yaml file.](https://github.com/strawberry-graphql/strawberry/blob/main/.pre-commit-config.yaml)[.pre-commit-config.yaml file](https://github.com/strawberry-graphql/strawberry/blob/main/.pre-commit-config.yaml) Sorry to ask these questions. I am new to contributing please bare me 😅.

**Comment by patrick91** [comment]
> @patrick91 So I need to add the above hook to [.pre-commit-config.yaml file.](https://github.com/strawberry-graphql/strawberry/blob/main/.pre-commit-config.yaml) Sorry to ask these questions. I am new to contributing please bare me 😅.

yup, that's correct

**Comment by sairevanth0007** [comment]
> > @patrick91 So I need to add the above hook to [.pre-commit-config.yaml file.](https://github.com/strawberry-graphql/strawberry/blob/main/.pre-commit-config.yaml) Sorry to ask these questions. I am new to contributing please bare me 😅.
> 
> yup, that's correct

Okay. Thank You 😊.

**Comment by rubensoleao** [comment]
blacken-docks is already configured in pre commit, this issue should be closed.


Line 34 `.pre-commit-config.yaml`
```
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
```
