### ISSUE TITLE
TypeError: Forward references must evaluate to types.

### ISSUE THREAD

**Issue by ccsv** [strawberry-graphql/strawberry#2465]
So I am running Strawberry with Fastapi

## Describe the Bug

I have a schema like this:

```
from __future__ import annotations
from enum import Enum
import strawberry
import datetime
from strawberry.scalars import JSON

@strawberry.enum
class Sex(Enum):
    male = "Male"
    female ="Female"

@strawberry.type
class PersonBase:
    name: JSON | None
    sex: Sex | None

@strawberry.type
class Client(PersonBase):
    firm: Firm | None = None


```
 When I try to run the server it throws back an error:

```
  File "C:\Users\0\Desktop\Fastapi\Test\.\app\main.py", line 14, in <module>
    from app.schema import schema
  File "C:\Users\0\Desktop\Fastapi\Test\.\app\schema.py", line 624, in <module>
    schema = strawberry.Schema(query=Query, mutation = Mutation)
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\strawberry\schema\schema.py", line 115, in __init__
    self._schema = GraphQLSchema(
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\graphql\type\schema.py", line 224, in __init__
    collect_referenced_types(query)
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\graphql\type\schema.py", line 433, in collect_referenced_types
    collect_referenced_types(field.type)
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\graphql\type\schema.py", line 433, in collect_referenced_types
    collect_referenced_types(field.type)
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\graphql\type\schema.py", line 432, in collect_referenced_types
    for field in named_type.fields.values():
  File "C:\Users\0\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Users\0\Envs\Fastapi\lib\site-packages\graphql\type\definition.py", line 811, in fields
    raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: Client fields cannot be resolved. Forward references must evaluate to types. Got <strawberry.type.StrawberryOptional object at 0x000002C85C5F5990>.
```
Note that if I change one thing like this making a required name field with a string the error is resolved

```
@strawberry.type
class Client(PersonBase):
    firm: Firm | None = None
    name: str | None
```

But if I put PersonBase into the model like this, it still throws an error even though the name field is required as JSON.

```
class Client:
    firm: Firm | None = None
    name: JSON | None
    sex: Sex | None
```

## System Information

 - Operating system: Windows 10
 - Strawberry version (if applicable): strawberry-graphql==0.139.0

## Additional Context

Not sure if this is an bug or I did something wrong but I find this behavior strange because the JSON and Enum are both scalars but required and they triggered a type error.

**Comment by twm** [comment]
@ccsv I was able to work around a similar issue with an optional union by specifying the field explicitly with a separate GraphQL type:

```py
# Python type used by type checkers
Foo = Union[Bar, Baz, None]

@strawberry.type
class Biff:
   foo: Foo = strawberry.field(
       # GraphQL type used by Strawberry
       graphql_type=strawberry.union([Bar, Baz]) | None
   )
```

I think that this is because an expression like `strawberry.union([...]) | None` results in a `StrawberryOptional` object that isn't a `type`, so not valid in a type annotation.

**Comment by ccsv** [comment]
@twm that should not be the case because by default you have a `id` field that is a type. It seems weird that you cannot have a required `scalar` field only.

**Comment by bellini666** [comment]
Hey @ccsv . I tried reproducing your issue but wasn't able to. What version of python are you using? I tested using python 3.11

**Comment by linusg** [comment]
@bellini666 the path in their error output contains `\Python310\lib`, which I can confirm - strawberry code using a `scalar | None` field works fine on 3.11 but fails with this error on 3.10.

**Comment by sirrus233** [comment]
Confirming this error occurs on 3.10, seemingly any time I type a field as `<some_custom_scalar> | None`.

The error does not occur if the type is `Optional[<some_custom_scalar>]`, even though this should be equivalent.

**Comment by sirrus233** [comment]
That is correct. I can confirm `str | None`, `int | None`, and `bool | None` all work without any problems.
