### ISSUE TITLE
Documentation page is buggy

### ISSUE THREAD

**Issue by matheushent** [strawberry-graphql/strawberry#2466]
## Describe the Bug

The bug is simple: the documentation for the [File Upload](https://strawberry.rocks/docs/guides/file-upload) has some bug in the curl commands. Not that it matters, it's just nice to have it right.

Check the video above:

https://user-images.githubusercontent.com/45343359/212929061-5513ebfe-d43a-4ebf-8b69-7efa026be2b5.mov

**Comment by patrick91** [comment]
Thanks @matheushent! This should be fixed now!

**Comment by matheushent** [comment]
Nice, it is. Thank you!

**Comment by XChikuX** [comment]
Not sure what was fixed. But I sent in a PR with something an example that works for me. #2467

**Comment by patrick91** [comment]
@XChikuX my bad, I thought the issue was referring to the copy icon! Thanks for sending the PR!
