### ISSUE TITLE
[federation]`resolve_reference` not working with `strawberry.federation.field(external=True)`

### ISSUE THREAD

**Issue by filwaline** [strawberry-graphql/strawberry#2468]
## Describe the Bug

Apollo federation entities may have an issue with using both `resolve_reference` and `strawberry.federation.field(external=True)` together. If both are present, strawberry may raise an error `graphql.error.graphql_error.GraphQLError: Unable to resolve reference for <class ...>`.

```python
@strawberry.federation.type(keys=["upc"], shareable=True)
class Product:
    upc: str
    # #################################
    # # resolve_reference don't work with @external together???

    # inStock: bool

    # @classmethod
    # def resolve_reference(cls, info: Info, upc: str):
    #     p = info.context.repo.find(upc)
    #     if p:
    #         return Product(
    #             upc=p.upc,
    #             inStock=p.inStock,
    #         )

    #################################

    weight: int = strawberry.federation.field(external=True, default=0)
    price: int = strawberry.federation.field(external=True, default=0)

    @strawberry.federation.field(requires=["weight price"])
    def shippingEstimate(self) -> Optional[int]:
        if self.price > 1000:
            return 0
        return int(self.weight * 0.5)

    @strawberry.field
    def in_stock(self, info: Info) -> bool:
        p = info.context.repo.find(self.upc)
        return p.inStock if p else False
```
https://github.com/filwaline/Apollo-Federation-Mutation-Demo/blob/main/services/inventory/inventory/stubs.py

## System Information

 - Strawberry version (if applicable):  0.151.2

## Additional Context

A simple setup for reproducing this issue can be found in the repository [filwaline/Apollo-Federation-Mutation-Demo](https://github.com/filwaline/Apollo-Federation-Mutation-Demo). By uncommenting [these lines](https://github.com/filwaline/Apollo-Federation-Mutation-Demo/blob/main/services/inventory/inventory/stubs.py#L10-L24) and starting the server, you should be able to reproduce the error.

```graphql
query ExampleQuery($upcs: [String!]!) {
  findProducts(upcs: $upcs) {
    upc
    weight
    price
    shippingEstimate
  }
}
```
http://localhost:4000/?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAKIAeAhnAA4A2CAiroQBQAkM1UAzukQNoBlFHgCWSAOYBCALpSAlEWAAdJESIAzcWAAKeCGBhQU3Fpx58OXbopVr1Rc6odEA7glESAFimcPqYlAIfurcXqLU1OISJNwoonAUKMH2AL6q6UggADQgAG4UYhQARvTcGCB26sog5tw1fDUAjDUZIKlAA

**Comment by patrick91** [comment]
@filwaline when using external, the external fields are passed to resolve reference:

```python
    @classmethod
    def resolve_reference(cls, info: Info, upc: str, **kwargs):
        print(kwargs)
        p = info.context.repo.find(upc)
        if p:
            return Product(
                upc=p.upc,
                inStock=p.inStock,
            )
```

I tried with your repo and works, I'll close the issue, let me know if you still have issues 😊

**Comment by filwaline** [comment]
```
@classmethod
    def resolve_reference(cls, info: Info, upc: str, **kwargs):
        p = info.context.repo.find(upc)
        if p:
            return Product(upc=p.upc, inStock=p.inStock, **kwargs)
```
Your advice worked, thank you! If you could document this, it would be even better!

**Comment by patrick91** [comment]
@filwaline I'll try in the weekend :) feel free to send a PR too if you want 😊

**Comment by filwaline** [comment]
@patrick91 I have discovered that when using a custom `resolve_reference` function, the parameters are not automatically validated. Is it my responsibility to ensure that the types of the parameters are correct?

**Comment by patrick91** [comment]
@filwaline validate as validating the types of the data coming from the gateway/router?

**Comment by filwaline** [comment]
@patrick91  Yes, for example, a datetime object may be automatically converted to an ISO-formatted string by the router, but the receiving side may not convert it back to a datetime object.

**Comment by patrick91** [comment]
@filwaline I think that's a missing feature on our side then! can you open a new issue? 😊

**Comment by filwaline** [comment]
@patrick91 #2478
