### ISSUE TITLE
RecursionError using Annotated type

### ISSUE THREAD

**Issue by jeemyeong** [strawberry-graphql/strawberry#2480]
## Describe the Bug

```
  File "/usr/local/lib/python3.9/typing.py", line 570, in __eq__
    self.__forward_value__ == other.__forward_value__)
  File "/usr/local/lib/python3.9/typing.py", line 1289, in __eq__
    return (self.__origin__ == other.__origin__
  File "/usr/local/lib/python3.9/typing.py", line 570, in __eq__
    self.__forward_value__ == other.__forward_value__)
  File "/usr/local/lib/python3.9/typing.py", line 1289, in __eq__
    return (self.__origin__ == other.__origin__
RecursionError: maximum recursion depth exceeded
```
RecursionError is raised when I change the code from LazyType["Type", "app.api.graphql.types.type"] to Annotated["Type", strawberry.lazy("app.api.graphql.types.type")]. No errors occurred when using LazyType.

## System Information

 - Operating system: osx 12.5
 - Strawberry version (if applicable): strawberry-graphql==0.137.1

**Comment by patrick91** [comment]
@jeemyeong thanks for the report! do you have a minimal reproduction?

have you tested with later version of Strawberry as well?

**Comment by jeemyeong** [comment]
> @jeemyeong thanks for the report! do you have a minimal reproduction?
> 
> have you tested with later version of Strawberry as well?

https://github.com/jeemyeong/strawberry-bug-report/blob/main/mysite/polls/graphql/types/show.py#L9-L12

Yes, I tested it with `strawberry-graphql==0.154.1`

And it is raised if I import input type with lazy function.

**Comment by skilkis** [comment]
Thanks for the bug report @jeemyeong ! I've managed to narrow down the cause to use of `_eval_type` from the typing module in `strawberry.types.fields.resolver`. It involves an edge-case where forward-referencing a type in `Annotated`, wrapping that in a GenericAlias (i.e. Optional) and then assigning the type expression to a variable of the same name as the referenced type. This is not unique to Strawberry as the test below demonstrates:

```python
@pytest.mark.xfail(strict=True, raises=RecursionError)
def test_recursion_error_eval_type():
    """Test infinite recursion on `_eval_type` with Generic Alias and Annotated.

    This edge-case is caused when the type name referenced within an `Annotated` type
    is assigned to a variable of the same name. This leads to the evaluated type
    returning a `ForwardRef` to the same type name, causing infinite recursion.

    This test demonstrates that this behavior is not caused by `strawberry.lazy`.
    """

    class Foo:
        pass

    FooType = Annotated["Foo", None]

    try:
        _eval_type(Optional[FooType], globals(), locals())
    except RecursionError:
        raise RuntimeError(
            "Recursion error should not have been raised when a variable name "
            "that is different than the foward referenced type is used."
        )

    Foo = Annotated["Foo", None]  # type: ignore

    _eval_type(Optional[Foo], globals(), locals())

```

I've found a hacky "fix" to this bug by not calling `_eval_type`. However, this might break functionality for other users and I want to test the implications of such a change in more depth. For the time being, please consider using a different name for the lazified type in your code as follows:

```python
from typing import TYPE_CHECKING, Annotated, List, Optional

import strawberry

from ...models import Show as ShowModel

if TYPE_CHECKING:
    from .slot import Param as LazyParam
    from .slot import Slot as LazySlot
else:
    LazySlot = Annotated["Slot", strawberry.lazy(".slot")]
    LazyParam = Annotated["Param", strawberry.lazy(".slot")]

@strawberry.django.type(ShowModel)
class Show:
    id: int

    @strawberry.field
    def slots(self: ShowModel, param: Optional[LazyParam]) -> List[LazySlot]:
        queryset = self.slots.all()
        return queryset
```

**Note:** the purpose of `TYPE_CHECKING` here is purely to allow type-checkers to resolve the actual definitions of your types 😊

**Comment by jeemyeong** [comment]
I greatly appreciate your detailed response. Thank you!
