### ISSUE TITLE
If I change the playlist or stop a song, the connection from strawberry to jack get lost

### ISSUE THREAD

**Issue by PeterWenger** [strawberry-graphql/strawberry#2507]
## System Information

 - Operating system:
 - Strawberry version (if applicable):

**Comment by patrick91** [comment]
Hi @PeterWenger, I think this was meant for https://github.com/strawberrymusicplayer/strawberry :D

**Comment by PeterWenger** [comment]
System: Xubuntu 22.04 
Every change of the playlist or stop the connection to the eq (calfplugin, Carla with Lv2 plugins) get lost. I can solve it when I bridge pulseaudio to jack. But  there is no solution with pipwire. Candence dos not bridge pulsaudio to Jack.

**Comment by PeterWenger** [comment]
Sorry the wrong list
