### ISSUE TITLE
Cursor Pagination does not work

### ISSUE THREAD

**Issue by soraia653** [strawberry-graphql/strawberry#2553]
I'm trying to learn how to use Strawberry, so I was following the Cursor Pagination documentation.

However, if you just directly copy + paste the code for the [Cursor Pagination](https://strawberry.rocks/docs/guides/pagination/cursor-based) it results in several errors. 

I tried fixing a few, for example:

- `filtered_data = map(lambda user: user.id > user_id, user_data)` -> `'id' is not an attribute`, so I replaced with `user['id']`.

- Also, since we are using map I get the error that a `'map' object is not subscriptable`.

- `UserType` is not defined.

- `id` field not defined in `User` class.

I'm using Python 3.10 and working on Github Codespaces.

These are just some of the errors I found, please do let me know if I'm missing any information on how to properly apply the cursors. Errors aside, I'm absolutely loving using 🍓!

**Comment by soraia653** [comment]
I was able to fix all the issues -> it's my first time contributing so I am now exactly sure how to proceed.

**Comment by patrick91** [comment]
@soraia653, would be interested in sending a PR to fix the documentation?

This is the file that needs updated: https://github.com/strawberry-graphql/strawberry/blob/main/docs/guides/pagination/cursor-based.md

Happy to guide you if you need more information!

**Comment by soraia653** [comment]
@patrick91 would love to!
