### ISSUE TITLE
Only pass info when resolver asks for it

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#257]
I was thinking of making the API slightly easier for resolvers

so instead of having:

```python
@strawberry.type
class Query:
    @strawberry.field
    def user(self, info) -> User:
        return User(name="Patrick", age=100)
```

we could have this:

```python
@strawberry.type
class Query:
    @strawberry.field
    def user(self) -> User:
        return User(name="Patrick", age=100)
```

the difference is minimal, but it should make the library slightly more user-friendly 😊

**Comment by mtszsobczak** [comment]
one example of practical usage of `info` is queries optimization like in here https://github.com/tfoxy/graphene-django-optimizer

**Comment by patrick91** [comment]
Yup, info is also useful for getting the current user for example. The idea here is to only pass it when it is in the resolver signature, kinda like dependency injection. If you use info it will be there, if you don’t use it, then you don’t have to put in the function signature. 

Same for the root object when using function resolvers (as opposed to method resolvers). 

Hope this is clearer (I’m on mobile otherwise I’d drop a couple of code samples).

**Comment by mtszsobczak** [comment]
Cool, in general, I like that concept. What about queries with arguments and the order of arguments? Could `info` be placed in whatever position or always after self?

**Comment by patrick91** [comment]
@mtszsobczak we would pass info as a keyword argument, so the position won't matter anymore:

```python
# not using info
@strawberry.type
class Query:
    @strawberry.field
    def user(self) -> User:
        return User(name="Patrick", age=100)
```

```python
# using info
@strawberry.type
class Query:
    @strawberry.field
    def user(self, info) -> User:
        return User(name=info.context.request.user.name, age=100)
```

```python
# not using info, with args
@strawberry.type
class Query:
    @strawberry.field
    def user(self, age: int) -> User:
        return User(name="Patrick", age=age)
```

```python
# using info, with args
@strawberry.type
class Query:
    @strawberry.field
    def user(self, age: int, info) -> User:
        return User(name=info.context.request.user.name, age=age)
```

I think where this gets even nicer is with function resolvers:

```python
# current function resolvers:
def get_user(root, info):
    return User(name="Patrick", age=age)

@strawberry.type
class Query:
    user: User = strawberry.field(resolver=get_user)
```


```python
# without passing root and info:
def get_user():
    return User(name="Patrick", age=age)

@strawberry.type
class Query:
    user: User = strawberry.field(resolver=get_user)
```

**Comment by mtszsobczak** [comment]
It simplifies basic usage and it does not limit the API :+1: . My only concern is that users might be confused by the dynamic position of info. But it might not be an issue after all.

**Comment by sarendsen** [comment]
How about context variables? https://docs.python.org/3/library/contextvars.html#module-contextvars

It would require 3.7+ but that wouldn't be a bad thing for such a young project.

```
from strawberry import context, field

@field
def resolver(self):
  info = context.get().info
```

**Comment by patrick91** [comment]
@sarendsen interesting, I'm not familiar with contextvars, at a quick glance it looks a bit like flask's request object, am I right?

**Comment by sarendsen** [comment]
The idea is similar. But context vars being async safe.

**Comment by patrick91** [comment]
@sarendsen I see, I'm a bit conflicted, to be honest, I like the idea, but it feels a bit magic 😊

Do you have a strong opinion on this? I'd personally chose the function params if I have to :)

@jaydenwindle @marcoacierno @mtszsobczak what do you think?

**Comment by mtszsobczak** [comment]
Hey, context vars look cool, but as you mentioned a bit magic.

I would also prefer function params as they look easier to reason about and test + the flow of information is explicit. But I didn't put much time for thinking about the context vars and using global context concept. I am curious to see how both approaches would scale taking into account testing :cat:

**Comment by sarendsen** [comment]
I think the magic feeling lies in the fact that its a quit new python feature?
I actually quit like it and expect it to see it a lot more in the async world.


Heres a more complete example that hopefully shows that the use is actually not that magical.

```python
@dataclasses.dataclass
class Context:
    schema: 'Schema'
    request: Optional[Any] = None
    variable_values: Optional[Any] = None

context: contextvars.ContextVar[Context] = contextvars.ContextVar('context')
```


```python
from strawberry import context, field, type

@type
class User:

    @field
    def name(self):
        schema = context.get().schema
```

**Comment by patrick91** [comment]
> I think the magic feeling lies in the fact that its a quit new python feature?

it is more about having request information coming from a "global" variable, if that makes sense

I'm going to read a bit about this, I'm +1 on using new features, but not sure in this case we really need it 😊
