### ISSUE TITLE
Ability to add descriptions on object type fields, input type fields

### ISSUE THREAD

**Issue by mikeldking** [strawberry-graphql/strawberry#2576]
Would like to be able to add descriptions on fields like below and see them in the schema:

## Input type fields
```python
@strawberry.input
class TimeRange:
    start: Annotated[
        datetime.datetime,
        strawberry.argument(description="The start of the time range"),
    ]
    end: Annotated[
        datetime.datetime,
        strawberry.argument(description="The end of the time range. Right exclusive."),
    ]
```
## type fields
```python
@strawberry.type
class Dataset:
    name: str
    start_time: Annotated[datetime, strawberry.field(description="The start of the time range")]
    end_time: Annotated[datetime, strawberry.field(description="The start of the time range")]
```

☝️ cases don't result in docstrings in the schema, which are super helpful when someone is trying to explore your schema via an IDE or graphiql.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

Adding more `description` support will help those who consume the API.

**Comment by jkimbo** [comment]
@mikeldking just to duplicate my comment https://github.com/strawberry-graphql/strawberry/issues/509#issuecomment-1436069924 for reference:

Both of those are possible by using `strawberry.field` (`strawberry.argument` is only used for arguments to fields).

So your examples should look like this:

## Input type fields
```python
@strawberry.input
class TimeRange:
    start: datetime.datetime = strawberry.field(description="The start of the time range")
    end: datetime.datetime = strawberry.field(description="The end of the time range. Right exclusive.")
```

## type fields
```python
@strawberry.type
class Dataset:
    name: str
    start_time: datetime = strawberry.field(description="The start of the time range")
    end_time: datetime = strawberry.field(description="The start of the time range")
```

**Comment by mikeldking** [comment]
ah thanks for the response. Much appreciated.

**Comment by XChikuX** [comment]
This is awesome. It imports well even when extracting from a pydantic class using the experimental library!!
