### ISSUE TITLE
How do I generate the schema definition?

### ISSUE THREAD

**Issue by Plaoo** [strawberry-graphql/strawberry#2590]
Hi all, I would like to use the [graphdoc](https://github.com/wallee94/graphdoc) library to generate documentation on an endpoint:

```python
@app.get("/docs")
async def graphql_docs():

    schema = strawberry.Schema(query=Query, mutation=Mutation)
    html = graphdoc.to_doc(schema)

    return Response(content=html, media_type="text/html")
```

The problem is that strawberry does not return an object graphql.GraphQLSchema, graphdoc request a GraphQLSchema object, this a part of the code:

```python
#graphdoc
#...
def to_doc(
    schema: Union[str, graphql.GraphQLSchema],
    templates_path: str = None,
    context: Optional[dict] = None,
    use_cache=True,
) -> str:
#...
```

Is there a way with strawberry to generate a GraphQLSchema?

**Comment by jkimbo** [comment]
@Plaoo you can access the `graphql.GraphQLSchema` through `schema._schema`: https://github.com/strawberry-graphql/strawberry/blob/debf2185b4df843ecda09ba4614586c0064cfbd0/strawberry/schema/schema.py#L125-L134

**Comment by Plaoo** [comment]
@jkimbo I had tried that, but I get this error
```
jinja2.exceptions.UndefinedError: 'graphql.type.definition.GraphQLUnionType object' has no attribute 'fields'
```

**Comment by jkimbo** [comment]
@Plaoo that looks like a bug in graphdoc. Do you have the full stack trace?

**Comment by Plaoo** [comment]
@jkimbo yes from the logs I see that it is a graphdoc problem, thanks for the help I will close.
