### ISSUE TITLE
Postponed annotation evaluation breaks `Annotated` when used alongside Info

### ISSUE THREAD

**Issue by edwardrjones97** [strawberry-graphql/strawberry#2607]
## Describe the Bug

The following will throw `TypeError: Query fields cannot be resolved. Unexpected type 'typing.Annotated[int, <strawberry.arguments.StrawberryArgumentAnnotation object at 0x7f55080339d0>]'`
```python
from __future__ import annotations

from typing import Any

import strawberry
from strawberry import field
from strawberry.fastapi import BaseContext
from typing_extensions import Annotated

class Ctx(BaseContext):

    def __init__(self) -> None:
        super().__init__()

Info = strawberry.types.Info[Ctx, Any]

@strawberry.type
class Tmp:
    id: int
    name: str


@strawberry.type
class Query:

    @field(description="Get Tmp by id.")  # type: ignore
    async def tmp(
        self,
        info: Info,
        id_: Annotated[
            int, strawberry.argument(name="id", description="The ID of the Tmp")
        ],
        name: str,
    ) -> Tmp:
        return Tmp(id=id_, name=name)


Schema = strawberry.Schema(Query)
```

Commenting out
```python
from __future__ import annotations
```
or 
```python
        info: Info,
```
allows the schema to generate successfully.

## System Information

 - Operating system: Ubuntu 20.04.5 LTS
 - Strawberry version (if applicable): Tried 0.158.2 and 0.159.0

## Additional Context

This same error was seen in #1819, but the root cause here seems to be different.

Adding types that weren't related to `Info` seemed to not be problematic (such as the non-`Annotated` `name` argument). Using `Info[Any, Any]` exhibits the same error (so it doesn't seem to be specific to the empty Ctx).

```
PYTHON_VERSION=3.10.10
```

**Comment by patrick91** [comment]
this might be fixed by: https://github.com/strawberry-graphql/strawberry/pull/2592

**Comment by bellini666** [comment]
https://github.com/strawberry-graphql/strawberry/pull/2592 got merged. Upgrading your strawberry dependency to [0.165.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.165.0) should fix the issue :)
