### ISSUE TITLE
@strawberry.group("Admin")

### ISSUE THREAD

**Issue by jediiry** [strawberry-graphql/strawberry#2650]
I am unable to group mutations and queries based on namespaces

**Comment by patrick91** [comment]
Hi @jediiry can you write more about your use case?

**Comment by jediiry** [comment]
import strawberry
from .schema import Admin
from strawberry import field
from Directives.directives import UserRole, HasRoleDirective


@strawberry.type
class AdminQuery:
    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    @strawberry.group("Admin")
    def admin(self) -> Admin:
        return Admin(name="Samuel", age=100)

    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    def adminOne(self) -> Admin:
        return Admin(name="Samuel", age=100)

**Comment by patrick91** [comment]
@jediiry how does the grouping affect the schema?

**Comment by jediiry** [comment]
@patrick91 it helps to group my mutations and queries in graphql playground into admin and users.

**Comment by patrick91** [comment]
@jediiry sorry for asking so many questions :D 

is there any docs on grouping for GraphQL playground? I have never seen this feature 😊

**Comment by jediiry** [comment]
<img width="345" alt="Screenshot 2023-03-19 at 12 10 26" src="https://user-images.githubusercontent.com/47888360/226171557-de1c4678-53bb-423a-a432-bca921cdf554.png">
 This is what I am trying to achieve

**Comment by patrick91** [comment]
I see! That's something you can do like this, I think:

```python
import strawberry
from .schema import Admin
from strawberry import field
from Directives.directives import UserRole, HasRoleDirective


@strawberry.type
class AdminQuery:
    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    def admin(self) -> Admin:
        return Admin(name="Samuel", age=100)

    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    def adminOne(self) -> Admin:
        return Admin(name="Samuel", age=100)

@strawberry.type
class Query:
    admin_group: AdminQuery
```

Adding a group parameter might not be easy (in terms of UX/DX and edge cases), and maybe you can implement an extension for this to make it easier if you don't like the snippet above?

**Comment by jediiry** [comment]
@strawberry.type
class AdminQuery:
    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    def admin(self) -> Admin:
        return Admin(name="Samuel", age=100)

    @field(extensions=[HasRoleDirective(UserRole.ADMIN)])
    def adminOne(self) -> Admin:
        return Admin(name="Samuel", age=100)
        
      
      
   
@strawberry.type
class UserQuery:
    @field(extensions=[HasRoleDirective(UserRole.USER)])
    async def user(self) -> User:
        try:
            return User(name="Patrick", age=100)
        except Exception as error:
            return error



@strawberry.type
class Query:
    AdminGroup: AdminQuery = strawberry.field(
        resolver=lambda: AdminQuery())
    UserGroup: UserQuery = strawberry.field(
        resolver=lambda: UserQuery())
        
        
  schema = strawberry.Schema(query=Query)
  
  Finally got it to work, Thanks

**Comment by patrick91** [comment]
I'm glad! I'll close the issue 😊
