### ISSUE TITLE
annotation errors with message "cannot import Self from typing_extensions"

### ISSUE THREAD

**Issue by tienman** [strawberry-graphql/strawberry#2697]
The change to import `Self` from `typing_extensions` was added in version `0.142.0`.  The problem is that by default, we're still building on version `3.7.4.3` of `typing_extensions`, which doesn't export that type.  We should be using at least `typing_extensions-4.0.0`, when `Self` was added.

**Comment by patrick91** [comment]
@tienman you're right! https://github.com/strawberry-graphql/strawberry/blob/main/pyproject.toml#L40

would you mind submitting a PR to bump the minumum version of typing extensions?

**Comment by tienman** [comment]
Thanks for the quick replay.  Will do shortly.
