### ISSUE TITLE
mypy: Need type annotation for "graphql_app"  [var-annotated]

### ISSUE THREAD

**Issue by yunzheng** [strawberry-graphql/strawberry#2711]
Since `strawberry-graphql==0.169.0` mypy gives the following error on `graphql_app = GraphQLRouter(schema)`:

```shell
app.py:16: error: Need type annotation for "graphql_app"  [var-annotated]
Found 1 error in 1 file (checked 1 source file)
```

## Describe the Bug

pip install in your virtualenv:

```shell
pip install mypy fastapi strawberry-graphql==0.169.0
```

Take the example web application:

```python
import strawberry

from fastapi import FastAPI
from strawberry.fastapi import GraphQLRouter


@strawberry.type
class Query:
    @strawberry.field
    def hello(self) -> str:
        return "Hello World"


schema = strawberry.Schema(Query)

graphql_app = GraphQLRouter(schema)

app = FastAPI()
app.include_router(graphql_app, prefix="/graphql")
```

Then run mypy:

```shell
$ mypy app.py

app.py:16: error: Need type annotation for "graphql_app"  [var-annotated]
Found 1 error in 1 file (checked 1 source file)
```

## System Information

 - Operating system: Linux 
 - Strawberry version (if applicable): 0.171.1

## Additional Context

The problem does not happen in version 0.168.2:

```shell
$ pip install strawberry-graphql==0.168.2
$ mypy app.py
Success: no issues found in 1 source file
```

A workaround is to just annotate the graphql_app variable manually:

```python
graphql_app: GraphQLRouter = GraphQLRouter(schema)
```

Of course it would be nicer if it can get fixed.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/2711">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2711/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2711/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
hi @yunzheng!

I think this is because I made GraphQLRouter (and all the other views) generic, can you try with:

`graphql_app = GraphQLRouter[object, object](schema)`?

(first type is the context type, second is the root value)

**Comment by yunzheng** [comment]
This works!, however it's unclear to me that I should define it like that. Also the examples are not updated to use this.

**Comment by chrisemke** [comment]
> hi @yunzheng!
> 
> I think this is because I made GraphQLRouter (and all the other views) generic, can you try with:
> 
> `graphql_app = GraphQLRouter[object, object](schema)`?
> 
> (first type is the context type, second is the root value)

Is this still the best way to do this?

**Comment by Topher-the-Geek** [comment]
I hit this when I put pyright in strict mode

> Type of "graphql_app" is partially unknown Type of "graphql_app" is "GraphQLRouter[Unknown, Unknown]" Pylance(reportUnknownVariableType)

And it took some master level Google fu to dig up anything helpful, like this conversation. Hopefully my copy-n-paste of that message helps others who search in the future.

Does it make sense to write

```
GraphQLRouter[None, None](schema, graphql_ide=None)
```

I don't have a root value or context object, so "None" sounds right. At the very least, "None" made the message go away.

**Comment by patrick91** [comment]
@Topher-the-Geek yes, it makes sense :)

I think we can now use default on typevars now to make this go away 😊
