### ISSUE TITLE
Syntax error in __doc__ ending colon

### ISSUE THREAD

**Issue by star2000** [strawberry-graphql/strawberry#2712]
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/field.py#L434
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/object_type.py#L226
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/object_type.py#L294
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/object_type.py#L347

**Comment by patrick91** [comment]
@star2000 good catch! can you send a PR to fix them? 😊

**Comment by DoctorJohn** [comment]
Fixed in #2714
