### ISSUE TITLE
Cannot return null for non-nullable field Subscription.count

### ISSUE THREAD

**Issue by Mukhametvaleev** [strawberry-graphql/strawberry#2756]
## Describe the Bug
Trying to make Subscription query from strawberry documentation example and got an error:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/8947056/236512042-318475c8-6c51-4b85-adb9-c4884a3cc543.png">

## System Information

 - Operating system: **macOS 13.2.1 (22D68)**
 - Strawberry version: **0.176.3**
 -  Python version: **3.10.10**

## Additional Context

```python
import asyncio
from typing import AsyncGenerator

import strawberry
from fastapi import FastAPI
from strawberry.fastapi import GraphQLRouter
from strawberry.subscriptions import GRAPHQL_TRANSPORT_WS_PROTOCOL, GRAPHQL_WS_PROTOCOL


@strawberry.type
class Query:
    @strawberry.field
    def ping(self) -> str:
        return "PONG"


@strawberry.type
class Subscription:
    @strawberry.subscription
    async def count(self, target: int = 100) -> AsyncGenerator[int, None]:
        for i in range(target):
            yield i
            await asyncio.sleep(0.5)


schema = strawberry.Schema(
    query=Query,
    subscription=Subscription,
)

graphql_app = GraphQLRouter(
    schema,
    subscription_protocols=[
        GRAPHQL_TRANSPORT_WS_PROTOCOL,
        GRAPHQL_WS_PROTOCOL,
    ],
)

app = FastAPI()
app.include_router(graphql_app, prefix='/graphql')
```

Running app with:
```bash
python -m uvicorn main:app --reload --port 12345 
```

**Comment by patrick91** [comment]
@Mukhametvaleev this seems to be fixed in the latest versions of strawberry:

<img width="1857" alt="CleanShot 2023-07-05 at 11 30 26@2x" src="https://github.com/strawberry-graphql/strawberry/assets/667029/d2922530-bcb3-4e35-88f3-7695f641ed2f">

I'll close this, but if you still have the issue let me know :)
