### ISSUE TITLE
Implement parse_multipart_body() in the Channels integration

### ISSUE THREAD

**Issue by cdroege** [strawberry-graphql/strawberry#2764]
## Feature Request Type

- [x] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

The Channels integration does not support `multipart/form-data` requests as [the parse_multipart_body() method is not implemented](https://github.com/strawberry-graphql/strawberry/blob/a621868f88d805f9c08176446a3ab03e81201235/strawberry/channels/handlers/http_handler.py#L158) and this causes file uploads to fail with a `Unable to parse the multipart body` error.

I intend to implement this feature myself as I already have some working code for this. I will create a PR for this in a few days (when I cleaned up the code and wrote a test).

**Comment by patrick91** [comment]
@cdroege thanks for wanting to submit a PR :) 

this might be a bit to ask, but would you be interested in also updating the channels integrations to use our base http view?

I did start this here: https://github.com/strawberry-graphql/strawberry/pull/2694/files

I might make your work on parsing forms easier, since it is already done in the base view

**Comment by cdroege** [comment]
Might be a good idea to migrate to the new base view as well. I will have a look at it!

**Comment by patrick91** [comment]
@cdroege thanks! happy to help if needed!

**Comment by cdroege** [comment]
Short update: I am halfway there with updating the channels integration and a lot of tests work. There are still some failing tests and I need to integrate the `multipart/form-data` handling (and then I need to clean up the code a little bit).

**Comment by patrick91** [comment]
@cdroege feel free to submit a WIP if you want 😊 

thanks so much for doing this!

**Comment by cdroege** [comment]
Fixed in #2775 :-)
