### ISSUE TITLE
Multiple keys not supported in federation

### ISSUE THREAD

**Issue by semtexzv** [strawberry-graphql/strawberry#2783]
Multi-attribute keys are not supported in federation.

## Describe the Bug
When extending an existing type, the 
```
@strawberry.federation.type(keys=["fromAddress", "toAddress", "inputData"])
``` 
annotation results in only the first key column being propagated into 
```
@classmethod
def resolve_reference(cls, **data: object):
    print(object)
```
Prints just `{'fromAddress': '...'}

**Comment by patrick91** [comment]
The SDL seems to be ok: https://play.strawberry.rocks/?gist=1b7b8136d853dc60bf19781f28feaefa

can you share a reproduction sample for your issue? 😊

**Comment by rahulsuthar0595** [comment]
We need to pass keys as a single string with space separated.
 
1. Subgraph 1:

```
@strawberry.federation.type(keys=["id title"])
class MovieType(FilteredDataMixin):
    id: int
    title: str
```

2. Subgraph 2:
```
@strawberry.federation.type(keys=["id title"], extend=True)
class MovieType(FilteredDataMixin):
    id: int = strawberry.federation.field(external=True)
    title: str = strawberry.federation.field(external=True)
```
