### ISSUE TITLE
Add the option in ChannelsConsumer to confirm topic subscription

### ISSUE THREAD

**Issue by moritz89** [strawberry-graphql/strawberry#2799]
In order to inform the subscriber (GraphQL client) that the GQL subscription has been activated, it would be useful to return a null message. In order to avoid a race condition, it would be useful to configure `ChannelsConsumer.channel_listen` to return None as soon as the subscription on the channels layer has been activated.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

In `ChannelsConsumer.channel_listen`, I would like to add the option of yielding None after the `channel_layer.group_add` loop:

```py
# strawberry/channels/handlers/base.py:150
for group in groups:
    await self.channel_layer.group_add(group, self.channel_name)
    added_groups.append(group)
```

This would allow the subscriber to be written like this:

```py
@strawberry.type
class FooSubscription:
    @strawberry.subscription
    @staticmethod
    async def foo_subscription(info: Info) -> AsyncGenerator[FooType | None, None]:
        # yield None
        async for message in info.context.ws.channel_listen("foo_type", groups=["a"]):
            if message is None:
                yield None
                continue
            yield FooType(message["payload"])
```

The commented out `yield None` is a workaround but confirms the subscription before the topic has been subscribed to. This is noticeable in tests when testing the Channels communication via REDIS.

**Comment by patrick91** [comment]
@DoctorJohn what do you think? 😊

**Comment by DoctorJohn** [comment]
Interesting. Yielding `None` from `channel_listen` would certainly work, but I feel like it's not obvious to newcomers why the first yielded value would always be `None`. After a quick local experiement I think it's possible to make the `channel_listen` method return an AsyncGenerator after all groups have been added to the channel layer. The method could then be used like this:

```python
@strawberry.type
class FooSubscription:
    @strawberry.subscription
    @staticmethod
    async def foo_subscription(info: Info) -> AsyncGenerator[FooType | None, None]:
        gen = await info.context.ws.channel_listen("foo_type", groups=["a"])
        yield None
        async for message in gen:
            yield FooType(message["payload"])
```

However, this would still be a breaking change since `channel_listen` would now return `Awaitable[AsyncGenerator]` instead of `AsyncGenerator`.

**Comment by moritz89** [comment]
Thanks for investigating possible solutions. Would an idea be to have a separate method that returns the awaitable AsyncGenerator but is used by the original channel_listen method?

I'd agree that having the option of returning an awaitable AsyncGenerator instead yielding None as the first message is the more expected behavior.

**Comment by moritz89** [comment]
Should I create a pull request based on the following interface or do have you already coded something up?

```py
class ChannelsConsumer(AsyncConsumer):
    async def channel_listen(...) -> AsyncGenerator[Any, None]:
            return await self.base_channel_listen(...)

    async def base_channel_listen(...) -> Awaitable[AsyncGenerator[Any, None]]:
            ...
```

**Comment by patrick91** [comment]
I think we can afford a breaking change for this 😊

**Comment by moritz89** [comment]
I created to approaches for handling channel_listen. One naive approach and one that uses a context manager to avoid missing cleanup.
