### ISSUE TITLE
Exception handling with status code . As graphql-strawberry always return status code as 200 OK.

### ISSUE THREAD

**Issue by itsckguru** [strawberry-graphql/strawberry#2813]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

def default_resolver(root, field):
    """resolver"""
    try:
        return operator.getitem(root, field)
    except KeyError:
        return getattr(root, field)

config = StrawberryConfig(
    default_resolver=default_resolver
)

 schema = strawberry.Schema(query=Query,config=config)
 graphql_app = GraphQLRouter(schema, graphiql = env!='production')

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/2813">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2813/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/2813/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
The reason Strawberry almost always returns 200 OK is because that's part of the [GraphQL specification](https://graphql.org/learn/serving-over-http/#status-codes). Following the specification is important to stay compatible with standard GraphQL clients and tools.
