### ISSUE TITLE
Tests failing from DeprecationWarnings in strawberry code

### ISSUE THREAD

**Issue by rjwills28** [strawberry-graphql/strawberry#2857]
## Describe the Bug

Our tests have started failing with a later release of Strawberry (0.183.6) because of deprecation warnings. They fail the moment they try to import a strawberry module. We run our tests to error on warnings and we do not ignore deprecation warnings. 

```
../xxx/strawberry/types/fields/resolver.py:199: in reserved_parameters
    return {spec: spec.find(parameters, self) for spec in self.RESERVED_PARAMSPEC}
../xxx/strawberry/types/fields/resolver.py:199: in <dictcomp>
    return {spec: spec.find(parameters, self) for spec in self.RESERVED_PARAMSPEC}
../xxx/strawberry/types/fields/resolver.py:128: in find
    warnings.warn(warning, stacklevel=3)
E   DeprecationWarning: Argument name-based matching of 'info' is deprecated and will be removed in v1.0. Ensure that reserved arguments are annotated their respective types (i.e. use value: 'DirectiveValue[str]' instead of 'value: str' and 'info: Info' instead of a plain 'info').

```

I've tracked this down and it seems that some strawberry code is actually triggering the deprecation warning. This is happening in `strawberry/relay/types.py:365`. 
https://github.com/strawberry-graphql/strawberry/blob/d4ae4a5f4504c34fd5c7234f0bb7266e8cfbe674/strawberry/relay/types.py#L365
The `info:Info` parameter looks like it is being declared in the recommended way (given the warning above), however it still triggers the warning. If I change the `info` variable to be named `info2` for example, the warning goes away.

As a test, I've also run the strawberry test locally but have removed the `ignore:DeprecationWarning:strawberry.*.resolver` flag (i.e. https://github.com/strawberry-graphql/strawberry/blob/d4ae4a5f4504c34fd5c7234f0bb7266e8cfbe674/pyproject.toml#LL164C1-L164C56) and also set to error on warning. In this case I get the same failures due to deprecation warnings in the strawberry tests.

## System Information

 - Operating system: Centos 7 
 - Strawberry version (if applicable): 0.183.6 (have not tested exactly which release introduced this issue). It is still present in 0.186.0

**Comment by patrick91** [comment]
on it! :D
