### ISSUE TITLE
mixins are incorrectly resolved

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2869]
having a mixin in a different file like:

_shared.py:
``` python

class ActionMixin:
    @gql.field()
    async def availableActions(self, info: Info) -> List[ActionEntry]:
```

``` python

@gql.django.type(Cluster, name="Cluster")
class ClusterNode(ActionMixin, relay.Node):
    ...

```
causes a
Cannot query field 'availableActions' on type 'Cluster'.

## System Information

 - Strawberry version (if applicable): 0.186.2

**Comment by devkral** [comment]
it used to work before the relay module was introduced

**Comment by ddoroshev** [comment]
@devkral I faced the same issue, decorating the mixin with `@gql.type` or `@strawberry.type` fixed it:

```python
@gql.type
class ActionMixin:
    @gql.field()
    async def availableActions(self, info: Info) -> List[ActionEntry]:
```

**Comment by devkral** [comment]
thank you, this works.
It may should be documented
