### ISSUE TITLE
Version incompatibility with `typing_extensions.deprecated`.

### ISSUE THREAD

**Issue by coady** [strawberry-graphql/strawberry#2871]
## Describe the Bug
The latest version imports `typing_extensions.deprecated`, which was added in [v4.5](https://typing-extensions.readthedocs.io/en/latest/index.html#deprecated). Pyproject.toml only requires version >=4.1.

```python
.venv/lib/python3.11/site-packages/strawberry/types/types.py:16: in <module>
    from typing_extensions import Self, deprecated
E   ImportError: cannot import name 'deprecated' from 'typing_extensions' 
```

## System Information

 - Operating system: any
 - Strawberry version (if applicable): 0.187.0

**Comment by patrick91** [comment]
thanks! I'll bump the requirement now 😊
