### ISSUE TITLE
Replace playground with GraphiQL

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#292]
When I added the playground I mainly did it because it supported subscription, but it looks like now GraphiQL supports them as well: https://github.com/graphql/graphiql/tree/master/packages/graphiql

It might also be nice to add the explorer plugin by default, since it provides a really nice dev experience: https://github.com/OneGraph/graphiql-explorer

We should also consider whether to disable this by default and only having it in debug mode. (Same for introspection).

**Comment by sarendsen** [comment]
How about a separate flag to enable/disable graphiql. I can imagine wanting to have debug off but but graphiql on.

```python
graphql_app = GraphQL(schema, debug=False, graphiql=True)
```

**Comment by patrick91** [comment]
@sarendsen yes!

We'd need this for our django, flask and asgi apps :)

**Comment by sarendsen** [comment]
I should be able to create a initial PR for this somewhere this week if that's fine by you.

**Comment by patrick91** [comment]
Sure!
