### ISSUE TITLE
tests on windows broken?

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2941]
Seemingly the hook tests on windows are broken.

First there are many deprecation warnings, second my code change works for all other tests.

PR on which "tests on windows" fail (there are also some other):

https://github.com/strawberry-graphql/strawberry/pull/2938

**Comment by patrick91** [comment]
yes, I need to take a look at them 😊

**Comment by devkral** [comment]
thank you.

I hope some day windows moves to the linux or BSD kernel.

Microsoft sells a desktop but couple it with a homegrown kernel with lots of problems
