### ISSUE TITLE
`ConnectionExtension` doesn't pass paging parameters to resolver

### ISSUE THREAD

**Issue by harrykao** [strawberry-graphql/strawberry#2949]
## Describe the Bug

I might be confused about the right way to implement paging...

Consider a schema that looks like this:

```python
@strawberry.type
class Query:
    @relay.connection(MyCustomConnection)
    def thing(self, **kwargs) -> Iterable[Thing]:
        // return Things from here?

class MyCustomConnection(relay.Connection[Thing]):
    @classmethod
    def resolve_connection(
        cls,
        nodes: Iterable[Order],  // return value from thing() resolver
        **kwargs,
    ):
        // take nodes and return a Connection object?
```

Is the intention for (1) the resolver to determine the list of nodes that will be returned from the GQL query and (2) the `resolve_connection()` method to create a `Connection` object from those nodes?

I'm finding that the resolver doesn't receive the paging parameters so it's not able to (efficiently) return the correct nodes. In my case I'm reading data from a DB and I need the paging params to determine the `limit` and `where` clauses.

Should the paging params be passed on line 269 here?

https://github.com/strawberry-graphql/strawberry/blob/fb7a9c463027d86965219b8647220d35fd692084/strawberry/relay/fields.py#L255-L275

Or am I not using the code as intended?

**Comment by harrykao** [comment]
@bellini666 Any thoughts on this? It looks like you were the original author?

**Comment by harrykao** [comment]
Ah, I see, thank you for the detailed explanation. That makes sense that you can return a `QuerySet` from the resolver (or, in our case, a SQLAlchemy query object) and defer the actual query to `resolve_connection()` after it's been sliced/chained using the paging params.

That doesn't quite work for me though. Our GQL layer is built around a Python API that encapsulates the business logic. The GQL resolvers don't access the DB directly because that's considered an implementation detail of the Python API.

I've worked around this by making my own versions of `connection()` and `ConnectionExtension` that pass the paging parameters to the resolver so that it can send them to the Python API.

Question: Even if the resolver did have direct access to the DB, are you sure it wouldn't be better for the resolver to receive the paging info? My understanding is that Relay doesn't use offset and limit, but rather per-node cursors that indicate the position of each node in the global ordering. The approach that you describe would apply the ordering in the resolver but the pagination (filtering with a `where` clause) in `resolve_connection()`. How to determine whether one node comes before the other depends on how they're ordered, so I think you end up with logic in two places (the resolver and the `Connection` object)? But if the resolver handles paging then all the logic is there and it's easier to make `Connection` generic, since all it does is take a list of nodes and returns it formatted as a Relay connection.

**Comment by harrykao** [comment]
Yeah, I think you're right that I might as well use the approach you mentioned above. I'll close this with a few observations:

1. It would be nice to get the `first`/`last`/`before`/`after` args for free as we do when we call `connection()`.
2. The [example in the docs](https://strawberry.rocks/docs/guides/relay#custom-connection-pagination) of cursor-based pagination shows a custom class that derives from `Connection`, which is what led me to think I should do that.
3. It feels a little weird that we should use `connection()` for some connections but not others. The difference is a bit subtle from a lay person's point of view.

Anyway, thanks again for the detailed comment!

**Comment by bellini666** [comment]
> The [example in the docs](https://strawberry.rocks/docs/guides/relay#custom-connection-pagination) of cursor-based pagination shows a custom class that derives from Connection, which is what led me to think I should do that.

What do you think should be changed in there to make that less confusing?

> It feels a little weird that we should use connection() for some connections but not others. The difference is a bit subtle from a lay person's point of view.

You can use `connection()` with any `Connection` subclass you want! It is just that when using it, you are able to return an iterable/generator and not worry about pagination at all, and the connection itself will handle that for you.

Maybe that's something that can be clarified in the docs as well?
