### ISSUE TITLE
Add support for converting UUID

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#301]
They should be converted to ID :)

```
import uuid

@strawberry.type
class X:
    id: uuid.UUID
```

**Comment by SanketDG** [comment]
I'd be interested in taking this up! What files/functions should I be looking for?

**Comment by patrick91** [comment]
This pr might be useful: https://github.com/strawberry-graphql/strawberry/pull/267

We also do the conversion of all the other types here: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/type_converter.py#L26

Let me know if this helps :)

**Comment by SanketDG** [comment]
I am a little confused on this.

I naively understand that I have to put some sort of check in https://github.com/strawberry-graphql/strawberry/blob/ae863ee8464b2c13f5b31ce20cd2aea23b634290/strawberry/type_converter.py#L85 but I am not sure if this is the right place.

**Comment by patrick91** [comment]
@SanketDG I would start by writing a test and see where it fails, that should help!

We also have a discord server if that's easier to chat: https://discord.gg/qWpCDkG

**Comment by patrick91** [comment]
This has been done and merged!
