### ISSUE TITLE
Allow alias for Resolver Functions' Param

### ISSUE THREAD

**Issue by maacck** [strawberry-graphql/strawberry#3029]
Provide "alias" ability to resolver functions' param.

Something like FastAPI

```python
async def example_resolver( _id: strawberry.Param(..., alias="id")) -> Res:
    ....
```

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Since GraphQL commonly using name "input" for mutation, and "input" is bultin function in python. It will be better if we could find a way to use "alias" and also fit both Python and GraphQL naming convention.

**Comment by patrick91** [comment]
hi @maacck! that's already possible with strawberry.argument, see: https://play.strawberry.rocks/?gist=433579242535b6715dd0e4b95f24c878

```python
import strawberry

from typing import Annotated

@strawberry.type
class User:
    name: str
    age: int

@strawberry.type
class Query:
    @strawberry.field
    def user(self, input_: Annotated[str, strawberry.argument(name="input")]) -> User:
        return User(name="Patrick", age=100)

schema = strawberry.Schema(query=Query)
```

This should be documented though!

**Comment by maacck** [comment]
Aha, Thanks you @patrick91 . It works now. 
I actually have tried to use strawberry.arugment before, but somehow it didn't work. And this should definitely be documented
