### ISSUE TITLE
Add output file to `export-schema`

### ISSUE THREAD

**Issue by stillmatic** [strawberry-graphql/strawberry#3032]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ X ] New behavior

## Description

Currently, schema export only supports printing to stdout. I would like to save to a file, and while it's possible to use redirection to do so, I think saving schema to a file is a common enough use case that it should have native support. I've made a diff here: https://github.com/strawberry-graphql/strawberry/compare/main...stillmatic:strawberry:main and am happy to submit that as a PR.

**Comment by patrick91** [comment]
I think that's fair 😊

happy to review the PR, I'd already suggest to use pathlib (and write a test) 😊
