### ISSUE TITLE
Missing 'typer' and 'libcst' dependencies.

### ISSUE THREAD

**Issue by DaudLN** [strawberry-graphql/strawberry#3056]
## Describe the Bug

I noticed that when running the 'strawberry codegen' command, the required dependencies.
This caused the command to fail with a 'ModuleNotFoundError.' As a workaround, I installed these dependencies manually to resolve the issue.

## System Information

 - Operating system: Ubuntu 23.04
 - Python version: 3.11.4
 - Strawberry version (if applicable): 0.205.0

## Steps to Reproduce

1. Install Strawberry.
``` bash
pipenv install strawberry-graphql==0.205.0
```
3. Attempt to run the 'strawberry codegen' command.
```bash
strawberry codegen --schema schema --output-dir . -p python query.graphql
```
4. Observe the 'ModuleNotFoundError' related to missing dependencies.

## Expected Behavior

The 'strawberry codegen' command should run successfully without missing dependencies.

**Comment by patrick91** [comment]
@DaudLN you can install all the cli dependencies by installing `strawberry-graphql[cli]` 😊

we've done it this way so you don't install dependencies that you might not need

**Comment by DaudLN** [comment]
Thank you Patrick

**Comment by patrick91** [comment]
I'll close then! 😊
