### ISSUE TITLE
Support comparison operators

### ISSUE THREAD

**Issue by cikay** [strawberry-graphql/strawberry#3070]
Strawberry should support comparison operators such as greater than, less than, starts with etc. [strawbeery-graphql-django](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/filters/) package supports it but strawberry should support it independent of an ORM. 

## Feature Request Type

- [x] New behavior

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3070">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3070/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3070/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
how should strawberry support them?

**Comment by cikay** [comment]
> how should strawberry support them?

The basic support is to just add t[his type](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/strawberry_django/filters.py#L54) to the package

and document how to use it like below

````py
@strawberry.type
class User:
    name: FilterLookup[str]

```

To make all fields as Lookup you can follow the same way in [strawberry-graphql-django ](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/filters/)

```py
@strawberry.type(lookups=True)
class User:
    firstname: str
    lastname: str
```

will be equivalent

```
@strawberry.type
class User:
    firstname: FilterLooup[str]
    lastname: FilterLookup[str]
```

**Comment by patrick91** [comment]
I think this might be a case where this feature could be implemented in a 3rd party package 😊

/cc @bellini666

**Comment by cikay** [comment]
I have written an [article](https://medium.com/@muzaffer-cikay/query-operators-in-graphql-1453e3b517ad) about it by the way.
