### ISSUE TITLE
`strawberry.field` does not type check properly for async resolvers, but `strawberry.field()` does

### ISSUE THREAD

**Issue by ben-xo** [strawberry-graphql/strawberry#3071]
## Describe the Bug

An example speaks a thousand words. Given the following minimal test case:

```python
import strawberry
from django.test import SimpleTestCase


@strawberry.type
class Example:
    @strawberry.field
    async def async_field_1(self) -> str:
        return "str 1"

    @strawberry.field()
    async def async_field_2(self) -> str:
        return "str 2"


class ExampleTest(SimpleTestCase):
    async def test_types(self):
        example = Example()

        self.assertEqual(await example.async_field_1(), "str 1")
        self.assertEqual(await example.async_field_2(), "str 2")
```

* the only difference between async_field_1 and async_field_2 is the parentheses after the `strawberry.field` annotation
* the test passes (demonstrated by green checkmark)
* the first assertion does not pass type check (demonstrated by red squiggly). The second one does.

Screenshot:
<img width="762" alt="Screenshot 2023-09-01 at 12 38 27" src="https://github.com/strawberry-graphql/strawberry/assets/75862/808048a1-a926-437b-8321-6e6e3b13e2f0">

The problem shows up as "async_field_1 is not awaitable" (if the field has args), or "missing argument for parameter resolver" (if the field has no args)

## System Information

 - Strawberry version: 0.204.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3071">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3071/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3071/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
hi @ben-xo! it this mypy or pyright?

**Comment by ben-xo** [comment]
> hi @ben-xo! it this mypy or pyright?

It's coming up as Pylance within VSCode so I guess it must be pyright. Our mypy config seems ok with it.

**Comment by ben-xo** [comment]
Here are the two variations
<img width="960" alt="Screenshot 2023-09-01 at 12 52 37" src="https://github.com/strawberry-graphql/strawberry/assets/75862/0ab752e6-101a-4b72-87f6-c9808102266b">
<img width="1024" alt="Screenshot 2023-09-01 at 12 40 35" src="https://github.com/strawberry-graphql/strawberry/assets/75862/4c9f7494-dc4a-4f8a-9033-c483748ad168">
