### ISSUE TITLE
Custom scalar types can not use literals starting with '-' sign

### ISSUE THREAD

**Issue by Ansud** [strawberry-graphql/strawberry#3075]
I'm writing custom scalar type to support NaN, Infinity and -Infinity. Unfortunately there is a problem with '-' sign, strawberry code requires that after minus sign there must be a number, not letters. 

## Describe the Bug

Let define custom scalar and call it `Double`

```
def parse_double(value: Any) -> float:
    if type(value) == str:
        if value == "NaN":
            return float("nan")
        elif value == "Infinity":
            return float("inf")
        elif value == "-Infinity":
            return float("-inf")

    if type(value) != float:
        raise GraphQLError(f"Value is not a float")

    return value


Double = strawberry.scalar(
    NewType("Double", float),
    serialize=lambda v: v,
    parse_value=parse_double,
)
```

I pass request to graphql like 

```
mutation
    { add_data(rows: [
       { val: NaN },
       { val: Infinity },
       { val: -Infinity },
    ] ) etc
```

And i properly receive NaN and Infinity in my `parse_double` function and handle it.
Unfortunately when i pass '-Infinity' i've got the error message "Syntax Error: Invalid number, expected digit but got: 'I'."
Looks like custom scalars should not make assumptions about data.

## System Information

FastAPI 0.103.1 + Strawberry 0.205

**Comment by Ansud** [comment]
No any updates? )

**Comment by patrick91** [comment]
@Ansud I haven't been able to check this yet, but it might be GraphQL not supporting this use case (you might need to send a string)

can you make a tiny demo here, so I can double check? https://play.strawberry.rocks/

**Comment by Ansud** [comment]
Sure, here we are:

Code 
```
import strawberry
from typing import Any, NewType, Optional

def parse_double(value: Any) -> float:
    if type(value) == str:
        if value == "NaN":
            return float("nan")
        elif value == "Infinity":
            return float("inf")
        elif value == "-Infinity":
            return float("-inf")

    if type(value) != float:
        raise GraphQLError(f"Value is not a float")

    return value


Double = strawberry.scalar(
    NewType("Double", float),
    serialize=lambda v: v,
    parse_value=parse_double,
)

@strawberry.type
class Test:
    value: Double
    response: Optional[str] = None

@strawberry.type
class Query:
    @strawberry.field
    def test(self) -> Test:
        return Test(value=1000)

@strawberry.type
class Mutation:
    @strawberry.mutation
    def add_it(self, value: Double) -> Test:
        resp = f"Adding {value} type {type(value)}"

        return Test(value=value, response=resp)
        
schema = strawberry.Schema(query=Query, mutation=Mutation)
```

Query
```
mutation {
    addIt(value: NaN) {
       response
    }
}
```

You can pass to value `NaN`, `Infinity` and them work well. But if you pass `-Inifity` you will get following error
```
Syntax Error: Invalid number, expected digit but got: 'I'.
```

**Comment by Ansud** [comment]
When i pass following mutation 
```
mutation {
    addIt(value: Inifinity) {
       response
    }
}
```
i got this
```
{
  "addIt": {
    "response": "Adding nan type <class 'float'>"
  }
}
```
This is correct answer of course.

**Comment by Ansud** [comment]
I suppose the problem is into `read_next_token` function, somewhere inside this code
```
            if is_digit(char) or char == "-":
                return self.read_number(position, char)
```

The code found minus sign and make an assumption that next part must be digits.

**Comment by Ansud** [comment]
And other suggestion is to support full IEEE754 standard for float numbers with three additional tokens: NaN, Infinity and minus Infinity.

**Comment by patrick91** [comment]
> I suppose the problem is into `read_next_token` function, somewhere inside this code
> 
> ```
>             if is_digit(char) or char == "-":
>                 return self.read_number(position, char)
> ```
> 
> The code found minus sign and make an assumption that next part must be digits.

I think this would be an issue for GraphQL core then: https://github.com/graphql-python/graphql-core

Just checked and GraphQL spec doesn't allow Infinity by default, and I'm assuming it's not also allowed by the grammar? Let me ask on discord 😊

**Comment by patrick91** [comment]
@Ansud hey, yes! so this: 

```
mutation {
    addIt(value: -Infinity) {
       response
    }
}
```

won't work (the spec doesn't allow it)

but you can still do this:

```
mutation {
    addIt(value: "-Infinity") {
       response
    }
}
```

see: https://play.strawberry.rocks/?gist=4591bb797e58b7fc0c1be892867a7659

**Comment by Ansud** [comment]
Ok, thanks for clarification. I close this issue then.

**Comment by Ansud** [comment]
Specs doesn't allow such format. There is workaround with quotes or adding another constant like 'MinusInfinity'.
