### ISSUE TITLE
Missing `starlite` docs

### ISSUE THREAD

**Issue by dhirschfeld** [strawberry-graphql/strawberry#3081]
`starlite` integration was added in https://github.com/strawberry-graphql/strawberry/pull/2391 in which docs were added.

The doc file does exist - https://github.com/strawberry-graphql/strawberry/blob/main/docs/integrations/starlite.md

...but on the website there is no mention of it under Integrations:

![image](https://github.com/strawberry-graphql/strawberry/assets/141107424/2ab0f850-89c5-4e07-b0bb-be3f53d622a7)

...and searching for `starlite` in the docs also brings up no results.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3081">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3081/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3081/pledge.svg">
</picture>
</a>

**Comment by dhirschfeld** [comment]
Interestingly, if you manually enter the url, it does work:
https://strawberry.rocks/docs/integrations/starlite

...so it seems like it's just missing an entry in the navigation.

**Comment by patrick91** [comment]
ah yes, we need to add a link to docs/index.md 😊

**Comment by dhirschfeld** [comment]
That's what I thought, but I couldn't see where to add it - I can't see the files being manually listed in the index :thinking:

**Comment by patrick91** [comment]
https://github.com/strawberry-graphql/strawberry/blob/main/docs/README.md here sorry, not docs/index.md 😊

**Comment by dhirschfeld** [comment]
> [`main`/docs/README.md](https://github.com/strawberry-graphql/strawberry/blob/main/docs/README.md?rgh-link-date=2023-09-07T22%3A45%3A55Z) here sorry, not docs/index.md 😊

I took a crack at it over in #3082!
