### ISSUE TITLE
Unable to use Unions with Generics

### ISSUE THREAD

**Issue by farzeni** [strawberry-graphql/strawberry#3098]
## Describe the Bug

Not sure if it is a bug or something non supported but when passing a union to a generic type strawberry is unable to initialize the schema.

The following example would work using a single strawberry type with Connection, but it fails when using an union 

```python
from typing import Generic, TypeVar, Union
import strawberry

T = TypeVar("T")


@strawberry.type
class Edge(Generic[T]):
    cursor: str
    node: T


@strawberry.type
class Connection(Generic[T]):
    edges: list["Edge[T]"]


@strawberry.type
class Entity1:
    id: int


@strawberry.type
class Entity2:
    id: int


Entities = Union[Entity1, Entity2]


@strawberry.type
class Query:
    @strawberry.field
    def entities(self) -> Connection[Entities]:
        return Connection(
            edges=[
                Edge(
                    cursor="1",
                    node=Entity1(id=1),
                ),
                Edge(
                    cursor="2",
                    node=Entity2(id=2),
                ),
            ],
        )


schema = strawberry.Schema(Query)
print(schema.execute_sync("{ entities { __typename } }"))

```
error
```
raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: Query fields cannot be resolved.
```

## System Information

 - Operating system:
 - Strawberry version (if applicable): 0.208.1

**Comment by patrick91** [comment]
hi @farzeni this seems to due to the union not having a name 😊

To fix it you can change this

```diff
-Entities = Union[Entity1, Entity2]
+Entities = Annotated[Union[Entity1, Entity2], strawberry.union(name="Entities")]
```

I'll see if I can make it work without passing a name 😊

**Comment by patrick91** [comment]
@farzeni just pushed a fix for this specific issue 😊

I'd still recommend you to give a name to the union, otherwise it would get automatically generate from the name of the types :)

**Comment by farzeni** [comment]
Hi @patrick91,

Awesome, thanks so much for resolving the issue so quickly, really appreciate it! 😄

I'll stick to your advice to always name unions. Thanks for the tip!
