### ISSUE TITLE
With pydantic v2 a field marked as Optional[conint] throws an exception

### ISSUE THREAD

**Issue by ppease** [strawberry-graphql/strawberry#3107]
## Description

I experienced this issue with `Optional[conint]`, but I suspect this will happen with any builtin pydantic field whose type ends up being an `Annotated` type.  I was able to reproduce this in the existing tests within `tests/experimental/pydantic/test_fields.py`, test method `test_conint`.  Just replace `field: pydantic.conint(lt=100)` with `field: Optional[pydantic.conint(lt=100)]`.  The exception is copied below in the additional context.

At least in my case I can work around this by just creating a validator for my field instead of using `conint`.  I only have one field that uses it.  However, it's definitely not ideal.

Example code below to see the error:

```python
class Model(pydantic.BaseModel):
    field: Optional[pydantic.conint(lt=100)]

@strawberry.experimental.pydantic.type(model=Model)
class Type:
    field: strawberry.auto
```

## System Information

 - Operating system: Mac OS
 - Strawberry version:  Need to use a new enough version for pydantic v2 support.

## Additional Context

I'm guessing we need to add some additional logic inside `replace_types_recursively` that handles the `Annotated` type more gracefully?  One thing that was interesting was when I was debugging, the `Annotated` type only comes in with `Optional`. If I just directly use `conint`, the type comes in as just an `int`.  I don't have a lot of experience with python type code so I was afraid to try and put in a fix.

```
tests/experimental/pydantic/test_fields.py:92 (test_conint)
@needs_pydantic_v2
    def test_conint():
        class Model(pydantic.BaseModel):
            field: Optional[pydantic.conint(lt=100)]
    
        @strawberry.experimental.pydantic.type(Model)
>       class Type:

test_fields.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../strawberry/experimental/pydantic/object_type.py:183: in wrap
    all_model_fields: List[DataclassCreationFields] = [
../../../strawberry/experimental/pydantic/object_type.py:184: in <listcomp>
    _build_dataclass_creation_fields(
../../../strawberry/experimental/pydantic/object_type.py:67: in _build_dataclass_creation_fields
    get_type_for_field(field, is_input)
../../../strawberry/experimental/pydantic/object_type.py:49: in get_type_for_field
    replaced_type = replace_types_recursively(outer_type, is_input)
../../../strawberry/experimental/pydantic/fields.py:172: in replace_types_recursively
    converted = tuple(
../../../strawberry/experimental/pydantic/fields.py:173: in <genexpr>
    replace_types_recursively(t, is_input=is_input) for t in get_args(replaced_type)
../../../strawberry/experimental/pydantic/fields.py:180: in replace_types_recursively
    replaced_type = replaced_type.copy_with(converted)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = typing.Annotated[int, None, Interval(gt=None, ge=None, lt=100, le=None), None]
params = (<class 'int'>, None, Interval(gt=None, ge=None, lt=100, le=None), None)

    def copy_with(self, params):
>       assert len(params) == 1
E       AssertionError
```

**Comment by patrick91** [comment]
can you add a tiny example code and the full error? 
 
hopefully this is easy to fix :D

**Comment by ppease** [comment]
@patrick91 Is what I added what you were looking for?  I was just copy/pasting the output from the terminal for the `pytest` run.  As I mentioned above it should be really easy to reproduce in the existing test in `test_fields.py`.

**Comment by patrick91** [comment]
> @patrick91 Is what I added what you were looking for? I was just copy/pasting the output from the terminal for the `pytest` run. As I mentioned above it should be really easy to reproduce in the existing test in `test_fields.py`.

yes! thanks :)

**Comment by gazorby** [comment]
I just encountered the same error yesterday and took a crack at it in #3109 ;)
