### ISSUE TITLE
[Enhancement] Allow Authenticated Introspection Query

### ISSUE THREAD

**Issue by XChikuX** [strawberry-graphql/strawberry#3108]
Allowing full introspection querying is not recommended from a security perspective.

However, completly blocking it using a strawberry extension doesn't make sense either.

Authenticated users with Admin priviledges should have access to the schema. I do not think strawberry has such a mechanism as of yet.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I'm thinking of moving to production soon and was trying out the disable introspection extension.
Do we have a way of returning the schema introspection. With auth headers?

Apollo supports this on their website. I'm thinking its a good idea as well.

![image](https://github.com/strawberry-graphql/strawberry/assets/5894493/5e834a94-66ab-497f-b8e4-a5475036f382)

This would make use of auth and strawberry permissions.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3108">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3108/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3108/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
This should be doable with an extension 😊

**Comment by XChikuX** [comment]
Are you in touch with the original creator of the disable introspection extension mentioned on the website?

Maybe we can tag them here. 

Or is it you 😅?

**Comment by XChikuX** [comment]
For anyone scouring the internet for an answer to this
```py
class DisableAnonymousIntrospection(base_extension.SchemaExtension):
    async def on_validation_start(self) -> None:
        schema_context = self.execution_context.context
        request = schema_context.request
        if not (await get_auth_user(request, type="introspection")):
            self.execution_context.validation_rules = (
                self.execution_context.validation_rules
                + tuple([NoSchemaIntrospectionCustomRule])
            )


user_schema = strawberry.Schema(
    query=Query,
    mutation=Mutation,
    subscription=Subscription,
    extensions=[
        QueryDepthLimiter(max_depth=7),
        MaxTokensLimiter(max_token_count=1000),
        MaskErrors(),
        DisableAnonymousIntrospection,
    ],
)
```

Have fun! Closing with comments..
