### ISSUE TITLE
Confusing Getting Started Guide

### ISSUE THREAD

**Issue by JacobGoldenArt** [strawberry-graphql/strawberry#3130]
Hi, I'm brand new to Graphql and Strawberry and sorry if this is obvious but I was going through the getting started guide
and starting on Step 3. [Step 3: Define your data set](https://strawberry.rocks/docs#step-3-define-your-data-set) It doesn't specify if you are suppose to start a new file, so I'm assuming you are still talking about the file we created in [Step 2: Define the schema](https://strawberry.rocks/docs#step-2-define-the-schema) - In your favorite editor create a file called schema.py, with the following contents:..., but I know that's probably not correct because then we are defining two classes called Query. So it would be helpful to know if I need to create a new file and then do I need to import that file into schema? Then in step 4. define your resolver. Where does that supposed to go, in the schema file or a new file? I realized that this is probably obvious if you already know some of the basics but maybe you could clarify? Thanks!

**Comment by patrick91** [comment]
Hi there!

> Hi, I'm brand new to Graphql and Strawberry and sorry if this is obvious but I was going through the getting started guide

No worries at all, we can always make the starting guide easier to follow 😊

> and starting on Step 3. [Step 3: Define your data set](https://strawberry.rocks/docs#step-3-define-your-data-set) It doesn't specify if you are suppose to start a new file, so I'm assuming you are still talking about the file we created in [Step 2: Define the schema](https://strawberry.rocks/docs#step-2-define-the-schema) 

yes same file should work

> - In your favorite editor create a file called schema.py, with the following contents:..., but I know that's probably not correct because then we are defining two classes called Query. So it would be helpful to know if I need to create a new file and then do I need to import that file into schema? 

The getting started should work in one single file, the second query is an update to the first one :)

> Then in step 4. define your resolver. Where does that supposed to go, in the schema file or a new file? I realized that this is probably obvious if you already know some of the basics but maybe you could clarify? Thanks!

All in the same file, we should definitely clarify that

also here's the complete example from the getting started: https://play.strawberry.rocks/?gist=509ba955c5e51fe48587b4036fb6053f

Hope this helps!
