### ISSUE TITLE
Add documentation for provided federated schema directives

### ISSUE THREAD

**Issue by bradleyoesch** [strawberry-graphql/strawberry#3134]
Strawberry helpfully provides a bunch of federated schema directives we can use:
https://github.com/strawberry-graphql/strawberry/blob/628e4980b50e317cf99999aef052b8bb095370df/strawberry/federation/schema_directives.py

There's no reference to the provided directives in documentation, so I didn't even know they existed until I stumbled upon the code.

I can add documentation to at the very least list the defined directives and link out to apollo with details about what they are.

Where should this live?
In https://strawberry.rocks/docs/guides/federation?
In https://strawberry.rocks/docs/types/schema-directives?
In a new Federated Schema Directives page?

**Comment by bradleyoesch** [comment]
Related:
https://github.com/strawberry-graphql/strawberry/pull/2047
https://github.com/strawberry-graphql/strawberry/issues/1873

**Comment by patrick91** [comment]
we can add it to [strawberry.rocks/docs/guides/federation](https://strawberry.rocks/docs/guides/federation) for now 😊
