### ISSUE TITLE
Messages from errors thrown in entity resolution are swallowed by a generic failure message

### ISSUE THREAD

**Issue by bradleyoesch** [strawberry-graphql/strawberry#3135]
In entity resolvers, if you throw an error, the library catches the error and wraps it in a GraphQL Error:
https://github.com/strawberry-graphql/strawberry/blob/628e4980b50e317cf99999aef052b8bb095370df/strawberry/federation/schema.py#L210-L216

* The message is replaced with a generic "Unable to resolve reference for {definition.origin}"
* The definition origin is the full python classpath, revealing underlying implementation details to the client
   * e.g. "Unable to resolve reference for <class 'somedjangoapp.graphql.types.MyEntity'>"
* I haven't double checked this but this might also remove all GraphQLError details like path/location if the thrown error is itself already a GraphQLError

The test itself obscures this issue:
https://github.com/strawberry-graphql/strawberry/blob/628e4980b50e317cf99999aef052b8bb095370df/tests/federation/test_entities.py#L215-L217

Dumbest potential solution:
```python
try:
    result = get_result()
except Exception as e:  # noqa: PERF203
    if isinstance(e, GraphQLError):
        result = e
    else:
        message = f"Unable to resolve reference for {definition.origin}"
        result = GraphQLError(
            e.message or message,
            original_error=e,
        )
```

I'm willing to make a PR if this seems reasonable!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3135">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3135/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3135/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
sounds good to me!

**Comment by bradleyoesch** [comment]
Having issues getting tests to run, so I'll have to come back to this later

Tried it on two machines, both get a bunch of pydantic errors. If this looks familiar to anyone and can point me in a good direction, I'd appreciate i!
`ERROR  - pydantic.errors.PydanticUserError: `const` is removed, use `Literal` instead`

**Comment by patrick91** [comment]
@bradleyoesch feel free to ignore that test, there's some dependency issue at the moment 😊

**Comment by DoctorJohn** [comment]
Just to make sure we're on the same page: Do I understand correctly that you want the original error message to be surfaced to the client instead of getting overwritten by "Unable to resolve reference for..." which also happens to leak project internal paths?

**Comment by bradleyoesch** [comment]
@DoctorJohn yes that is correct
