### ISSUE TITLE
Add documentation for non-root mutations

### ISSUE THREAD

**Issue by bradleyoesch** [strawberry-graphql/strawberry#3136]
Namespaced mutations are recommended by apollo and other organizations (TODO: links).

We could provide a small section for how to implement this idea.

See https://github.com/strawberry-graphql/strawberry/issues/2853 for example

**Comment by patrick91** [comment]
I'm ok with having them document as long as we explicitly define the tradeoffs 😊

**Comment by bradleyoesch** [comment]
@patrick91 the tradeoffs of using the schema directives themselves? Of using the strawberry ones vs defining your own?

**Comment by bradleyoesch** [comment]
Oh woops yes, mixed it up with https://github.com/strawberry-graphql/strawberry/issues/3134 that I created too 🙃
