### ISSUE TITLE
Aborting Querys 

### ISSUE THREAD

**Issue by Stainless2k** [strawberry-graphql/strawberry#3142]
In our project we use [Apollo-Client for React](https://www.apollographql.com/docs/react/)  and Strawberry.
We want to use abort signals to abort the executions of a queries to safe resources.
While using the simple approach from Apollo  seems to work on the client side it does nothing on the server side.
We assume we would need to use Apollo-Server for their approach to work.

Since we could not find anything about aborting in the strawberry docs, we wanted to ask here how it would be possible to implement aborting the execution of a query with strawberry.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3142">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3142/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3142/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
looks like this not even supported by graphql.js (and thus apollo server): https://github.com/graphql/graphql-js/issues/3764

**Comment by DoctorJohn** [comment]
This is also highly webserver and framework specific. I remember checking whether we could detect when clients disconnect before request handlers are done. I expected an exception to be raised when clients disconnect, but it turns out most frameworks are not even aware whether a client is still connected when a response is returned.
