### ISSUE TITLE
Root object is not set in service.

### ISSUE THREAD

**Issue by coady** [strawberry-graphql/strawberry#315]
There doesn't appear to be a way to actually set the `root_value`, as it isn't passed through to `execute`.  Examples like this from `test_schema`:
```python
def resolve_name(root, info) -> str:
    return root.name

@strawberry.type
class Query:
    get_name: str = strawberry.field(resolver=resolve_name)

    name = "Patrick"

schema = strawberry.Schema(query=Query)

query = """{
    getName
}"""

result = graphql.graphql_sync(schema, query, root_value=Query())
```
work because it's passed directly to the GraphQL operation.  But the same code run as a service throws `'NoneType' object has no attribute 'name'`.

**Comment by patrick91** [comment]
Uhm, we have this for the Django view:

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/django/views.py#L34-L35

We need it for flask and ASGI though
