### ISSUE TITLE
Ability to set per request context info

### ISSUE THREAD

**Issue by ogrodnek** [strawberry-graphql/strawberry#316]
I'd like to be able to set per-request context information (e.g. who is the current logged in user, etc.).  Ideally you could pass in a function that would take the current request and return context info that gets passed to resolvers.

It would be nice if it worked with the development workflow, i.e. using `strawberry server`... but I guess also allowing something to be passed in to the GraphQLView would work...

thanks! awesome work on strawberry!

**Comment by patrick91** [comment]
@ogrodnek oh interesting, we provide something like that for Django already, as we pass the request[1]:

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/django/views.py#L63-L74

Is this what you intended? Or something else? We definitely need to do this for ASGI and Flask :)

[1] I'd love to use a dataclass for this in future :)

**Comment by ogrodnek** [comment]
Hey thanks @patrick91 ! I think you have a similar thing for ASGI/flask where the request is provided.

I want to be able to add additional context info based on the request, almost like middleware, something like

```
class GraphQLView(View):
    def __init__(self, schema=None, graphiql=True, contextProvider=defaultContextProvider):
```
(I can pass in my own context provider)

then

```
context = contextProvider.requestContext(request)
```

and so in my code I could do something like

```
MyContextProvider:
   requestContext(request):
     userInfo = ... # something looking at request info
     dbConnection = ...
     whatever = ...
    
     return {"request", request, "userInfo": userInfo, "db" : dbConnection, ...}
```

and then in my resolvers I'd have access to not just the request, but also the currently authenticated user I provided, and anything else I wanted to share across resolvers...

There's a similar idea in [apollo-server](https://www.apollographql.com/docs/apollo-server/api/apollo-server/) (node/JS graphql server) (sorry, can't link directly to the option, but it's `context`)

It would also be cool if `strawberry server` could automatically pick it up like it does the schema for development, but I guess just being able to pass into the `GraphQL` classes for ASGI, etc. would be enough...

**Comment by patrick91** [comment]
@ogrodnek would be enough to being able to extend the GraphQLView like this?

```python
class MyGraphQLView(GraphQLView):
    def get_context(self, request):
         return Something()
```

**Comment by patrick91** [comment]
@ogrodnek  this should be good now, let me know if you need more ;)

**Comment by ogrodnek** [comment]
@patrick91 long overdue but thanks for adding this!!
