### ISSUE TITLE
Mypy doesn't see attributes on @strawberry.type

### ISSUE THREAD

**Issue by ziehlke** [strawberry-graphql/strawberry#3171]
Mypy throws error: 'Unexpected keyword argument...' on instance creation for @strawberry.type.

## Describe the Bug

minimal example scratch_9.py:
```python
import strawberry


@strawberry.type
class Dog:
    name: str


reksio = Dog(
    name="Reksio",
)
```

`mypy scratch_9.py`

output:
...scratch_9.py:9: error: Unexpected keyword argument "name" for "Dog"  [call-arg]

## System Information

 - Operating system: MacOs Ventura
 - Strawberry version:  using 0.211.0 (any 0.185.0+)
 - mypy version: using 1.6.1 (any 1.5.0+)
 - mypy-extensions==1.0.0
 - setup:
    [mypy]
    plugins =
        strawberry.ext.mypy_plugin

**Comment by patrick91** [comment]
@ziehlke this seems to be working fine for me:

![CleanShot 2023-11-02 at 22 23 47@2x](https://github.com/strawberry-graphql/strawberry/assets/667029/a668e154-5c8e-4816-bdec-a97876d29da3)

I think we have pretty much the same setup, can you ping me on discord if this is still happening for you?

**Comment by crabdul** [comment]
Was there a solution to this?

**Comment by ziehlke** [comment]
Hi guys, when I posted the issue I stripped most of the configuration. Unfortunatelly I stripped the part that was actually causing the issue, which was:
mypy.ini
```
[mypy]
-> follow_imports = skip <-
plugins = strawberry.ext.mypy_plugin
```
@crabdul not sure if that's the same in your case but this is still causing the issue with setup:
> graphql-core==3.2.5
> mypy==1.13.0
> mypy-extensions==1.0.0
> strawberry-graphql==0.248.1

mypy --config mypy.ini main.py
```
main.py:9: error: Unexpected keyword argument "name" for "Dog"  [call-arg]
.venv/lib/python3.12/site-packages/mypy/typeshed/stdlib/builtins.pyi:106: note: "Dog" defined here
Found 1 error in 1 file (checked 1 source file)
```
