### ISSUE TITLE
Integration of SQLAlchemy with Strawberry

### ISSUE THREAD

**Issue by DeanNeaht** [strawberry-graphql/strawberry#3198]
Hello,

I have been working with Strawberry GraphQL for a while and I am enjoying the experience and the simplicity it brings to working with GraphQL in Python. I have a query regarding the integration of ORM tools, specifically SQLAlchemy, with Strawberry.

As many projects rely on SQLAlchemy for their database operations, it would be greatly beneficial if there was a direct way to integrate Strawberry models with SQLAlchemy. Therefore, I am reaching out to inquire about the plans, if any, for incorporating SQLAlchemy support into Strawberry, or the potential for a companion library that facilitates this integration.

The key features that would be highly advantageous include:

- **SQL Query Generation from Strawberry Models**: Automating the creation of SQLAlchemy queries based on the Strawberry GraphQL models would streamline backend development, ensuring that the database queries are consistent with the GraphQL schema.
  
- **Strawberry Model Generation from SQLAlchemy Models**: Conversely, generating Strawberry GraphQL types from existing SQLAlchemy models would help in rapidly bootstrapping GraphQL APIs on top of existing databases, reducing boilerplate and accelerating development.

These features would not only improve developer productivity but would also enhance the seamless integration of GraphQL with traditional ORM-based workflows. I believe these additions would be welcomed by the community and could potentially become a best practice for integrating GraphQL with SQLAlchemy.

If there are any ongoing projects, discussions, or plans in this regard, I would love to learn more about them and potentially contribute.

Thank you for your time and the amazing work on Strawberry GraphQL.

**Comment by patrick91** [comment]
We have an integration here, is not mature as the one for django, but it will get there :D

https://github.com/strawberry-graphql/strawberry-sqlalchemy

**Comment by DeanNeaht** [comment]
Oops, I must have missed that integration – my bad! . Thanks a lot for the quick response
