### ISSUE TITLE
Outdated documentation or a bug: `KeyError: 'ws'`?

### ISSUE THREAD

**Issue by Byloth** [strawberry-graphql/strawberry#3261]
I was following the [Channels documentation](https://strawberry.rocks/docs/integrations/channels) trying to implement some Subscription behaviour using Django.  
I went through all the examples but -at the end- I'm still not able to send a chat message as described.

The problem -which cause the server to raise an Exception- is located in the `send_chat_message` mutation example.
In fact, the line `ws = info.context["ws"]` raise the `KeyError` as described in the title.

```py
class Mutation:
    @strawberry.mutation
    async def send_chat_message(
        self,
        info: Info,
        room: ChatRoom,
        message: str,
    ) -> None:
        ws = info.context["ws"]
        channel_layer = ws.channel_layer
 
        await channel_layer.group_send(
            f"chat_{room.room_name}",
            {
                "type": "chat.message",
                "room_id": f"chat_{room.room_name}",
                "message": message,
            },
        )
```

> [!NOTE]
> The `@strawberry.type` decorator is also missing from the example in the documentation.

---

In first place, I thought I was doing something wrong but then I did a little investigating into the two `Consumer` classes.

I started from the [`GraphQLWSConsumer`](https://github.com/strawberry-graphql/strawberry/blob/a90dea2a3053e857aa2adf685d5c4f5d39c527c4/strawberry/channels/handlers/ws_handler.py#L17) which works fine and can access the `ws` key object without any problems.  
It actually provides a [`ChannelsConsumer`](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/channels/handlers/base.py#L64) object (which has the reference to the `channel_layer`) in the context.

https://github.com/strawberry-graphql/strawberry/blob/a90dea2a3053e857aa2adf685d5c4f5d39c527c4/strawberry/channels/handlers/ws_handler.py#L121-L128

---

I then moved on the [`GraphQLHTTPConsumer`](https://github.com/strawberry-graphql/strawberry/blob/a90dea2a3053e857aa2adf685d5c4f5d39c527c4/strawberry/channels/handlers/http_handler.py#L202), the one that gave me the initial exception.
It seems to provide no `ws` key in the context.

https://github.com/strawberry-graphql/strawberry/blob/a90dea2a3053e857aa2adf685d5c4f5d39c527c4/strawberry/channels/handlers/http_handler.py#L239-L245

In this case, unlike the previous class where `request` and `ws` keys were a reference to the same object, even using `request` instead of `ws` doesn't provide proper access to `channel_layer` since the [`ChannelsRequest`](https://github.com/strawberry-graphql/strawberry/blob/a90dea2a3053e857aa2adf685d5c4f5d39c527c4/strawberry/channels/handlers/http_handler.py#L47) class appears to not have the `channel_layer` property.

---

And here we return to the initial question...  
Is it a bug and the `channel_layer` property is actually missing or is the documentation simply outdated?

If so... How can I properly access the `channel_layer` object within a standard mutation?  
Should I use something like [this](https://channels.readthedocs.io/en/stable/topics/channel_layers.html#using-outside-of-consumers)?

```py
from channels.layers import get_channel_layer

channel_layer = get_channel_layer()
```

**Comment by patrick91** [comment]
`info.context["ws"]` is only available in subscriptions, if you need to "update" a subscription from a mutation (or any other event) you need to use a pubsub mechanism, I'm not familiar with channels, but I think what you wrote at the end is correct:

```
from channels.layers import get_channel_layer

channel_layer = get_channel_layer()
```

😊

**Comment by cdroege** [comment]
> Before doing that... Since I'm completely new to this... Can we ask for confirmation from someone who actually knows how to properly use `channel_layer` outside of subscriptions?
> 
> What about the one that wrote the current documentation page? 🤔

The example above is fine. You can call `channels.layers.get_channel_layer().group_send(...)` outside of your subscriptions, so the following function should work:

```py
async def broadcast_message_to_room(message, room):
    channel_layer = channels.layers.get_channel_layer()

    await channel_layer.group_send(
            f"chat_{room.room_name}",
            {
                "type": "chat.message",
                "room_id": f"chat_{room.room_name}",
                "message": message,
            },
        )
```
