### ISSUE TITLE
Add support for uploading files

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#327]
I think we’d benefit from having built-in support for upload files, similar to what Apollo server does: https://www.apollographql.com/blog/file-uploads-with-apollo-server-2-0-5db2f3f60675

I did implement something like this in a side project, so shouldn’t be too hard to do. 

Support should be available for Flask, Django and ASGI :)

- [x] Django
- [x] Flask
- [x] ASGI
- [ ] Sanic

**Comment by japrogramer** [comment]
This is how one graphene implementation that I use in production does it.

Pretty simple
https://github.com/lmcgartland/graphene-file-upload/blob/master/graphene_file_upload/django/__init__.py

**Comment by patrick91** [comment]
First version for django is here, we'll test this in our repo and then add support for ASGI and Flask :) 

https://github.com/strawberry-graphql/strawberry/pull/407

**Comment by jkimbo** [comment]
@patrick91 I think we can close this now.

**Comment by patrick91** [comment]
I think sanic is missing upload support :)

**Comment by jkimbo** [comment]
Ah ok. I've added it as a todo list to the description.

**Comment by fkromer** [comment]
@patrick91 ASGI does include support with Starlette/FastAPI, right?

**Comment by patrick91** [comment]
@fkromer ASGI can be used for both starlette (https://strawberry.rocks/docs/integrations/starlette) FastAPI

but for FastAPI we have a better integration -> https://strawberry.rocks/docs/integrations/fastapi
