### ISSUE TITLE
Do I need `= None` for `Optional` fields in Strawberry types?

### ISSUE THREAD

**Issue by enginecan** [strawberry-graphql/strawberry#3335]
Hey guys, do I need `= None` in Strawberry type for `str`, `int`, or `List` fields that can have `None`, or is `Optional[...]` sufficient?

```
@strawberry.type
class X:
    id: int
    name: Optional[str] = None
    y_id: Optional[int] = None
    items: Optional[List[Item]] = None
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3335">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3335/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3335/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@enginecan it depends on how you want to use your object, if you want to skip passing some fields from the constructor then you need `= None`, if you want to be able to pass `None` to one of the field just `Optional` is fine 😊

Some examples here: https://play.strawberry.rocks/?gist=ac0cbfe7f40c0c50d45b28a74eac9022

Feel free to join our discord if you have more questions 😊 https://strawberry.rocks/discord
