### ISSUE TITLE
Private fields not private in Python 3.12.

### ISSUE THREAD

**Issue by rsr5** [strawberry-graphql/strawberry#3358]
## Describe the Bug

Private fields not private in Python 3.12.   I reproduced with the following code:

```
import strawberry

@strawberry.type
class User:
    name: str
    age: int
    secret: str = strawberry.Private[str]

@strawberry.type
class Query:
    @strawberry.field
    def user(self) -> User:
        return User(name="Patrick", age=100, secret="can't tell")

schema = strawberry.Schema(query=Query)
```

and I see the following at `http://0.0.0.0:8000/graphql`:

![image](https://github.com/strawberry-graphql/strawberry.rocks/assets/1335924/c8d44398-f780-40c4-a604-1d36eb3b628c)

## System Information

 - Operating system: Apple M1 Sonoma | Python 3.12
 - Strawberry version (if applicable): 0.218.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3358">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3358/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3358/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@rsr5 oh, that's unexpected! I'll check this today!

**Comment by rsr5** [comment]
Well spotted!   I just realised that as well.   I was trying to reproduce something we are seeing in a larger project.   I will have to keep trying!

**Comment by patrick91** [comment]
@rsr5 happy to do a call if you need help 😊

**Comment by rsr5** [comment]
Very kind of you.   I will have another go at reproducing first.
