### ISSUE TITLE
"Getting Started" instructions resulting in a "Not Found" when accessing GraphiQL

### ISSUE THREAD

**Issue by zeantsoi** [strawberry-graphql/strawberry#3362]
Following the [rudimentary instructions](https://strawberry.rocks/docs) on a clean build, I'm unable to access GraphiQL at http://0.0.0.0:8000/graphql and instead get a "Not Found" message.

## System Information

 - OSX 11.6.8
 - Strawberry version (if applicable): 0.219.0

## Additional Context

No errors manifest are surfaced to the log when running `log-level` on `debug`.

Raw response body:
```
{"detail":"Not Found"}
```

Response headers:
```
content-length	22
content-type	application/json
date	Fri, 26 Jan 2024 23:11:45 GMT
server	uvicorn
```

Request headers:
```
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding	gzip, deflate
Accept-Language	en-US,en;q=0.5
Connection	keep-alive
Host	0.0.0.0:8000
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
```

When accessing https://0.0.0.0:8000, the raw response body is:
```
{"Hello":"World"}
```

**Comment by patrick91** [comment]
@zeantsoi did you try with http://0.0.0.0:8000/graphql?

**Comment by zeantsoi** [comment]
Apologies, I mistyped the URL that’s erroring; I’ve corrected it above.

to answer your question: yes, I encounter the error when attempting to access https://0.0.0.0:8000/graphql

**Comment by zeantsoi** [comment]
@patrick91 apologies, I mistyped the URL that’s erroring; I’ve corrected it above.

To answer your question: yes, I encounter the error specifically when attempting to access https://0.0.0.0:8000/graphql.

**Comment by zeantsoi** [comment]
Quick update here: an **OS restart resolved the issue** and I can now access GraphiQL. My guess is that I had some environment variables in my previous session that were throwing off lookups.

**Comment by patrick91** [comment]
@zeantsoi thanks for letting us know!
