### ISSUE TITLE
Breaking in 0.217.0: kwargs in has_permission changed to snake_case

### ISSUE THREAD

**Issue by catwell** [strawberry-graphql/strawberry#3370]
This was also reported as a comment here last week: https://github.com/strawberry-graphql/strawberry/pull/2570#issuecomment-1915347674

Imagine you have a permission class where the user passes e.g. `projectId` and you did `user.can_access(kwargs["projectId"])`. Now it breaks and you have to do `user.can_access(kwargs["project_id"])`.

I have the same question as @wlaub: is it expected (i.e. should we update our code bases) or will this be reverted?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3370">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3370/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3370/pledge.svg">
</picture>
</a>

**Comment by catwell** [comment]
Thanks @patrick91 I agree! Then it this case updating the release note sounds fine to me.

**Comment by erikwrede** [comment]
Let's add it to the release notes and add a new test case. Will put this on my list but won't have time before next week
