### ISSUE TITLE
a custom resolver with permission_classes doesn't accept @sync_to_async decorator

### ISSUE THREAD

**Issue by shmoon-kr** [strawberry-graphql/strawberry#3385]
a custom resolver with permission_classes doesn't accept @sync_to_async decorator

Here is a code sample.

```
@strawberry.type
class Query:
    test: typing.Optional[User] = strawberry.field(resolver=test, permission_classes=[IsAuthenticated])

class IsAuthenticated(BasePermission):
    message = str(UnauthorizedError)

    @sync_to_async
    # This method can also be async!
    def has_permission(self, source: typing.Any, info: Info, **kwargs) -> bool:
        user = info.context['user'] if type(info.context) is dict else info.context.user
        return user

async def test(info: Info) -> typing.Optional[apps.user.models.User]:
    user = info.context['user'] if type(info.context) is dict else await info.context.async_user
    return user
```

When I define a custom async resolver like above, it works correctly.
But when I define a custom async resolver using @sync_to_async decorator, it returns an error.

```
@sync_to_async
def test(info: Info) -> typing.Optional[apps.user.models.User]:
    user = info.context['user'] if type(info.context) is dict else info.context.user
    return user

graphql.error.graphql_error.GraphQLError: Expected value of type 'User' but got: <coroutine __call__>.
```

It happens only when a permission_classes parameter is given to a custom resolver.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3385">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3385/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3385/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
Very interesting! Do you happen to have an example repo for this where we could try some things out?

Also out of curiosity, does it work if you define the field like in the following snipped?

```python
@strawberry.type
class Query:
    test: typing.Optional[User] = strawberry.field(permission_classes=[IsAuthenticated])(test)
    #                                           this is also a way to apply a decorator ^^^^^^
```

**Comment by shmoon-kr** [comment]
I just created a source code repository for this case.
Please refer to https://github.com/shmoon-kr/channels-auth-test 
meSync query raises an exception "Expected value of type 'CustomUser' but got: <coroutine __call__>." while me query has no problem.

**Comment by shmoon-kr** [comment]
I found a root cause for the issue:
`strawberry.types.resolver.StrawberryResolver.is_async` returns False for a resolver function decorated by @sync_to_async decorator. It uses inspect.iscoroutinefunction() checker and it returns True only for functions defined with "async def".
I think we could add a simple walkaround for this behavior.
