### ISSUE TITLE
Support both Pydantic 1 and 2

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#3425]
This has been a request from Discord 😊 I didn't realise you can import v1 from pydantic 2:

```python
from pydantic import v1 as pydantic
```

I don't don't know if it is a lot of work to implement this, if it is not we should do it 😊

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3425">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3425/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3425/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel

**Comment by Skeen** [comment]
Is there any way to force strawberry to use `pydantic.v1` so Pydantic 1 models still work, while Pydantic 2 is installed? - Currently trying to migrate a project to Pydantic 2, and would like to keep the changeset minimal by simply changing imports to `pydantic.v1` and then updating the code later.
