### ISSUE TITLE
Visual bug in documentation

### ISSUE THREAD

**Issue by el1sha256** [strawberry-graphql/strawberry#3434]
In new version of documentation exists visual bug

Bug when hover to links

<img width="216" alt="Screenshot 2024-04-03 at 6 29 37 PM" src="https://github.com/strawberry-graphql/strawberry/assets/45532828/959fc81b-507b-42d6-bfd7-1f3903dc3d2b">

looks like problem with z-index and wrong colors

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3434">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3434/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3434/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@el1sha256 thanks! can you link me the page that has this issue? 😊

**Comment by el1sha256** [comment]
@patrick91 I think we can close this issue, i don't see now this bug in documentation
