### ISSUE TITLE
Add support for using FastAPI APIRouter arguments in GraphQLRouter

### ISSUE THREAD

**Issue by nparamonov** [strawberry-graphql/strawberry#3441]
## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Sometimes it is necessary to use additional parameters of the FastAPI APIRouter such as `tags`, `route_class`,
`deprecated`, `include_in_schema`, etc. For example, in our project we actively use custom route_class.

I suggest adding kwargs to pass any arguments to the router.

```python
import strawberry

from fastapi import FastAPI
from strawberry.fastapi import GraphQLRouter


@strawberry.type
class Query:
    @strawberry.field
    def hello(self) -> str:
        return "Hello World"


schema = strawberry.Schema(Query)

graphql_app = GraphQLRouter(schema, tags=["graphql"], route_class=...)

app = FastAPI()
app.include_router(graphql_app, prefix="/graphql")
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3441">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3441/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3441/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
This was done in #3442
