### ISSUE TITLE
Broken documentation examples in page https://strawberry.rocks/docs/guides/dataloaders

### ISSUE THREAD

**Issue by tejusp** [strawberry-graphql/strawberry#3444]
Example within https://strawberry.rocks/docs/guides/dataloaders#usage-with-context is broken and can't be run due to invalid imports. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3444">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3444/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3444/pledge.svg">
</picture>
</a>

**Comment by tejusp** [comment]
This issue can be closed after merging https://github.com/strawberry-graphql/strawberry/pull/3445

**Comment by patrick91** [comment]
@tejusp what error do you get?

**Comment by tejusp** [comment]
![image](https://github.com/strawberry-graphql/strawberry/assets/6009613/4f406b27-abdc-4628-b18e-b185fc38cfff)

Created another PR to fix it https://github.com/strawberry-graphql/strawberry/pull/3446

**Comment by patrick91** [comment]
@tejusp what version of strawberry do you have? that error shouldn't be there anymore

**Comment by tejusp** [comment]
I'm using strawberry-graphql==0.219.2

How can we ensure the documentation is backwards compatible ?

**Comment by patrick91** [comment]
@tejusp I think we need to add a version selector to the docs, but I'd prefer to do that after v1 😊
