### ISSUE TITLE
`print_schema` does not prefix the `extend` keyword when Schema uses apollo federation

### ISSUE THREAD

**Issue by garryod** [strawberry-graphql/strawberry#3457]
## Describe the Bug

The [Apollo Federation V2 spec](https://www.apollographql.com/docs/federation/subgraph-spec/#required-resolvers-for-introspection) expects the SDL to define a [schema extension](http://spec.graphql.org/October2021/#sec-Schema-Extension) using the keywords `extend schema`. When `print_schema` is used to produce the SDL for a federated schema only `schema` is produced. This causes issues with other apps in the ecosystem such as the [Apollo Router](https://github.com/apollographql/router).

## System Information

 - Container: `docker.io/library/python:3.11`
 - Strawberry version (if applicable): `0.225.1`

**Comment by patrick91** [comment]
@garryod can you show me an example of issue caused by this? 😊 I remember it working fine in federation 2

**Comment by garryod** [comment]
I would love to, but I don't seem to be able to reproduce the issue like I could earlier, it may have been resolved when I upgraded the Apollo Router version :thinking:

**Comment by patrick91** [comment]
@garryod that's good :D  let me know if you find any other issue 😊
