### ISSUE TITLE
Ability to disable auto-camelcasing per field

### ISSUE THREAD

**Issue by magicmark** [strawberry-graphql/strawberry#3479]
Let's say I want to keep auto-camelcasing enabled for my whole service _except_ for a couple of fields

e.g. maybe i have a translations service and want to write schema/query like this:

```graphql
query {
  getTranslations(string: "Hello world") {
    en_US
    fr_FR
  }
}
```

Ideally, I could write resolvers like this

```python
@strawberry.type
class Translations:
    @strawberry.field(disable_auto_camelcase=True)
    def en_US(self) -> str: ...

    @strawberry.field(disable_auto_camelcase=True)
    def fr_FR(self) -> str: ...
```

or maybe even for a whole type?

```python
@strawberry.type(disable_auto_camelcase=True)
class Translations:
    @strawberry.field
    def en_US(self) -> str: ...

    @strawberry.field
    def fr_FR(self) -> str: ...
```

Thanks!

## Feature Request Type

[x] Alteration (enhancement/optimization) of existing feature(s)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3479">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3479/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3479/pledge.svg">
</picture>
</a>

**Comment by jacobmoshipco** [comment]
It looks like the `name=...` parameter takes priority over auto camel-casing, so this should work:

```
@strawberry.type
class Translations:
    @strawberry.field(name="en_US")
    def en_US(self) -> str: ...

    @strawberry.field(name="fr_FR")
    def fr_FR(self) -> str: ...
```

I'm unsure if there's a unit test for this use-case.

**Comment by patrick91** [comment]
I was going to suggest that, but I wonder if @magicmark would prefer to avoid the duplication?

**Comment by magicmark** [comment]
This works for me. Thanks!
