### ISSUE TITLE
Changelog on PYPI redirect to error

### ISSUE THREAD

**Issue by Philaeux** [strawberry-graphql/strawberry#3498]
Was checking the strawberry page on [PYPI](https://pypi.org/project/strawberry-graphql/), and in the left column you have a "changelog" link:

![image](https://github.com/strawberry-graphql/strawberry/assets/3007278/db82c083-f6b6-4f04-83f2-51860772e55c)

The links redirects to [https://strawberry.rocks/changelog](https://strawberry.rocks/changelog) but I get this error:

![image](https://github.com/strawberry-graphql/strawberry/assets/3007278/7d200471-9ebb-4b3e-b64e-02beb4ce2364)

The information link sends to Vercel, so I guess some configuration is wrong.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3498">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3498/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3498/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@Philaeux thank you so much, I'll make a page soon!

**Comment by patrick91** [comment]
Done here :) https://github.com/strawberry-graphql/strawberry.rocks/pull/505
