### ISSUE TITLE
Subgraph: "'NoneType' object has no attribute '...'"

### ISSUE THREAD

**Issue by dgram** [strawberry-graphql/strawberry#3506]
When i make use of subgraphs i can start the graphql server, also the docs generated successfully but when i execute a query i get the error "'NoneType' object has no attribute '...'"

```python
@strawberry.type
class TestType:
    name: str

@strawberry.type
class TestQuery:
    @strawberry.field()
    async def test() -> TestType:
        return TestType(name="test")

@strawberry.type
class Query:
    sub: TestQuery = strawberry.field(default_factory=TestQuery)

graphql_app = GraphQL(
    strawberry.Schema(
        query=Query
    )
)
# ... other fastapi graphql connection here

# query
query MyQuery {
  sub {
    test {
      name
    }
  }
}
```

## System Information

 - Operating system: MacOS
 - Strawberry version: 0.229.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3506">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3506/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3506/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@dgram to make this work you need to have a root value 😊 we don't instantiate the query type 😊

https://strawberry.rocks/docs/integrations/fastapi#root_value_getter

**Comment by dgram** [comment]
hey @patrick91 thanks for your response, what did you mean with this? i can't found an answer about this case

**Comment by patrick91** [comment]
@dgram there's an example here: https://strawberry.rocks/docs/integrations/asgi#get_root_value

**Comment by dgram** [comment]
thanks, i've found the answer. because i don't have any fields to set per default this is the right answer.

```python
@strawberry.type
class Query:
    sub: TestQuery = strawberry.field(resolver=lambda: TestQuery())
```
