### ISSUE TITLE
Allow create interfaces without fields.

### ISSUE THREAD

**Issue by koldakov** [strawberry-graphql/strawberry#3512]
Allow interfaces without fields.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description
I want to create an interface with "get" or whatever method which will get sqlalchemy object and cast to strawberry object.

```python
@strawberry.interface
class TypeBase:
    model: ClassVar[Base]

    @cassmethod
    async def get(cls, session: AsyncSession, id_: int) -> Self | None:
        try:
            obj: Base = await cls.model.get(
                session,
                id_,
            )
        except ModelDoesNotExistError:
            return None

        values: dict[str, Any]
        # Some magic with values
        return cls(**values)
```

But in this case I'm getting `❌ Type TypeBase must define one or more fields.`, which doesn't make sense IMO, as for interfaces fields are not required (usually).

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3512">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3512/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3512/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@koldakov could this interface just be a base class (so, without the decorator)?

Does it need to be an interface in GraphQL? I don't think empty interfaces are allowed in GraphQL

**Comment by koldakov** [comment]
Hi @patrick91! Thank you for the quick response.

Hmm actually you are right. Interfaces require one or more fields in GraphQL.

Closing the issue for now
