### ISSUE TITLE
Functionality for filtering events in Subscriptions

### ISSUE THREAD

**Issue by HenriKorver** [strawberry-graphql/strawberry#3513]
It would be nice if an equivalent of the `withFilter`-function as described in Apollo Server (https://www.apollographql.com/docs/apollo-server/data/subscriptions#filtering-events) is added to Strawberry.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3513">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3513/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3513/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
Hey @HenriKorver , 
thanks for the request. 
I'm not sure this is in scope for strawberry, neither am I certain about wether or not we would set the wrong incentives with this. Event bus subscriptions can have massive throughput. My personal preference is to keep the stateful part of a GraphQL application as small as possible, thereby reducing the amount of messages arriving in your resolver. This implies moving this functionality into _business logic_ (optimally a filter on the event bus subscription topic), as opposed to the resolver itself.


You can already achieve async iterable filtering with userland libraries: 
https://asyncstdlib.readthedocs.io/en/latest/source/api/builtins.html#asyncstdlib.builtins.filter

It might make sense to just document the aforementioned library in the guide, this should help anyone achieve your desired functionality. Please LMK your thoughts on this 😊

**Comment by DoctorJohn** [comment]
I agreeing with Erik on this. The python ecosystem already has great tooling for business logic specific issue. I don't see much value in providing an extra helper for from the strawberry library. But feel free to open a PR updating the docs which a library recommendation and feel free to request us to reopen this issue if needed.
