### ISSUE TITLE
GlobalID#resolve_type does not handle invalid IDs

### ISSUE THREAD

**Issue by diesieben07** [strawberry-graphql/strawberry#3532]
## Describe the Bug
`GlobalID#resolve_type` asserts that the resolved type is a `StrawberryObjectDefinition` and is a subclass of `Node`. However the Global ID is usually provided _by the user_, so an invalid ID will trigger this assertion (because there is no such type or the type is not a relay Node) and result in a bogus error response to the client. Instead such an ID should be handled just like a normal "not found".

## System Information

 - Operating system: Ubuntu
 - Strawberry version (if applicable): 0.234.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3532">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3532/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3532/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@diesieben07 can you share a reproduction? :D 

Thanks 😊

**Comment by diesieben07** [comment]
Here you go: https://play.strawberry.rocks/?gist=feaeb32b37ac52cadf807ad4b24b483a
Note the ID being passed decodes to `�erson:1` (I intentionally changed the first character of the correct Base64 for `Person:1`).
When passing `UGVyc29uOjI=` ("Person:2") you get the correct response: null.
