### ISSUE TITLE
Rename modules that have same name as aliases

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#3542]
I'm working on generating API docs for Strawberry, and noticed some issue with how we named some modules. For example we have `strawberry.auto` as an export, but we also have `strawberry.auto` as a module.

(Un)fortunately, this hasn't really caused any issue (as far as I know), but when using `griffe` to get a JSON I can use to generate the API docs I don't get everything (since some aliases and some modules have the same name). This could potentially be fixed with some changes to griffe, but I don't think it is worth it, because we'd still have some issue, for example if we have `strawberry.auto`, how do we go to its docs?

would it be `https://strawberry.rocks/docs/api/strawberry.auto`? or its full path: `https://strawberry.rocks/docs/api/strawberry.auto.auto`?

Second option could work, but I'd love to make it easier for people to find the docs by just writing the url (so `https://strawberry.rocks/docs/api/strawberry.auto` would be the best option for me).

To achieve this we'd need to change the name of the modules, while working on the site I've done some changes already (in `feature/docstring`), for example I changed `strawberry.type` to `strawberry.strawberry_type`, but while writing this issue I thought of maybe keeping the same name and making the module "private", so `strawberry._type` (it could be a good way to also tell people that they shouldn't import things from these modules)

What do you all think?

| alias name                  | proposed module name         | alternate module name      |
|-----------------------------|------------------------------|----------------------------|
| strawberry.auto             | strawberry._auto             |                            |
| strawberry.type             | strawberry._type             | strawberry.strawberry_type |
| strawberry.directive        | strawberry._directive        | strawberry.graphql_types   |
| strawberry.enum             | strawberry._enum             | strawberry.graphql_types   |
| strawberry.field            | strawberry._field            |                            |
| strawberry.mutation         | strawberry._mutation         |                            |
| strawberry.schema_directive | strawberry._schema_directive |                            |
| strawberry.union            | strawberry._union            |                            |

/cc @strawberry-graphql/core 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3542">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3542/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3542/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
+1 to the `_` names. It also enforces that those contains internal code that should only be messed with if "you know what you are doing"

**Comment by patrick91** [comment]
@bellini666 sounds good to me, I wonder if we should make a code for this? it could be a big breaking change (though, easy to fix)

**Comment by bellini666** [comment]
A codemod you mean?

Hrmmm, not sure if we need to spend time with that as this is really an internal usage.

Maybe changing `from strawberry.auto import auto` to `from strawberry import auto`, as auto importers can sometimes import from the module instead of `strawberry` directly. But other than that I don't think we need to worry as anyone importing anything other than `auto` from `strawberry.auto`, `type`/`interface`/`input`/etc from `strawberry.type` is probably doing an advanced usage and can probably fix it easily :)

**Comment by patrick91** [comment]
@bellini666 it's mostly make sure people can update easily 😊

**Comment by bellini666** [comment]
> @bellini666 it's mostly make sure people can update easily 😊

Not against it :), was just worried if it was going to be complicated.

If it is not, then we should go for it! :)

**Comment by patrick91** [comment]
it should be easy: https://libcst.readthedocs.io/en/latest/codemods.html#libcst.codemod.CodemodCommand

**Comment by DoctorJohn** [comment]
I'm late to the party but personally not fully convinced by the prefixes yet. The prefixes and the rule for applying them feels like a pretty uncommon pattern to me (on a module level).

Since this is a breaking change anyways, here is a third option: Let's move all these modules into into a package. Possibly `strawberry.types` as proposed in #849? This would solve the issue and keep the repo structure pretty standardized as well.

I need to double check whether having all of these in `strawberry.types` makes sense or whether another package name would be better. Just wanted to post this quickly before some of our modules suddently have magic underscore in front of them :O

**Comment by patrick91** [comment]
@DoctorJohn the underscore pattern is something I've noticed in [httpx](https://github.com/encode/httpx) (and probably other places)

Regarding `strawberry.types`, I'm not opposed, but we also need to figure out what to do with https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/types.py :D

**Comment by DoctorJohn** [comment]
> @DoctorJohn the underscore pattern is something I've noticed in [httpx](https://github.com/encode/httpx) (and probably other places)

Thanks for that insight! I was looking at a few repositories trying to find an example of that pattern. Should have checked httpx.

It looks like they consistently prefix every "private" module, which I personally like more than just prefixing "private" modules which happen to have an "alias". But that would be a lot of files in strawberry. Maybe this is just a me-problem lol

> Regarding strawberry.types, I'm not opposed, but we also need to figure out what to do with https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/types.py :D

Good point. In this instance I would propose `types.py` -> `object_definition.py`

**Comment by patrick91** [comment]
> It looks like they consistently prefix every "private" module, which I personally like more than just prefixing "private" modules which happen to have an "alias". But that would be a lot of files in strawberry. Maybe this is just a me-problem lol

Oh, I'd prefix all of them too, sorry I wasn't clear :D

**Comment by bellini666** [comment]
I like @DoctorJohn 's take as well

**Comment by patrick91** [comment]
@erikwrede @bellini666 can you summarise what you think we should do? :D

**Comment by bellini666** [comment]
@patrick91 following @DoctorJohn's suggestion, I'd do:

| alias name                  | proposed module name                   |
|-----------------------------|----------------------------------------|
| strawberry.auto             | strawberry.types.auto                  |
| strawberry.type             | strawberry.types.type                  |
| strawberry.directive        | strawberry.directives.directive        |
| strawberry.enum             | strawberry.types.enum                  |
| strawberry.field            | strawberry.types.fields.field          |
| strawberry.mutation         | strawberry.types.fields.mutation       |
| strawberry.schema_directive | strawberry.directives.schema_directive |
| strawberry.union            | strawberry.types.union                 |
| strawberry.union            | strawberry.types.union                 |

We can also do the same with those, if it makes sense:

| alias name                  | proposed module name                   |
|-----------------------------|----------------------------------------|
| strawberry.schema_directive | strawberry.directives.schema_directive |
| strawberry.arguments        | strawberry.types.fields                |
| strawberry.custom_scalar    | strawberry.types.custom_scalar         |
| strawberry.lazy_type        | strawberry.types.lazy                  |
| strawberry.object_type      | strawberry.types.object_type           |
| strawberry.unset            | strawberry.types.unset                 |
| strawberry.private          | strawberry.types.private               |

Also:

1) Maybe `schema_directive` and `schema_directives` can be merged into one with this change?
2) Should we just move `scalars` to `types.scalars` and rename `custom_scalars` to `scalars` only? As long as they are not living in the same package we will not have conflicts anymore

Not sure if I'm missing something or some of the suggestions are not great 😅

**Comment by skilkis** [comment]
I'm also in favor of the suggestion of  @DoctorJohn to use packages instead. The added benefit is that the repository becomes a bit more discoverable for newcomers who can quickly navigate to the `strawberry.types` if they want to find type related code

**Comment by pawamoy** [comment]
A bit of context around Griffe: https://mkdocstrings.github.io/griffe/best_practices/#avoid-member-submodule-name-shadowing.

At some point I wanted to support this, but due to the ambiguous nature of this "feature" of Python, and the complexity of the implementation to support it, I changed my mind.

I do recommend making all your modules private if you explicitly expose the public interface at the top-level. An alternative is to provide two packages in the same distribution: a private one containing all internals, and a public one just exposing the public API. With a private package you don't have to prefix all modules with `_`. It's a more drastic change though.
