### ISSUE TITLE
Feature: Default GraphQL Enums from Python Enums.

### ISSUE THREAD

**Issue by nrbnlulu** [strawberry-graphql/strawberry#3543]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description
Currently to register a GraphQL Enum from an existing enums that resides elsewhere in your code base
you need to do the following ~
```python
from somewhere import MyEnum

MyEnumGQL = strawberry.enum(MyEnum)

@strawberry.type
class Foo:
	bar: MyEnumGQL
```
This results in a [pyright error ](https://discord.com/channels/689806334337482765/1252599999380983869/1253019059281199275) that can be fixed like this
```python
from somewhere import MyEnum
if TYPE_CHECKING:
	MyEnumGQL = MyEnum
else:
	MyEnumGQL = strawberry.enum(MyEnum)
	
@strawberry.type
class Foo:
	bar: MyEnumGQL
```
It would be nice if we could just use a default GraphQL implementation of the enum on the fly
so that the `strawberry.enum` call would not be needed.
```python
from somewhere import MyEnum

@strawberry.type
class Foo:
	bar: MyEnum
```  

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3543">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3543/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3543/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
I like this! We would need some sort of a registry to ensure we don't duplicate enums across types, but other than that it's a very straight-forward devX improvement. 

The only "issue" I see is documentation - we need to make a decision on wether we want to include docstrings of the original python enum in the GraphQL schema, and we need to be aware that specific enum values are not annotatable with their own docstrings in python.

**Comment by patrick91** [comment]
> I like this! We would need some sort of a registry to ensure we don't duplicate enums across types, but other than that it's a very straight-forward devX improvement.

Good point! We might also think of this in the context of Strawberry Django (and other integrations)

Would we make a registry per schema, right? 😊

**Comment by erikwrede** [comment]
Yes, per schema. We could directly use this for Django and Sqlalchemy to reduce redundancies there :)

**Comment by nrbnlulu** [comment]
> > I like this! We would need some sort of a registry to ensure we don't duplicate enums across types, but other than that it's a very straight-forward devX improvement.
> 
> Good point! We might also think of this in the context of Strawberry Django (and other integrations)
> 
> Would we make a registry per schema, right? 😊

How can that be per schema? all of strawberry decorators are evaluated before the schema does, and AFAIK even deferred types doesn't have access to the schema. or I'm wrong?

**Comment by ryanpetrello** [comment]
@nrbnlulu @erikwrede is there some documented way to specify docstrings/descriptions on these enum types that are generated from native Python enums?  Based on the commentary above, it sounds like the answer is no, but figured I'd ask if a solution for this was ever developed and documented.

Thanks!

**Comment by ryanpetrello** [comment]
(it also sounds like https://github.com/strawberry-graphql/strawberry/issues/653 is closely related to this)

**Comment by patrick91** [comment]
@ryanpetrello do you mean something like this?

```python
import strawberry

from enum import Enum


@strawberry.enum(description="Some description")
class IceCreamFlavour(Enum):
    VANILLA = strawberry.enum_value("vanilla" , description="Vanilla")
    STRAWBERRY = "strawberry"
    CHOCOLATE = "chocolate"

@strawberry.type
class Query:
    @strawberry.field
    def hello(self, info: strawberry.Info) -> IceCreamFlavour:
        return "vanilla"

schema = strawberry.Schema(Query)
```

**Comment by ryanpetrello** [comment]
Well, in this situation, I'm using the feature outlined in this issue i.e., I'm just writing types that reference the native enum:

```python
class IceCreamFlavour(Enum):
    VANILLA = strawberry.enum_value("vanilla" , description="Vanilla")
    STRAWBERRY = "strawberry"
    CHOCOLATE = "chocolate"

@strawberry.type
class MyType:
    flavor: IceCreamFlavour
```

...and I'm trying to add a `description=...` to the `strawberry.enum()` call that is implicitly happening under the hood.

**Comment by patrick91** [comment]
@ryanpetrello yeah, we should just do that 🤔

this won't work for you, right?

```python
import strawberry

from enum import Enum



class IceCreamFlavour(Enum):
    VANILLA = strawberry.enum_value("vanilla" , description="Vanilla")
    STRAWBERRY = "strawberry"
    CHOCOLATE = "chocolate"

F = strawberry.enum(description="Some description")(IceCreamFlavour)

@strawberry.type
class Query:
    @strawberry.field
    def hello(self, info: strawberry.Info) -> F:
        return "vanilla"

schema = strawberry.Schema(Query)
```

**Comment by ryanpetrello** [comment]
Right, I'm actually wanting to just use this feature (native Python enums) instead of having to make an extra enum class for every `strawberry.enum` in my codebase.

**Comment by patrick91** [comment]
got it 😊

**Comment by ryanpetrello** [comment]
Also, I should say, this isn't a huge deal for me, and Strawberry is awesome 😄.  I just wanted to gut check that wasn't missing some obvious way to accomplish this 👍 

Thanks!
