### ISSUE TITLE
Slow performance for queries that return many items

### ISSUE THREAD

**Issue by dancoates** [strawberry-graphql/strawberry#3544]
Hello, I'm trying to improve the performance of a graphql query that looks like:

```graphql
query GetSampleEidMapQuery($project: String!) {
  project(name: $project) {
    samples {
      assays {
        id
        externalIds
        meta
      }
    }
  }
}
```

This returns a result that has around 3000 samples, and each sample has between 1 and 4 assays. So less than 10,000 objects in total. The query takes between 3 and 5 seconds and returns around 600kB of json. So it's not a small amount of data but also not exactly huge. I initially thought this might be slow SQL queries but it turns out around 85% of the query time is in strawberry processing the results. Here's the pyinstrument profiling that shows this [pyinstrument.html.zip](https://github.com/user-attachments/files/15923872/pyinstrument.html.zip)

Is there anything that can be done to reduce the time that it takes for strawberry to handle results? I've tried both the `ParserCache` and `ValidationCache` as well as disabling validation entirely but unfortunately that made very little difference. 

Not sure if it helps but this is our graphql schema: https://github.com/populationgenomics/metamist/blob/dev/api/graphql/schema.py

Thank you!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3544">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3544/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3544/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
Hey dan, thanks for the report. This is a known problem in the GraphQL reference implementation and we're actively investigating ways to fix this. If you have any specific ideas, we'd highly appreciate any input.
Here are some related issues:
- https://github.com/graphql-python/graphql-core/issues/190

**Comment by dancoates** [comment]
Hi Erik, thanks for the quick response. It does sound like a tricky one to solve! Feel free to close this if you'd like as it sounds like the issue isn't within strawberry and it is a well known issue in graphql-core.

**Comment by dancoates** [comment]
Actually, sorry, I've just had another look at the profiling I included in the issue, and it does seem like the majority of the time is spent within strawberry, particularly it seems like lots of time is spent in inferring the schema from the types? But I could well be reading the profiling wrong, I'm pretty new to python profiling.

**Comment by dancoates** [comment]
I've narrowed this down further to our usage of a input that has a generic type on the assays field on a sample. Changing this line https://github.com/populationgenomics/metamist/blob/dev/api/graphql/schema.py#L754 to use a non generic type cuts the execution time from 5 seconds down to 1

**Comment by dancoates** [comment]
Sorry to spam messages, I've made a minimal repro repo to help show the issue:
https://github.com/dancoates/strawberry-generic-input-repro

**Comment by patrick91** [comment]
@dancoates could you test this pre-release if you have time? 

`poetry add strawberry-graphql==0.235.1.dev.1719337273`

**Comment by dancoates** [comment]
Hi @patrick91 I can confirm that the pre-release is a big performance improvement. Thank you very much for the quick fix!
