### ISSUE TITLE
strawberry.ext.mypy_plugin Pydantic 2.8 PydanticModelField.to_argument error 'force_typevars_invariant'

### ISSUE THREAD

**Issue by lindycoder** [strawberry-graphql/strawberry#3560]
Hello!

It seems the Pydantic 2.8 version introduced a breaking change on `PydanticModelField.to_argument` adding a new argument:
https://github.com/pydantic/pydantic/commit/8333bd59dd3424811f4e73cdd6e9414fd15bb6d7 

## Describe the Bug

Here's the mypy stack trace

```
./file.py:...: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.10.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6714, in accept
  File "mypy/nodes.py", line 1142, in accept
  File "mypy/semanal.py", line 1621, in visit_class_def
  File "mypy/semanal.py", line 1706, in analyze_class
  File "mypy/semanal.py", line 1740, in analyze_class_body_common
  File "mypy/semanal.py", line 1811, in apply_class_plugin_hooks
  File "/.../.venv/lib/python3.12/site-packages/strawberry/ext/mypy_plugin.py", line 482, in strawberry_pydantic_class_callback
    f.to_argument(
TypeError: PydanticModelField.to_argument() missing 1 required positional argument: 'force_typevars_invariant'
./file.py:...: : note: use --pdb to drop into pdb
```

## System Information

 - Operating system: OSX
- strawberry-graphql 0.235.2 
- pydantic 2.8.2
- pydantic-core 2.20.1
- mypy 1.10.1
- mypy-extensions 1.0.0

## Additional Context

Here's closely what the source code look like
```
@strawberry.interface(name="ResourceBase")
class ResourceBaseSchema:
    resource_id: str
    resource_type: ResourceTypeSchema

@strawberry.experimental.pydantic.type(MyModel, name="MyModel")
class MyModelSchema(ResourceBaseSchema):
    provider: strawberry.auto
    url: strawberry.auto
    name: strawberry.auto
    tags: list[str]
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3560">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3560/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3560/pledge.svg">
</picture>
</a>

**Comment by micahstairs** [comment]
This bug is also affecting me! @lindycoder do you have an ETA on https://github.com/strawberry-graphql/strawberry/pull/3562?
