### ISSUE TITLE
GraphQL Core 3.3 tests appear to be running 3.2 instead

### ISSUE THREAD

**Issue by parafoxia** [strawberry-graphql/strawberry#3598]
## Describe the Bug

Within the `nox -r -t tests -s "Tests-3.12(gql_core='3.3.0')"` tests (it happens on all Python versions):
```
Package operations: 0 installs, 1 update, 0 removals

  - Downgrading graphql-core (3.3.0a5 https://github.com/graphql-python/graphql-core/archive/876aef67b6f1e1f21b3b5db94c7ff03726cb6bdf.zip -> 3.2.3)
```

This also appears in the logs for the Core 3.2 tests as well. The Pydantic tests have different logs, but they're also installing 3.2 rather than 3.3.

https://github.com/strawberry-graphql/strawberry/actions/runs/10384390719/job/28751301930?pr=3592

## System Information

N/A -- This is a CI bug.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3598">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3598/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3598/pledge.svg">
</picture>
</a>

**Comment by nrbnlulu** [comment]
Thanks for the alert :upside_down_face: 
It is already fixed in #3554
