### ISSUE TITLE
Convert field names to camel case

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#36]
Currently, when creating a field with underscores it will be kept with underscores. We should convert them to camel case by default, and allow users to change that if they want :)

```
import strawberry

@strawberry.type
class Query:
    i_have_underscores: int = 2

print(repr(Query()))
```

Returns:

```
type Query {
  i_have_underscores: Int!
}
```

**Comment by patrick91** [comment]
Closing this for now, we can make this optional later, if needed :)

**Comment by basvandriel** [comment]
Even though it's closed; [find the merged PR here](https://github.com/strawberry-graphql/strawberry/pull/798)
