### ISSUE TITLE
Support of Geometry Scalars

### ISSUE THREAD

**Issue by tokr-bit** [strawberry-graphql/strawberry#3608]
The Strawberry Django integration provides geometry scalars such as `Polygon`, `Point`, etc (https://github.com/strawberry-graphql/strawberry-django/blob/main/strawberry_django/fields/types.py#L339). Are there any plans to implement these in strawberry?

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Since Postgres is a widely used database driver that is popular for its GIS extension, geometry types are present in many applications. Therefore, the feature of using GraphQL types in `strawberry` might be helpful.

However, this is in contrast to the GraphQL spec.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3608">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3608/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3608/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@tokr-bit did you mean to close this?

**Comment by tokr-bit** [comment]
@patrick91 Yes I wanted to close this issue.
