### ISSUE TITLE
Untyped decorator makes function "hello" untyped

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#3611]
```python
import strawberry

from strawberry.permission import BasePermission, PermissionExtension
from typing import Any


class IsAuthenticated(BasePermission):
    def has_permission(self, *arg: Any, **kwargs: Any) -> bool:
        return True


@strawberry.type
class ABC:
    @strawberry.mutation(name="hello")
    def hello(self) -> str:
        return "world"
```

```
➜ uv run mypy --strict app.py
app.py:14: error: Untyped decorator makes function "hello" untyped  [misc]
Found 1 error in 1 file (checked 1 source file)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3611">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3611/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3611/pledge.svg">
</picture>
</a>

**Comment by magicmark** [comment]
dupe https://github.com/strawberry-graphql/strawberry/issues/1929 ?

**Comment by erikwrede** [comment]
@magicmark yup, thanks!
