### ISSUE TITLE
MaskErrors does not work since version 0.240.0

### ISSUE THREAD

**Issue by ericdevries** [strawberry-graphql/strawberry#3625]
Since version 0.240.0, the MaskErrors extension fails to mask errors. 

## Describe the Bug

See example script here:

```python
import typing
import strawberry

from strawberry.extensions import MaskErrors


@strawberry.type
class Book:
    title: str
    author: str


def get_books():
    raise Exception("Something went wrong")


@strawberry.type
class Query:
    books: typing.List[Book] = strawberry.field(resolver=get_books)


schema = strawberry.Schema(query=Query, extensions=[MaskErrors(error_message="Internal server error")])
```

In the previous version it would show `Internal server error` as the message. Since 0.240.0 it shows this:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Something went wrong",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "books"
      ]
    }
  ]
}
```

## System Information

 - Operating system: macos
 - Strawberry version (if applicable): 0.240.0 and up

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3625">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3625/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3625/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
I'll check this today! thanks for the report 😊

**Comment by ericdevries** [comment]
Thanks!
