### ISSUE TITLE
Add a public function to get graphql-core type for a strawberry class

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#363]
From this discussion https://graphenetools.slack.com/archives/CBFAJ502C/p1593595408041700?thread_ts=1593589607.026600&cid=CBFAJ502C

In summary, it would be nice to have a function to get the graphql-core field generated by strawberry, so we could use it with Graphene:

```python
@strawberry.type
class MyStrawberryType:
    tasty: bool


class MyGrapheneType(ObjectType):
    strawberry = Field(strawberry.core.get_graphql_type(MyStrawberryType))
```

**Comment by jkimbo** [comment]
@patrick91 I created a function to do this in my project:

```python
from strawberry.schema.types.type import get_type_for_annotation
from strawberry.schema.types.union import get_union_type


type_map = {}


def get_graphql_type(_type):
    if hasattr(_type, "_union_definition"):
        return get_union_type(_type, type_map)

    return get_type_for_annotation(_type, type_map)
```

Then I can do:

```python
from graphene import ObjectType, Field

class Query(ObjectType):
    strawberry_type = Field(get_graphql_type(MyStrawberryType))
```

Have I missed any cases here?

**Comment by patrick91** [comment]
@jkimbo that should be enough! I guess maybe we should move the union check inside `get_type_for_annotation`.

I wonder if need to support also using Graphene types, like this:


```python
class Info(ObjectType):
    data = graphene.String()

@strawberry.type
class MyStrawberryType:
    tasty: bool
    legacy_info: Info


class MyGrapheneType(ObjectType):
    strawberry = Field(strawberry.core.get_graphql_type(MyStrawberryType))
```

I think it might be doable without a lot of effort :)

**Comment by jkimbo** [comment]
I'm not sure that would be possible @patrick91 because converting a Graphene type to a graphql-core type requires a Graphene schema. There is an issue for it: https://github.com/graphql-python/graphene/issues/1238

**Comment by patrick91** [comment]
oh, that's interesting, maybe it's not worth looking into it, until someone needs it :)

**Comment by patrick91** [comment]
closing this, if someone needs a way to convert graphene into strawberry they can check @jkimbo's project -> https://github.com/jkimbo/strawberry-graphene
