### ISSUE TITLE
Schema directives not included in introspection

### ISSUE THREAD

**Issue by jacobmoshipco** [strawberry-graphql/strawberry#3649]
## Describe the Bug

When using introspection, Strawberry is not returning any custom schema directives. Looking into it, I found a partial cause and a workaround.

I created a [repository](https://github.com/jacobmoshipco/strawberry-directive-bug) to show the issue. If you run `main.py`, it will run eight tests:

- `test field directive schema export` Should pass showing that export-schema correctly outputs directives
- `test one of schema export` Should pass showing the same for the `one_of` property
- `test field directive introspection` Should fail showing that custom directives are not listed in an introspection query
- `test one of introspection` Should fail showing the same for the `one_of` property

The last four tests should all pass, they show a work-around of passing the directives to `Schema(..., types=[...])`. **Note** that this doesn't work if passed to `schema_directives=[...]` instead.

There is also no automatic collection of directives when generating introspection. Leaving the types off `Schema` entirely works when running schema export, but not when running introspection.

### What I personally consider to be "the bug"

1. Types passed to `Schema` via `schema_directives` aren't being added to the `graphql_directives` list, but they probably should be
2. Automatic collection of schema directives works in export-schema but not in introspection.

## System Information

 - Operating system: MacOS Ventura 13.2.1
 - Strawberry version (if applicable): 0.243.1 (but the issue exists much further back)

## Additional Context

I believe it makes the most sense to pass the schema directives to `Schema` via `schema_directives`. Currently, `Schema` is looking for them in `types` and using `compat.is_schema_directive` to check if they're schema directives. By modifying `Schema` to simply iterate over `schema_directives` and running the same code, I was able to get that portion working exactly as I expected. This probably solves part one of the bug, but I haven't had time to run the unit tests against this yet.

No idea why part two is happening.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3649">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3649/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3649/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
> Types passed to Schema via schema_directives aren't being added to the graphql_directives list, but they probably should be

Schema directives won't show in the introspection because that's not supported by the spec 😊 see: https://github.com/graphql/graphql-spec/issues/300

What are you trying to do, why do you need schema directives in introspection? Maybe you need operation directives?

**Comment by jacobmoshipco** [comment]
I didn't notice that it wasn't part of the spec. It appears I confused schema directives and operation directives when experimenting with work-arounds.

I was trying to use the schema directives for metadata for codegen (particularly `oneOf`). I had misremembered using the introspection feature to do just that on an earlier project, but looking at it, it appears I was using export-schema and using that for the codegen. Is that the best approach?

**Comment by jacobmoshipco** [comment]
Okay, using export-schema to export an SDL to be served by my API works perfectly. I'll be closing this issue; feel free to reopen if anyone needs more from it. Thanks for your help!

**Comment by kevinmsun** [comment]
> > Types passed to Schema via schema_directives aren't being added to the graphql_directives list, but they probably should be
> 
> Schema directives won't show in the introspection because that's not supported by the spec 😊 see: [graphql/graphql-spec#300](https://github.com/graphql/graphql-spec/issues/300)
> 
> What are you trying to do, why do you need schema directives in introspection? Maybe you need operation directives?

I'm encountering an issue that I *think* might be the same as described in this one, but i'm not 100% sure. I have a `@strawberry.input(one_of=True)` class
```
@strawberry.input(one_of=True)
class InputWithOneOf:
    string: strawberry.Maybe[str]
    boolean: strawberry.Maybe[bool]
```
when I generate the `.graphql` file via `export_schema`, the result has the `@oneOf` embedded in it
```
input InputWithOneOf @oneOf {
  string: String
  boolean: Boolean
}
```
If i `codegen` against this file, I get this `graphql.ts`
```
export type InputWithOneOf =
  { boolean: Scalars['Boolean']['input']; string?: never; }
  |  { boolean?: never; string: Scalars['String']['input']; };
```

however, when I attempt to generate the equivalent from introspection, using https://github.com/prisma-labs/get-graphql-schema, it omits `@oneOf`
```
input InputWithOneOf {
  string: String
  boolean: Boolean
}
```
... leading to this less-specific `graphql.ts`
```
export type InputWithOneOf = {
  boolean?: InputMaybe<Scalars['Boolean']['input']>;
  string?: InputMaybe<Scalars['String']['input']>;
};
```

I am attempting to do something similar as what @jacobmoshipco was presumably doing - to do graphql-codegen for my schema; my preferred workflow in my development environment is to codegen against my local `/graphql` endpoint rather than via a file-based method. However, I also have a CI step that instead uses a file-based approach (via `export_schema`) to verify the data is in sync.

... so in terms of "what i'm trying to do", it is to attempt to get consistent output for codegen purposes between introspection via API and the `.graphql` document exported schema. Am I reading this correctly that this is the same reported issue and is not supported (and thus instead, I should probably use a workflow that does similar operations as CI)?

**Comment by patrick91** [comment]
@kevinmsun can you open a new issue? 

I don't think we added support for oneOf in the introspection of GraphQL 😊 GraphQL core alpha does have oneOf and I'm assuming it also has support for it in the introspection, but not sure if conflicts with our implementation

**Comment by kevinmsun** [comment]
> [@kevinmsun](https://github.com/kevinmsun) can you open a new issue?
> 
> I don't think we added support for oneOf in the introspection of GraphQL 😊 GraphQL core alpha does have oneOf and I'm assuming it also has support for it in the introspection, but not sure if conflicts with our implementation

will do - thanks!

edit: created at https://github.com/strawberry-graphql/strawberry/issues/3975
