### ISSUE TITLE
schema-configurations info_class example code is missing StrawberryConfig

### ISSUE THREAD

**Issue by topher-g** [strawberry-graphql/strawberry#3650]
The code example at the end of the schema-configurations.md file is incorrect and will not run.

```
class CustomInfo(Info):
    @property
    def response_headers(self) -> Headers:
        return self.context["response"].headers


schema = strawberry.Schema(query=Query, info_class=CustomInfo)
```

should be:

```
class CustomInfo(Info):
    @property
    def response_headers(self) -> Headers:
        return self.context["response"].headers


schema = strawberry.Schema(query=Query, config=StrawberryConfig(info_class=CustomInfo))
```

The current documentation says to pass info_class directly into strawberry.Schema.__init__() intead of wrapping.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3650">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3650/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3650/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
Great Catch, thanks! Would you like to submit a PR for this? Feel free to ping me 😊

**Comment by patrick91** [comment]
Thanks for the report and PR!
