### ISSUE TITLE
multipart upload struggle

### ISSUE THREAD

**Issue by itsklimov** [strawberry-graphql/strawberry#3655]
I am trying to make the file upload work and no luck yet
I got back to the example on https://strawberry.rocks/docs/guides/file-upload#sending-file-upload-requests
but just copy past multi file requests from postman returns "Unsupported content type"

## System Information

 - Operating system: macOS sequoia 
 - Strawberry version (if applicable):
 - latest

## Additional Context

python code

    @strawberry.mutation
    def read_files(self, files: List[Upload]) -> List[str]:
        print(f"Received read_files mutation. Number of files: {len(files)}")
        contents = []
        for file in files:
            content = file.read().decode("utf-8")
            contents.append(content)
        return contents

curl --location 'localhost:7675/graphql' \
--form 'operations="{ \"query\": \"mutation(\$files: [Upload\!]\!) { readFiles(files: \$files) }\", \"variables\": { \"files\": [null, null] } }"' \
--form 'map="{\"file1\": [\"variables.files.0\"], \"file2\": [\"variables.files.1\"]}"' \
--form 'file1=@"/Users/its/Documents/roll.csv"' \
--form 'file2=@"/Users/its/Documents/dump.csv"'

Request Body
  operations: "{ "query": "mutation($files: [Upload!]!) { readFiles(files: $files) }", "variables": { "files": [null, null] } }"
  map: "{"file1": ["variables.files.0"], "file2": ["variables.files.1"]}"
  file1: undefined
  file2: undefined
Response Headers
  date: Tue, 01 Oct 2024 15:10:58 GMT
  server: uvicorn
  content-length: 24
  content-type: text/plain; charset=utf-8
Response Body
  Unsupported content type

response
Unsupported content type

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3655">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3655/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3655/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@itsklimov sorry about that! we recently release a change that disabled multipart uploads by default you can see it here: https://strawberry.rocks/docs/breaking-changes/0.243.0

you need to update your view config, here's how can do it with django: https://strawberry.rocks/docs/integrations/django#options (the param should be the same for all the integrations)

I'll keep this open so we can update that doc page :)

**Comment by itsklimov** [comment]
as I do not use Django, not much experince with graphql

> @itsklimov sorry about that! we recently release a change that disabled multipart uploads by default you can see it here: https://strawberry.rocks/docs/breaking-changes/0.243.0
> 
> you need to update your view config, here's how can do it with django: https://strawberry.rocks/docs/integrations/django#options (the param should be the same for all the integrations)
> 
> I'll keep this open so we can update that doc page :)

`from fastapi import FastAPI, UploadFile, File
from strawberry.fastapi import GraphQLRouter

from src.config import settings
from src.schemas.graphql import schema
from src.utils.logger import logger


async def lifespan(app: FastAPI):
    logger.info("GraphQL File Server is starting...")
    yield
    logger.info("GraphQL File Server is shutting down...")


app = FastAPI(title="GraphQL File Server", lifespan=lifespan)

graphql_app = GraphQLRouter(schema)
app.include_router(graphql_app, prefix="/graphql")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app:app",
        host=settings.host,
        port=settings.port,
        reload=True,
    )
`

Can you advice on how to adjust app to enable it?

**Comment by itsklimov** [comment]
thanks, do you want me to resolve the ticket or leave it opened

**Comment by patrick91** [comment]
let's leave it open, I think we should update the guide
