### ISSUE TITLE
handle_ping when client is disconnected raises an uncatched WebSocketDisconnect (sometimes)

### ISSUE THREAD

**Issue by Speedy1991** [strawberry-graphql/strawberry#3678]
Steps to repdroduce:

- Add a async.sleep(10s) to [handle_ping](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/subscriptions/protocols/graphql_transport_ws/handlers.py#L206)
- Open websocket
- wait for a ping (async.sleep(10s) is now running/blocking)
- disconnect client
- server tries to send a pong but websocket is disconnected and throws a WebSocketDisconnect (but not always???)

This looks like a racecondition, and I can't make a failing reliable example -.-'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3678">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3678/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3678/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Maybe we need to check if the websocket is still opened? Not sure if we can do that at the handler level

What exception gets raised? Maybe we could suppress the error if it is a very specific one?

**Comment by Speedy1991** [comment]
Sure, see this screenshot from sentry:
![Image](https://github.com/user-attachments/assets/32928792-e343-42a6-b896-11e59f6c97d3)

-------------
> Maybe we could suppress the error if it is a very specific one?

Maybe it is "fixed" if [this line](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/subscriptions/protocols/graphql_transport_ws/handlers.py#L322) is wrapped with a try/except(WebSocketDisconnect) + warning? I don't think this is standalone `pong` error but a possible error on each `json_send`?

**Comment by bellini666** [comment]
> Maybe it is "fixed" if [this line](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/subscriptions/protocols/graphql_transport_ws/handlers.py#L322) is wrapped with a try/except(WebSocketDisconnect) + warning? I don't think this is standalone pong error but a possible error on each json_send?

Hrm, that exception is specific to starlette, so we would either need to do that in the starlette implementation, or find a way to make it in a general way.

@DoctorJohn what do you think about this?
