### ISSUE TITLE
GraohiQL is not disabled by None type

### ISSUE THREAD

**Issue by ldynia** [strawberry-graphql/strawberry#3681]
## Describe the Bug

Seeting `graphiq=None` doesn't disable GraphiQL view.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3681">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3681/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3681/pledge.svg">
</picture>
</a>

**Comment by erikwrede** [comment]
Hey @ldynia, can you please provide a minimal reproduction for this behavior, including the strawberry version you're using? 😊

**Comment by ldynia** [comment]
Example using Django framework

```
# urls.py
urlpatterns = [
    ...
    path("graphiql", AsyncGraphQLView.as_view(schema=schema, graphiql=None, allow_queries_via_get=False)),
    ...
]
```

![Image](https://github.com/user-attachments/assets/cb77dc75-8e9b-45ed-95dd-8e9024152bff)


```shell
$  pip show strawberry-graphql-django
Name: strawberry-graphql-django
Version: 0.49.1
Summary: Strawberry GraphQL Django extension
Home-page: https://github.com/strawberry-graphql/strawberry-django
Author: Lauri Hintsala
Author-email: lauri.hintsala@verkkopaja.fi
License: MIT
Location: /home/nonroot/.local/lib/python3.11/site-packages
Requires: asgiref, django, strawberry-graphql
Required-by: strawberry-django-auth

$ pip show strawberry-graphql
Name: strawberry-graphql
Version: 0.247.0
Summary: A library for creating GraphQL APIs
Home-page: https://strawberry.rocks/
Author: Patrick Arminio
Author-email: patrick.arminio@gmail.com
License: MIT
Location: /home/nonroot/.local/lib/python3.11/site-packages
Requires: graphql-core, python-dateutil, typing-extensions
Required-by: strawberry-graphql-django
```

**Comment by asmabash** [comment]
From strawberry graphql v0.213.0, the argument `graphiql` has been deprecated, which used the values`True` and `False` to enable and disable the GraphiQL view, respectively. The argument `graphql_ide` is now used to choose an IDE, or disable it [[documentation]](https://strawberry.rocks/docs/breaking-changes/0.213.0). If you want to disable it you can use `graphql_ide = None`.

**Comment by patrick91** [comment]
@asmabash is correct (thanks!), I'll close the issue for now 😊
