### ISSUE TITLE
Support for field permissions & visibility

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#37]
Would be nice to have a simple way to require permission for specific fields and also hide them from the schema (visibility).

Permission example (borrowed from DRF)

```py
import strawberry

from strawberry.permission import BasePermission


class IsAuthenticated(BasePermission):
    def has_permission(self, info) -> bool:
        return False


@strawberry.type
class User:
    name: str
    age: int


@strawberry.type
class Query:
    @strawberry.field(permission_classes=[IsAuthenticated])
    def me(self, info) -> Optional[User]:
        return User(name="Patrick", age=100)
```

Visibility example, what this should do is to completely hide the field from the schema if the client is not able to see it (so not even shown when doing introspection).

```py
import strawberry

from strawberry.permission import BasePermission


class IsAdminClient(BasePermission):
    def has_permission(self, info) -> bool:
        return False


@strawberry.type
class User:
    name: str
    age: int


@strawberry.type
class Query:
    @strawberry.field(visiblity_classes=[IsAdminClient])
    def me(self, info) -> Optional[User]:
        return User(name="Patrick", age=100)
```

**Comment by johnchuks** [comment]
Hi @patrick91! great package you have here. I have been working with graphene-python more than a year now. I really like how you are utilising python dataclasses. I am interested in contributing to your project. Do you mind if I take a crack at this issue?

**Comment by patrick91** [comment]
@johnchuks not at all :) let me know how it goes! :D

Are you on Graphene's slack? I'm usually there if you want to chat :)

**Comment by johnchuks** [comment]
Awesome! - Thank you. I am not on there actually - I will join it now

**Comment by gonzalezzfelipe** [comment]
Hey there, any updates regarding the visibility part? I'm trying to achieve exactly what is described here, and failing

**Comment by patrick91** [comment]
@gonzalezzfelipe not for visibility, what's your use case?

**Comment by gonzalezzfelipe** [comment]
> @gonzalezzfelipe not for visibility, what's your use case?

We are building a API for both internal and external use, and we would like to keep some parts of it not only unauthorised, but also hidden. The way we are working around it is to disable introspection altogether, and generating dynamic documentation with directives to hide these fields.

**Comment by XChikuX** [comment]
Is there an example or another isue tracking the things mentioned in the last comment? @gonzalezzfelipe

**Comment by XChikuX** [comment]
Yes please

**Comment by willstott101** [comment]
Relates to: #3343
