### ISSUE TITLE
Support for nullable Connection

### ISSUE THREAD

**Issue by marmor157** [strawberry-graphql/strawberry#3703]
The field using `strawberry.connection` should be able to be nullable.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

This is needed in case if connection field would return an error e.g. from `PermissionExtension` and we don't want to error out the whole query.
Right now when the field has a declared type of `strawberry.relay.ListConnection[...] | None` the following error is thrown
```
strawberry.relay.exceptions.RelayWrongAnnotationError: Wrong annotation used on field "...". It should be annotated with a "Connection" subclass.
```

**Comment by patrick91** [comment]
@sourcery-ai plan

**Comment by patrick91** [comment]
@sourcery-ai develop
