### ISSUE TITLE
Add support for field deprecation

### ISSUE THREAD

**Issue by EmiM** [strawberry-graphql/strawberry#375]
I was looking in the code and I couldn't find a way to mark field as deprecated. I also didn't find any issues regarding this.
I know that it is handled by `deprecation_reason` in graphql's `GraphQLField` but how I mark a field as deprecated in strawberry-graphql?

**Comment by patrick91** [comment]
We don't support that at the moment, but should be easy to add :)

```python
@strawberry.type
class Query:
    user: User = strawberry.field(deprecation_reason='This is a test')
```

something like this. 

I'm finishing up a rewrite of strawberry, I'll see if I can add this in before finishing that, or after, anyway I don't see this taking too much time to be supported :)

**Comment by EmiM** [comment]
That would be great!! Thank you very much :D
