### ISSUE TITLE
 where is GraphQL Playground 

### ISSUE THREAD

**Issue by LiGuoV** [strawberry-graphql/strawberry#376]
in docs>Getting started with Strawberry>step6 say:
'Strawberry comes with a tool called GraphQL Playground.'
but But i got GraphiQL.... 
(maby i need to wait...)

**Comment by patrick91** [comment]
@LiGuoV oh, we removed GraphQL Playground because it didn't support subscriptions well and didn't have the explorer. I'll update the docs as soon as I can :)
