### ISSUE TITLE
Cannot create type with multiple Unions

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#377]
```python
from typing import Union

import strawberry


@strawberry.type
class CoolType:
    @strawberry.type
    class UnionA1:
        value: int

    @strawberry.type
    class UnionA2:
        value: int

    @strawberry.type
    class UnionB1:
        value: int

    @strawberry.type
    class UnionB2:
        value: int

    field1: Union[UnionA1, UnionA2]
    field2: Union[UnionB1, UnionB2]


schema = strawberry.Schema(query=CoolType)
```

```.pytb
Traceback (most recent call last):
  File "/home/ignormies/.config/JetBrains/PyCharm2020.1/scratches/scratch.py", line 28, in <module>
    schema = strawberry.Schema(query=CoolType)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/schema.py", line 25, in __init__
    super().__init__(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 239, in __init__
    raise TypeError(
TypeError: Schema must contain uniquely named types but contains multiple types named '_resolver'.
```

Removing either `field1` or `field2` allows the schema to be created

**Comment by patrick91** [comment]
Oh nice, thanks for the report. This is fixed in the rewrite I'm doing -> #352.

If it is a deal breaker I can do another PR to fix it, so you don't have have to wait for the rewrite :)

PS.Is there a reason why the types are defined inside the CoolType class? :)

**Comment by BryceBeagle** [comment]
> I can do another PR to fix it, so you don't have have to wait for the rewrite

That would be quite appreciated. I was trying to figure out how I was going to find a workaround for this issue.

> Is there a reason why the types are defined inside the CoolType class?

I just have a practice where I try to keep my namespaces minimal. In hindsight, it wasn't necessary for this example, but the code I was making the example from had it going on, where the analogous nested types are only used with the parent type. I prefer doing `[module.]CoolType.UnionA1` instead of just `[module.]UnionA1`, if `UnionA1` will only _ever_ be used for `CoolType`.

Hopefully that's not too confusing... 🙃

**Comment by patrick91** [comment]
> I just have a practice where I try to keep my namespaces minimal.

oh I see, I'd use python modules for that, but that's my preference :) But I understand the thinking about the type being only used with the parent type.

I'll try to see if I can make a quick PR now to fix the issue with current master :)
