### ISSUE TITLE
Schema merging support for remote schemas

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#38]
This might make Strawberry a good API gateway tool, the idea is to allow merging of multiple GraphQL schemas into one, and delegating the execution of queries to those APIs when requested.

The API might look like this:

```py
import strawberry

schema_a = strawberry.remote_schema(
    "https://apollo-server.sse.codesandbox.io/grapqhl"
)

schema_b = strawberry.remote_schema(
    "https://apollo-server.sse.codesandbox.io/grapqhl"
)


schema = strawberry.merge_schemas([
    schema_a,
    schema_b
])
```

We might want to think of transforming the schemas when needed, for example when names are conflicting or when we want to add fields (extending types)

**Comment by jaydenwindle** [comment]
Apollo just released [Apollo Federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/), which looks like their attempt at solving this problem. I'll need to dive into the source code a little more to find out how it's implemented, but we might be able to port their solution to python and include it. 

Their implementation also looks like it supports merging local and remote schemas, which would be very useful.

**Comment by patrick91** [comment]
@jaydenwindle yes, I had a quick look at that, not sure we should port it to python, at least for now[1] :)

What we could implement is the federation spec so strawberry APIs can be used with Apollo federation: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

[1] I'm guessing if people do schema stitching they might be fine with a gateway in node, not sure though, I don't really have a strong opinion :D

**Comment by patrick91** [comment]
@jaydenwindle I'm going to close this for now, we should talk about getting federation support in, seems something quite useful!
