### ISSUE TITLE
Type and field descriptions no longer defaulting to docstrings.

### ISSUE THREAD

**Issue by coady** [strawberry-graphql/strawberry#391]
Prior to 0.28, docstrings were used as descriptions when not explicitly supplied.

**Comment by patrick91** [comment]
Uhm, that was an intentional change. We had leaked internal information because not everyone realised docstrings where going to be used as GraphQL description. So I'm not sure we should support this again. What do you think?

**Comment by coady** [comment]
Oh, well I thought it was nicely readable, just like using `__name__`.  What if it's opt-in: `use_docstring=False`?

**Comment by patrick91** [comment]
@coady I'd prefer a global setting (disabled by default), what do you think?
