### ISSUE TITLE
Add support for unions

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#4]
- [x] Anonymous unions
- [x] Named unions

**Comment by jaydenwindle** [comment]
@patrick91 I'd love to take a crack at this - can you provide a little more info?

**Comment by patrick91** [comment]
Sure! Currently, we only support "anonymous" unions[1], I mean unions declared inline:

```python
@strawberry.type
class Example:
    a: typing.Union[A, B]
```

this would create a new union type with name "A", not sure I like this as we can easily end up with conflicting union types (maybe we can namespace them with the type name, so "ExampleA").

Anyway, I was thinking that maybe we should support named unions, like this:

```python
AOrB = typing.Union[A, B]

@strawberry.type
class Example:
    a: AOrB
```

or maybe like this, not sure:

```python
AOrB: typing.Union[A, B] = strawberry.union(name="AOrB", description="ABC")

@strawberry.type
class Example:
    a: AOrB
```

[1] code here: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/type_converter.py#L68-L74

**Comment by marcoacierno** [comment]
What about using `NewType` to define named unions?

Something like:

```
NewType('AOrB', Union[A, B])
```

**Comment by patrick91** [comment]
This is done, we will need a better support for MyPy, but it seems that’s not doable at the moment, so I’ll close this for now :)
