### ISSUE TITLE
N + 1 problem - Support for dataloaders?

### ISSUE THREAD

**Issue by hyzyla** [strawberry-graphql/strawberry#413]
Hi 👋

How to solve N+1 problem when using strawberry?

**Comment by patrick91** [comment]
Hello! Good question, you might be able to use the same dataloader that works for Graphene, but not 100% sure as I have never used it.

We are doing some work around N+1 at work with Strawberry, so we might add some support for this.

I need to get familiar with dataloaders, but I guess that would be one solution :)

@hyzyla can you provide more context on what you're doing? maybe there's other ways to solve your problem :)

**Comment by hyzyla** [comment]
Currently, I just seeking a library for a new project and this library seems promising. I have experience in solving the N+1 problem for Graphene by using [aiodatalodaer](https://github.com/syrusakbary/aiodataloader). But the solution was non-intuitive and solved just by adopting some tutorials from the web for non-async data loader.

As example I can give you most iconic version of query for blog.
```graphql
{
    blog(id: "1") {
        text,
        comments {
            text,
            date,
            author {   # resolving authors for N comments causes N requests
                  name,
                  avatarURL
            }
        }
    }
}
```

**Comment by patrick91** [comment]
Yeah, from what I've seen you either need async or to use a Promise library. I'll think about this a bit, for example we use Django and using async is not possible with the database right now, so we need some other solution for this. 🤔

**Comment by jkimbo** [comment]
Looks like you can get around the async DB issue in Django by using the `async_to_sync` wrapper:

```python
from asgiref.sync import sync_to_async

class FooLoader(aiodataloader.DataLoader):
    @sync_to_async
    def fetch_foo(self, keys):
        return Foo.objects.in_bulk(keys)

    async def batch_load_fn(self, keys):
        foos = await self.fetch_foo(keys)
        # some other processing
        return foos
```

https://github.com/graphql-python/graphene-django/issues/705#issuecomment-670511313

**Comment by patrick91** [comment]
@jkimbo that's a good point, but I guess when wouldn't be able to use that with old version of django, right? 

Plus it needs to work with the async view (which we aren't providing yet[1]), so might not be that easy.

I wonder if we can make this work without requiring async, I mean with django we can still do bulk fetching of data, no? I was naively thinking that we could have some sort of sync dataloader that first collects the keys/ids and then our GraphQL executor could do the final resolve of the data, some sort of mix of promises and awaitable if that makes sense, but specific for this use case. It might be a stupid idea though :D

In any case the aiodataloader might be a good interim solution.

[1] We have an ASGI one, so should be easy to add one for Django too.

**Comment by patrick91** [comment]
I'm going to mark this issue as required for v1. I think it is pretty important to have it, at least a basic support for dataloaders :)

**Comment by hyzyla** [comment]
Hi, I created an [example](https://gist.github.com/hyzyla/68d42951cf5788dd4fc7331d98c4a2be) of using aiodataloader with strawberries. May be helpfull for async integration of strawberry

**Comment by patrick91** [comment]
That's pretty cool! I'm going to check it in the next few days. I need to work on caching some of our data on redis and I think we'll probably use the dataloader pattern for that. so this snipped will be handy. I definitely want to add first class support for dataloaders in strawberry, but I need to work with them first (I'm still unfamiliar with them).

I also saw this blog post that might useful: https://medium.com/@menecio/using-djangos-orm-from-aiohttp-fb9538072ba0

**Comment by AndrewIngram** [comment]
A non-async dataloader is installed with Graphene, it's part of the author's [promise](https://github.com/syrusakbary/promise) library, I used it with some success. I don't _think_ it should require any special magic to use it with Strawberry instead. `aiodataloader` is from the same person and has basically the same API but without the underlying promise implementation.

**Comment by jkimbo** [comment]
@AndrewIngram graphql-core v3 dropped support for the promise library so it won't work with Strawberry. The aiodataloader does work but because Django doesn't have full async support getting it working with the orm is a problem. All the solutions I've come across require code changes in the application and not the just in Strawberry which is not great.

**Comment by AndrewIngram** [comment]
😢
