### ISSUE TITLE
Add flake8-eradicate

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#430]
This plugin might have been useful in the past as I forgot to uncomment some code, I guess it is worth adding it :)

https://github.com/sobolevn/flake8-eradicate

**Comment by flpStrri** [comment]
Can I give it a try? So I can familiarize with the the repo. 😃

**Comment by patrick91** [comment]
@flpStrri sure! feel free to ping me on discord if you need any help!

**Comment by flpStrri** [comment]
I simply installed it and it is returning `1` when calling `flake8`. Great. But I think it is marking as an error some comments that were not supposed to be marked, like this:
<img width="449" alt="Captura de Tela 2020-09-04 às 07 55 34" src="https://user-images.githubusercontent.com/13003392/92231937-05493900-ee84-11ea-92df-69a29339e40a.png">

**Comment by flpStrri** [comment]
But it works. 😄 
<img width="483" alt="Captura de Tela 2020-09-04 às 08 17 43" src="https://user-images.githubusercontent.com/13003392/92233731-2e1efd80-ee87-11ea-9509-1946362ceb26.png">

**Comment by patrick91** [comment]
@flpStrri nice, can you send a PR?

**Comment by BryceBeagle** [comment]
#443 should have closed this, right?

**Comment by patrick91** [comment]
Yes 😊 I'll close this now :)
