### ISSUE TITLE
aiohttp integration

### ISSUE THREAD

**Issue by hyzyla** [strawberry-graphql/strawberry#437]
It would be nice to see [aiohttp](https://docs.aiohttp.org/en/stable/) integration with your library.

**Comment by patrick91** [comment]
@hyzyla doesn't aiohttp support asgi? (never used it)

**Comment by hyzyla** [comment]
No, there is not resolved closed issue about ASGI support for aiohttp https://github.com/aio-libs/aiohttp/issues/2902

**Comment by patrick91** [comment]
Closing this as it was done in #895
