### ISSUE TITLE
Fields declared with strawberry.field function with resolver from same class are not created properly

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#448]
(Issue will be introduced with the merge of PR #429)

```python
@strawberry.type
 class Query:  # noqa: F841
     def adios(self) -> int:
         return -1
 
     goodbye: int = strawberry.field(resolver=adios)
```

This fails:
```python
definition = Query._type_definition
assert len(definition.fields) == 1
```

This also fails. Only `adios` is added as a field to the schema, which is not what we want:
```python
schema =  strawberry.Schema(query=Query)
query = "{ goodbye }"
result = schema.execute_sync(query)

assert not result.errors
```

**Comment by jordangarside** [comment]
This is related to not being able to use the same function for multiple resolvers correct?

```py
def get_empty_string(root, info) -> str:
    return ""

@strawberry.type
class Book:
    id: str = strawberry.field(resolver=get_empty_string)
    title: str = strawberry.field(resolver=get_empty_string)

async def get_books():
    ...

@strawberry.type
class Query:
    books: typing.List[Book] = strawberry.field(resolver=get_books)
```

Only `id` will be added to the schema.

**Comment by BryceBeagle** [comment]
Yes I believe this is related. It also provides a bit clearer of a picture for the source of the problem:

https://github.com/strawberry-graphql/strawberry/blob/ebcf62a8b91130d98ef98cf795b6d251effec2cb/strawberry/field.py#L39-L49

When a resolver is added to a field (either immediately using the `strawberry.field` argument, or deferred using `StrawberryField.__call__`), what's returned is the resolver _itself_, with a monkeypatched `_field_definition` attribute.

When the resolver exists on the class, or two different fields use the same resolver, the class will end up having multiple fields that refer to the same resolver object, causing problems when generating the schema.

**Comment by patrick91** [comment]
@BryceBeagle I think this is fixed, @jordangarside's example works well now too, shall we close?

**Comment by BryceBeagle** [comment]
Sounds good to me 👍
