### ISSUE TITLE
Improve public interface of TypeDefinition

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#449]
We internally use TypeDefinition to generate an intermediate GraphQL type what will later used to create GraphQL-core types.

This TypeDefinition should be improve in order to allow developers to programmatically create types when needed. For example this will be useful for adding support to pydantic.

Something we need to improve for sure are:

- the `_fields` init param should be `fields`
- we should find a better way to call `_resolve_types`, this is useful for schema generation as it can be used to resolve types later (when they are all defined).

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/types/types.py#L16-L54

**Comment by patrick91** [comment]
Closing this as we have #489 that has better way of improving the internal structure :)

**Comment by nrbnlulu** [comment]
This should probably re-opened @patrick91 ?
