### ISSUE TITLE
Investigate the necessity of comparing against NoneType in UnionDefinition.types

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#461]
Currently, `UnionDefinition.types` returns all de-generified types, after filtering those that are `NoneType` (`None.__class__`)
https://github.com/strawberry-graphql/strawberry/blob/8126ec0b6a7acf0edf553752d703bcd1f6273ac4/strawberry/union.py#L18-L22

@patrick91 explained that the `NoneType` filter was added to handle `Optional[...]` (which expands to `Union[..., NoneType]`), but this may not be an issue after all.

No test fails if this check is removed. Either the check is not necessary or we have a missing test.

**Comment by DoctorJohn** [comment]
Closing since the mentioned code does no longer exist in this form (especially the filtering seems to be gone).
