### ISSUE TITLE
Tracing - ignore introspection and default resolvers

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#478]
We just merged support for Apollo tracing, but we can improve it to not trace introspection queries and default resolvers (tracing all the resolvers will probably be too expensive, and also it is not a useful information).

The check should be done in both async and non-async `resolve`: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/extensions/tracing/apollo.py#L132

**Comment by flpStrri** [comment]
It is easy to figure out with the self, _next and root what is being done? I can help here.

**Comment by patrick91** [comment]
@flpStrri we migth need to add an attribute on the resolver, here's where we fallback to gettattr: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/resolvers.py#L50-L52

this is our version of default resolver, it might not be easy to understand if it is default resolver though (unless we can access `field.base_resolver`), so we might need a bit of restructuring of the code, happy to pair on this if needed

for introspection I think we can check the field name in `info` :)

**Comment by flpStrri** [comment]
Would be great. You ping me at Discord so we can set a time? Now that JetBrains released their [pair programming extension](https://blog.jetbrains.com/blog/2020/09/28/code-with-me-eap/), it will be much better!
