### ISSUE TITLE
Tracing - add support for opentracing

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#481]
Similar to apollo tracing we should make an extension to add tracing using opentracing. 

Apollo tracing code: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/extensions/tracing/apollo.py

We need to use the opentracing python package (as optional install) for this.

**Comment by anoopmsivadas** [comment]
Can I work on this @patrick91

**Comment by Ambro17** [comment]
Hello, i installed `strawberry` today and i get the following error running `poetry run pytest`
```
E   ModuleNotFoundError: No module named 'opentelemetry'
```
It appears that is listed as an optional dependency, but tests need it to run properly.

Perhaps we could add it as a dev dependency or skip those tests if the lib is not installed.

**Comment by patrick91** [comment]
@Ambro17 that’s been fixed now ^^ I added the dependency as dev dep :)

Also I forgot to close this issue! Will do now :)
