### ISSUE TITLE
Feature request: Be able to add descriptions to field arguments

### ISSUE THREAD

**Issue by jkimbo** [strawberry-graphql/strawberry#509]
Currently it isn't possible (I don't think) to add descriptions to field arguments. This would be a useful feature to help document a GraphQL schema.

Not sure what the api for this should look like but here is one example:

```python
@strawberry.type
class Query:
	@strawberry.field
	def user_by_id(id: str = strawberry.argument(description="The ID of the user")) -> User:
		...
```

Which would result in the following schema:

```graphql
type Query {
  userById(
    """The ID of the user"""
    id: String
  ): User!
}

**Comment by patrick91** [comment]
@jkimbo yes, I think that's the best API, fastapi does something similar too, so I think we go this way :)

**Comment by jkimbo** [comment]
After some discussion on Discord we're going use the new [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) type to add extra metadata to an argument:

```python
from typing import Annotated

@strawberry.type
class Query:
	@strawberry.field
	def user_by_id(id: Annotated[str, strawberry.argument(description="The ID of the user")]) -> User:
		...
```

**Comment by patrick91** [comment]
annotated is available in typing_extensions for python < 3.9, I wonder if we should expose it from strawberry too, but maybe not :) 

https://github.com/python/typing/blob/master/typing_extensions/src_py3/typing_extensions.py#L1781

**Comment by jkimbo** [comment]
I don't think it's necessary to expose it directly from strawberry @patrick91 since typing_extensions is part of the dependencies anyway.

**Comment by jkimbo** [comment]
#513 has been released

**Comment by mikeldking** [comment]
Is there support for descriptions on static fields of an object type?

**Comment by jkimbo** [comment]
@mikeldking I'm not sure I understand. Can you provide an example of what you're trying to achieve?

**Comment by mikeldking** [comment]
@jkimbo I want to add descriptions to more places like such:

## Input type fields
```python
@strawberry.input
class TimeRange:
    start: Annotated[
        datetime.datetime,
        strawberry.argument(description="The start of the time range"),
    ]
    end: Annotated[
        datetime.datetime,
        strawberry.argument(description="The end of the time range. Right exclusive."),
    ]

    def is_valid(self) -> bool:
        return self.start < self.end
```
## type fields
```python
@strawberry.type
class Dataset:
    name: str
    start_time: Annotated[datetime, strawberry.field(description="The start of the time range")]
    end_time: Annotated[datetime, strawberry.field(description="The start of the time range")]
```

☝️ cases don't result in docstrings in the schema, which are super helpful when someone is trying to explore your schema via an IDE or graphiql.

Hope that makes sense.

**Comment by jkimbo** [comment]
@mikeldking both of those are possible by using `strawberry.field` (`strawberry.argument` is only used for arguments to fields).

So your examples should look like this:

## Input type fields
```python
@strawberry.input
class TimeRange:
    start: datetime.datetime = strawberry.field(description="The start of the time range")
    end: datetime.datetime = strawberry.field(description="The end of the time range. Right exclusive.")
```

## type fields
```python
@strawberry.type
class Dataset:
    name: str
    start_time: datetime = strawberry.field(description="The start of the time range")
    end_time: datetime = strawberry.field(description="The start of the time range")
```

**Comment by mikeldking** [comment]
A thanks so much. Still new to strawberry so got confused with the `Annotated` approach for field params.
