### ISSUE TITLE
Deprecate strawberry.union('name', types=(A, B)) in favour of using Annoted

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#521]
So, I though having our own way of defining union type was a good idea, but turns out it is quite hard to make a mypy plugin that understands this syntax:

```python
Result = strawberry.union("Result", (A, B))
```

also this won't really be supported in other type checkers, so the alternative is this:

```python
Result = Annotated[Union[A, B], strawberry.union("Result")]
```

which is not that bad, also this allows to define named unions on fields directly:

```python
@strawberry.type
class X:
     result: Annotated[Union[A, B], strawberry.union("Result")]
```

which isn't the best thing to ready, but might be useful in some cases :D

**Comment by BryceBeagle** [comment]
> turns out it is quite hard to make a mypy plugin that understands this syntax:
> ```python
> Result = strawberry.union("Result", (A, B))
> ```

what about this requires a mypy extension? Or does the _usage_ of `Result` cause problems?

**Comment by patrick91** [comment]
@BryceBeagle so, we need the plugin to tell mypy that result now is a Type, more specifically a `TypeAlias` so that you can do things like `A: Result`.

Unfortunately our current plugin seems to break in some cases, and I'm having a hard time finding a solution, basically here:

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/ext/mypy_plugin.py#L55

one of the type breaks `api.named_type(expr.name)`, but I have no idea why, from what I've seen it seems that mypy things the type is coming from a variable, but well, it comes from an import 🤷

**Comment by BryceBeagle** [comment]
Does [PEP-613](https://www.python.org/dev/peps/pep-0613/) not work for this case?

```python
Result: TypeAlias = strawberry.union("Result", (A, B, C))
```

**Comment by patrick91** [comment]
@BryceBeagle didn't know about that one! I think the problem would still be that mypy doesn't know the actual type of Result :(

**Comment by patrick91** [comment]
Oh well, turns out we can't do this for now, as mypy doesn't support it, from https://github.com/python/mypy/issues/9315

> Because A = Annotated[int, Positive] works, and so does x: Annotated[int, Positive()], but indeed B = Annotated[int, Positive()] does not.

**Comment by patrick91** [comment]
We might not deprecate `strawberry.union`, but we might introduce support for the annotated version, when the next release of mypy gets released :)

**Comment by rmzr7** [comment]
@patrick91 has a new annotated version been released yet or is `Result = strawberry.union("Result", (A, B))` still the preferred way of using union types?

**Comment by patrick91** [comment]
> @patrick91 has a new annotated version been released yet or is `Result = strawberry.union("Result", (A, B))` still the preferred way of using union types?

we are keeping strawberry.union 😊

**Comment by jkimbo** [comment]
Can we close this issue then @patrick91 ?

**Comment by patrick91** [comment]
let's close for now, maybe we'll come back to it in future 😊
