### ISSUE TITLE
Allow to deprecate enums values

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#537]
We should be able to deprecate enum fields :) as per spec, GraphQL allows to deprecate enum values by passing a directive: https://spec.graphql.org/June2018/#sec-Enums

GraphQL-core allows that too: https://github.com/graphql-python/graphql-core/blob/4dbb9d4a5b1ed33c988c55ad277022aa9f850c8f/src/graphql/type/definition.py#L1204-L1210

This is where we process enum definitions: https://github.com/strawberry-graphql/strawberry/blob/c8fb7619e76588d61a6732ad3233acb4eb93a843/strawberry/enum.py
This is where we convert them to GraphQL-core types

https://github.com/strawberry-graphql/strawberry/blob/c8fb7619e76588d61a6732ad3233acb4eb93a843/strawberry/schema/schema_converter.py#L97-L120

we defined enums like this:

```python
@strawberry.enum
class IceCreamFlavour(Enum):
    VANILLA = "vanilla"
    STRAWBERRY = "strawberry"
    CHOCOLATE = "chocolate"
```

we might want to allow this syntax in order to pass deprecation_reasons:

```python
@strawberry.enum
class IceCreamFlavour(Enum):
    VANILLA = strawberry.enum_value("vanilla", deprecation_reason="ABC")
    STRAWBERRY = "strawberry"
    CHOCOLATE = "chocolate"
```

**Comment by sadielbartholomew** [comment]
Hi @patrick91, I am looking for an Issue to contribute to for Hacktoberfest since another I started towards it will take longer than October. Please can I take this one on, if someone isn't planning to do it already? I am fairly sure I know what to do and can strive to put up a PR before the end of tomorrow.

**Comment by patrick91** [comment]
> Hi @patrick91, I am looking for an Issue to contribute to for Hacktoberfest since another I started towards it will take longer than October. Please can I take this one on, if someone isn't planning to do it already? I am fairly sure I know what to do and can strive to put up a PR before the end of tomorrow.

Awesome! No one is working on this as far as I know! 

Feel free to join our discord in case you have questions! https://discord.gg/ZkRTEJQ

**Comment by sadielbartholomew** [comment]
Excellent, thanks :) I'll ask on the forum if I get stuck in some way otherwise put up a PR shortly.

**Comment by sadielbartholomew** [comment]
Hi, just to provide an update, I've missed the chance to finish this for Hacktoberfest because I was busier than I thought over the weekend, but I still plan to address this with a PR. I am perhaps halfway there.

Due to other priorities I estimate it will be towards the end of the week (most likely Friday) before I can finish it and open the PR. I hope that is still okay and sorry for the delay relative to my original plan. Thanks.

**Comment by patrick91** [comment]
@sadielbartholomew no worries! Thanks for the update!

I think we will still send Strawberry stickers to new contributors if they want 😊

**Comment by msobas** [comment]
@patrick91 What do you mean by deprecating enums? 
`GraphQLEnumType` doesn't have `deprecation_reason` - https://github.com/graphql-python/graphql-core/blob/3359fe60d9940b174270426438a89d629b6cc6e2/src/graphql/type/definition.py#L1044-L1052

I believe we already can deprecate field that is using enum. 

```
@strawberry.field(deprecation_reason="Deprecated Enum")
def enum_field(self, info, id: int) -> IceCreamFlavour:
    return IceCreamFlavour.STRAWBERRY
```

**Comment by patrick91** [comment]
@msobas you can deprecate enum fields:

```GraphQL 
enum Direction {
  UP
  DOWN
  LEFT
  """
  The other left
  """
  RIGHT
  SIDEWAYS @deprecated(reason: "Replaced with Left or Right")
}
```

Apologies for not being clear in the issue description ☺️

**Comment by sadielbartholomew** [comment]
Hi, sorry this fell off my radar after November, I'm happy to still give it a go in the next month or so, but if this is urgent then by all means someone else can step in to do this (not sure if that is the case now given these new comments in this thread), in which case please accept my apologies for not getting it done. (I was a over-optimistic with the time I would have to devote to other open-source projects).

**Comment by patrick91** [comment]
@sadielbartholomew no worries at all :) feel free to come back to this task when you have time, don't think it is urgent :)

**Comment by msobas** [comment]
I looked at this a little bit before @patrick91 updated description and I implemented this kind of API:

```
@strawberry.enum(
        values_config=dict(
            CHOCOLATE=dict(deprecation_reason="Strawberry is so much better"),
            STRAWBERRY=dict(description="This is obvious winner in all tastes"),
        ),
    )
    class IceCreamFlavour(Enum):
        VANILLA = "vanilla"
        STRAWBERRY = "strawberry"
        CHOCOLATE = "chocolate"
```

What do you think about this approach? 
If it's working for us, I could create pull request @sadielbartholomew (I'm only missing some better tests) if not, than it probably would be quite easy to covert to API suggested by @patrick91

**Comment by BryceBeagle** [comment]
Hmm that feels a little heavy on the enum decorator. Personally, I'd like to keep the value metadata closer to the actual values

**Comment by patrick91** [comment]
@msobas oh, didn't realise you were working on it ☺️

I had a short chat with @BryceBeagle on discord and, while we have different preferences, we kinda settled on the api in the description, I think it's consistent with what we have at the moment :)

Feel free to join our discord too https://strawberry.rocks/discord

**Comment by msobas** [comment]
Well it was more of a case of I have a free evening :D and wanted to play around something. Sorry for not saying anything before ;) probably a good practice so we don't do stuff twice. I'll search for your discussion and think about API again :)
