### ISSUE TITLE
Alllow to customise how data is returned in our views

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#540]
Currently we allow to customise how we get the context and root value for our views (asgi, django and flask). We should allow to return data differently, like for example using ujson instead of json.

I think extracting the code that renders the response to a method should be enough: 

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/django/views.py#L85-L87

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/flask/views.py#L65-L69

https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/asgi/http.py#L60-L61

**Comment by bhargavasomya** [comment]
Hey, @patrick91! I would like to contribute to this project. Can you please assign this issue to me? Thanks.

**Comment by patrick91** [comment]
@bhargavasomya done!

**Comment by patrick91** [comment]
I think we support this already :)
