### ISSUE TITLE
Add support for sanic

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#541]
Sanic seems to be quite popular for performance reasons, might be nice to add built-in support for it, should be similar to asgi :)

https://github.com/huge-success/sanic

**Comment by shinybrar** [comment]
Hi @patrick91 ,
I would happy to help with this issue, since I use Sanic for a lot of my production software and want to promote the use of Strawberry within our organization. If you can guide me in the right direction -- I can take the rest from there.

**Comment by patrick91** [comment]
@shinybrar nice! thanks for wanting to help (and promote strawberry)! 😊 

I'm not familiar with sanic, but it shouldn't be too different than how we did Flask support: https://github.com/strawberry-graphql/strawberry/tree/master/strawberry/flask

or even better ASGI (since it is async): https://github.com/strawberry-graphql/strawberry/tree/master/strawberry/asgi

so I create a new namespace `strawberry.sanic` that exposes what's needed for sanic 😊
