### ISSUE TITLE
Make camelCasing optional

### ISSUE THREAD

**Issue by jordangarside** [strawberry-graphql/strawberry#542]
Would be nice if we could make camelCasing optional:

`schema = strawberry.Schema(query=Query, auto_camelcase=False)`

https://github.com/strawberry-graphql/strawberry/issues/36

**Comment by peniqliotuv** [comment]
@patrick91 is there an update on this :O

**Comment by patrick91** [comment]
> @patrick91 is there an update on this :O

sorry I've been quite busy in the last months, I'll make sure this happens over next week 😊

**Comment by zerocewl** [comment]
Any news?

**Comment by patrick91** [comment]
@zerocewl I'm aiming to finish it this week :) I made some changes to make this easier in #1044 so hopefully I won't find any blockers :)

**Comment by patrick91** [comment]
Sorry this took more than expected, we want to release a big refactor before doing it! Now it is done and should be released soon!

Thanks for waiting!
