### ISSUE TITLE
Could not determine type of stream

### ISSUE THREAD

**Issue by fiercebrake** [strawberry-graphql/strawberry#561]
A good day to you,

When using my own oauth clientid, and "Hi resolution", Strawberry complaints with "Could not determine type of stream".

This does not happen if using a working API token.

On terminal, i get the logs down below for that error.

Any advise ?

`06:36:22.064 DEBUG MainWindow:1002                  Started QThread(0x55db3ab85c80)
06:36:22.076 INFO  DeviceManager:442                Device added: "Gio/unmounted/140704806428704" ("Gio/unmounted/140704806428704")
06:36:29.829 DEBUG MainWindow:1300                  Song changed to "Sandi Patty" "Everlasting" "God & King"
06:36:29.853 DEBUG MusixmatchLyricsProvider:88      MusixmatchLyrics: Sending request for "sandi-patty" "god-king" QUrl("https://www.musixmatch.com/lyrics/sandi-patty/god-king")
06:36:29.854 DEBUG PlaylistBackend:336              Saving playlist 39
06:36:29.854 DEBUG Player:349                       URL handler for QUrl("tidal:29344511") is loading asynchronously
06:36:30.176 DEBUG LoloLyricsProvider:148           LoloLyrics: No lyrics for "Sandi Patty" "God & King" "Error transferring http://api.lololyrics.com/0.5/getLyric?artist=Sandi Patty&track=God %26 King - server replied: Not Found (203)"
06:36:30.388 ERROR MusixmatchLyricsProvider:223     MusixmatchLyrics: "Json lyrics is missing body."
06:36:30.388 DEBUG MusixmatchLyricsProvider:224     QVariant(QJsonObject, QJsonObject())
06:36:30.388 DEBUG MusixmatchLyricsProvider:211     MusixmatchLyrics: No lyrics for "Sandi Patty" "God & King"
06:36:30.397 DEBUG Player:275                       URL handler for QUrl("tidal:29344511") returned QUrl("http://en-pr-fa.audio.tidal.com/v2/0/d2d660857483f289c2b39752ca2816b9_26.flac?token=1604752590~MDhmYzAzNWZmZDU5ZjE5Yzk0OGY1ZjNkMzBlNmE4ZTIwY2E2YWI0ZA==")
06:36:30.397 DEBUG Player:336                       Playing song "God & King" QUrl("http://en-pr-fa.audio.tidal.com/v2/0/d2d660857483f289c2b39752ca2816b9_26.flac?token=1604752590~MDhmYzAzNWZmZDU5ZjE5Yzk0OGY1ZjNkMzBlNmE4ZTIwY2E2YWI0ZA==")
06:36:30.400 INFO  GstEnginePipeline:366            Setting buffer duration: 4000000000 low watermark: 0.33 high watermark: 0.99
06:36:30.405 DEBUG logging:83(GLib-GIO)             _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
06:36:30.407 DEBUG logging:83(GLib-GIO)             _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
06:36:30.408 DEBUG logging:83(GLib-GIO)             _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
06:36:30.489 DEBUG AuddLyricsProvider:140           AudDLyrics: Got lyrics for "Sandi Patty" "God & King"
06:36:30.667 DEBUG OVHLyricsProvider:105            OVHLyrics: Got lyrics for "Sandi Patty" "God & King"
06:36:30.667 DEBUG LyricsFetcherSearch:129          Using lyrics from "AudD" for "Sandi Patty" "God & King" with score 1.5
06:36:30.815 ERROR GstEnginePipeline:852            ErrorMessageReceived ID: 1 Domain: 4051 Code: 4 Error: "Could not determine type of stream."
06:36:30.815 ERROR GstEnginePipeline:853            ErrorMessageReceived ID: 1 Domain: 4051 Code: 4 Debug: "../gstreamer/plugins/elements/gsttypefindelement.c(999): gst_type_find_element_chain_do_typefinding (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstTypeFindElement:typefindelement1"
06:36:30.815 ERROR GstEngine:563                    GStreamer error: 4051 4 "Could not determine type of stream."
06:36:30.815 ERROR GstEnginePipeline:852            ErrorMessageReceived ID: 1 Domain: 4051 Code: 1 Error: "Internal data stream error."
06:36:30.815 ERROR logging:72(GLib)                 Source ID 21 was not found when attempting to remove it
06:36:30.815 ERROR GstEnginePipeline:853            ErrorMessageReceived ID: 1 Domain: 4051 Code: 1 Debug: "../gstreamer/libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:\nstreaming stopped, reason error (-5)"
06:38:17.873 DEBUG Database:489                     Starting database integrity check
06:38:17.943 DEBUG Database:550                     Starting database backup
06:42:07.713 DEBUG GlobalShortcutsSettingsPage:121  Gnome (GSD) D-Bus backend is unavailable.
06:42:07.713 DEBUG GlobalShortcutsSettingsPage:126  X11 backend is available.
`

**Comment by patrick91** [comment]
Hi there @fiercebrake!

```
 GStreamer error: 4051 4 "Could not determine type of stream."
```

This doesn't seem like an error coming from strawberry, would be able to post some code to reproduce this? :)

**Comment by fiercebrake** [comment]
> Hi there @fiercebrake!
> 
> ```
>  GStreamer error: 4051 4 "Could not determine type of stream."
> ```
> 
> This doesn't seem like an error coming from strawberry, would be able to post some code to reproduce this? :)

Sure, let me know what you would require

**Comment by patrick91** [comment]
@fiercebrake I checked the issue better, and it seems that maybe you're in the wrong repo? 

Are you this maybe? https://github.com/strawberrymusicplayer/strawberry

**Comment by fiercebrake** [comment]
Ah! my apologies

yes indeed I am in the wrong repo, sorry about that
