### ISSUE TITLE
Merging schemas, schema stitching

### ISSUE THREAD

**Issue by kristofgilicze** [strawberry-graphql/strawberry#566]
I have seen the issue https://github.com/strawberry-graphql/strawberry/issues/38 which addresses remote schemas, i believe this is slightly different.

Most Django projects written in the pattern where the project is split into several smaller 'apps'..

**What I do right now**
```
- models.py
- admin.py
- typing.py
- mutations.py
- resolvers.py
- etc...
```
create these for every app, then assemble my schema at the project level.

**Proposal**
Ideally I would like to have one schema defined per app, and merge them into a main schema.
**Is there a way to merge schemas, that I overlooked ?**
( ? Probably schema stitching is the correct terminology, not sure ? )

This is something that is implemented by Graphene, but in every other way I prefer Strawberry.
It feels very clean and Pythonic indeed, thanks ! :)

**Comment by patrick91** [comment]
> I have seen the issue #38 which addresses remote schemas, i believe this is slightly different.
> 
> Most Django projects written in the pattern where the project is split into several smaller 'apps'..

Oh, interesting, at work we are doing one big app that contains all the API code 😊
but that's just another way of doing it :)

> **Proposal**
> Ideally I would like to have one schema defined per app, and merge them into a main schema.
> **Is there a way to merge schemas, that I overlooked ?**

What I do is this:

```python
import strawberry

from app_a.query import Query as AppAQuery
from app_b.query import Query as AppBQuery

@strawberry.type
class Query(AppAQuery, AppBQuery):
    ...

schema = strawberry.Schema(Query)
```

not great, but it works. But I think we could provide a way for merging/stitching schemas, shouldn't be too complicated[1]

we could provide an API like:

```
schema = strawberry.merge_schemas(a, b, c)
```

or something better, @jkimbo do you have any suggestion? :)

> This is something that is implemented by Graphene
How do you do that in Graphene? :)

> but in every other way I prefer Strawberry.
> It feels very clean and Pythonic indeed, thanks ! :)

Thank you for the feedback! 😊

[1] though we might need to figure out how to solve name clashes and similar potential issues

**Comment by jkimbo** [comment]
> Oh, interesting, at work we are doing one big app that contains all the API code 😊
but that's just another way of doing it :)

This is the way I do it as well but it's interesting to see other ways of structuring projects.

> schema = strawberry.merge_schemas(a, b, c)

This would essentially be the same as `class Query(AppAQuery, AppBQuery):` but with extra checking for collisions @patrick91 ?

This might be a good use case for a registry pattern. For example something like this:

```python
# api/schema.py
import strawberry

schema = strawberry.schema_builder()  # or some other function name

# my_app/query.py
from api.schema import schema

@schema.type(merge=True)
class Query:
	...

# my_other_app/query.py
from api.schema import schema

@schema.type(merge=True)
class Query:
	...
```

Or could do something similar to [ariadne](https://ariadnegraphql.org/docs/intro#completed-code) with a specific query type:

```python
# api/schema.py
import strawberry

query = strawberry.query_type()

# my_app/query.py
from api.schema import query

@query.field
def my_field() -> str:
	...
```

I think I prefer the first one though.

**Comment by Ambro17** [comment]
I like the `merge_schemas` api a little better since there would be a single place to look when we want to customize the result.
That function will probably end with some optional arguments (based on how schema stitching works on Javascript) and I feel like having them decorating query objects that may not be on the same place might make harder to understand what's happening and why

**Comment by jkimbo** [comment]
That is a good point @Ambro17 . Having a `merge_schemas` function makes sense though my concern is that that function could get quite complicated (for example https://www.graphql-tools.com/docs/stitch-type-merging is pretty scary). IMO the registry pattern has other benefits for structuring your code but maybe this is not the right place for it.

I didn't follow why Apollo decided to drop Schema Stitching for Federation. Does anyone have a good summary?

**Comment by kristofgilicze** [comment]
> What I do is this:
> 
> ```python
> import strawberry
> 
> from app_a.query import Query as AppAQuery
> from app_b.query import Query as AppBQuery
> 
> @strawberry.type
> class Query(AppAQuery, AppBQuery):
>     ...
> 
> schema = strawberry.Schema(Query)
> ```
> 
> not great, but it works. But I think we could provide a way for merging/stitching schemas, shouldn't be too complicated[1]

_Thanks! Soo this is basically the same as Graphene, using inheritance._

Having an exception raised upon collision seems useful.

Using registry pattern the 'apps' would be dependent on a import from the main `api.schema` module.
This way the app is not decoupled from the project, so it is not as simple to reuse in a different project.

Ideally the app level schema could be used standalone, then stitched into the 'project' schema where the app is used. 
So the `schema = strawberry.merge_schemas(a, b, c)` approach seems better.

**Comment by jkimbo** [comment]
> Using registry pattern the 'apps' would be dependent on a import from the main api.schema module.

Yep very true. Sounds like a `merge_schemas` function is the way forward here. Maybe under a `.tools` namespace (like the graphql-tools project).

**Comment by la4de** [comment]
I would propose following syntax. It's intuitive and easy to use.

```python
import strawberry
import app1, app2
schema = strawberry.Schema(query=[app1.Query, app2.Query], mutation=[app1.Mutation, app2.Mutation])
```

**Comment by kristofgilicze** [comment]
> ```python
> import strawberry
> import app1, app2
> schema = strawberry.Schema(query=[app1.Query, app2.Query], mutation=[app1.Mutation, app2.Mutation])
> ```
So this proposes making the **query and mutation argument type flexible**.
No need for extra tooling, _intuitive_ for the developer.

However it is little different from the `schema = strawberry.merge_schemas(a, b, c)` approach.
Not merging schemas, but the queries and mutations separately.

I like both approaches ¯\_(ツ)_/¯, though I have slight preference for the flex arg one.

**Comment by jkimbo** [comment]
> ```python
> import strawberry
> import app1, app2
> schema = strawberry.Schema(query=[app1.Query, app2.Query], mutation=[app1.Mutation, app2.Mutation])
> ```

I am personally not a fan of overloading arguments to accept multiple types because I think it can get confusing. I think a better API would be to have a utility function that can just merge types together. E.g.

```python
import strawberry
from strawberry.tools import merge_types
import app1, app2

Query = merge_types([app1.Query, app2.Query])
Mutation = merge_types([app1.Mutation, app2.Mutation])

schema = strawberry.Schema(query=Query, mutation=Query)
```

The benefit of this API is that it maintains the same Schema api and, by having a dedicated function, it allows us to support passing options to control how the types are merged (should it raise an error on field conflicts or just overwrite for example). A `merge_schemas` function would probably no longer be necessary.

What do you think @la4de @kristofgilicze ?

**Comment by la4de** [comment]
@jkimbo, I see your point and it would be good to have possibility to give extra arguments as well.

Could we support both syntaxes? I don't see any problems if one could use more flexible API and one would use simpler and less verbose API. Library can internally use the same `merge_types` method. Most of the cases simpler API would be enough.

**Comment by jkimbo** [comment]
> Could we support both syntaxes? I don't see any problems if one could use more flexible API and one would use simpler and less verbose API. Library can internally use the same `merge_types` method. Most of the cases simpler API would be enough.

@la4de possibly, though TBH I don't see much benefit to supporting the simplified API and I would rather there just be one way of doing it. To quote the Zen of Python "There should be one-- and preferably only one --obvious way to do it."

Regardless I'll have a go at creating a `merge_types` function first and see how it goes.

**Comment by kristofgilicze** [comment]
I also agree that there should be a single API.

`merge_types()` is for sure absolutely needed.


My input is that  we should  consider keeping the direct way to  `merge_schemas()`.

Just seems weird that I would need to import my schema in multiple parts, since the original request was to stitch schemas not types.

**Comment by jkimbo** [comment]
Update on this: I've been hacking around with a `merge_types` function (which will form the basis of a `merge_schemas` function and I've got some basic functionality working. However I don't think it's worth me spending more time on it until @BryceBeagle 's work on refactoring `StrawberryFields` is done because a lot is going to change so anything I do now will have to be rewritten.

**Comment by claytonkreisel** [comment]
I am sure that you have already got this working, but just for reference here is the `merge_types` way to do this.

```python
from strawberry.fastapi import GraphQLRouter
from strawberry import Schema
from strawberry.tools import merge_types
from .schema import Query as QueryA, Mutation as MutationA
from .schema2 import Query as QueryB, Mutation as MutationB

# Add your query types to the query list
queries = (QueryB, QueryA)

# Add your mutation types to the mutation list
mutations = (MutationB, MutationA)

# Do not touch these
Query = merge_types("Query", queries)
Mutation = merge_types("Mutation", mutations)
schema = Schema(query=Query, mutation=Mutation)
```
