### ISSUE TITLE
Parity with `dataclasses.field`

### ISSUE THREAD

**Issue by LouisAmon** [strawberry-graphql/strawberry#569]
While starting to use Strawberry 🍓  and admittedly being a beginner, I noticed I had to make a choice : I have to choose between Strawberry features on my fields via `strawberry.field` (e.g. adding a description) and using native `dataclasses.field` features.

Some of the native `dataclasses.field` attributes that I do use on my dataclasses are `default_factory` and `metadata` (which allows me to pass an arbitrary dictionary of extra settings to my field)

Is there a reason why `strawberry.field` doesn't directly extend `dataclasses.field` ? Wouldn't that be more pythonic ? 😺 

Practically speaking:
```python
import faker

# https://faker.readthedocs.io/en/master/
fake = faker.Faker()

@strawberry.type
class User:
    first_name: str = strawberry.field(description="First name",  default_factory=fake.first_name, metadata={"foo": "bar"})
```

This isn't currently possible because `@strawberry.field` doesn't accept `default_factory` and `metadata`.
Would've been cool though, especially in the context of being able to generate fake data on the fly

**Comment by LouisAmon** [comment]
FYI [pydantic does have](https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation) parity with `dataclasses.field`, mostly by allowing `**` extra kwargs in their field function

They consider `default_factory` to be a [beta](https://pydantic-docs.helpmanual.io/usage/models/#field-with-dynamic-default-value) feature tho

**Comment by patrick91** [comment]
I personally want to add these feature, there's a small discussion on adding support for init -> https://github.com/strawberry-graphql/strawberry/issues/539

We'll also need `default_factory` too (this will affect the schema generation too as we expose default values on the schema).

Not sure about metadata, I guess it won't hurt to add it, but I wonder if users would get confused by it? 
What do use it for?

**Comment by LouisAmon** [comment]
I personally use it to define my data generator, for which I opened a different discussion [here](https://github.com/strawberry-graphql/strawberry/discussions/570) as I believe it is its own topic :)

Looks something like this:
```python
from __future__ import annotations

from abc import ABC
from dataclasses import field, fields

import faker
import strawberry

fake = faker.Faker()

FACTORY_FIELD = "factory"


class FactoryMixin(ABC):
    """
    Abstract class that defines the ability to generate fake data from a dataclass'
    metadata
    """

    @classmethod
    def fake(cls) -> FactoryMixin:
        # Find all fields that define a data generator
        factory_fields = [
            field for field in fields(cls) if field.metadata.get(FACTORY_FIELD)
        ]
        fake_data = {
            field.name: field.metadata[FACTORY_FIELD]() for field in factory_fields
        }
        return cls(**fake_data)


@strawberry.type
class User(FactoryMixin):

    first_name: str = field(metadata={FACTORY_FIELD: fake.first_name})
    last_name: str = field(metadata={FACTORY_FIELD: fake.last_name})
    email: date = field(metadata={FACTORY_FIELD: fake.email})
    phone: str = field(metadata={FACTORY_FIELD: fake.phone_number})

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"
```

The `metadata` field, although a bit inexpressive, was literally intended for that usage by the Python core team:

> It is not used at all by Data Classes, and is provided as a third-party extension mechanism. Multiple third-parties can each have their own key, to use as a namespace in the metadata.

In theory, I guess Strawberry should claim it's own namespace in there:
```python
first_name: str = field(metadata={"strawberry": {"description": "Given name"}})
```

Practically speaking, this wouldn't work as you'd lose all the typing information and IDE support that functions and classes provide, which is why Pydantic, Strawberry... no one really uses `metadata`

It did work for me as a drop-in for a possibly new feature though (data generation, that is) 😸
