### ISSUE TITLE
Improve structure of mypy plugin

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#577]
Would be ideal to split it into multiple files as now it is a big mess :D

**Comment by BryceBeagle** [comment]
A specific desire would be to split the code copied from external sources/libraries into their own files, for code separation purposes.

**Comment by patrick91** [comment]
> A specific desire would be to split the code copied from external sources/libraries into their own files, for code separation purposes.

we do modify the data classes plugin though, does that change your idea?

**Comment by BryceBeagle** [comment]
Somewhat, but I think it would be best to not have external code embedded in first-party code, because then it can become unclear what comes from where, especially if refactoring is done by someone unaware of the original source.

**Comment by patrick91** [comment]
I'm going to close this, I don't think it is a priority and we can also wait for this PEP to be implemented by mypy: https://peps.python.org/pep-0681/. Having that PEP implemented means we'll remove a lot of code from our mypy plugin 😊
