### ISSUE TITLE
Schema-basics documentation uses wrong field name for books query

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#604]
https://github.com/strawberry-graphql/strawberry/blob/a973af56317548925d0f57a7fac338adc6aef9fa/docs/01_general/01_schema-basics.md#L223-L231

This snippet should use `books` instead of `getBooks`

**Comment by Paolo-Cosentino** [comment]
Hello!

Can I work on this issue? It will be my first open source contribution.

**Comment by BryceBeagle** [comment]
Sure! Feel free to ask any questions (here or on our discord) if you have any

**Comment by Paolo-Cosentino** [comment]
> Sure! Feel free to ask any questions (here or on our discord) if you have any

Just submitted the PR, thank you for letting me get my feet wet.
