### ISSUE TITLE
Missing magic dependency prevents install

### ISSUE THREAD

**Issue by benwis** [strawberry-graphql/strawberry#608]
pip and poetry won't install strawberry because magic does not exist. Perhaps it got renamed to python-magic?
I can't find where in this project it lists dependencies, otherwise I'd submit a pull request.

`[SolverProblemError]
Because no versions of strawberry match >3.0,<4.0
 and strawberry (3.0) depends on magic (>=0.1), strawberry (>=3.0,<4.0) requires magic (>=0.1).
So, because no versions of magic match >=0.1
 and vidette depends on strawberry (^3.0), version solving failed.
`

`Collecting strawberry
  Downloading strawberry-3.0.tar.gz (267 kB)
     |████████████████████████████████| 267 kB 1.7 MB/s 
ERROR: Could not find a version that satisfies the requirement magic>=0.1 (from strawberry) (from versions: none)
ERROR: No matching distribution found for magic>=0.1 (from strawberry)
`

Looking forward to trying strawberry!

**Comment by patrick91** [comment]
@benwis can you try with 

`
pip install strawberry-graphql 
`

? 

It looks like you're trying to install the package `strawberry`, unfortunately we don't have access to it :)

**Comment by benwis** [comment]
@patrick91 You are absolutely right. I totally missed that. It works fine now :+1: 

Happy Holidays.
