### ISSUE TITLE
Access to selected attributes for type in info parameter for resolvers

### ISSUE THREAD

**Issue by AdamStrojek** [strawberry-graphql/strawberry#676]
Currently, in resolvers, there is no possibility to retrieve a list of selected attributes in GraphQL query for type. This would be useful when using a database to limit query size

**Comment by patrick91** [comment]
Hi @AdamStrojek do you mean accessing the list of selected fields? 

If you pass an info argument to a resolver you should be able to do that:

```
@strawberry.type
class Query:
    @strawberry.field
    def a(self, info, **kwargs) -> str:
        print(dir(info))
        return "a"
```

we haven't documented this yet as it is not properly typed yet, but you can use it already :)

**Comment by patrick91** [comment]
This is supported now :)

https://strawberry.rocks/docs/types/resolvers#api
