### ISSUE TITLE
Strawberry mypy plugin not working with new 0.800 mypy version

### ISSUE THREAD

**Issue by AGASS007** [strawberry-graphql/strawberry#678]
Due to the new `info: TypeInfo` arg in `DataclassAttribute` (see [here](https://github.com/python/mypy/pull/9380/files#diff-1fdad80f805993800524fbb9b684cc3d09879f54a0e51c71f2a447c7d46c1eb4R38)), `DataclassAttribute` instantiation fails [here](https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/ext/mypy_plugin.py#L476).

I do not have any solution to offer yet, but I guess it will have to be addressed before bumping mypy.

Cheers

**Comment by patrick91** [comment]
@AGASS007 thanks for the report! Will take a look at it now, hopefully it is something simple 😊
