### ISSUE TITLE
Add safety checks around strawberry.type, strawberry.input and strawberry.interface

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#681]
I found a place where I had this:

```
from .enums import ExampleEnum

ABC = strawberry.type(ExampleEnum)
```

I think we should add a safety check as we already for enums: https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/enum.py#L24-L25

We should only allow to decorate classes with strawberry.type, strawberry.input and strawberry.interface

**Comment by estyxx** [comment]
*Think the code change a bit meanwhile, here there is now the reference:
https://github.com/strawberry-graphql/strawberry/blob/50684a7ca74af876441438351daf6de5ca22a394/strawberry/enum.py#L40-L41

**Comment by marcoacierno** [comment]
I think we can close this? :)
