### ISSUE TITLE
Add IDE support for strawberry.Private

### ISSUE THREAD

**Issue by lijok** [strawberry-graphql/strawberry#702]
My apologies, not knowing the internals of pythons type hinting system, I can't articulate this issue well
Is there something that can be done to strawberry.Private to prevent this from happening?

![image](https://user-images.githubusercontent.com/28689084/106826807-90bb3600-667f-11eb-8e6a-a1e84e64d382.png)

**Comment by BryceBeagle** [comment]
As discussed on Discord, `Private.__class_getitem__` is currently implemented like this:
```python
class Private:
    def __class_getitem(cls, item) -> Private:
        ...
```

PyCharm, unsurprisingly, does not understand that Strawberry change the field type behind the scenes. 

I mentioned that something along the lines of 
```python
class Private:
    def __class_getitem(cls, item: T) -> T:
        ...
```
is probably necessary to convince a type system of what's going on. This might involve lying to the type system and still returning a `Private` instance after annotating it as `T`, or actually changing the method to return `T`.

**Comment by lijok** [comment]
Did another deep dive into this today, seems like this is not possible
https://stackoverflow.com/questions/48722835/custom-type-hint-annotation#comment84446327_48722879

**Comment by BryceBeagle** [comment]
Thanks for looking into it some more. 

As a PyCharm devotee, I'm very interested in making all the typing work properly at the IDE level. Do you have any potential alternatives to the current implementation that would allow us to mark a field as to be excluded from the Schema?

**Comment by lijok** [comment]
Can't think of anything that's as clean and intuitive as strawberry.Private
A less clean solution could be to add another field to `strawberry.type` i.e `private_fields`

```py
@strawberry.type(private_fields=["queryset"])
class Integration(Node):
    queryset: models.Integration
```

**Comment by patrick91** [comment]
+1 for making it just work with PyCharm :)

The other option would be to have `field_name: str = strawberry.field(private=True)`

but let’s see if we can make it work with PyCharm. I’ll see if I can reach out someone from PyCharm 😊

**Comment by jkimbo** [comment]
If we can make this work I think we should go with:

`field_name: str = strawberry.private()`

(No need to make it an argument to .field because it wouldn't make sense to pass any of the other arguments to it)

**Comment by lijok** [comment]
> +1 for making it just work with PyCharm :)
> 
> The other option would be to have `field_name: str = strawberry.field(private=True)`
> 
> but let’s see if we can make it work with PyCharm. I’ll see if I can reach out someone from PyCharm 😊

I believe this is also a mypy problem in general, as if I run mypy on my repo with any `strawberry.Private[whatever]` fields, it spits out the same error messages as seen in the ide

**Comment by patrick91** [comment]
> > +1 for making it just work with PyCharm :)
> > The other option would be to have `field_name: str = strawberry.field(private=True)`
> > but let’s see if we can make it work with PyCharm. I’ll see if I can reach out someone from PyCharm 😊
> 
> I believe this is also a mypy problem in general, as if I run mypy on my repo with any `strawberry.Private[whatever]` fields, it spits out the same error messages as seen in the ide

oh, we can fix that too 😊

**Comment by jkimbo** [comment]
> I believe this is also a mypy problem in general, as if I run mypy on my repo with any `strawberry.Private[whatever]` fields, it spits out the same error messages as seen in the ide

I'm pretty sure I don't get that error and I use `.Private` quite a lot in my code.

**Comment by patrick91** [comment]
> > I believe this is also a mypy problem in general, as if I run mypy on my repo with any `strawberry.Private[whatever]` fields, it spits out the same error messages as seen in the ide
> 
> I'm pretty sure I don't get that error and I use `.Private` quite a lot in my code.

True, we have support for that in mypy 😊 https://github.com/strawberry-graphql/strawberry/blob/42b05b30d6177d5d54fd93c2dcec9bfaaf73a08b/strawberry/ext/mypy_plugin.py#L76-L80

**Comment by lijok** [comment]
```py
@strawberry.type(private_fields=["queryset"])
class Mapping(Node):
    queryset: strawberry.Private[models.Mapping]

    @strawberry.field
    def id(self) -> ID:
        return self.queryset.uid

    @strawberry.field
    def created(self) -> datetime:
        return self.queryset.created

    @strawberry.field
    def updated(self) -> datetime:
        return self.queryset.updated

    @strawberry.field
    def last_synced(self) -> Optional[datetime]:
        return self.queryset.last_synced
```

```sh
src/api/app/integration/types/mapping.py:82: error: "Private" has no attribute "uid"
src/api/app/integration/types/mapping.py:86: error: "Private" has no attribute "created"
src/api/app/integration/types/mapping.py:90: error: "Private" has no attribute "updated"
src/api/app/integration/types/mapping.py:94: error: "Private" has no attribute "last_synced"
```

not being familiar with mypy, I'm just running `mypy src` on my service
what am I supposed to be doing to make use of the plugin?

**Comment by patrick91** [comment]
@lijok you need to add the plugin to mypy.ini:

```
[mypy]
plugins = strawberry.ext.mypy_plugin
```

:)

**Comment by BryceBeagle** [comment]
> I think we should go with:

> ```python
> field_name: str = strawberry.private()
> ```

How would you initialize this to a value?

**Comment by jkimbo** [comment]
> > I think we should go with:
> 
> > 
> 
> > ```python
> 
> > field_name: str = strawberry.private()
> 
> > ```
> 
> 
> 
> How would you initialize this to a value? 

@BryceBeagle using a `defualt` value like the dataclass field? 

Just noticed that `strawberry.field` doesn't implement the default param. Is that intentional or just an oversight?

**Comment by patrick91** [comment]
> Just noticed that strawberry.field doesn't implement the default param. Is that intentional or just an oversight?

Definitely an oversight, we also need to implement default_factory :)

By the way, supporting strawberry.Private seems to be doable with a plugin: https://github.com/koxudaxi/pydantic-pycharm-plugin

**Comment by patrick91** [comment]
Going to close this in favour of https://github.com/strawberry-graphql/strawberry/issues/796 which has more details :)

**Comment by hddn** [comment]
> @lijok you need to add the plugin to mypy.ini:
> 
> ```
> [mypy]
> plugins = strawberry.ext.mypy_plugin
> ```
> 
> :)
> 
> EDIT: we should document this on our website :)

Is it compatible with pyproject.toml?
