### ISSUE TITLE
UploadFile causes ASGI application's exception when it is in debug mode

### ISSUE THREAD

**Issue by pablohenriq** [strawberry-graphql/strawberry#714]
Apparently when we use the ASGI application in debug mode, it cannot print the value of variables if they are not JSON serializable.

In my use case, when I tried to use the [file upload](https://strawberry.rocks/docs/features/file-upload) example in debug mode this issue ended up happening.

I believe it is because of this:

https://github.com/strawberry-graphql/strawberry/blob/de215370b247a417af8a8dd5fc382d71e305bcd7/strawberry/utils/debug.py#L26-L29

Perhaps converting variables to string might help.

**Comment by patrick91** [comment]
Thanks for the report @pablohenriq, will try to fix this during the weekend :)
