### ISSUE TITLE
De-shadow resolver arguments that have the same name as builtin functions

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#727]
this:

```
@strawberry.field
def my_resolver(self, id_: strawberry.ID) -> ...:
    ...
```

should change the `id_` name to be `id` on the schema.

**Comment by BryceBeagle** [comment]
This should also work with arguments with the same name as Python keywords

**Comment by BryceBeagle** [comment]
Similar in function to #725. Potentially one of the solutions will rely on the other

**Comment by jkimbo** [comment]
Not sure this is a good idea because it feels like too much magic to me. What if you want to have an argument with a trailing underscore? I think being able to override the name of an argument (#725) is a better solution than automagically renaming arguments.

**Comment by BryceBeagle** [comment]
Would having this be a feature that can be enabled/disabled work?

**Comment by patrick91** [comment]
> Would having this be a feature that can be enabled/disabled work?

I think this might be a good trade-off. 

By the way we should to the same for autoCamecasing, so we could do both at once (post-refactor I'd say).

What do you think @jkimbo?

**Comment by jkimbo** [comment]
Being able to enable/disable would definitely be better but I worry that it’s something that could cause some confusion when someone comes across it for the first time since it’s not that obvious. Maybe it’s opt in behaviour?

**Comment by patrick91** [comment]
Yes, I’d make it opt-in :)

**Comment by saschametz** [comment]
This would be a great addition. Same issue with mutation arguments:
```python
@strawberry.mutation
def order_create(input: OrderCreateInput) -> ...:
   ...
```
`input` is often used for mutations, which conflicts with Python's `input()` function.

**Comment by skilkis** [comment]
@saschametz please have a look at https://github.com/strawberry-graphql/strawberry/issues/725. This should be supported already 😊

**Comment by patrick91** [comment]
I'm going to close this issue, we have support for renaming arguments and we didn't have people asking for something like this 😊 We can always revisit it in future :)
