### ISSUE TITLE
Add "return fields" to Info object

### ISSUE THREAD

**Issue by sivy** [strawberry-graphql/strawberry#738]
When writing a query the user can provide a limited list of fields to retrieve for a given entity:

```
{ user(id: 1) {
    firstName
    lastName
    gender
}}
```

The docs explain [how to get execution info](https://strawberry.rocks/docs/types/resolvers#accessing-execution-information), and the `Info` object has a `field_name` attribute which (in this case) would contain `user`. But other than buried in the AST, there's no way to know what fields within `user` were requested (firstName, lastName, gender).

This makes it difficult (without walking the AST like django does with graphene) to optimize database queries by only retrieving relevant columns.

It would be good to include an attribute like `info.return_fields` or similar.

**Comment by mcsheehan** [comment]
```python
def get_all_field_names_from_selection_set(selection_set_node: SelectionSetNode) -> List[str]:
    """
    SelectionSetNode is part of the Info object and can be parsed to obtain a list of fields in the query
    Args:
        selection_set_node: This is contained on the info object info.field_nodes[0].selection_set

    Returns:
        A list containing all field names in the selection set
    """
    return [selection.name.value for selection in selection_set_node.selections]
```

**Comment by sivy** [comment]
Thanks @mcsheehan

**Comment by mcsheehan** [comment]
Patrick helped point me in the right direction. It's worth noting that this doesn't traverse more than one layer of nodes deep, but you can get at those from this object. Might write an example of that soon.

**Comment by patrick91** [comment]
I'll close this as it seems to be resolved :D
