### ISSUE TITLE
GraphiQL subscription websocket proxied to incorrect backend

### ISSUE THREAD

**Issue by mecampbellsoup** [strawberry-graphql/strawberry#739]
## Description

We are running what I suspect is a somewhat unique dev environment using strawberry with fast-api.

Additionally, in our development environment, we run webpack dev server so that we can quickly make changes to both our frontend SPA as well as our backend Python/GraphQL code - what's better than a tight iteration loop, right?! 😄 

At the moment, we mount strawberry (with the debug server, of course) as follows in `main.py`:

```python3

# ... (rest of file contents truncated)

@strawberry.type
class Query:
    @strawberry.field
    async def get_current_user(self, info: Info) -> User:
        # RemotePdb('0.0.0.0', 4444).set_trace()
        x_consumer_id = info.context['request'].headers
        return await get_current_user(x_consumer_id=x_consumer_id)

    users: List[User] = strawberry.field(resolver=get_users)


schema = strawberry.Schema(query=Query)
graphql = GraphQL(schema)

# TODO: Remove CORSMiddleware once frontend and backend hosted on same domain
app.mount('/api', CORSMiddleware(graphql, allow_origins=['*'], allow_methods=('GET', 'POST', 'OPTIONS')))

app.mount('/', WSGIMiddleware(django_app))
```
In this configuration, when I visit `http://dev-host/api/`, the GraphiQL test app/interface is loaded.

It seems from #344 however that this requires a subscription be created in the browser/client, and it specifically attempts to open a WS connection to the GraphQL server.

This is where wires seem to become crossed.

In development, the domain `http://dev-host` is actually served by WDS, and we have configured WDS to proxy requests matching path `/api` to our fast-api backend like so:

```js
  devServer: {
    clientLogLevel: 'debug',
    proxy: {
      '/api': process.env.PROXY_URI,
      onError: err => {
        console.log('Suppressing WDS proxy upgrade error:', err);
      },
```
When the GraphiQL client attempts to establish a WS connection, the requested location is of the pattern `ws://dev-host/api/` which attempts to connect (unless I have some invalid assumption in what I've explained so far) to WDS, and WDS in turn does not seem to be proxying the WS connection correctly. WDS typically then throws an error of the format:

```
[gatekeeper-frontend] Version: webpack 4.46.0
[gatekeeper-frontend] Time: 347ms
[gatekeeper-frontend] Built at: 03/04/2021 2:50:54 AM
[gatekeeper-frontend]  1 asset
[gatekeeper-frontend] Entrypoint main = main.js
[gatekeeper-frontend] [./src/App.jsx] 2.97 KiB {main} [built]
[gatekeeper-frontend] [./src/index.jsx] 705 bytes {main} [built]
[gatekeeper-frontend]     + 302 hidden modules
[gatekeeper-frontend] ℹ ｢wdm｣: Compiled successfully.
[gatekeeper-frontend] events.js:291
[gatekeeper-frontend]       throw er; // Unhandled 'error' event
[gatekeeper-frontend]       ^
[gatekeeper-frontend]
[gatekeeper-frontend] Error: read ECONNRESET
[gatekeeper-frontend]     at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[gatekeeper-frontend] Emitted 'error' event on Socket instance at:
[gatekeeper-frontend]     at emitErrorNT (internal/streams/destroy.js:100:8)
[gatekeeper-frontend]     at emitErrorCloseNT (internal/streams/destroy.js:68:3)
[gatekeeper-frontend]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[gatekeeper-frontend]   errno: -104,
[gatekeeper-frontend]   code: 'ECONNRESET',
[gatekeeper-frontend]   syscall: 'read'
[gatekeeper-frontend] }
[gatekeeper-frontend] error Command failed with exit code 1.
```
Frankly I'm not sure if I should be opening an issue with strawberry but I'm sort of scratching my head on this one and hoping you can assist in some fashion.

## References

* https://github.com/strawberry-graphql/strawberry/pull/344/files
* https://webpack.js.org/configuration/dev-server/#devserverproxy

**Comment by patrick91** [comment]
@mecampbellsoup have you tried proxying websockets as shown here? 

https://stackoverflow.com/questions/31654239/proxy-websockets-connection-within-webpack-dev-server

**Comment by mecampbellsoup** [comment]
@patrick91 thanks for getting back to me 😄 

I figured it out - my WDS proxy config was invalid. Compare the following two:

### Bad

```
proxy: {
      '/api': process.env.PROXY_URI,
      ws: true,
      onError: err => {
        console.log('Suppressing WDS proxy upgrade error:', err);
      },
    },
```

### Good

```
proxy: {
      '/api': {
        target: process.env.PROXY_URI,
        ws: true,
        onError: err => {
          console.log('Suppressing WDS proxy upgrade error:', err);
        },
      },
    },
```
I blame JS/WDS for letting me pass a _slightly invalid but correct-seeming_ proxy configuration object!

**Comment by patrick91** [comment]
@mecampbellsoup no worries, I've been there too :D
