### ISSUE TITLE
Examples for "Errors" docs

### ISSUE THREAD

**Issue by mecampbellsoup** [strawberry-graphql/strawberry#751]
Currently https://strawberry.rocks/docs/features/errors is an empty page.

I'm happy to include some examples but, I wanted to ask, which kind(s) of errors should this page describe?

* GraphQL server erros, e.g. invalid query syntax
* Resolver errors, e.g. a `strawberry.mutation` that performs an SQL `INSERT` which fails a DB constraint

Perhaps you intend to document some data class-based pattern like the following:

```
type User {
  id: ID!
  login: String!
}

type UserNotFoundError {
  message: String!
}

union UserResult = User | UserNotFoundError

type Query {
  user(id: ID!): UserResult!
}
```

## Refs

* https://graphql-ruby.org/mutations/mutation_errors
* https://www.apollographql.com/blog/full-stack-error-handling-with-graphql-apollo-5c12da407210/

**Comment by BryceBeagle** [comment]
My assumption was that it would be a dedicated page to cover the exceptions that are currently collected [here](https://github.com/strawberry-graphql/strawberry/blob/d1ec87e9b5ca814f6f42a50632af035e36a4cb41/strawberry/exceptions.py), but maybe @patrick91 had different ideas?

**Comment by patrick91** [comment]
@mecampbellsoup thanks for wanting to take this on. I think we should document what happens with exception now, something I've noticed many people struggle with is the fact that exception are swallowed and returned in the graphql errors response.

Then I think it would be a good idea to document the best practise of using union types for modelling errors in the schema

> My assumption was that it would be a dedicated page to cover the exceptions that are currently collected [here](https://github.com/strawberry-graphql/strawberry/blob/d1ec87e9b5ca814f6f42a50632af035e36a4cb41/strawberry/exceptions.py), but maybe @patrick91 had different ideas?

Oh yes, that page was for describing errors in GraphQL in general. I think these might live in a different section?

**Comment by jkimbo** [comment]
I think it's work separating out the "Exceptions" that strawberry could through from a guide on how to handle errors in a graphql server. For the guide I copied a list that @patrick91 came up with a while back into the description of this issue: https://github.com/strawberry-graphql/strawberry/issues/328 (under the features section).
