### ISSUE TITLE
Using arguments in a resolver on a generic type causes schema initialization to fail

### ISSUE THREAD

**Issue by ts-rodgers** [strawberry-graphql/strawberry#757]
Take the following generic collection type:

```python
@strawberry.type
class Collection(Generic[ItemType]):
    @strawberry.field
    async def by_id(self, ids: List[int]) -> List[int]:
        return []
```

Using it as follows yields the following error:

```python
@strawberry.type
class Post:
    id: int

@strawberry.type
class Query:
    @strawberry.field
    async def posts(self) -> Collection[Post]:
        ...
```

```
TypeError: PostCollection fields cannot be resolved. 'dict' object has no attribute 'name'
```

This error is caused by the `ArgumentDefinition` obj getting converted to a dict in this line: https://github.com/strawberry-graphql/strawberry/blob/6e4af5ba8f3908758c3de33b2711c37c30a25063/strawberry/types/generics.py#L77

Locally, I'm able to fix this by editing that to become:

```python
preserved_subfields = {
    subfield_name: getattr(field, subfield_name)
    for subfield_name in ["arguments", "federation"]
}
kwargs = dataclasses.asdict(field)
kwargs.update(preserved_subfields) 
```

(and also removing the reconversion for `"federation"` at https://github.com/strawberry-graphql/strawberry/blob/6e4af5ba8f3908758c3de33b2711c37c30a25063/strawberry/types/generics.py#L100-101)

**Comment by BryceBeagle** [comment]
Did #758 solve this issue?

**Comment by mr-rodgers** [comment]
Yes, it did.
