### ISSUE TITLE
mypy complains when using custom Scalars as described in the docs

### ISSUE THREAD

**Issue by mr-rodgers** [strawberry-graphql/strawberry#767]
Using this:

```python
PostTitle = strawberry.scalar(
    NewType("PostTitle", str),
    description="..."
)

@strawberry.type
class Post(AppPost):
    ...
    title: PostTitle
```

I receive the following:
```
blog_app/posts/types.py:31: error: Variable "blog_app.posts.types.PostTitle" is not valid as a type
blog_app/posts/types.py:31: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
```

and similar errors wherever PostTitle is used as a Type.

**Comment by patrick91** [comment]
Looks like I forgot to add support for that! Will try to make it work in the next couple of days :)

**Comment by N-Maas** [comment]
Has there been any progress on this? We have a bunch of custom scalars in our code and currently try to work around this issue by defining a second type for MyPy, but it is rather annoying to handle

**Comment by patrick91** [comment]
@N-Maas this should be fixed! Let me know if this is still a problem for you, and sorry for not letting you know earlier 😊
