### ISSUE TITLE
Function-based queries/mutations

### ISSUE THREAD

**Issue by marcoacierno** [strawberry-graphql/strawberry#825]
The current approach of defining mutations and queries isn't scalable for any medium/large sized codebase, a possible solution would be to have Strawberry be able to register/discover queries and mutation in any file, an example of how it might look like:

> schema.py

```
schema = strawberry.Schema()
```

> queries/user.py

```
from .schema import schema

@schema.query
def user(id: ID) -> User:
    return User(name="Marco")
```

> mutations/register.py

```
from .schema import schema

@schema.mutation
def register(email: str, password: str) -> User:
    return User(name="New user")
```

This would be equivalent to today's code:

```
@strawberry.type
class Query:
    @strawberry.field
    def user(self, id: ID) -> User:
        return User(name="Marco")

@strawberry.type
class Mutation:
    @strawberry.mutation
    def register(email: str, password: str) -> User:
        return User(name="New user")

schema = strawberry.Schema(query=Query, mutation=Mutation)
```

**Comment by DoctorJohn** [comment]
Hi @marcoacierno I agree the "everything in one class approche" does not scale well. I had this problem myself and switched to the following notation which served me well so far:

```python
from mypackage.mymodule import user, register

@strawberry.type
class Query:
    user = strawberry.field(resolver=user)


@strawberry.type
class Mutation:
    user = strawberry.mutation(resolver=register)
```

**Comment by patrick91** [comment]
@DoctorJohn we recently released this, maybe it's something you can use too  😊

https://github.com/strawberry-graphql/strawberry/pull/884

Regarding this:

```
@strawberry.type
class Mutation:
    user = strawberry.mutation(resolver=register)
```

we are considering emitting a warning/error (maybe we can make this optional and configurable) when the field doesn't have a type or when the type doesn't match the resolver 😊

**Comment by Object905** [comment]
In my experience, when you have a lot of fields, then it's better to nest them, like that:
```
@strawberry.type
class Query:
    products: products_schema.ProductsQuery = strawberry.field(resolver=lambda: True)
    project: project_schema.ProjectQuery = strawberry.field(resolver=lambda: True)
```
There is one downside with this approach is that you have to unnest such fields on the frontend, which is relatively easy with react-query or apollo.

**Comment by marcoacierno** [comment]
I am closing this since I can use `create_type` to have my queries/mutations in separate files and then merge them together
