### ISSUE TITLE
Improve support for extending/overriding fields in Pydantic

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#829]
Currently this code is broken:

```python
class User(pydantic.BaseModel):
    age: int
    password: Optional[str]

@strawberry.experimental.pydantic.type(User, fields=["age", "password"])
class UserType:
    name: str = "Michael"
```

https://github.com/strawberry-graphql/strawberry/pull/826/files#diff-998cad7d53bd87d5dc5e6e4cf3c76e6757da8a4691b786cd76cfc8b3f63852daR175-R181

**Comment by jerber** [comment]
This is broken for me too

**Comment by jerber** [comment]
I think this was fixed in a recent version, this is working for me now.

**Comment by patrick91** [comment]
@jerber thanks! will close this issue now :)
