### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#83]
Currently only me and @marcoacierno know that we can automatically release strawberry on PyPI. We should document this, and maybe make a bot that suggests to add a Release file :)

**Comment by patrick91** [comment]
We could use this for the bot: https://probot.github.io/

**Comment by blaggacao** [comment]
Somebody seemed to already got inspired: https://github.com/autopub/autopub

**Comment by blaggacao** [comment]
I'm just gathering the bits (for what it's worth):
- Comment: https://octokit.github.io/rest.js/#octokit-routes-pulls-create-comment
- Delete a file: https://octokit.github.io/rest.js/#octokit-routes-repos-delete-file
- Get contents: https://octokit.github.io/rest.js/#octokit-routes-repos-get-contents
- Creat or Update: https://octokit.github.io/rest.js/#octokit-routes-repos-create-or-update-file
- Delete file: https://octokit.github.io/rest.js/#octokit-routes-repos-delete-file

Note: I haven't found a trivial way to delete and update in a single commit through the GithubAPI, but for the sake of code simplicity, this _might_ be acceptable.

**Comment by patrick91** [comment]
@blaggacao I think at some point we should move to autopub (and also migrate everything off of circle-ci).

> Note: I haven't found a trivial way to delete and update in a single commit through the GithubAPI, but for the sake of code simplicity, this might be acceptable.

what do you mean with this? :)

PS. I think maybe we could close this issue for now, as we have a bot that comments and tells contributors to add a RELEASE.md file, that might suffice for now :)

**Comment by blaggacao** [comment]
> what do you mean with this? :)

I noticed that both, CHANGELOG modification & RELEASE deletion would produce a commit through github API, autopub / your solutins.

A bot would still be nice (eg. hosted on now.sh) just for the sake of easy adoption... But that's probably not something for your todo list, I'd agree with that. :)

**Comment by patrick91** [comment]
I’m going to close this as it seems the bot is being quite helpful :D
