### ISSUE TITLE
Support GET requests for queries?

### ISSUE THREAD

**Issue by nat-n** [strawberry-graphql/strawberry#834]
[Apollo client supports](https://www.apollographql.com/docs/react/networking/advanced-http-networking/) using GET instead of POST for GraphQL queries.

As far as I can tell strawberry doesn't seem to support this (at least [in the ASGI wrapper](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/asgi/__init__.py#L237)). Am I missing something? Is there already a plan to do so?

**Comment by jkimbo** [comment]
Seems like a good thing to support! Maybe each view should take an "allowed_methods" argument? What do you think @patrick91 ?

**Comment by patrick91** [comment]
I think we can do this, but we should only allow queries over get. so maybe the configuration option should be `allow_queries_via_get` 😊

**Comment by jkimbo** [comment]
> I think we can do this, but we should only allow queries over get. so maybe the configuration option should be `allow_queries_via_get` 😊

Oh I've just looked up the option in the Apollo docs. In that case why don't we always just always allow it?

**Comment by patrick91** [comment]
> > I think we can do this, but we should only allow queries over get. so maybe the configuration option should be `allow_queries_via_get` 😊
> 
> Oh I've just looked up the option in the Apollo docs. In that case why don't we always just always allow it?

We can, as long as we make sure we are only allowing queries via GET then we are good 😊
