### ISSUE TITLE
Add default_resolver for strawberry.type

### ISSUE THREAD

**Issue by la4de** [strawberry-graphql/strawberry#839]
I'd propose to add `default_resolver` for `strawberry.type`.

```python
def default_resolver():
    return Car(model='Ferrari')

@strawberry.type(default_resolver=default_resolver)
class Car:
    model: str
```

Following schema would use default resolver which would be overridable by field.
```python
@strawberry.type
class Query:
    car: Car
    @strawberry.field
    def another_car() -> Car:
        return Car(models='BMW')
```

With that schema, following query
```graphql
query {
  car { model }
  anotherCar { model }
}
```
would return 
```js
{
  data: {
    car: { model: "Ferrari" },
    anotherCar: { model: "BMW" },
}
```

That could be used by django integration for auto resolution of related objects as an example.

It would be nice if new resolver would have access to default resolver and could "extend" `default_resolver` something like this.
```python
@strawberry.type
class Query:
    @strawberry.field
    def yet_another_car(info) -> Car:
        # I'm not sure if info is right place for it, but you got the idea
        car = info.default_resolver()
        car.model = car.model.upper()
        return car
```

**Comment by la4de** [comment]
@patrick91, any comments? I created draft pull request for this: #842.

This would help us in django integration. Default resolver can be used to resolve relation fields of django types.

**Comment by patrick91** [comment]
I haven't seen the need of this, but if it can help the development of strawberry django then I'm for it.  

I'm only worried about the name, `default_resolver` sounds like we are change the default resolver for this type's fields, what do you think?

Apollo federation has a resolve reference function, what if used a similar approach?
https://www.apollographql.com/docs/federation/api/apollo-federation/#__resolvereference

**Comment by la4de** [comment]
> I haven't seen the need of this, but if it can help the development of strawberry django then I'm for it.

With this the developer could just write type like this
```python
@strawberry_django.type(models.User)
class User:
    name: auto
    groups: List[Group]

@strawberry.type
class Query:
    user: User
```
and then just query all groups of requested user without need to worry about resolver. Default resolver would handle filters, relations and everything =)

> I'm only worried about the name, `default_resolver` sounds like we are change the default resolver for this type's fields, what do you think?

Good point, it may mislead the reader. 


> Apollo federation has a resolve reference function, what if used a similar approach?
> https://www.apollographql.com/docs/federation/api/apollo-federation/#__resolvereference

Relation resolving is just one example. This should be generic in my opinion.

**Comment by patrick91** [comment]
Would something like this be ugly:

```python

@strawberry.type(default_resolver=default_resolver)
class Car:
    model: str

    @classmethod # or even @strawberry.type_resolver
    def _resolve(cls):
        return cls(model='Ferrari')
```
?

**Comment by la4de** [comment]
> Would something like this be ugly:
> 
> ```python
> @strawberry.type(default_resolver=default_resolver)
> class Car:
>     model: str
> 
>     @classmethod # or even @strawberry.type_resolver
>     def _resolve(cls):
>         return cls(model='Ferrari')
> ```
> 
> ?

That was my first proposal in discord django channel :), Then we started to think about if this could be defined through schema.

**Comment by patrick91** [comment]
By the way for federation we have this: https://github.com/strawberry-graphql/strawberry/blob/main/tests/federation/test_entities.py#L11-L13

so we already have some precedent for classmethods used by strawberry

**Comment by patrick91** [comment]
@BryceBeagle what do you think?

**Comment by la4de** [comment]
Both works for me. Django code would use that internally so it would not be visible for the end user there.

**Comment by BryceBeagle** [comment]
Either works, but my preference is to not encourage the creation of module-scoped functions. 

Could we combine this feature with #850 and have the default resolver defined alongside the other configuration options?

**Comment by la4de** [comment]
> Either works, but my preference is to not encourage the creation of module-scoped functions.
> 
> Could we combine this feature with #850 and have the default resolver defined alongside the other configuration options?

How this configuration would work in practise?

In Django we need to add `default_resolver` only for those types which are generated from Django models.

**Comment by BryceBeagle** [comment]
> we need to add `default_resolver` only for those types which are generated from Django models

oh, so the default resolver will vary between different types?

**Comment by la4de** [comment]
> > we need to add `default_resolver` only for those types which are generated from Django models
> 
> oh, so the default resolver will vary between different types?

Correct, we need django specific resolver for django types. One may need another resolver for other types.

**Comment by la4de** [comment]
I'm feeling that it might be better to handle django specific resolvers through field instead of type. It is already possible to do that with fields. I close this issue now and go with fields.

```python
class Query:
    users: List[User] = strawberry_django.field()
```
