### ISSUE TITLE
dataclasses metadata isn't copied 

### ISSUE THREAD

**Issue by mcsheehan** [strawberry-graphql/strawberry#844]
```python
NOT_BLANK_VALIDATION = validate.Length(min=1, error='Field cannot be blank')

@dataclass()
@strawberry.type(description="This is a description of our schema")
class ASchema(DataClassJsonMixin):
    a_field: str = field(metadata= {"validate": NOT_BLANK_VALIDATION})
```
This metadata information is a property of dataclasses, and is used for a few other software packages. 
The above example uses marshmallow validation, this metadata field is not propagated through the strawberry field.

**Comment by patrick91** [comment]
@mcsheehan would be enough if we provided support for metadata on `strawberry.field`?

**Comment by mcsheehan** [comment]
Hi @patrick91. I believe that should do it.

**Comment by pgerlich** [comment]
Would love to see this. Am also seeing this issue, which requires me to basically just subtype the actual dataclass

**Comment by jkimbo** [comment]
Solve in https://github.com/strawberry-graphql/strawberry/pull/2190
