### ISSUE TITLE
Incompatibility between ExecutionResult and ASGI Result format

### ISSUE THREAD

**Issue by ossareh** [strawberry-graphql/strawberry#856]
A number of times lately I've been bitten by the following type of error:

```
19:23:37 optical_dev.1   | 19:23:37.422 - asyncio                   - ERROR   - Task exception was never retrieved
19:23:37 optical_dev.1   | future: <Task finished name='Task-9338' coro=<GraphQL.handle_async_results() done, defined at /home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/strawberry/asgi/__init__.py:144> exception=RuntimeError("Unexpected ASGI message
'websocket.send', after sending 'websocket.close'.")>
19:23:37 optical_dev.1   | Traceback (most recent call last):
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/strawberry/asgi/__init__.py", line 148, in handle_async_results
19:23:37 optical_dev.1   |     async for result in results:
19:23:37 optical_dev.1   | TypeError: 'async for' requires an object with __aiter__ method, got ExecutionResult
19:23:37 optical_dev.1   |
19:23:37 optical_dev.1   | During handling of the above exception, another exception occurred:
19:23:37 optical_dev.1   |
19:23:37 optical_dev.1   | Traceback (most recent call last):
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/strawberry/asgi/__init__.py", line 161, in handle_async_results
19:23:37 optical_dev.1   |     await self._send_message(
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/strawberry/asgi/__init__.py", line 189, in _send_message
19:23:37 optical_dev.1   |     return await websocket.send_json(data)
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/starlette/websockets.py", line 137, in send_json
19:23:37 optical_dev.1   |     await self.send({"type": "websocket.send", "text": text})
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/starlette/websockets.py", line 68, in send
19:23:37 optical_dev.1   |     await self._send(message)
19:23:37 optical_dev.1   |   File "/home/ossareh/.cache/pypoetry/virtualenvs/vega-bx_b103Q-py3.9/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 231, in asgi_send
19:23:37 optical_dev.1   |     raise RuntimeError(msg % message_type)
19:23:37 optical_dev.1   | RuntimeError: Unexpected ASGI message 'websocket.send', after sending 'websocket.close'.
```

This has been discussed on Discord: https://discord.com/channels/689806334337482765/773519351423827978/832696949656387645

The two cases I've seen this in are:

1. introspection query returned over a websocket
2. (as above) a malformed subscription query

### introspection query returned over websocket

Some clients will issue an introspection query prior to executing queries, they use this as a pre-flight check to ensure the query is well formed and alert the developer if it is not. When those queries are over a websocket, i.e. a subscription query, Strawberry correctly returns the result but in a format that is not ASGI compatible and the "`'async for' requires an object with __aiter__ method, got ExecutionResult`" occurs. 

### malformed subscription query

In the case above I had the following query:

```gql
    subscription liveView($exposureMs: Int!, $serials: [String!]!) {
        streamFrames(exposureMs: $exposureMs, serialNos: $serials) {
            serialNo
            url
        }
    }
```

with the following variables: `{ exposureMs: 100, serialNos: [] }`. The name mismatch between `serialNos` and the expected `serials` being the root cause - which presents as "`'async for' requires an object with __aiter__ method, got ExecutionResult`".

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/856">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/856/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/856/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
I'm assuming this has been fixed at some point! Feel free to reopen if that's not the case 😊
