### ISSUE TITLE
Can the Query parameter in strawberry.Schema be optional?

### ISSUE THREAD

**Issue by wuyuanyi135** [strawberry-graphql/strawberry#880]
Hello,
I wonder why the Query is mandatory in `strawberry.Schema`? If I want to create a endpoint with only `Subscription` how could I bypass the Query schema?

Thanks !

**Comment by BryceBeagle** [comment]
The `Query` type is mandated by the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Root-Operation-Types): 

> A schema defines the initial root operation type for each kind of operation it supports: query, mutation, and subscription; this determines the place in the type system where those operations begin.
> 
> The query root operation type must be provided and must be an Object type.
> 
> The mutation root operation type is optional; if it is not provided, the service does not support mutations. If it is provided, it must be an Object type.
> 
> Similarly, the subscription root operation type is also optional; if it is not provided, the service does not support subscriptions. If it is provided, it must be an Object type.

**Comment by wuyuanyi135** [comment]
I see. Thanks a lot!
