### ISSUE TITLE
Schema export command

### ISSUE THREAD

**Issue by DoctorJohn** [strawberry-graphql/strawberry#898]
For client code generation and editior autocompletion I regularely export my graphql schema from the server. I'm used to using a command to do so. As far as I can tell strawberry does not (yet) provide a command for it.

Alternatives to using a command would be programmatically exporting the schema or fetching the schema from a running server. IMHO both methods are incovenient (in my case the later one requires a token for authentication).

I'm planning to draft a PR for this shortly, unless someone guides me in a different direction in the meantime ;)

**Comment by BryceBeagle** [comment]
It's not yet documented, but we do have a function to print out the schema:
 https://github.com/strawberry-graphql/strawberry/blob/f31e6c17238ba4372129c4f291ddf336b4e6b901/strawberry/printer.py#L107-123

I definitely think that this could be useful as a CLI tool.

**Comment by BryceBeagle** [comment]
Ahaha great timing. Glad you found `print_schema`

**Comment by DoctorJohn** [comment]
Furtunately I discovered the `print_schema` function yesterday. It made implementing the CLI command trivial

**Comment by DoctorJohn** [comment]
The suggested command was implemented in #899
