### ISSUE TITLE
Link to Strawberry Django repo in the docs on the main website

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#987]
Currently, https://strawberry.rocks/docs/integrations/django doesn't include a link to https://github.com/strawberry-graphql/strawberry-graphql-django. This would be helpful to people just getting started with the extension.

**Comment by Kommandat** [comment]
Hi @BryceBeagle,

Been eyeing a "good first issue" to help with (however small it may be). Let me know if this looks ok.

https://github.com/strawberry-graphql/strawberry/pull/992

Thanks,
Lakshay
