### ISSUE TITLE
Input values: Nullable fields and defaults

### ISSUE THREAD

**Issue by joeydebreuk** [strawberry-graphql/strawberry#999]
Lets say we have a resolver with the input `orderBy: Order = created`, what should happen if we pass `{"orderBy": null}`?

### Example code

**Resolver**
```py
@strawberry.enum
class Order(Enum):
    ....

def resolver(
    order_by: Optional[Order] = Order.created,
) -> ...:
    if not hasattr(order_by, "value"):
        raise GraphQLError("orderBy is not valid")
    ...
```
**Mutation**
```
query doQuery($orderBy: Order) {
    resolve (orderBy: $orderBy){
        ...
  }
}
```

Expected cases:
1. orderBy is omitted: query with variables `{}` will use the default `Order.created`
2. orderBy is incorrect type: query with variables `{"orderBy": 1}` will return `Variable '$order' got invalid value` because `order = 1` is not a valid type

But when querying with variables `{"orderBy": null}`, a third case happens: No error raised by graphql, no default value is set. `order_by` will be `None` in runtime, and in the example code `raise GraphQLError("orderBy is not valid")` will be called. Here I would expect case 2, because `null` is a value which is not of type `Order`.

I don't find this very well explained in the spec either https://spec.graphql.org/June2018/#sec-Null-Value

**Comment by coady** [comment]
GraphQL supports distinguishing an explicit null from omission. For your use case - non-null with a default - it can be specified that way: `order_by: Order = Order.created` (no `Optional`). Then the usual validation will return the appropriate error.

**Comment by joeydebreuk** [comment]
@coady I tried your suggestion, but without success. Now the schema is `orderBy: Order! = default` while before it was `orderBy: Order = default`. Maybe you misunderstood my ticket.

Can you describe what would be expected if I send `{"orderBy": null}` while `orderBy: Order = default`? Shouldn't this result in incorrect type error on schema level?

**Comment by coady** [comment]
> Can you describe what would be expected if I send `{"orderBy": null}` while `orderBy: Order = default`? Shouldn't this result in incorrect type error on schema level?

`!` indicates the input is non-null:
* `orderBy: Order! = default` will error if `{"orderBy": null}` is sent
* `orderBy: Order = default` will allow it

**Comment by joeydebreuk** [comment]
@coady No error is raised (by strawberry) for `{"orderBy": null}`, as described in my issue description:

> But when querying with variables {"orderBy": null}, a third case happens: No error raised by graphql, no default value is set. order_by will be None in runtime, and in the example code raise GraphQLError("orderBy is not valid") will be called.

**Comment by joeydebreuk** [comment]
@coady  so sending `{"orderBy": null}` to `orderBy: Order = default`, and in runtime the value being `None` is expected?

Wouldn't it make sense to throw incorrect type error here?

**Comment by jkimbo** [comment]
@joeydebreuk in your example I would expect the resolver to receive `None` because the value has been explicitly set to `null` by the client. It also matches the behaviour you would get with a plain Python function. i.e.:

```python
def my_func(order_by = default):
	return order_by

assert my_func(order_by=None) is None
```

**Comment by joeydebreuk** [comment]
I understand how this works in plain Python, but personally I'd expect `null` not to be of valid type according to the schema. Don't the GraphQL specs describe how this case should be handled? I couldn't find it myself :thinking:

**Comment by jkimbo** [comment]
I think the spec does make it quite clear:
https://spec.graphql.org/June2018/#sec-Null-Value

> ```
> {
>   field(arg: null)
>   field
> }
> ```
> The first has explictly provided null to the argument “arg”, while the second has implicitly not provided a value to the argument “arg”. These two forms may be interpreted differently.

By passing `None` when `null` is passed we can differentiate between the 2 different cases.

**Comment by joeydebreuk** [comment]
@jkimbo Thanks for your help. So if I understand correctly:
-  `orderBy: Order = default` means you can omit the value, in this case it will be defaulted
-  but will also allow `null`, in which case it will be `None`

And there is no way to make a distinction between these cases in the schema? So if I for example would want to disallow `null`, but omitting is allowed, I would have to handle this in my resolver?

eg imagine I have a resolver to update instance in DB, it has a lot of optional fields, fields that shouldn't be updated can be omitted. Lets say `name` column in DB only allows `str` not `None`, I'd have to handle it like:
```py
def update_instance(
    id: ...,
    name: Optional[str] = UNSET,
    some_other_fields: Optional[str] = UNSET,
    # a bunch of other fields
) -> ...:
    if name is None:
        raise GraphQLError("name can not be null")
```

**Comment by jkimbo** [comment]
Yep thats correct. As far as I'm aware there is no way to disallow null but allow omitting in the schema alone. You would have to do the checks in the resolver.

Related: I would consider that any field that has lots of optional fields should probably be split out into multiple fields. To make full use of the benefits of the GraphQL typing it's beneficial to be very specific with your fields and types.

**Comment by joeydebreuk** [comment]
Thanks a lot @jkimbo

**Comment by coady** [comment]
> And there is no way to make a distinction between these cases in the schema? So if I for example would want to disallow `null`, but omitting is allowed, I would have to handle this in my resolver?

It is allowed (just poorly documented). Having a default value also makes the input optional, regardless of whether the type is nullable.
* `orderBy: Order! = default`: doesn't allow nulls, sends default if omitted
* `orderBy: Order = default`: allows nulls, and sends default if omitted

**Comment by jkimbo** [comment]
Oh yeah that looks like it should work @coady in which case this is a bug in Strawberry.

**Comment by coady** [comment]
> Oh yeah that looks like it should work @coady in which case this is a bug in Strawberry.

There's no bug that I'm aware of. It does work in strawberry:
strawberry | graphql | description
----------  | -------- | ------------
`order_by: Order = default` | `orderBy: Order! = default` | doesn't allow nulls, sends default if omitted 
`order_by: Optional[Order] = default` | `orderBy: Order = default` | allows nulls, and sends default if omitted

**Comment by jkimbo** [comment]
@joeydebreuk can verify that the options @coady has outlined work for you?

**Comment by joeydebreuk** [comment]
Yes. Now I realize where I got mixed up.

I was doing
```py
@query("test")
@strawberry.field
def test_query(
    choice: Order = Order.startsAtDesc,
    optional_choice: Optional[Order] = Order.startsAtDesc,
) -> bool:
    print(f"{choice.value=}")
    print(f"{optional_choice.value=}")
    return True
```
This runs fine, default work, but schema looks like
```
choice: Order!
optionalChoice: Order
```

If I do
```py
@query("test")
@strawberry.field
def test_query(
    choice: Order = Order.startsAtDesc.value,
    optional_choice: Optional[Order] = Order.startsAtDesc.value,
) -> bool:
    print(f"{choice.value=}")
    print(f"{optional_choice.value=}")
    return True
```
schema looks like 
```
choice: Order! = startsAtDesc
optionalChoice: Order = startsAtDesc
```
And everything works as expected.
